<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product Composite Dialog Block
 *
 * Elements:
 * - product_composite_configure_confirmed - contains per product configure form template with formData property
 * - product_composite_configure_form - edit form with validation for maho dialog
 * - product_composite_configure_form_fields - per product configure form area
 * - product_composite_configure_form_additional - overriding fields added with `window.productConfigure.addFields()`
 * - product_composite_configure_form_confirmed - when using urlSubmit for batch submit,  confirmed products will be
 *                                                renamed and appended here for form submission
 *
 * @var Mage_Adminhtml_Block_Catalog_Product_Composite_Configure $this
 */
?>
<div id="product_composite_configure" class="no-display">
    <div id="product_composite_configure_confirmed"></div>
    <form id="product_composite_configure_form">
        <div id="product_composite_configure_messages"></div>
        <div id="product_composite_configure_form_fields" class="content"></div>
        <div id="product_composite_configure_form_additional" class="no-display"></div>
        <div id="product_composite_configure_form_confirmed" class="no-display"></div>
    </form>
</div>
