<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Adminhtml_Catalog_Product_Composite_Fieldset_Options_Type_Checkbox $this */
$option = $this->getOption();
$selections = $option->getSelections();
$skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck();
?>
<dt>
    <label<?= $option->getRequired() ? ' class="required"' : '' ?>>
        <?= $this->escapeHtml($option->getTitle()) ?>
    </label>
</dt>
<dd>
    <div class="input-box">
    <?php if (count($selections) == 1 && $option->getRequired()): ?>
        <?= $this->getSelectionQtyTitlePrice($selections[0]) ?>
        <input type="hidden" name="bundle_option[<?= $option->getId() ?>]" value="<?= $selections[0]->getSelectionId() ?>" price="<?= $this->getSelectionPrice($selections[0]) ?>"/>
    <?php else: ?>
        <ul class="options-list">
        <?php foreach ($selections as $selection): ?>
            <li>
                <?php $checked = $this->_isSelected($selection) ? ' checked="checked"' : '' ?>
                <?php $disabled = !$selection->isSaleable() && !$skipSaleableCheck ? ' disabled="disabled"' : '' ?>
                <input type="checkbox" class="change-container-classname checkbox bundle-option-<?= $option->getId() ?><?= $option->getRequired() ? ' validate-one-required-by-name' : '' ?>" id="bundle-option-<?= $option->getId() ?>-<?= $selection->getSelectionId() ?>" name="bundle_option[<?= $option->getId() ?>][]"<?= $checked ?><?= $disabled ?> value="<?= $selection->getSelectionId() ?>" onclick="ProductConfigure.bundleControl.changeSelection(this)" price="<?= $this->getSelectionPrice($selection) ?>"/>
                <span class="label"><label for="bundle-option-<?= $option->getId() ?>-<?= $selection->getSelectionId() ?>"><?= $this->getSelectionQtyTitlePrice($selection) ?></label></span>
            <?php if ($option->getRequired()): ?>
                <?= $this->setValidationContainer("bundle-option-{$option->getId()}-{$selection->getSelectionId()}", "bundle-option-{$option->getId()}-container") ?>
            <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
        <div id="bundle-option-<?= $option->getId() ?>-container"></div>
    <?php endif ?>
    </div>
</dd>
