<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<?php $_shipment = $this->getShipment() ?>
<?php $_order = $this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?= $this->__('Shipped By') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?= $this->__('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $i = 0;
        foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
            <tr>
                <td align="left" valign="top" style="padding:3px 9px"><?= $this->escapeHtml($_item->getTitle()) ?></td>
                <td align="center" valign="top" style="padding:3px 9px"><?= $this->escapeHtml($_item->getNumber()) ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
