<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2018-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Widget_Gender $this */
?>
<label for="<?= $this->getFieldId('gender')?>"<?= $this->isRequired() ? ' class="required"' : '' ?>><?= $this->__('Gender') ?></label>
<div class="input-box">
    <select id="<?= $this->getFieldId('gender')?>" name="<?= $this->getFieldName('gender') ?>" title="<?= $this->quoteEscape($this->__('Gender')) ?>"<?php if ($this->isRequired()):?> class="validate-select"<?php endif ?> <?= $this->getFieldParams() ?>>
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
        <?php $value = $this->getGender();?>
        <?php foreach ($options as $option):?>
            <option value="<?= $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?= $this->__($option['label']) ?></option>
        <?php endforeach ?>
    </select>
</div>
