<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Widget_Taxvat $this */
?>
<label for="<?= $this->getFieldId('taxvat')?>"<?= $this->isRequired() ? ' class="required"' : '' ?>><?= $this->__('Tax/VAT number') ?></label>
<div class="input-box">
    <input type="text" id="<?= $this->getFieldId('taxvat')?>" name="<?= $this->getFieldName('taxvat') ?>" value="<?= $this->escapeHtml($this->getTaxvat()) ?>" title="<?= $this->quoteEscape($this->__('Tax/VAT number')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?= $this->getFieldParams() ?> />
</div>
