<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Widget_Taxvat $this */
?>
<label for="<?= $this->getFieldId('taxvat')?>"<?= $this->isRequired() ? ' class="required"' : '' ?>><?= $this->__('Tax/VAT number') ?></label>
<div class="input-box">
    <input type="text" id="<?= $this->getFieldId('taxvat')?>" name="<?= $this->getFieldName('taxvat') ?>" value="<?= $this->escapeHtml($this->getTaxvat()) ?>" title="<?= $this->quoteEscape($this->__('Tax/VAT number')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?= $this->getFieldParams() ?>>
</div>
