<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_System_Design_Edit $this */
?>
<div class="content-header">
    <h3><?= $this->getHeader() ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getChildHtml('back_button') ?>
        <?php if($this->getDesignChangeId()): ?>
            <?= $this->getChildHtml('delete_button') ?>
        <?php endif ?>
        <?= $this->getChildHtml('save_button') ?>
    </p>
</div>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="design_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
    var designForm = new varienForm('design_edit_form');
</script>
