<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_System_Design $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('catalog')->__('Design') ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getChildHtml('add_new_button') ?>
    </p>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
