<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?= Mage::helper('catalog')->__('Design') ?></h3></td>
        <td class="form-buttons">
            <?= $this->getChildHtml('add_new_button') ?>
        </td>
    </tr>
</table>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
