<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_System_Design $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('catalog')->__('Design') ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getChildHtml('add_new_button') ?>
    </p>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
