<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Reports_Block_Product_Compared $this */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="widget widget-compared">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?= $this->__('Recently Compared') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol id="widget-compared-<?= $suffix ?>">
            <?php $i = 0; foreach ($_products as $_product): ?>
                <li class="item">
                    <p class="product-name"><a href="<?= $_product->getProductUrl() ?>"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                </li>
            <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif ?>
