<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @var Mage_Customer_Block_Address_Edit $this
 */
?>
<?php if($this->getTitle()): ?>
<div class="page-title">
    <h1><?= $this->getTitle() ?></h1>
</div>
<?php endif ?>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
    <?= $this->getBlockHtml('formkey') ?>
    <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>" />

    <?= $this->getChildHtml('form_customer_address_edit') ?>

    <div class="fieldset">
        <ul class="form-list">
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?= $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?= Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" /><label for="primary_billing"><?= $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?= $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?= Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?= $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
        <button type="submit" title="<?= Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><?= $this->__('Save Address') ?></button>
    </div>
</form>
<script type="text/javascript">
    const countryRegions = <?= Mage::helper('directory')->getRegionJsonByStore() ?>;
    const dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', countryRegions, undefined, 'zip');
</script>
