<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Edit $this */

$formBlock = $this->getChild('form');
$tabsBlock = $this->getLayout()->getBlock('tabs');
$treeBlock = $this->getLayout()->getBlock('category.tree');
?>

<div id="category-edit-container" class="category-content">
    <?= $this->getChildHtml('form') ?>
</div>

<script type="module">
    document.addEventListener('DOMContentLoaded', () => {
        const categoryForm = new CategoryEditForm({
            editUrl: '<?= $formBlock->getEditUrl() ?>',
            moveUrl: '<?= $treeBlock->getMoveUrl() ?>',
            switchTreeUrl: '<?= $treeBlock->getSwitchTreeUrl() ?>',
            loadTreeUrl: '<?= $treeBlock->getLoadTreeUrl() ?>',

            treeDiv: 'tree-div',
            containerDiv: 'category-edit-container',
            addRootCategoryBtn: 'add_root_category_button',
            addSubCategoryBtn: 'add_subcategory_button',
            categoryProductsEl: 'in_category_products',

            tabsJsObjectName: '<?= $tabsBlock->getJsObjectName() ?>',
            useAjax: <?= var_export((bool) $this->getUseAjax(), true) ?>,
        });

    <?php if ($treeBlock->getRootNode()): ?>
        categoryForm.renderTree(<?= $this->jsonEncode($treeBlock->getRootTreeParameters()) ?>);
    <?php endif ?>

        // Expose global functions called by form buttons to instance methods
        if (typeof window.varienStoreSwitcher !== 'undefined') {
            window.varienStoreSwitcher.storeSelectorClickCallback = categoryForm.switchStore.bind(categoryForm);
        }
        window.tree = {
            collapseTree: categoryForm.collapseTree.bind(categoryForm),
            expandTree: categoryForm.expandTree.bind(categoryForm),
        }
        window.addNew = categoryForm.addCategory.bind(categoryForm);
        window.categoryReset = categoryForm.resetCategory.bind(categoryForm);
        window.categoryDelete = categoryForm.deleteCategory.bind(categoryForm);
        window.categorySubmit = categoryForm.saveCategory.bind(categoryForm);
    });
</script>
