<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Tree $this */
?>
<div class="categories-side-col">
    <div class="content-header">
        <h3><?= Mage::helper('catalog')->__('Categories') ?></h3>
        <?php if ($this->getRoot()): ?>
            <?= $this->getAddRootButtonHtml() ?>
            <?= $this->getAddSubButtonHtml() ?>
        <?php endif ?>
    </div>
    <?= $this->getStoreSwitcherHtml() ?>
    <div class="tree-actions">
        <?php if($this->getRoot()): ?>
            <a href="#" onclick="tree.collapseTree(); return false;"><?= Mage::helper('catalog')->__('Collapse All') ?></a>
            <span class="separator">|</span>
            <a href="#" onclick="tree.expandTree(); return false;"><?= Mage::helper('catalog')->__('Expand All') ?></a>
        <?php endif ?>
    </div>
    <div class="tree-holder">
        <div id="tree-div" class="hor-scroll"></div>
    </div>
</div>
