<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Tree $this */
?>
<?= $this->getStoreSwitcherHtml() ?>
<div class="categories-side-col">
    <?php if ($this->getRoot()): ?>
        <?= $this->getAddRootButtonHtml() ?>
        <?= $this->getAddSubButtonHtml() ?>
    <?php endif ?>
    <?php if($this->getRoot()): ?>
    <div class="tree-actions">
        <a href="#" onclick="tree.collapseTree(); return false;"><?= Mage::helper('catalog')->__('Collapse All') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="tree.expandTree(); return false;"><?= Mage::helper('catalog')->__('Expand All') ?></a>
    </div>
    <?php endif ?>
    <div class="tree-holder">
        <div id="tree-div" class="hor-scroll"></div>
    </div>
</div>
