<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 */

declare(strict_types=1);

namespace Maho\Db\Schema;

use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\FloatType;
use Doctrine\DBAL\Types\SmallFloatType;
use Doctrine\DBAL\Types\Type;

/**
 * Reduce an introspected table and its declarative target to the same
 * representation before DBAL's Comparator runs, so the Comparator emits only
 * genuine structural differences.
 *
 * The Comparator decides column equality by rendering the full column
 * declaration and decides index/FK identity partly by name. Introspection and
 * the declarative schema describe behaviourally identical tables differently,
 * so without this the Comparator reports large, non-converging diffs of pure
 * representation — each difference below is representation-only, describing the
 * same physical schema two different ways:
 *
 *   - comments: introspected columns carry them, the declarative schema sets
 *     none, and MySQL folds the comment into the column declaration;
 *   - CURRENT_TIMESTAMP: introspected as the string 'CURRENT_TIMESTAMP',
 *     declared as a CurrentTimestamp expression object;
 *   - float precision: MySQL reports double as precision 22, the schema sets
 *     none, so DOUBLE(22,0) vs DOUBLE re-emits on every run;
 *   - numeric default spelling ('1' vs 1.0);
 *   - index names: introspected names vs DBAL's autogenerated ones;
 *   - phantom FK indexes: introspection synthesizes a single-column index for a
 *     foreign key backed only by a composite prefix, with no physical
 *     counterpart (see stripPhantomIndexes()).
 *
 * The equivalence applied here is purely representational, so it never hides a
 * genuine structural difference. Methods mutate the passed tables in place;
 * both are built fresh per plan() (introspection / Collector).
 */
final class Canonicalizer
{
    /**
     * Bring a live/target table pair into parity-equivalent form.
     *
     * @param list<string> $physicalLiveIndexNames Names of the indexes that
     *        physically exist on the live table (from introspectTableIndexes),
     *        used to tell a real index from a DBAL-synthesized phantom.
     */
    public static function reconcile(Table $live, Table $target, array $physicalLiveIndexNames): void
    {
        self::stripPhantomIndexes($live, $physicalLiveIndexNames);
        self::alignIndexNames($live, $target);
        self::stripColumnComments($live);
        self::stripColumnComments($target);
        self::reconcileColumns($live, $target);
        self::preserveUndeclaredColumns($live, $target);
        // Only columns are preserved, not indexes/FKs. An undeclared index or FK
        // on a managed table is legacy cruft the migration normalizes away (the
        // declarative target is the canonical structure); declare it in a
        // schema.php to keep it. Columns differ: they hold data, so dropping one
        // is irreversible loss.
    }

    /**
     * Drop the single-column indexes DBAL synthesizes during introspection for
     * foreign-key columns that have no dedicated physical index (they are backed
     * by a composite index's prefix or the primary key).
     *
     * Removing them serves two ends at once:
     *  - The Comparator no longer emits a `DROP INDEX` against an index that does
     *    not physically exist (which aborts the whole migration on MySQL).
     *  - When the declarative target legitimately keeps the implicit FK index,
     *    the Comparator now sees it as missing on the live side and emits a
     *    `CREATE INDEX`, so the migrated schema gains the same index a fresh
     *    install materializes from its CREATE TABLE — keeping the two identical.
     *
     * A "phantom" is precisely an index present in the full introspection
     * (introspectTable, which runs FK index synthesis) but absent from the
     * physical index list (introspectTableIndexes). The primary key is never a
     * phantom.
     *
     * @param list<string> $physicalIndexNames
     */
    private static function stripPhantomIndexes(Table $table, array $physicalIndexNames): void
    {
        $physical = array_map('strtolower', $physicalIndexNames);
        foreach ($table->getIndexes() as $index) {
            if (self::isPrimaryIndex($table, $index)) {
                continue;
            }
            $name = $index->getObjectName()->toString();
            if (!in_array(strtolower($name), $physical, true)) {
                $table->dropIndex($name);
            }
        }
    }

    /**
     * Rename each live index that matches a target index by structure to the
     * target's name, so the Comparator treats the pair as identical and emits
     * nothing for it. Indexes are equivalent by columns and semantics, not by
     * name, so this realignment is invisible to a structural comparison and
     * removes the rename churn the Comparator would otherwise generate (every
     * legacy index name differs from DBAL's autogenerated one).
     */
    private static function alignIndexNames(Table $live, Table $target): void
    {
        $usedTargetNames = [];
        $targetBySignature = [];
        foreach ($target->getIndexes() as $index) {
            if (self::isPrimaryIndex($target, $index)) {
                continue;
            }
            // Keep all candidates per signature; a single signature can name
            // more than one structurally-identical target index.
            $targetBySignature[self::indexSignature($index)][] = $index->getObjectName()->toString();
        }
        if ($targetBySignature === []) {
            return;
        }

        foreach ($live->getIndexes() as $index) {
            if (self::isPrimaryIndex($live, $index)) {
                continue;
            }
            $signature = self::indexSignature($index);
            $liveName = $index->getObjectName()->toString();

            // If the live name is already a valid target name for this signature,
            // claim it and move on — never rename a correctly-named index.
            $candidates = $targetBySignature[$signature] ?? [];
            $matchLower = array_map('strtolower', $candidates);
            if (in_array(strtolower($liveName), $matchLower, true)) {
                $usedTargetNames[strtolower($liveName)] = true;
                continue;
            }

            // Take the first target name for this signature not yet claimed and
            // not already present on the live table (renaming onto an existing
            // name would collide).
            foreach ($candidates as $candidate) {
                if (isset($usedTargetNames[strtolower($candidate)]) || $live->hasIndex($candidate)) {
                    continue;
                }
                $live->renameIndex($liveName, $candidate);
                $usedTargetNames[strtolower($candidate)] = true;
                break;
            }
        }
    }

    /**
     * Structural fingerprint of an index: type (REGULAR/UNIQUE/FULLTEXT/SPATIAL)
     * plus its ordered columns and their prefix lengths. Two indexes with the
     * same signature differ only in name, so aligning the name makes the
     * Comparator treat them as identical. Anything the signature omits (e.g. a
     * prefix length present on one side only) is a real difference the Comparator
     * must still act on, so it is included here to avoid renaming a pair the
     * Comparator would otherwise drop and recreate.
     */
    private static function indexSignature(Index $index): string
    {
        $columns = array_map(
            static fn($column): string => strtolower(trim($column->getColumnName()->toString(), '"`'))
                . ':' . ($column->getLength() ?? ''),
            $index->getIndexedColumns(),
        );

        return $index->getType()->name . '|' . implode(',', $columns);
    }

    /**
     * Clear every column comment. The declarative schema sets none, the parity
     * dump ignores them, and they are the largest single source of phantom
     * column diffs.
     */
    private static function stripColumnComments(Table $table): void
    {
        foreach ($table->getColumns() as $column) {
            $column->setComment('');
        }
    }

    /**
     * For each column the two tables share, neutralize representational-only
     * differences by copying the target's representation onto the live column
     * when the two are equivalent. Genuine differences (a real type change, a
     * nullability change, a different default value) are left untouched so the
     * Comparator still emits them.
     */
    private static function reconcileColumns(Table $live, Table $target): void
    {
        foreach ($target->getColumns() as $targetColumn) {
            $name = $targetColumn->getObjectName()->toString();
            if (!$live->hasColumn($name)) {
                continue;
            }
            $liveColumn = $live->getColumn($name);

            // Only reconcile the default when the types already match. When the
            // type itself changes (e.g. boolean to smallint), the default changes
            // with it and the Comparator must emit that change; aligning the
            // default here would make the two look equal and suppress the
            // Comparator's SET DEFAULT, leaving the migrated column without the
            // target default.
            if ($liveColumn->getType()::class === $targetColumn->getType()::class
                && self::defaultsEquivalent($liveColumn->getDefault(), $targetColumn->getDefault())
            ) {
                $liveColumn->setDefault($targetColumn->getDefault());
            }

            // MySQL reports a storage precision/scale for float/double columns
            // (e.g. 22/0) that the declarative schema never sets. Align them so
            // DOUBLE(22,0) vs DOUBLE stops re-emitting forever.
            if ($liveColumn->getType() instanceof FloatType && $targetColumn->getType() instanceof FloatType
                || $liveColumn->getType() instanceof SmallFloatType && $targetColumn->getType() instanceof SmallFloatType
            ) {
                $liveColumn->setPrecision($targetColumn->getPrecision());
                $liveColumn->setScale($targetColumn->getScale());
            }

            // Postgres represents an autoincrement column the legacy installer
            // created as SERIAL (a nextval(...) default), the declarative schema
            // as IDENTITY (autoincrement flag, no default). Both are the same
            // autoincrement column, so align the live column to the target's
            // identity form. This removes a per-column
            // DROP DEFAULT + ADD IDENTITY churn pair and, more importantly,
            // avoids rebuilding the live sequence — which would restart its
            // counter and collide with existing rows.
            $liveDefault = $liveColumn->getDefault();
            if ($targetColumn->getAutoincrement() && !$liveColumn->getAutoincrement()
                && is_string($liveDefault) && str_starts_with(strtolower($liveDefault), 'nextval(')
            ) {
                $liveColumn->setAutoincrement(true);
                $liveColumn->setDefault($targetColumn->getDefault());
            }
        }
    }

    /**
     * Are two column defaults the same stored value, ignoring representation?
     * Covers the CURRENT_TIMESTAMP string-vs-expression and the numeric
     * string-vs-number spellings. A null on only one side is a genuine change.
     */
    private static function defaultsEquivalent(mixed $live, mixed $target): bool
    {
        if ($live === null || $target === null) {
            return $live === $target;
        }

        $isCurrentTimestamp = static fn(mixed $d): bool => $d instanceof CurrentTimestamp
            || (is_string($d) && preg_match('/^current_timestamp(\(\d*\))?$/i', $d) === 1);
        if ($isCurrentTimestamp($live) && $isCurrentTimestamp($target)) {
            return true;
        }

        if (is_numeric($live) && is_numeric($target)) {
            return (float) $live === (float) $target;
        }

        return false;
    }

    /**
     * Add to the target any column that exists live but is not declared, so the
     * diff never drops it.
     *
     * This is the additive-merge policy: a declarative migration creates and
     * modifies, but never drops a column it does not know about. It protects
     * columns a third-party module added to a core table, and it keeps the
     * migration safe by construction rather than by a destructive-statement
     * denylist. For a clean core install there are no undeclared columns, so
     * this is a no-op and full parity with a fresh install is preserved.
     *
     * The merged column is copied from the (already comment-stripped) live
     * column, so the Comparator then sees it as equal.
     */
    private static function preserveUndeclaredColumns(Table $live, Table $target): void
    {
        foreach ($live->getColumns() as $column) {
            if ($target->hasColumn($column->getObjectName()->toString())) {
                continue;
            }
            // Column::toArray() flattens platform options (charset, collation,
            // ...) into the top level, but Table::addColumn() only accepts the
            // generic column options and rejects the rest. Keep the generic
            // keys; route everything else back through platformOptions.
            $generic = ['default', 'notnull', 'length', 'precision', 'scale', 'fixed', 'unsigned', 'autoincrement', 'columnDefinition', 'comment', 'values'];
            $options = array_intersect_key($column->toArray(), array_flip($generic));
            $platformOptions = [];
            if ($column->getCharset() !== null) {
                $platformOptions['charset'] = $column->getCharset();
            }
            if ($column->getCollation() !== null) {
                $platformOptions['collation'] = $column->getCollation();
            }
            $options['platformOptions'] = $platformOptions;
            $target->addColumn($column->getObjectName()->toString(), Type::lookupName($column->getType()), $options);
        }
    }

    /**
     * Is this index the table's primary key? In DBAL 4 the primary key is a
     * separate constraint, but introspection still surfaces it among the
     * table's indexes under the engine's primary-key name ("PRIMARY" on MySQL,
     * "<table>_pkey" on Postgres). We must never treat it as a phantom or a
     * rename candidate, so match it by the primary-key constraint's name.
     */
    private static function isPrimaryIndex(Table $table, Index $index): bool
    {
        $name = strtolower($index->getObjectName()->toString());
        if ($name === 'primary') {
            return true;
        }
        $primaryKey = $table->getPrimaryKeyConstraint();
        $primaryName = $primaryKey?->getObjectName()?->toString();

        return $primaryName !== null && strtolower($primaryName) === $name;
    }
}
