<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 */

declare(strict_types=1);

uses(Tests\MahoBackendTestCase::class);

/**
 * Run $fn with a time zone far from UTC on store 1 and on the current store.
 */
function segmentationCouponInStoreTimezone(callable $fn): void
{
    $stores = [Mage::app()->getStore(1), Mage::app()->getStore()];
    $originals = array_map(
        fn(Mage_Core_Model_Store $store) => $store->getConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE),
        $stores,
    );
    foreach ($stores as $store) {
        $store->setConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE, 'Pacific/Kiritimati');
    }
    try {
        $fn();
    } finally {
        foreach ($stores as $i => $store) {
            $store->setConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE, $originals[$i]);
        }
    }
}

function segmentationCouponCustomer(): Mage_Customer_Model_Customer
{
    $customer = Mage::getModel('customer/customer');
    $customer->setWebsiteId(1)
        ->setStoreId(1)
        ->setEmail('segmentation-coupon-' . uniqid() . '@example.com')
        ->setFirstname('Segmentation')
        ->setLastname('Coupon')
        ->setGroupId(1)
        ->save();
    return $customer;
}

function segmentationCouponRule(): Mage_SalesRule_Model_Rule
{
    $rule = Mage::getModel('salesrule/rule');
    $rule->setName('Segmentation coupon ' . uniqid())
        ->setIsActive()
        ->setWebsiteIds([1])
        ->setCustomerGroupIds([0, 1])
        ->setCouponType(Mage_SalesRule_Model_Rule::COUPON_TYPE_SPECIFIC)
        ->setUseAutoGeneration()
        ->setSimpleAction('by_percent')
        ->setDiscountAmount(10)
        ->save();
    return $rule;
}

function segmentationCouponStoreTime(string $modify): string
{
    return Mage::app()->getLocale()->utcToStore(1)->modify($modify)->format(Mage_Core_Model_Locale::DATETIME_FORMAT);
}

describe('the expiration of a customer segmentation coupon', function () {
    test('a generated coupon expires in the time of the store of the customer', function () {
        segmentationCouponInStoreTimezone(function () {
            $customerId = (int) segmentationCouponCustomer()->getId();
            $code = Mage::helper('customersegmentation/coupon')
                ->generateCustomerCoupon($customerId, (int) segmentationCouponRule()->getId(), 'TZ', 2);

            $stored = (string) Mage::getModel('salesrule/coupon')->loadByCode($code)->getData('expiration_date');

            expect(abs(strtotime($stored) - strtotime(segmentationCouponStoreTime('+2 days'))))->toBeLessThan(60);
        });
    });

    test('an unused coupon that expired in store time is not active', function () {
        segmentationCouponInStoreTimezone(function () {
            $customerId = (int) segmentationCouponCustomer()->getId();
            $rule = segmentationCouponRule();
            Mage::getModel('salesrule/coupon')
                ->setRuleId((int) $rule->getId())
                ->setCode('TZ' . $customerId . strtoupper(uniqid()))
                ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                ->setExpirationDate(segmentationCouponStoreTime('-1 hour'))
                ->save();

            $activeCoupon = Mage::helper('customersegmentation/coupon')
                ->getCustomerActiveCoupon($customerId, (int) $rule->getId(), 1);

            expect($activeCoupon)->toBeNull();
        });
    });

    test('the email shows the stored expiration date without a time zone shift', function () {
        segmentationCouponInStoreTimezone(function () {
            $variables = Mage::helper('customersegmentation/coupon')
                ->getCouponTemplateVariables('TZCODE', '2026-10-05 23:00:00');

            expect($variables['coupon_expires_formatted'])->toBe('Oct 5, 2026');
        });
    });
});
