<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Maho_Blog_Block_Post_List $this */
$posts = $this->getPosts();
?>

<h1><?= $this->__('Blog') ?></h1>

<?php foreach ($posts->getItems() as $post): ?>
    <div>
        <div><strong><?= $post->getTitle() ?></strong></div>
        <div class="blog_post_date"><?= $post->getPublishedAt() ?></div>
        <div><?= $post->getContent() ?></div>
    </div>
<?php endforeach ?>
