<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Maho_Blog_Block_Post_View $this */
$post = $this->getPost();
?>

<div class="blog_post_date"><?= $this->formatDate($post->getPublishDate() ?? $post->getCreatedAt()) ?></div>

<?php if ($post->hasImage()): ?>
    <img class="blog_post_image" src="<?= $post->getImageUrl() ?>" alt="<?= $this->escapeHtml($post->getTitle()) ?>" />
<?php endif ?>

<div><?= $post->getFilteredContent() ?></div>
