<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var Mage_Catalog_Block_Product_Compare_Sidebar $this */
?>
<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<?php if ($_items): ?>
<div class="block block-list block-compare">
    <div class="block-title">
        <strong><span><?= $this->__('Compare Products') ?>
            <?php if ($_helper->getItemCount() > 0): ?>
                <small><?= $this->__('(%d)', $_helper->getItemCount()) ?></small>
            <?php endif ?>
        </span></strong>
    </div>
    <div class="block-content">
    <?php if ($_helper->getItemCount() > 0): ?>
        <ol id="compare-items">
        <?php foreach ($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?= $_item->getId() ?>">
                <form action="<?= $this->escapeUrl($_helper->getRemoveUrl($_item)) ?>" method="post" class="inline" onsubmit="return confirm('<?= $this->jsQuoteEscape($this->__('Are you sure you would like to remove this item from the compare products?')) ?>')">
                    <?= $this->getBlockHtml('formkey') ?>
                    <button type="submit" title="<?= $this->quoteEscape($this->__('Remove This Item')) ?>" class="btn-link btn-remove"><?= $this->__('Remove This Item') ?></button>
                </form>
                <p class="product-name"><a href="<?= $this->getProductUrl($_item) ?>"><?= $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
        <?php endforeach ?>
        </ol>
        <div class="actions">
            <button type="button" title="<?= $this->quoteEscape($this->__('Compare')) ?>" class="button" onclick="popWin('<?= $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?= $this->__('Compare') ?></button>
            <form action="<?= $this->escapeUrl($_helper->getClearListUrl()) ?>" method="post" class="inline" onsubmit="return confirm('<?= $this->jsQuoteEscape($this->__('Are you sure you would like to remove all products from your comparison?')) ?>')">
                <?= $this->getBlockHtml('formkey') ?>
                <button type="submit" class="btn-link"><?= $this->__('Clear All') ?></button>
            </form>
        </div>
    <?php else: ?>
        <p class="empty"><?= $this->__('You have no items to compare.') ?></p>
    <?php endif ?>
    </div>
</div>
<?php endif ?>
