<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Catalog_Product_View_Profile $this */
?>
<?php if ($dateHtml = $this->getDateHtml()): ?>
<dl>
    <dt>
        <label for="<?= $this->getDateHtmlId() ?>"><?= $this->__('Recurring Profile Start Date') ?></label>
    </dt>
    <dd>
        <?= $dateHtml ?>
    </dd>
</dl>
<?php endif ?>
