<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Catalog_Product_View_Profile $this */
?>
<?php if ($dateHtml = $this->getDateHtml()): ?>
<dl>
    <dt>
        <label for="<?= $this->getDateHtmlId() ?>"><?= $this->__('Recurring Profile Start Date') ?></label>
    </dt>
    <dd>
        <?= $dateHtml ?>
    </dd>
</dl>
<?php endif ?>
