<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?= nl2br($this->escapeHtml($this->getObjectData($row, 'value'))) ?></address>
<?php endforeach ?>

<?php else: ?>

<table cellspacing="0" class="form-list">
<tbody>
<?php foreach ($this->getRenderedInfo() as $row):?>
<?php $isAmount = $this->getObjectData($row, 'is_amount');?>
    <tr>
    <td class="label"><label><?= $this->escapeHtml($this->getObjectData($row, 'label')) ?></label></td>
    <td<?= $isAmount ? ' class="a-right"' : '' ?>>
        <strong><?= $this->renderRowValue($row) ?></strong>
    </td>
    </tr>
<?php endforeach ?>
</tbody>
</table>
<?php endif ?>
