<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Reports_Block_Product_Widget_Bestsellers $this */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-bestsellers">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?= $this->__('Bestsellers') ?></span></strong>
        </div>
        <div class="block-content">
            <?= $this->getPagerHtml() ?>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol id="widget-bestsellers-<?= $suffix ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <p class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                </li>
            <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif ?>
