<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Categories tree for urlrewrites
 *
 * @var Mage_Adminhtml_Block_Urlrewrite_Category_Tree $this
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= Mage::helper('adminhtml')->__('Select Category') ?></h4>
    </div>
    <fieldset>
        <input type="hidden" name="categories" id="product_categories" value="" />
        <div id="tree-div" class="hor-scroll"></div>
    </fieldset>
</div>

<?php if ($this->getRoot()): ?>
<script type="module">
    const tree = new MahoTree('tree-div', {
        showRootNode: false,
        lazyload: {
            nodeParameter: 'id',
            dataUrl: '<?= $this->getLoadTreeUrl() ?>',
        },
        selectable: {
            mode: 'single',
            showInputs: false,
            onSelect: (selected) => {
                if (selected.length === 1) {
                    window.location = window.location + '/' + selected[0].id;
                }
            }
        },
    });
    tree.setRootNode(<?= $this->getTreeArray(null, true) ?>);
</script>
<?php endif ?>
