<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Urlrewrites edit container
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Edit
 * @var Mage_Adminhtml_Block_Urlrewrite_Edit $this
 */
?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml() ?></p>
</div>

<?= $this->getChildHtml() ?>

<?php if ($this->getChild('form')): ?>
<script type="text/javascript">
    var editForm = new varienForm('edit_form', '<?= $this->getValidationUrl() ?>');
</script>
<?php endif ?>
