<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * Urlrewrites edit container
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Edit
 * @var Mage_Adminhtml_Block_Urlrewrite_Edit $this
 */
?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml() ?></p>
</div>

<?= $this->getChildHtml() ?>

<?php if ($this->getChild('form')): ?>
<script>
    var editForm = new varienForm('edit_form', '<?= $this->getValidationUrl() ?>');
</script>
<?php endif ?>
