<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * Urlrewrites edit mode selector
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Selector
 * @var Mage_Adminhtml_Block_Urlrewrite_Selector $this
 */
?>
<div class="entry-edit">
<div class="fieldset">

<table cellspacing="0" class="form-list">
    <tr>
        <td class="label"><?= $this->getSelectorLabel() ?></td>
        <td class="value">
            <?php $url = Mage::helper('adminhtml')->getUrl('*/*/*')?>
            <select class="select" onchange="window.location = this.value;">
            <?php foreach ($this->getModes() as $mode => $label): ?>
                <option <?= ($this->isMode($mode) ? 'selected="selected" ' :'' ) ?>value="<?= $url . $mode ?>"><?= $label ?></option>
            <?php endforeach ?>
            </select>
        </td>
    </tr>
</table>
</div>
</div>
