<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
    <div class="ratings-container">
        <?php foreach ($this->getRating() as $_rating): ?>
        <?php if($_rating->getPercent()): ?>
            <div class="ratings">
               <?= $this->escapeHtml($_rating->getRatingCode()) ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?= ceil($_rating->getPercent()) ?>%;"></div>
                </div>
            </div>
        <?php endif ?>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <?= Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif ?>
