<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Review_Rating_Summary $this */
?>
<?php if($this->getRatingSummary()->getCount()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?= ceil($this->getRatingSummary()->getSum() / ($this->getRatingSummary()->getCount())) ?>%;"></div>
    </div>
<?php else: ?>
    <?= Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif ?>
