<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Configurable $this */

$product = $this->getProduct();
$attributes = $this->getAllowAttributes();
$skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck();
?>

<?php if (($product->isSaleable() || $skipSaleableCheck) && count($attributes)): ?>
<div>
    <h4><?= Mage::helper('catalog')->__('Associated Products') ?></h4>
    <div class="product-options">
        <dl>
        <?php foreach($attributes as $attribute): ?>
            <dt>
                <label for="attribute<?= $attribute->getAttributeId() ?>" class="required">
                    <?= $this->escapeHtml($attribute->getLabel()) ?>
                </label>
            </dt>
            <dd>
                <div class="input-box">
                    <select name="super_attribute[<?= $attribute->getAttributeId() ?>]" id="attribute<?= $attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                        <option><?= Mage::helper('catalog')->__('Choose an Option...') ?></option>
                    </select>
                </div>
            </dd>
        <?php endforeach ?>
        </dl>
    </div>
</div>
<script>
    window.productConfigure?.registerConfigurableFieldset(<?= $this->getJsonConfig() ?>);
</script>
<?php endif ?>
