<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Grouped $this */

$skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck();
?>
<div id="catalog_product_composite_configure_fields_grouped" class="grid">
    <h4><?= Mage::helper('catalog')->__('Associated Products') ?></h4>
    <div class="product-options">
        <?php $product = $this->getProduct(); ?>
        <?php $this->setPreconfiguredValue(); ?>
        <?php $associatedProducts = $this->getAssociatedProducts(); ?>
        <?php $hasAssociatedProducts = count($associatedProducts) > 0; ?>
        <?php if ((!$product->isAvailable() && !$skipSaleableCheck) || !$hasAssociatedProducts): ?>
            <p class="availability out-of-stock"><?= Mage::helper('catalog')->__('Availability:') ?> <span><?= Mage::helper('catalog')->__('Out of stock') ?></span></p>
        <?php endif ?>
        <table class="data-table grouped-items-table" id="super-product-table">
            <col />
            <col />
            <col />
            <col />
            <col width="1" />
            <thead>
                <tr class="headings">
                    <th><?= Mage::helper('catalog')->__('ID') ?></th>
                    <th><?= Mage::helper('catalog')->__('SKU') ?></th>
                    <th><?= Mage::helper('catalog')->__('Product Name') ?></th>
                <?php if ($this->getCanShowProductPrice($product)): ?>
                    <th class="a-right"><?= Mage::helper('catalog')->__('Price') ?></th>
                <?php endif ?>
                <?php if ($product->isSaleable() || $skipSaleableCheck): ?>
                    <th class="a-center"><?= Mage::helper('catalog')->__('Qty') ?></th>
                <?php endif ?>
                </tr>
            </thead>
            <tbody>
            <?php if ($hasAssociatedProducts): ?>
                <?php $i = 0 ?>
            <?php foreach ($associatedProducts as $item): ?>
                <?php $finalPriceInclTax = $this->helper('tax')->getPrice($item, $item->getFinalPrice(), true) ?>
                <tr>
                    <td><?= $item->getId() ?></td>
                    <td><?= $this->escapeHtml($item->getSku()) ?></td>
                    <td><?= $this->escapeHtml($item->getName()) ?></td>
                    <?php if ($this->getCanShowProductPrice($product)): ?>
                    <td class="a-right">
                        <?php if ($this->getCanShowProductPrice($item)): ?>
                        <?= $this->getPriceHtml($item, true) ?>
                        <?php endif ?>
                    </td>
                    <?php endif ?>
                    <?php if ($product->isSaleable() || $skipSaleableCheck): ?>
                    <td class="a-center">
                    <?php if ($item->isSaleable() || $skipSaleableCheck): ?>
                        <input type="number" name="super_group[<?= $item->getId() ?>]" id="super_group[<?= $item->getId() ?>]" maxlength="12" min="0" value="<?= $item->getQty()*1 ?>" title="<?= $this->quoteEscape(Mage::helper('catalog')->__('Qty')) ?>" class="input-text qty" />
                        <input type="hidden" value="1" price="<?= $this->getCurrencyPrice($item->getPrice()) ?>" qtyId="super_group[<?= $item->getId() ?>]" />
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                    </td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
            <?php else: ?>
               <tr>
                   <td colspan="<?= $product->isSaleable() || $skipSaleableCheck ? 4 : 3 ?>">
                       <?= Mage::helper('catalog')->__('No options of this product are available.') ?>
                   </td>
               </tr>
            <?php endif ?>
            </tbody>
        </table>
    </div>
</div>
