<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2017-2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Qty $this */ ?>
<div id="product_composite_configure_fields_qty" class="<?= $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <div class="product-options">
        <dl>
            <dt><label><?= Mage::helper('catalog')->__('Quantity') ?></label> <input id="product_composite_configure_input_qty" class="input-text" type="text" name="qty" value="<?= $this->getQtyValue() * 1 ?>"></dt>
        </dl>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var input = document.getElementById('product_composite_configure_input_qty');
    if(input.value.length == 0) {
        input.value = "1";
    }
    //]]>
</script>

