<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2017-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Qty $this */
?>
<div>
    <div class="product-options">
        <dl>
            <dt>
                <label>
                    <?= Mage::helper('catalog')->__('Quantity') ?>
                    <input type="number" min="1" name="qty" value="<?= $this->getQtyValue() ?>" class="input-text validate-digits validate-greater-than-zero">
                </label>
            </dt>
        </dl>
    </div>
</div>
