<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2017-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Qty $this */
?>
<div>
    <div class="product-options">
        <dl>
            <dt>
                <label>
                    <?= Mage::helper('catalog')->__('Quantity') ?>
                    <input type="number" min="1" name="qty" value="<?= $this->getQtyValue() ?>" class="input-text validate-digits validate-greater-than-zero">
                </label>
            </dt>
        </dl>
    </div>
</div>
