<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Widget_Form_Container $this */
$headerHtml = $this->getHeaderHtml();
$headerButtons = $this->getButtonsHtml('header');
?>
<?= $this->getFormInitScripts() ?>
<?php if ($this->getHeaderText() || $headerButtons): ?>
    <div class="content-header">
        <?= $headerHtml ?>
        <p class="form-buttons"><?= $headerButtons ?></p>
    </div>
<?php endif ?>
<?= $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?= $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif ?>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '<?= $this->getValidationUrl() ?>');
</script>
<?= $this->getFormScripts() ?>
