<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
    $columns = $this->getColumns();
?>
<table class="clean-table linearize-table" id="wishlist-table">
    <thead>
        <tr>
            <?php
                /* @var $column Mage_Wishlist_Block_Customer_Wishlist_Item_Column */
                foreach ($columns as $column):
                    $_blockName = str_replace('.','-',strtolower($column->getNameInLayout()));
            ?>
                <th class="<?= $_blockName ?>"><?= $column->getTitle() ?></th>
            <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->getItems())): ?>
            <?php foreach ($this->getItems() as $item): ?>
                <tr id="item_<?= $item->getId() ?>">
                    <?php
                        foreach ($columns as $key => $column):
                            $_blockName = str_replace('.','-',strtolower($column->getNameInLayout()));

                            /* Override default column title in layout, useful for certain cases like select all box */
                            if ($column->getRwdTitle()) {
                                $_rwdLabel = $column->getRwdTitle();
                            } else {
                                $_rwdLabel = ($column->getTitle()) ? $column->getTitle() : false;
                            }
                    ?>
                        <td class="<?= 'wishlist-cell'.$key ?> <?= $_blockName ?>"<?php if($_rwdLabel): ?> data-rwd-label="<?= $_rwdLabel ?>"<?php endif ?>><?php $column->setItem($item); echo $column->toHtml($item);?></td>
                    <?php endforeach ?>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <td colspan="<?= count($columns) ?>" class="wishlist-empty"><?= $this->__('This Wishlist has no Items') ?></td>
        <?php endif ?>
    </tbody>
</table>
<?php foreach ($columns as $column): ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach ?>
<script type="text/javascript">
<?php foreach ($columns as $column): ?>
    <?= $column->getJs() ?>
<?php endforeach ?>
</script>
