<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<div class="entry-edit" id="import_validation_container" style="display:none;">
    <div class="entry-edit-head">
        <h4 id="import_validation_container_header"><?= $this->__('Validation Results') ?></h4>
    </div>
    <div id="import_validation_messages" class="fieldset "><!-- --></div>
</div>
