<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<div class="cards-list">

<?php if (!$this->getHideTitle()): ?>
    <div class="bold"><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></div>
<?php endif ?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

    <?php foreach ($cards as $key => $card): ?>
        <?php if ($showCount): ?>
            <span><?= sprintf($this->__('Credit Card %s'), $key + 1) ?></span>
        <?php endif ?>

        <table class="info-table<?php if ($showCount):?> offset<?php endif ?>">
            <tbody>
            <?php foreach ($card as $_label => $_value):?>
            <tr>
                <td><?= $this->escapeHtml($_label) ?>:</td>
                <td><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></td>
            </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endforeach ?>

</div>
