<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Paygate_Block_Authorizenet_Info_Cc $this */
?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
       <?= sprintf($this->__('Credit Card %s'), $key + 1) ?>
       {{pdf_row_separator}}
    <?php endif ?>

    <?php foreach ($card as $_label => $_value):?>
        <?= $_label ?>: <?= implode(' ', $this->getValueAsArray($_value)) ?>{{pdf_row_separator}}
     <?php endforeach ?>
<?php endforeach ?>
