<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Paygate_Block_Authorizenet_Info_Cc $this */
?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
       <?= sprintf($this->__('Credit Card %s'), $key + 1) ?>
       {{pdf_row_separator}}
    <?php endif ?>

    <?php foreach ($card as $_label => $_value):?>
        <?= $_label ?>: <?= implode(' ', $this->getValueAsArray($_value)) ?>{{pdf_row_separator}}
     <?php endforeach ?>
<?php endforeach ?>
