<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_View_History $this */
?>
<div id="order_history_block">
    <?php if ($this->canAddComment()):?>
    <div id="history_form" class="order-history-form">
        <div><?= Mage::helper('sales')->__('Add Order Comments') ?></div>
        <span class="field-row">
            <label class="normal" for="history_status"><?= Mage::helper('sales')->__('Status') ?></label><br/>
            <select name="history[status]" class="select" id="history_status">
            <?php foreach ($this->getStatuses() as $_code=>$_label): ?>
                <option value="<?= $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif ?>><?= $_label ?></option>
            <?php endforeach ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?= Mage::helper('sales')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
        </span>
        <div class="f-left">
            <?php if ($this->canSendCommentEmail()): ?>
                <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label class="normal" for="history_notify"> <?= Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
            <?php endif ?>
            <input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?= Mage::helper('sales')->__('Visible on Frontend') ?></label>
        </div>
        <div class="f-right">
            <?= $this->getChildHtml('submit_button') ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <?php endif ?>
    <ul class="note-list">
    <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
        <li>
            <div class="note-header">
                <span>
                    <strong><?= $this->helper('core')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
                    <?= $this->helper('core')->formatTime($_item->getCreatedAtDate(), 'medium') ?>
                </span>
                <strong><?= $_item->getStatusLabel() ?></strong>
                <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                <span class="icon" title="<?= $this->helper('sales')->__('Customer Notification Not Applicable') ?>"><?= $this->getIconSvg('message-question') ?></span>
                <?php elseif ($_item->getIsCustomerNotified()): ?>
                <span class="icon" title="<?= $this->helper('sales')->__('Customer Notified') ?>"><?= $this->getIconSvg('message') ?></span>
                <?php else: ?>
                <span class="icon" title="<?= $this->helper('sales')->__('Customer Not Notified') ?>"><?= $this->getIconSvg('message-off') ?></span>
                <?php endif ?>
            </div>
            <?php if ($_item->getComment()): ?>
                <div><?= $this->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
            <?php endif ?>
        </li>
    <?php endforeach ?>
    </ul>
    <script type="text/javascript">
        if (document.getElementById('order_status')) document.getElementById('order_status').textContent = '<?= $this->jsQuoteEscape($this->getOrder()->getStatusLabel()) ?>';
    </script>
</div>
