<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_View_Items $this */
?>
<?php $_order = $this->getOrder() ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col>
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <col width="1">
        <thead>
            <tr class="headings">
                <th><?= $this->helper('sales')->__('Product') ?></th>
                <th><span class="nobr"><?= $this->helper('sales')->__('Item Status') ?></span></th>
                <th><span class="nobr"><?= $this->helper('sales')->__('Original Price') ?></span></th>
                <th><?= $this->helper('sales')->__('Price') ?></th>
                <th class="a-center"><?= $this->helper('sales')->__('Qty') ?></th>
                <th><?= $this->helper('sales')->__('Subtotal') ?></th>
                <th><span class="nobr"><?= $this->helper('sales')->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?= $this->helper('sales')->__('Tax Percent') ?></span></th>
                <th><span class="nobr"><?= $this->helper('sales')->__('Discount Amount') ?></span></th>
                <th class="last"><span class="nobr"><?= $this->helper('sales')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?= $i%2?'even':'odd' ?>">
                <?= $this->getItemHtml($_item) ?>
                <?= $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach ?>
    </table>
  </div>
</div>
<br>
