<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Catalog_Block_Product_View_Options_Type_Date $this */
$option = $this->getOption();
$optionId = $option->getId();
?>
<dt>
    <label<?= $option->getIsRequired() ? ' class="required"' : '' ?>><?=  $this->escapeHtml($option->getTitle()) ?></label>
    <?= $this->getFormatedPrice() ?>
</dt>
<dd>
<?php if ($option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME || $option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>
    <?= $this->getDateHtml() ?>
<?php endif ?>

<?php if ($option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_TIME): ?>
    <span class="time-picker"><?= $this->getTimeHtml() ?></span>
<?php endif ?>

    <input type="hidden" name="validate_datetime_<?= $optionId ?>" class="validate-datetime-<?= $optionId ?>" value="">
</dd>

<script>
<?php if ($option->getIsRequired()): ?>
    Validation.add(
        'validate-datetime-<?= $optionId ?>',
        '<?= $this->jsQuoteEscape( Mage::helper('catalog')->__('This is a required option') ) ?>',
        function(v, el) {
            const parts = el.parentNode.querySelectorAll('.datetime-picker[id^="options_<?= $optionId ?>"]:not([id$=day_part])');
            return [...parts].every(el => el.value !== '');
        }
    );
<?php else: ?>
    Validation.add(
        'validate-datetime-<?= $optionId ?>',
        '<?= $this->jsQuoteEscape( Mage::helper('catalog')->__('Field is not complete') ) ?>',
        function(v, el) {
            const parts = el.parentNode.querySelectorAll('.datetime-picker[id^="options_<?= $optionId ?>"]:not([id$=day_part])');
            return [...parts].every(el => el.value === '')
                || [...parts].every(el => el.value !== '');
        }
    );
<?php endif ?>
</script>
