<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Catalog_Block_Product_View_Options_Type_Text $this */ ?>
<?php $_option = $this->getOption(); ?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?=  $this->escapeHtml($_option->getTitle()) ?></label>
    <?= $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_FIELD): ?>
        <input type="text" id="options_<?= $_option->getId() ?>_text" class="input-text<?= $_option->getIsRequire() ? ' required-entry' : '' ?> <?= $_option->getMaxCharacters() ? ' validate-length maximum-length-' . $_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?= $_option->getId() ?>]" value="<?= $this->escapeHtml($this->getDefaultValue()) ?>" price="<?= $this->getCurrencyPrice($_option->getPrice(true)) ?>" />
    <?php elseif ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_AREA): ?>
        <textarea id="options_<?= $_option->getId() ?>_text" class="<?= $_option->getIsRequire() ? ' required-entry' : '' ?> <?= $_option->getMaxCharacters() ? ' validate-length maximum-length-' . $_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?= $_option->getId() ?>]" rows="5" cols="25" price="<?= $this->getCurrencyPrice($_option->getPrice(true)) ?>"><?= $this->escapeHtml($this->getDefaultValue()) ?></textarea>
    <?php endif ?>
    <?php if ($_option->getMaxCharacters()): ?>
        <p class="note"><?= Mage::helper('catalog')->__('Maximum number of characters:')?> <strong><?= $_option->getMaxCharacters() ?></strong></p>
    <?php endif ?>
    </div>
</dd>
