<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * @var Mage_Adminhtml_Block_Tax_Rate_Toolbar_Add $this
 * @var string $header
 */
?>
<div class="content-header">
    <h3><?= $header ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getChildHtml('addButton') ?>
    </p>
</div>
