<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?= $header ?></h3></td>
            <td class="form-buttons">
                <?= $this->getBackButtonHtml() ?>
                <?= $this->getResetButtonHtml() ?>
                <?= $this->getDeleteButtonHtml() ?>
                <?= $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php if( $form ): ?>
<?= $form->toHtml() ?>
<script type="text/javascript">
    var wigetForm = new varienForm('<?= $form->getForm()->getId() ?>');
</script>
<?php endif ?>
