<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Adminhtml_Block_Tax_Rate_Toolbar_Save $this
 * @var string $header
 * @var Mage_Adminhtml_Block_Tax_Rate_Form $form
 */
?>
<div class="content-header">
    <h3><?= $header ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php if( $form ): ?>
<?= $form->toHtml() ?>
<script type="text/javascript">
    var wigetForm = new varienForm('<?= $form->getForm()->getId() ?>');
</script>
<?php endif ?>
