<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * "Grant Access" button
 *
 * @var Mage_Oauth_Block_Authorize_ButtonBaseAbstract $this
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?= $this->__('Authorize application') ?></h1>
        </div>
        <div class="form-box">
            <div>
                <div id="messages">
                    <?= $this->getMessagesBlock()->toHtml() ?>
                </div>
                <?php if (!$this->getHasException()) : ?>
                    <h2><?= $this->__('<strong>%s</strong> requests access to your account', $this->escapeHtml($this->getConsumer()->getName())) ?></h2>
                    <p><?= $this->__('After authorization application will have access to you account.') ?></p>
                    <form id="oauth_authorize_confirm" action="<?= $this->getConfirmUrl() ?>" method="get">
                        <input type="hidden" name="oauth_token" value="<?= $this->escapeHtml($this->getToken()) ?>">
                        <button type="submit" class="button" title="<?= $this->quoteEscape($this->__('Authorize')) ?>">
                            <?= $this->__('Authorize') ?></button>
                    </form>
                    <form id="oauth_authorize_reject" action="<?= $this->getRejectUrl() ?>" method="get">
                        <input type="hidden" name="oauth_token" value="<?= $this->escapeHtml($this->getToken()) ?>">
                        <button type="submit" class="button" title="<?= $this->quoteEscape($this->__('Reject')) ?>">
                            <?= $this->__('Reject') ?></button>
                    </form>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
