<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * "Grant Access" button
 *
 * @var Mage_Core_Block_Template $this
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?= $this->__('Confirmation Of Authorization') ?></h1>
            <?= $this->getMessagesBlock()->toHtml() ?>
            <?php if (!$this->getHasException()): ?>
                <p><?= $this->__('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?= $this->__('Verifier code: %s', $this->getVerifier()) ?></p>
            <?php endif ?>
        </div>
        <div class="bottom"></div>
    </div>
</div>
