<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Head block Oauth simple pages
 *
 * @var Mage_Adminhtml_Block_Page_Head $this
 */

//Code partially copied from adminhtml/default/default/template/page/head.phtml
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>"/>
<title><?= htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" type="image/svg+xml" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" sizes="any">
<link rel="icon" type="image/png" href="<?= $this->getSkinUrl('images/favicon.png') ?>">

<script type="text/javascript">
//<![CDATA[
    var BASE_URL = '<?= $this->getUrl('*') ?>';
    var SKIN_URL = '<?= $this->jsQuoteEscape($this->getSkinUrl()) ?>';
    var FORM_KEY = '<?= $this->getFormKey() ?>';
//]]>
</script>

<?= $this->getCssJsHtml() ?>
