<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * Head block Oauth simple pages
 *
 * @var Mage_Adminhtml_Block_Page_Head $this
 */

//Code partially copied from adminhtml/default/default/template/page/head.phtml
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>">
<title><?= htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<?= Mage::helper('page')->getFaviconHtml() ?>

<script>
    var BASE_URL = '<?= $this->getUrl('*') ?>';
    var SKIN_URL = '<?= $this->getSkinUrl() ?>';
    var FORM_KEY = '<?= $this->getFormKey() ?>';
</script>

<?= $this->getCssJsHtml() ?>
