<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Authorize rejection simple template
 *
 * @var Mage_Oauth_Block_AuthorizeBaseAbstract $this
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?= $this->__('Rejection Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <div id="messages">
                <?= $this->getMessagesBlock()->toHtml() ?>
            </div>
            <button type="submit" class="button" onclick="window.close();" title="<?= $this->quoteEscape($this->__('Close')) ?>">
                <?= $this->__('Close') ?>
            </button>
        </div>
    </div>
</div>
