<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?= $this->__('Rejection Of Authorization') ?></h1>
            <?= $this->getMessagesBlock()->toHtml() ?>
        </div>
        <div class="bottom"></div>
    </div>
</div>
