<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Abstract $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="fieldset-legend <?= $this->getHeaderCssClass() ?: '' ?>"><?= $this->getHeaderText() ?></h4>
        <div class="form-buttons"><?= $this->getButtonsHtml() ?></div>
    </div>
    <div class="fieldset">
        <?= $this->getChildHtml('', true, true) ?>
    </div>
</div>
