<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Form $this */
?>
<script>
    var order = new AdminOrder(<?= $this->getOrderDataJson() ?>);
    order.setLoadBaseUrl('<?= $this->getLoadBlockUrl() ?>');
    var payment = {};
    payment.switchMethod = order.switchPaymentMethod.bind(order);
</script>
<form id="edit_form" action="<?= $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?= $this->getBlockHtml('formkey') ?>
    <div id="order-message">
        <?= $this->getChildHtml('message') ?>
    </div>
    <div id="order-customer-selector" style="display:<?= $this->getCustomerSelectorDisplay() ?>">
        <?php if (!$this->getCustomerId()): ?>
            <?= $this->getChildHtml('customer') ?>
        <?php endif ?>
    </div>
    <div id="order-store-selector" style="display:<?= $this->getStoreSelectorDisplay() ?>">
        <?= $this->getChildHtml('store') ?>
    </div>
    <div id="order-data" style="display:<?= $this->getDataSelectorDisplay() ?>">
        <?= $this->getChildHtml('data') ?>
    </div>
</form>
