<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Giftmessage $this */
?>
<?php if ($this->canDisplayGiftmessage()): ?>
<?php $_items = $this->getItems(); ?>
<fieldset id="order-giftmessage" class="fieldset-wide">
    <h4><?= Mage::helper('sales')->__('Gift Message for the Entire Order') ?></h4>
    <small><?= Mage::helper('sales')->__('You can leave a box blank if you don\'t wish to add a gift message for whole order') ?></small>
    <?= $this->getFormHtml($this->getQuote(), 'main') ?>
</fieldset>
<script type="text/javascript">
    order.giftmessageFieldsBind('order-giftmessage');
</script>
<?php endif ?>
