<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Giftmessage $this */
?>
<?php if ($this->canDisplayGiftmessage()): ?>
<?php $_items = $this->getItems(); ?>
<div id="order-giftmessage">
<div class="clear"></div>
<div class="giftmessage-order-create box-left">
    <div class="entry-edit">
        <div><?= Mage::helper('sales')->__('Gift Message for the Entire Order') ?></div><br>
        <div class="fieldset">
            <div>
                <div class="entire-order">
                    <h5><?= Mage::helper('sales')->__('You can leave a box blank if you don\'t wish to add a gift message for whole order') ?></h5>
                    <?= $this->getFormHtml($this->getQuote(), 'main') ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<script>
    order.giftmessageFieldsBind('order-giftmessage');
</script>
</div>
<?php endif ?>
