<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<script>
    order.sidebarHide();
    window.addEventListener('load', function() {
        if (window.productConfigure) {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?= $this->getUrl('*/sales_order_create/configureProductToAdd') ?>'
            });
            productConfigure.addListType('quote_items', {
                urlFetch: '<?= $this->getUrl('*/sales_order_create/configureQuoteItems') ?>'
            });
        }
    });
</script>
