<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?= $this->__('New Products') ?></span></strong>
        </div>
        <div class="block-content">
            <?= $this->getPagerHtml() ?>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-images-list" id="widget-new-products-<?= $suffix ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(76) ?>" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(152) ?> 2x" width="76" height="76" alt="<?= $this->stripTags($_product->getName(), null, true) ?>" /></a>
                </li>
            <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif ?>
