<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View $this */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->isAllow() ? $this->helper('wishlist')->getAddUrlWithCustomParams($_product, [], false) : '' ?>
<?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrlCustom($_product, false); ?>

<?php if ($_wishlistSubmitUrl || $_compareUrl): ?>
    <div class="add-to-links">
        <?php if ($_wishlistSubmitUrl) : ?>
            <a href="<?= $_wishlistSubmitUrl ?>" class="link-wishlist" title="<?= $this->__('Add to Wishlist') ?>"
               onclick="productAddToCartForm.submitLight(this, this.href); return false;">
                <?= $this->getIconSvg('heart') ?>
            </a>
        <?php endif ?>
        <?php if ($_compareUrl) : ?>
            <?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])) ?>
            <a href="#" class="link-compare" title="<?= $this->__('Add to Compare') ?>"
               onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                <?= $this->getIconSvg('scale') ?>
            </a>
        <?php endif ?>
    </div>
<?php endif ?>
