<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Catalog_Block_Product_View_Attributes $this */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <table class="data-table" id="product-attribute-specs-table">
        <caption><?= $this->__('Additional Information') ?></caption>
        <col width="25%">
        <col>
        <tbody>
        <?php foreach ($_additional as $_data): ?>
            <tr>
                <th class="label"><?= $this->escapeHtml($this->__($_data['label'])) ?></th>
                <td class="data"><?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
