<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Media $this */
?>
<?php
$_product = $this->getProduct();
$mainImage = $this->helper('catalog/image')->init($_product, 'image');
?>
    <div class="product-image" role="region" aria-label="<?= $this->__('Product Images') ?>">
        <div class="product-image-gallery" style="aspect-ratio: <?= $mainImage->getOriginalWidth() ?>/<?= $mainImage->getOriginalHeight() ?>">
            <img id="image-main"
                class="gallery-image visible"
                src="<?= $mainImage ?>"
                alt="<?= $this->escapeHtml($this->getImageLabel()) ?>"
                title="<?= $this->escapeHtml($this->getImageLabel()) ?>"
                fetchpriority="high"
                width="<?= $mainImage->getOriginalWidth() ?>" height="<?= $mainImage->getOriginalHeight() ?>" />

            <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
                <?php if ($this->isGalleryImageVisible($_image)): ?>
                    <?php
                        $galleryHelper = $this->helper('catalog/image')
                            ->init($_product, 'image', $_image->getFile())
                            ->keepFrame(false);
                        $gallerySize = Mage::getStoreConfig(Mage_Catalog_Helper_Image::XML_NODE_PRODUCT_BASE_IMAGE_WIDTH);
                        if (is_numeric($gallerySize)) {
                            $galleryHelper->constrainOnly(true)->resize($gallerySize);
                        }
                    ?>
                    <img id="image-<?= $i ?>"
                         class="gallery-image" loading="lazy"
                         src="<?= $galleryHelper ?>"
                         data-zoom-image="<?= $galleryHelper ?>"
                         width="<?= $galleryHelper->getOriginalWidth() ?>" height="<?= $galleryHelper->getOriginalHeight() ?>"
                         alt="<?= $this->escapeHtml($_image->getLabel() ?: $_product->getName() . ' - ' . $this->__('Image') . ' ' . ($i+1)) ?>" />
                <?php endif ?>
                <?php $i++; endforeach; ?>
        </div>
    </div>

<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="more-views" role="region" aria-label="<?= $this->__('Additional Views') ?>">
        <ul class="product-image-thumbs">
            <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
                <?php if ($this->isGalleryImageVisible($_image)): ?>
                    <li>
                        <a class="thumb-link" href="#" title="<?= $this->escapeHtml($_image->getLabel() ?: $_product->getName() . ' - ' . $this->__('Thumbnail') . ' ' . ($i+1)) ?>" data-image-index="<?= $i ?>" role="button" aria-label="<?= $this->__('View image %s', $i+1) ?>">
                            <img src="<?= $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75) ?>"
                                 srcset="<?= $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(150) ?> 2x"
                                 width="75" height="75" alt="<?= $this->escapeHtml($_image->getLabel() ?: $_product->getName() . ' - ' . $this->__('Thumbnail') . ' ' . ($i+1)) ?>" />
                        </a>
                    </li>
                <?php endif ?>
                <?php $i++; endforeach; ?>
        </ul>
    </div>
<?php endif ?>

<?= $this->getChildHtml('after') ?>
