<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Catalog_Block_Product_View_Options $this */
$options = $this->getOptions();
?>
<?php if (count($options)): ?>
    <script type="module">
        window.validateOptionsCallback = (elmId, result) => {
            const container = document.getElementById(elmId).closest('ul.options-list');
            if (result === 'failed') {
                container.classList.remove('validation-passed');
                container.classList.add('validation-failed');
            } else {
                container.classList.remove('validation-failed');
                container.classList.add('validation-passed');
            }
        }

        window.opConfig = new Product.Options(<?= $this->getJsonConfig() ?>);
    </script>
    <dl>
    <?php foreach($options as $option): ?>
        <?= $this->getOptionHtml($option) ?>
    <?php endforeach ?>
    </dl>
<?php endif ?>
