<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Options $this */
$options = $this->getOptions();
?>
<?php if (count($options)): ?>
    <script type="module">
        window.validateOptionsCallback = (elmId, result) => {
            const container = document.getElementById(elmId).closest('ul.options-list');
            if (result === 'failed') {
                container.classList.remove('validation-passed');
                container.classList.add('validation-failed');
            } else {
                container.classList.remove('validation-failed');
                container.classList.add('validation-passed');
            }
        }

        window.opConfig = new Product.Options(<?= $this->getJsonConfig() ?>);
    </script>
    <dl>
    <?php foreach($options as $option): ?>
        <?= $this->getOptionHtml($option) ?>
    <?php endforeach ?>
    </dl>
<?php endif ?>
