<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<div class="price-box" id="product_price">
    <p class="old-price"><?= $this->__('Old Price:') ?> <?= $this->getPrice() ?></p>
    <p class="special-price"><?= $this->getPrice() ?></p>
</div>
