<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?= $this->getHeaderWidth() ?>"><?= $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?= $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?= $this->getChildHtml('store.switcher') ?>
</div>
<div>
    <?= $this->getChildHtml('grid.filter.form') ?>
</div>
<div>
    <?= $this->getGridHtml() ?>
</div>
<script type="text/javascript">
//<![CDATA[
    function filterFormSubmit() {
        var filters = $$('#filter_form input', '#filter_form select');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
        }
        var validator  = new Validation('filter_form');
        if (validator.validate()) {
            setLocation('<?= $this->getFilterUrl() ?>filter/'+btoa(Form.serializeElements(elements))+'/');
        }
    }
//]]>
</script>
