<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_Paypal
 */

/** @var Maho_Paypal_Block_Payment_Info $this */
?>
<p><strong><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>
<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
<table class="data-table" style="width: auto;">
    <?php foreach ($_specificInfo as $label => $value): ?>
    <tr>
        <td style="padding-right: 15px;"><strong><?= $this->escapeHtml($label) ?>:</strong></td>
        <td><?= $this->escapeHtml($value) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
