<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Sales_Block_Order_Info_Buttons $this */
?>
<?php  $_order = $this->getOrder() ?>
<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?= $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss f-none"><?= $this->__('Subscribe to Order Status') ?></a>
    <span class="separator">|</span>
<?php endif ?>
<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?= $this->getReorderUrl($_order) ?>" class="link-reorder"><?= $this->__('Reorder') ?></a>
    <span class="separator">|</span>
<?php endif ?>
<a href="<?= $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?= $this->__('Print Order') ?></a>
<?= $this->getChildHtml() ?>
