<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Adminhtml_Catalog_Product_Edit_Tab_Downloadable_Links $this */
?>
<?php $product = $this->getProduct() ?>
<?php $helper = Mage::helper('downloadable') ?>
<div class="fieldset">
<table cellspacing="0" class="form-list">
    <tbody>
        <tr class="headings">
            <td class="label">
                <label for="name"><?= $helper->__('Title') ?></label>
            </td>
            <td class="value">
                <input type="text" class="input-text" id="downloadable_links_title" name="product[links_title]" value="<?= $this->escapeHtml($product->getId() ? $product->getLinksTitle() : $this->getLinksTitle()) ?>" <?= ($product->getStoreId() && $this->getUsedDefault()) ? 'disabled': '' ?> />
            </td>
            <td class="scope-label">
            <?php if (!Mage::app()->isSingleStoreMode()): ?>
                <?= Mage::helper('adminhtml')->__('[STORE VIEW]') ?>
            <?php endif ?>
            </td>
            <td class="value use-default">
            <?php if($product->getStoreId()): ?>
                <input id="link_title_default" type="checkbox" name="use_default[]" value="links_title" onclick="toggleValueElements(this, this.parentNode.parentNode)" <?= $this->getUsedDefault() ? 'checked' : '' ?> />
                <label class="normal" for="link_title_default"><?= $helper->__('Use Default Value') ?></label>
            <?php endif ?>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="name"><?= $helper->__('Links can be purchased separately') ?></label>
            </td>
            <td class="value">
                <?= $this->getPurchasedSeparatelySelect() ?>
            </td>
            <td class="scope-label">
            <?php if (!Mage::app()->isSingleStoreMode()): ?>
                <?= Mage::helper('adminhtml')->__('[STORE VIEW]') ?>
            <?php endif ?>
            </td>
            <td>
                <small>&nbsp;</small>
            </td>
        </tr>
    </tbody>
</table>
<br>
<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" id="downloadable_link_table" class="data border">
            <col width="33%" />
            <col />
            <col />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr class="headings">
                    <th><?= $helper->__('Title') ?> <span class="required">*</span></th>
                    <?php if ($this->getCanReadPrice() !== false) : ?>
                    <th><?= $helper->__('Price') ?></th>
                    <?php endif ?>
                    <th><span class="nobr"><?= $helper->__('Max. Downloads') ?></span></th>
                    <th><?= $helper->__('Shareable') ?></th>
                    <th><?= $helper->__('Sample') ?></th>
                    <th><?= $helper->__('File') ?></th>
                    <th><span class="nobr"><?= $helper->__('Sort Order') ?></span></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="8" class="a-right"><?= $this->getAddButtonHtml()?>&nbsp;<?= $this->getUploadButtonHtml() ?></td>
                </tr>
            </tfoot>
            <tbody id="link_items_body">
            </tbody>
        </table>
    </div>
</div>
</div>

<template id="downloadable-link-template">
    <tr id="downloadable_link_{{id}}">
        <td>
            <input type="hidden" class="__delete__" name="downloadable[link][{{id}}][is_delete]" value="" />
            <input type="hidden" name="downloadable[link][{{id}}][link_id]" value="{{link_id}}" />
            <input type="text" class="required-entry input-text" name="downloadable[link][{{id}}][title]" value="{{title}}" />
            <?php if ($product->getStoreId()): ?>
            <br>
            <input type="checkbox" id="downloadable_link_{{id}}_title" name="downloadable[link][{{id}}][use_default_title]" value="1" />
            <label class="normal" for="downloadable_link_{{id}}_title"><?= $helper->__('Use Default Value') ?></label>
            <?php endif ?>
        </td>
        <?php if ($this->getCanReadPrice() !== false) : ?>
        <?php $disabled = $this->getCanEditPrice() === false ? 'disabled' : '' ?>
        <td class="input-price">
            <input type="text" id="downloadable_link_{{id}}_price_value" class="input-text validate-number link-prices <?= $disabled ?>" name="downloadable[link][{{id}}][price]" value="{{price}}" <?= $disabled ?> />
            <label>[<?= Mage::app()->getStore($product->getStoreId())->getBaseCurrencyCode() ?>]</label>
            <?php if ($product->getStoreId() && Mage::helper('downloadable')->getIsPriceWebsiteScope()): ?>
            <br>
            <input type="checkbox" id="downloadable_link_{{id}}_price" name="downloadable[link][{{id}}][use_default_price]" value="1" <?= $disabled ?> /> <label for="downloadable_link_{{id}}_price"><?= $helper->__('Use Default Value') ?></label>
            <?php endif ?>
        </td>
        <?php else: ?>
        <input type="hidden" id="downloadable_link_{{id}}_price_value" class="link-prices" name="downloadable[link][{{id}}][price]" value="0" />
        <?php if ($product->getStoreId() && Mage::helper('downloadable')->getIsPriceWebsiteScope()): ?>
        <input type="hidden" id="downloadable_link_{{id}}_price" name="downloadable[link][{{id}}][use_default_price]" value="1" />
        <?php endif ?>
        <?php endif ?>
        <td>
            <input type="text" id="downloadable_link_{{id}}_downloads" name="downloadable[link][{{id}}][number_of_downloads]" class="input-text downloads" value="{{number_of_downloads}}" />
            <p><input type="checkbox" class="checkbox" id="downloadable_link_{{id}}_is_unlimited" name="downloadable[link][{{id}}][is_unlimited]" value="1" /> <label for="downloadable_link_{{id}}_is_unlimited">Unlimited</label></p>
        </td>
        <td class="a-center">
            <select id="downloadable_link_{{id}}_shareable" name="downloadable[link][{{id}}][is_shareable]">
                <option value="1">Yes</option>
                <option value="0">No</option>
                <option value="2" selected="selected">Use config</option>
            </select>
        </td>
        <td>
            <div class="files">
                <div class="row a-right">
                    <label for="downloadable_link_{{id}}_sample_file_type" class="a-left">
                        <input type="radio" class="radio" id="downloadable_link_{{id}}_sample_file_type" name="downloadable[link][{{id}}][sample][type]" value="file" />
                        <?= $helper->__('File:') ?>
                    </label>
                    <input type="hidden" class="validate-downloadable-file" id="downloadable_link_{{id}}_sample_file_save" name="downloadable[link][{{id}}][sample][file]" value="{{sample_file_save}}" />
                    <?= $this->getBrowseButtonHtml('sample_') ?>
                    <?= $this->getDeleteButtonHtml('sample_') ?>
                    <div id="downloadable_link_{{id}}_sample_file" class="uploader a-left">
                        <div id="downloadable_link_{{id}}_sample_file-old" class="file-row-info"></div>
                        <div id="downloadable_link_{{id}}_sample_file-new" class="file-row-info new-file"></div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="row">
                    <label for="downloadable_link_{{id}}_sample_url_type">
                        <input type="radio" class="radio" id="downloadable_link_{{id}}_sample_url_type" name="downloadable[link][{{id}}][sample][type]" value="url" />
                        <?= $helper->__('URL:') ?>
                    </label>
                    <input type="text" class="validate-downloadable-url input-text" id="downloadable_link_{{id}}_sample_url_save" name="downloadable[link][{{id}}][sample][url]" value="{{sample_url}}" />
                </div>
            </div>
            <div>
                <input type="radio" class="radio" id="downloadable_link_{{id}}_sample_none_type" name="downloadable[link][{{id}}][sample][type]" value="none" />
                <label for="downloadable_link_{{id}}_sample_none_type"><?= $helper->__('Disable Sample') ?></label>
            </div>
            <div>
                <span id="downloadable_link_{{id}}_sample_container"></span>
            </div>
        </td>
        <td>
            <div class="files">
                <div class="row a-right">
                    <label for="downloadable_link_{{id}}_file_type" class="a-left">
                        <input type="radio" class="radio validate-one-required-by-name" id="downloadable_link_{{id}}_file_type" name="downloadable[link][{{id}}][type]" value="file" />
                        <?= $helper->__('File:') ?>
                    </label>
                    <input type="hidden" class="validate-downloadable-file" id="downloadable_link_{{id}}_file_save" name="downloadable[link][{{id}}][file]" value="{{file_save}}" />
                    <?= $this->getBrowseButtonHtml() ?>
                    <?= $this->getDeleteButtonHtml() ?>
                    <div id="downloadable_link_{{id}}_file" class="uploader a-left">
                        <div id="downloadable_link_{{id}}_file-old" class="file-row-info"></div>
                        <div id="downloadable_link_{{id}}_file-new" class="file-row-info new-file"></div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="row">
                    <label for="downloadable_link_{{id}}_url_type">
                        <input type="radio" class="radio validate-one-required-by-name" id="downloadable_link_{{id}}_url_type" name="downloadable[link][{{id}}][type]" value="url" />
                        <?= $helper->__('URL:') ?>
                    </label>
                    <input type="text" class="validate-downloadable-url input-text" id="downloadable_link_{{id}}_url_save" name="downloadable[link][{{id}}][link_url]" value="{{link_url}}" />
                </div>
            </div>
            <div>
                <span id="downloadable_link_{{id}}_link_container"></span>
            </div>
        </td>
        <td class="a-center">
            <input type="text" name="downloadable[link][{{id}}][sort_order]" value="{{sort_order}}" class="input-text sort" />
        </td>
        <td>
            <button id="downloadable_link_{{id}}_delete_button" type="button" class="scalable delete icon-btn delete-link-item"><span><?= $helper->__('Delete') ?></span></button>
        </td>
    </tr>
</template>

<script>
document.addEventListener('DOMContentLoaded', () => {
    Downloadable.configMaxDownloads = <?= $this->getConfigMaxDownloads() ?>;

    window.linkItems =  new Downloadable.LinkItems('downloadable_link_table', 'downloadable-link-template', '<?= $this->getId() ?>', <?= $this->getConfigJson() ?>);

<?php foreach ($this->getLinkData() as $item): ?>
    linkItems.add(<?= $item->toJson() ?>);
<?php endforeach ?>

    document.getElementById('downloadable_link_purchase_type')?.addEventListener('change', linkItems.togglePriceFields);
});
</script>
