<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Token rejection template
 *
 * @var Mage_Oauth_Block_Authorize_Button $this
 */
?>
<div class="account-login login-only">
        <div class="page-title">
            <h1><?= $this->__('Reject authorization') ?></h1>
        </div>
        <?= $this->getMessagesBlock()->toHtml() ?>
</div>
