<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Sales_Block_Widget_Guest_Form $this */
?>
<?php if ($this->isEnable()): ?>
    <div class="widget">
        <div class="block block-gr-search">
            <div class="block-title">
                <strong>
                    <span><?= $this->__('Orders and Returns') ?></span>
                </strong>
            </div>
            <div class="block-content">
               <form id="oar_widget_orders_and_returns_form" action="<?= $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
                   <ul class="form-alt">
                       <li>
                           <label class="required"><?= Mage::helper('sales')->__('Find Order By:') ?></label>
                           <div class="input-box">
                               <select name="oar_type" id="quick_search_type_id" class="select" title="" onchange="showIdentifyBlock(this.value);">
                                   <option value="email"><?= $this->__('Email Address') ?></option>
                                   <option value="zip"><?= $this->__('ZIP Code') ?></option>
                               </select>
                           </div>
                       </li>
                       <li>
                           <label for="oar_order_id" class="required"><?= Mage::helper('sales')->__('Order ID') ?> </label>
                           <div class="input-box">
                               <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id"  autocomplete="off" />
                           </div>
                       </li>
                       <li>
                           <label for="oar_billing_lastname" class="required"><?= Mage::helper('sales')->__('Billing Last Name') ?> </label>
                           <div class="input-box">
                               <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname" autocomplete="off" />
                           </div>
                       </li>
                       <li id="oar-email">
                           <label for="oar_email" class="required"><?= Mage::helper('sales')->__('Email Address') ?> </label>
                           <div class="input-box">
                               <input type="email" autocomplete="on" autocapitalize="off" autocorrect="off" spellcheck="false" class="input-text validate-email required-entry" id="oar_email" name="oar_email" />
                           </div>
                       </li>
                       <li id="oar-zip" style="display:none;">
                           <label for="oar_zip" class="required"><?= Mage::helper('sales')->__('Billing ZIP Code') ?> </label>
                           <div class="input-box">
                               <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" />
                           </div>
                       </li>
                   </ul>
                   <div class="actions">
                       <button type="submit" title="Continue" class="button"><?= Mage::helper('sales')->__('Continue') ?></button>
                   </div>
               </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        if (document.getElementById('quick_search_type_id').value === 'zip') {
            document.getElementById('oar-zip').style.display = 'block';
            document.getElementById('oar-email').style.display = 'none';
        } else {
            document.getElementById('oar-zip').style.display = 'none';
            document.getElementById('oar-email').style.display = 'block';
        }

        const dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

        function showIdentifyBlock(id) {
            if (id === 'zip') {
                document.getElementById('oar-zip').style.display = 'block';
                document.getElementById('oar-email').style.display = 'none';
            } else if (id == 'email') {
                document.getElementById('oar-zip').style.display = 'none';
                document.getElementById('oar-email').style.display = 'block';
            }
            return false;
        }
    </script>
<?php endif ?>
