<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Account_Dashboard_Address $this */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h2><?= $this->__('Address Book') ?> <a href="<?= $this->getAddressBookUrl() ?>" title="<?= $this->quoteEscape($this->__('Manage Addresses')) ?>"><?= $this->getIconSvg('edit') ?></a></h2>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?= $this->__('Default Billing Address') ?> <a href="<?= $this->getPrimaryBillingAddressEditUrl() ?>" title="<?= $this->quoteEscape($this->__('Edit Address')) ?>"><?= $this->getIconSvg('edit') ?></a></h3>
                </div>
                <div class="box-content">
                    <address><?= $this->getPrimaryBillingAddressHtml() ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?= $this->__('Default Shipping Address') ?> <a href="<?= $this->getPrimaryShippingAddressEditUrl() ?>" title="<?= $this->quoteEscape($this->__('Edit Address')) ?>"><?= $this->getIconSvg('edit') ?></a></h3>
                </div>
                <div class="box-content">
                    <address><?= $this->getPrimaryShippingAddressHtml() ?></address>
                </div>
            </div>
        </div>
    </div>
</div>
