<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Account_Dashboard_Newsletter $this */
?>
<div class="col-2">
    <h4><?= $this->__('Newsletter') ?></h4>
    <a href="<?= $this->getUrl('newsletter/manage') ?>"><?= $this->__('Edit') ?></a>
    <p><?= $this->__('You are currently subscribed to our newsletter.') ?></p>
</div>
