<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Cart_Item_Renderer $this */
?>
<?php
    $_item = $this->getItem();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item" xmlns="http://www.w3.org/1999/html">
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?= $this->getProductUrl()?>" title="<?= $this->escapeHtml($this->getProductName()) ?>" class="product-image"><img src="<?= $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10') ?>" width="50" height="50" alt="<?= $this->escapeHtml($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?= $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10') ?>" width="50" height="50" alt="<?= $this->escapeHtml($this->getProductName()) ?>" /></span>
    <?php endif ?>
    <div class="product-details">
        <p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?= $this->getProductUrl() ?>"><?php endif ?><?= $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif ?></p>

        <table class="info-wrapper">
            <tbody>
                <tr>
                    <th><?= $this->__('Price') ?></th>
                    <td>
                        <?php if ($canApplyMsrp): ?>

                            <span class="map-cart-sidebar-item"><?= $this->__('See price before order confirmation.') ?></span>

                        <?php else: ?>
                            <?php
                            $_weeeHelper = Mage::helper('weee');
                            $_checkoutHelper = $this->helper('checkout');
                            $_weeeApplied = $_weeeHelper->getApplied($_item);
                            $_displayInclTax = $this->helper('tax')->displayCartPriceInclTax();
                            $_displayBothPrices = $this->helper('tax')->displayCartBothPrices();
                            ?>

                            <?php if (!$_displayInclTax || $_displayBothPrices): ?>
                                <?php if ($_displayBothPrices): ?><?= $this->__('Excl. Tax') ?>: <?php endif ?>
                                <?php if ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales')): ?>
                                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?>
                                <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeApplied): ?>
                                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?>
                                    <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_item->getCalculationPrice())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount_incl_tax'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
                                <?php else: ?>
                                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice()) ?>
                                <?php endif ?>
                                <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, 1, 'sales')): ?>
                                    <span class="weee-info" data-tooltip="<?php foreach ($_weeeApplied as $tax): ?><?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount'])) ?> <?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
                                <?php endif ?>
                            <?php endif ?>

                            <?php if ($_displayInclTax || $_displayBothPrices): ?>
                                <?php $_incl = $_checkoutHelper->getPriceInclTax($_item); ?>
                                <?php if ($_displayBothPrices): ?><br /><?= $this->__('Incl. Tax') ?>: <?php endif ?>
                                <?php if ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales')): ?>
                                    <?= $_checkoutHelper->formatPrice($_incl + $_weeeHelper->getWeeeTaxInclTax($_item)) ?>
                                <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeApplied): ?>
                                    <?= $_checkoutHelper->formatPrice($_incl + $_weeeHelper->getWeeeTaxInclTax($_item)) ?>
                                    <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_incl - $_item->getWeeeTaxDisposition())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount_incl_tax'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
                                <?php else: ?>
                                    <?= $_checkoutHelper->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                                <?php endif ?>
                                <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, 1, 'sales')): ?>
                                    <span class="weee-info" data-tooltip="<?php foreach ($_weeeApplied as $tax): ?><?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount'])) ?> <?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
                                <?php endif ?>
                            <?php endif ?>

                        <?php endif //Can apply MSRP ?>
                    </td>
                </tr>
                <tr class="qty-wrapper">
                    <th><?= $this->__('Qty') ?></th>
                    <td>
                        <input
                            id="qinput-<?= $_item->getId() ?>"
                            data-link="<?= $this->getAjaxUpdateUrl() ?>"
                            data-item-id="<?= $_item->getId() ?>"
                            data-cart-item-id="<?= $_item->getSku() ?>"
                            class="qty cart-item-quantity input-text" name=""
                            value="<?= $this->getQty() ?>"
                            <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
                            />

                        <button id="qbutton-<?= $_item->getId() ?>"
                                data-item-id="<?= $_item->getId() ?>"
                                disabled="disabled"
                                data-update
                                data-cart-item-update
                                class="button quantity-button">
                            <?= $this->__('ok') ?>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

        <?php if ($isVisibleProduct): ?>
        <a href="<?= $this->getConfigureUrl() ?>" title="<?= $this->quoteEscape($this->__('Edit')) ?>" class="btn-edit">
            <?= $this->__('Edit') ?>
        </a>
            |
            <?php if (!$this->isOnCheckoutPage()): ?>
                <a href="<?= $this->getAjaxDeleteUrl() ?>" title="<?= $this->quoteEscape($this->__('Remove This Item')) ?>"
                   data-confirm="<?= $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>"
                   class="remove">
                    <?= $this->__('Remove') ?>
                </a>
            <?php else: ?>
                <span><?= $this->__('Remove') ?></span>
            <?php endif ?>
        <?php endif ?>

        <?php if ($_options = $this->getOptionList()):?>
        |
        <div class="truncated">
          <div class="truncated_full_value">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                <dd>
                    <?php if (is_array($_option['value'])): ?>
                    <?= nl2br(implode("\n", $_option['value'])) ?>
                    <?php else: ?>
                    <?= $_option['value'] ?>
                    <?php endif ?>
                </dd>
                <?php endforeach ?>
            </dl>
          </div>
        <a href="#" onclick="return false;" class="details"><?= $this->__('Details') ?></a>
        </div>
        <?php endif ?>

    </div>
</li>
