<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Billing_Method_Form $this */
?>
<?php if($this->hasMethods()): ?>
<div id="order-billing_method_form">
    <dl class="payment-methods">
    <?php
        $_methods       = $this->getMethods();
        $_methodsCount  = count($_methods);
        $_counter = 0;
    ?>
    <?php foreach ($_methods as $_method): $_code = $_method->getCode(); $_counter++; ?>
        <dt>
        <?php if ($_methodsCount > 1): ?>
            <input id="p_method_<?= $_code ?>" value="<?= $_code ?>" type="radio" name="payment[method]" title="<?= $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?= $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif ?> <?php if ($_counter == $_methodsCount) : ?>class="validate-one-required-by-name"<?php endif ?>/>
        <?php else: ?>
            <span class="no-display"><input id="p_method_<?= $_code ?>" value="<?= $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
        <?php endif ?>

            <label for="p_method_<?= $_code ?>"><?= $this->escapeHtml($_method->getTitle()) ?></label>
        </dt>
        <dd>
            <?= $this->getChildHtml('payment.method.'.$_code) ?>
        </dd>
    <?php endforeach ?>
    </dl>
</div>
<script type="text/javascript">order.setPaymentMethod('<?= $this->getSelectedMethodCode() ?>')</script>
<?php else: ?>
    <div><?= Mage::helper('sales')->__('No Payment Methods') ?></div>
<?php endif ?>
