<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Info_Checkmo $this */
?>
<p><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?>
        <p><strong><?= $this->__('Make Check payable to:') ?></strong> <?= $this->escapeHtml($this->getPayableTo()) ?></p>
    <?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <p><strong><?= Mage::helper('payment')->__('Send Check to:') ?></strong></p>
        <address class="checkmo-mailing-address">
            <?= nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        </address>
    <?php endif ?>
<?php endif ?>
