<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><strong><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <th><strong><?= $this->escapeHtml($_label) ?>:</strong></th>
        </tr>
        <tr>
            <td><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>

<?= $this->getChildHtml() ?>
