<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Info $this */
?>
<p class="subtitle"><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<dl class="payment-info">
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <dt><?= $this->escapeHtml($_label) ?></dt>
        <dd><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></dd>
    <?php endforeach ?>
</dl>
<?php endif ?>

<?= $this->getChildHtml() ?>
