<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Info $this */
?>
<p class="subtitle"><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<dl class="payment-info">
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <dt><?= $this->escapeHtml($_label) ?></dt>
        <dd><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></dd>
    <?php endforeach ?>
</dl>
<?php endif ?>

<?= $this->getChildHtml() ?>
