<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<p><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<p><strong><?= $this->__('Purchase Order Number:') ?></strong> <span class="nobr"><?= $this->escapeHtml($this->getInfo()->getPoNumber()) ?></span></p>
