<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Report_Refresh_Statistics $this */
?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml() ?></p>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
