<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html_Header $this */
?>
<header id="header" class="page-header">
    <div class="page-header-container" style="display: flex; place-items: center; gap: 0.5rem">
        <div>
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?= $this->__('Menu') ?></span>
            </a>

            <a class="logo" href="<?= $this->getUrl('') ?>" title="<?= $this->__('Go to Home Page') ?>">
                <img src="<?= $this->getLogoSrc() ?>" alt="<?= $this->getLogoAlt() ?>" width="<?= $this->getLogoWidth() ?>" height="<?= $this->getLogoHeight() ?>" />
            </a>
        </div>

        <?= $this->getChildHtml('topSearch') ?>

        <div>
            <?= $this->getChildHtml('store_language') ?>
            <?= $this->getChildHtml('currency_switcher') ?>

            <a href="<?= $this->helper('customer')->getAccountUrl() ?>" data-target-element="#header-account" class="skip-link skip-account" title="<?= $this->__('Account') ?>">
                <span class="icon"></span>
                <span class="label"><?= $this->__('Account') ?></span>
            </a>

            <a href="" class="skip-link skip-wishlist" title="<?= $this->__('Wishlist') ?>">
                <span class="icon"></span>
                <span class="label"><?= $this->__('Wishlist') ?></span>
            </a>

            <div class="header-minicart">
                <?= $this->getChildHtml('minicart_head') ?>
            </div>
        </div>
    </div>

    <div id="header-nav" class="skip-content">
        <?= $this->getChildHtml('topMenu') ?>
    </div>
</header>

<div id="header-account" class="skip-content">
    <?= $this->getChildHtml('topLinks') ?>
</div>

<?= $this->getChildHtml('topContainer') ?>

<style>
    .page-header-container {padding-top:0.5rem}
    .page-header-container > div {display: flex; place-items: center; gap: 0.5rem}
    .page-header-container > div:first-of-type > a:first-of-type {display: none}
    .currency-switcher label, .form-language label {display: none}
    #search_mini_form {flex-grow: 1; width: 100%}
    .skip-account, .skip-cart, .skip-wishlist {
        display: grid;
        position: relative;
        grid-auto-flow: row;
        justify-items: center;
        padding: 0;
        gap: 0.1rem;
        border: none;
        color: var(--maho-color-text-primary)
    }
    .skip-link .icon {width:30px; height:30px;background-size: 30px;}
    .skip-link * {margin:0 !important; text-transform: none; line-height:normal; font-size: 0.688rem}

    .skip-cart .count {
        border-radius: 50%;
        position: absolute;
        top: -5px;
        right: -5px;
        color: var(--maho-color-background);
        background: var(--maho-color-primary);
        display: block;
        padding: 2px;
        min-width: 17px;
        text-align: center;
    }

    #select-language, #select-currency {border:none; height: 30px;}
    #search_mini_form .input-box {text-align: right}
    #search_mini_form .input-box input {max-width: 450px}

    @media (max-width: 770px) {
        #search_mini_form .input-box input {max-width: none}
        .logo img {max-height: 50px}
        .skip-link .label {display: none}
        .page-header-container {
            display: grid !important;
            place-items: normal !important;
            grid-template-columns: auto min-content;
            grid-template-areas:
                "logo links"
                "search search";
            margin-inline: 1rem;
        }

        .page-header-container > div:first-of-type a:first-of-type {display: block}
        .page-header-container > *:nth-child(1) {grid-area: logo}
        .page-header-container > *:nth-child(2) {grid-area: search; width: 100%; padding-bottom: 20px}
        .page-header-container > *:nth-child(3) {grid-area: links}
    }
</style>