<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Review_Block_Helper $this */
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?= $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif ?>
        <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='<?= $this->getReviewsUrl() ?>'; return false;"><?= $this->__('%d Review(s)', $this->getReviewsCount()) ?></a></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?= $this->getReviewsUrl() ?>#review-form"><?= $this->__('Be the first to review this product') ?></a></p>
<?php endif ?>
