<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/**
 * @see Mage_Tax_Block_Checkout_Grandtotal
 * @var Mage_Tax_Block_Checkout_Grandtotal $this
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <strong><?= $this->helper('tax')->__('Grand Total Excl. Tax') ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <strong><?= $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?= $this->renderTotals('taxes', $this->getColspan()) ?>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <strong><?= $this->helper('tax')->__('Grand Total Incl. Tax') ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <strong><?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php else: ?>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <strong><?= $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <strong><?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php endif ?>
