<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * @see Mage_Tax_Block_Checkout_Subtotal
 * @var Mage_Tax_Block_Checkout_Subtotal $this
 */
?>
<?php if ($this->displayBoth()):?>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <?= $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <?= $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else: ?>
<tr>
    <td style="<?= $this->getStyle() ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <?= $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?= $this->getStyle() ?>" class="a-right">
        <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif ?>
