<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * @see Mage_Tax_Block_Checkout_Tax
 * @var Mage_Tax_Block_Checkout_Tax $this
 */
?>
<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?= $taxIter ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <td class="a-right" style="<?= $_style ?>" colspan="<?= $this->getColspan() ?>">
                <?= $this->escapeHtml($rate['title']) ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?= (float)$rate['percent'] ?>%)
                <?php endif ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td style="<?= $_style ?>" class="a-right" rowspan="<?= count($rates) ?>">
                    <?= $this->helper('checkout')->formatPrice($amount) ?>
                </td>
            <?php endif ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach ?>
    <?php endforeach ?>
    <?php $weees = $this->getAllWeee(); ?>
    <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>
    <tr class="summary-details-<?= $taxIter ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
        <td class="a-right" style="<?= $_style ?>" colspan="<?= $this->getColspan() ?>">
            <?= $this->escapeHtml($weeeTitle) ?>
            <br />
        </td>
        <td style="<?= $_style ?>" class="a-right" rowspan="1">
            <?= $this->helper('checkout')->formatPrice($weeeAmount) ?>
        </td>
    </tr>
    <?php endforeach ?>
<?php endif ?>
<tr <?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?= $taxIter;?>')"<?php endif ?>>
    <td style="<?= $_style ?>" class="a-right" colspan="<?= $this->getColspan() ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?= $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?= $this->getTotal()->getTitle() ?>
        <?php endif ?>
    </td>
    <td style="<?= $_style ?>" class="a-right"><?= $this->helper('checkout')->formatPrice($_value) ?></td>
</tr>
