<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 *
 * @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts $this
 */
?>
<div id="alert_messages_block"><?= $this->getMessageHtml() ?></div>
<div>
    <h4><?= Mage::helper('productalert')->__('Product Alerts') ?></h4>
</div>
<div class="clear"></div>
<?= $this->getAccordionHtml() ?>
