<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Switch $this */
?>
<?php if(count($this->getStores())>1): ?>
<div class="form-language">
    <label for="select-language" class="visually-hidden"><?= $this->__('Your Language:') ?></label>
    <select id="select-language" title="<?= $this->__('Your Language') ?>" onchange="window.location.href=this.value">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?= $_lang->getCurrentUrl() ?>"<?= $_selected ?>><?= $this->escapeHtml($_lang->getName()) ?></option>
    <?php endforeach ?>
    </select>
</div>
<?php endif ?>
