<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Switch_Website $this */
?>
<div class="store-switcher website-switcher">
    <label for="select-website" class="visually-hidden"><?= $this->__('Store:') ?></label>
    <select id="select-website" title="<?= $this->__('Store') ?>" onchange="window.location.href=this.value">
    <?php foreach ($this->getWebsites() as $website): ?>
        <option value="<?= $this->escapeHtml($website['url']) ?>"<?= $website['is_current'] ? ' selected="selected"' : '' ?>><?= $this->escapeHtml($website['name']) ?></option>
    <?php endforeach ?>
    </select>
</div>
