<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Widget_Guest_Form $this */
?>
<div class="page-title">
   <h1><?= Mage::helper('sales')->__('Orders and Returns') ?></h1>
</div>


<form id="oar_widget_orders_and_returns_form" action="<?= $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
    <div class="fieldset">
        <h2 class="legend"><?= Mage::helper('sales')->__('Order Information') ?></h2>

        <ul class="form-list">
           <li>
               <div class="input-box">
                   <label for="oar_order_id" class="required"><?= Mage::helper('sales')->__('Order ID') ?></label>
               </div>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" style="width:300px;"/>
               </div>
           </li>
           <li class="wide">
               <div class="input-box">
                   <?= Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                </div>
           </li>
           <li>
               <div class="input-box">
                   <label for="oar_billing_lastname" class="required"><?= Mage::helper('sales')->__('Billing Last Name') ?></label>
               </div>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;"/>
               </div>
           </li>
           <li>
               <div class="input-box">
                   <label class="required"><?= Mage::helper('sales')->__('Find Order By:') ?></label>
               </div>
               <div class="input-box">
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email"><?= Mage::helper('sales')->__('Email Address') ?></option>
                       <option value="zip"><?= Mage::helper('sales')->__('ZIP Code') ?></option>
                   </select>
               </div>
           </li>
           <li id="oar-email">
               <div class="input-box">
                   <label for="oar_email" class="required"><?= Mage::helper('sales')->__('Email Address') ?></label>
               </div>
               <div class="input-box">
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  style="width:300px;"/>
               </div>
           </li>
           <li id="oar-zip" style="display:none;">
               <div class="input-box">
                   <label for="oar_zip" class="required"><?= Mage::helper('sales')->__('Billing ZIP Code') ?></label>
               </div>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" style="width:300px;"/>
               </div>
           </li>
       </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?= Mage::helper('sales')->__('* Required Fields') ?></p>
        <button type="submit" title="<?= Mage::helper('sales')->__('Continue') ?>" class="button"><?= Mage::helper('sales')->__('Continue') ?></button>
    </div>
</form>

<script type="text/javascript">
    if (document.getElementById('quick_search_type_id').value === 'zip') {
        document.getElementById('oar-zip').style.display = 'block';
        document.getElementById('oar-email').style.display = 'none';
    } else {
        document.getElementById('oar-zip').style.display = 'none';
        document.getElementById('oar-email').style.display = 'block';
    }

    const dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

    function showIdentifyBlock(id) {
        if (id === 'zip') {
            document.getElementById('oar-zip').style.display = 'block';
            document.getElementById('oar-email').style.display = 'none';
        } else if (id == 'email') {
            document.getElementById('oar-zip').style.display = 'none';
            document.getElementById('oar-email').style.display = 'block';
        }
        return false;
    }
</script>
