<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Widget_Chooser $this */
?>

<?php $divId = 'tree' . $this->getId() ?>
<div id="<?= $divId ?>" class="hor-scroll"></div>

<?php if ($this->getRoot()): ?>
<script type="module">
    const selected = '<?= implode(',', $this->getSelectedCategories()) ?>';
    const useMassaction = <?= var_export((bool) $this->getUseMassaction(), true) ?>;

    const tree = new MahoTree('<?= $divId ?>', {
        showRootNode: false,
        lazyload: {
            nodeParameter: 'id',
            dataUrl: '<?= $this->getLoadTreeUrl() ?>',
            onBeforeLoad: (tree, params) => {
                params.set('selected', selected);
            },
        },
        selectable: {
            mode: useMassaction ? 'simple' : 'radio',
            showInputs: useMassaction,
            allowDeselect: false,
            onSelect: <?= $this->getNodeClickListener() ?? 'null' ?>,
        },
    });
    tree.setRootNode(<?= $this->getTreeJson() ?>);

<?php if ($this->getWithEmptyNode()): ?>
    const emptyNode = new MahoTreeNode(tree, {
        id: 'none',
        text: '<?= $this->jsQuoteEscape($this->__('View All Products')) ?>',
        cls: 'leaf',
    });
    tree.rootNode.prependChild(emptyNode);
<?php endif ?>
</script>
<?php endif ?>
