<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<a href="#main-content" id="skip-to-main-content"><?= $this->__('Skip to main content') ?></a>
<?= $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?= $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?= $this->getChildHtml('header') ?>
        <main class="main-container col3-layout" role="main">
            <div class="main">
                <?= $this->getChildHtml('breadcrumbs') ?>
                <?= $this->getChildHtml('title') ?>
                <div class="col-wrapper">
                    <?php // This left_first block will display above the main content on smaller viewports ?>
                    <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                        <aside class="col-left sidebar col-left-first" aria-label="<?= $this->__('Primary sidebar') ?>"><?= $_leftContent ?></aside>
                    <?php endif ?>
                    <div class="col-main" id="main-content">
                        <?= $this->getChildHtml('global_messages') ?>
                        <?= $this->getChildHtml('content') ?>
                    </div>
                    <aside class="col-left sidebar" aria-label="<?= $this->__('Secondary sidebar') ?>"><?= $this->getChildHtml('left') ?></aside>
                </div>
                <aside class="col-right sidebar" aria-label="<?= $this->__('Right sidebar') ?>"><?= $this->getChildHtml('right') ?></aside>
            </div>
        </main>
        <?= $this->getChildHtml('footer_before') ?>
        <?= $this->getChildHtml('footer') ?>
        <?= $this->getChildHtml('global_cookie_notice') ?>
        <?= $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?= $this->getAbsoluteFooter() ?>
</body>
</html>
