<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
    <?= $this->getChildHtml('head') ?>
</head>
<body class="page-empty <?= $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <div>
        <?= $this->getChildHtml('after_body_start') ?>
        <?= $this->getChildHtml('global_messages') ?>
        <?= $this->getChildHtml('content') ?>
        <?= $this->getChildHtml('before_body_end') ?>
        <?= $this->getAbsoluteFooter() ?>
    </div>
</body>
</html>
