<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2020-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-popup <?= $this->getBodyClass()?$this->getBodyClass() : '' ?>">
<div>
    <?= $this->getChildHtml('after_body_start') ?>
    <?= $this->getChildHtml('content') ?>
    <?= $this->getChildHtml('before_body_end') ?>
</div>
<?= $this->getAbsoluteFooter() ?>
</body>
</html>
