<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-popup <?= $this->getBodyClass()?$this->getBodyClass() : '' ?>">
<div>
    <?= $this->getChildHtml('after_body_start') ?>
    <?= $this->getChildHtml('content') ?>
    <?= $this->getChildHtml('before_body_end') ?>
</div>
<?= $this->getAbsoluteFooter() ?>
</body>
</html>
