<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2020-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html $this */
?><!DOCTYPE html>
<html lang="<?= $this->getLang() ?>" id="top">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-print <?= $this->getBodyClass()?$this->getBodyClass():'' ?>">
<div>
    <div class="print-head">
        <img src="<?= $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getChild('header')->getLogoSrc() ?>" class="logo" alt="">
        <?php if ($this->getPrintLogoText()):?>
            <address><?= nl2br($this->escapeHtml($this->getPrintLogoText())) ?></address>
        <?php endif ?>
    </div>
    <?= $this->getChildHtml('content') ?>
    <div class="buttons-set">
        <button type="button" title="<?= $this->quoteEscape($this->__('Close Window')) ?>" class="button" onclick="window.close();"><?= $this->__('Close Window') ?></button>
    </div>
    <?= $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
