<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html $this */
?><!DOCTYPE html>
<html lang="<?= $this->getLang() ?>" id="top">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-print <?= $this->getBodyClass()?$this->getBodyClass():'' ?>">
<div>
    <div class="print-head">
        <img src="<?= $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getChild('header')->getLogoSrc() ?>" class="logo" alt="" />
        <?php if ($this->getPrintLogoText()):?>
            <address><?= nl2br($this->escapeHtml($this->getPrintLogoText())) ?></address>
        <?php endif ?>
    </div>
    <?= $this->getChildHtml('content') ?>
    <div class="buttons-set">
        <button type="button" title="<?= $this->quoteEscape($this->__('Close Window')) ?>" class="button" onclick="window.close();"><?= $this->__('Close Window') ?></button>
    </div>
    <?= $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
