<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?= $this->__('Redirecting...') ?></h1>
</div>
<?php if($this->getMessage()): ?>
    <p><?= $this->getMessage() ?></p>
<?php endif ?>
<?= $this->getRedirectOutput() ?>
<?php if(!$this->isHtmlFormRedirect()): ?>
    <p><?= $this->__('Click <a href="%s">here</a> if nothing has happened', $this->getTargetURL()) ?></p>
<?php endif ?>
