<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Container for product link widget chooser
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container
 * @var Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container $this
 */
?>
<div class="columns">
    <div class="side-col"><?= $this->getTreeHtml() ?></div>
    <div class="main-col"><?= $this->getGridHtml() ?></div>
</div>
