<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * Container for product link widget chooser
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container
 * @var Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container $this
 */
?>
<div class="columns">
    <div class="side-col"><?= $this->getTreeHtml() ?></div>
    <div class="main-col"><?= $this->getGridHtml() ?></div>
</div>
