<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Paypal_Block_Payflow_Advanced_Iframe $this
 */
?>
<html>
<head>
    <script type="text/javascript">
        if (window.top == window.self) {
            window.location = "<?= $this->getUrl('checkout/cart') ?>";
        }
        var window_top = window.top;
        <?php if ($this->getGotoSection()): ?>
        var checkout_steps;

        try{
            checkout_steps = window.top.checkout.steps
        }catch(e){
            window_top.location="<?= $this->getUrl('checkout/cart') ?>";
        }

        for (var s = 0; s < checkout_steps.length; s++) {
            if (checkout_steps[s] == '<?= $this->getGotoSection() ?>') {
                break;
            }
            if (window_top.document.getElementById('opc-' + checkout_steps[s])) {
                window_top.document.getElementById('opc-' + checkout_steps[s]).classList.add('allow');
            }
        }
        window_top.checkout.gotoSection("<?= $this->getGotoSection() ?>");
        window_top.document.getElementById('checkout-review-submit').style.display = 'block';
        window_top.document.getElementById('iframe-warning').style.display = 'none';
        <?php if ($this->getErrorMsg()): ?>
        alert('<?= $this->jsQuoteEscape($this->getErrorMsg()) ?>');
        <?php endif ?>
        <?php elseif ($this->getGotoSuccessPage()) : ?>
        window_top.location="<?= $this->getUrl('checkout/onepage/success') ?>";
        <?php else: ?>
        window_top.location="<?= $this->getUrl('checkout/cart') ?>";
        <?php endif ?>
    </script>
</head>
<body></body>
</html>
