<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, [], false); ?>

<ul class="sharing-links">
    <?php $_helper = $this->helper('catalog/output'); ?>
    <?php $_productName = urlencode(trim($_helper->productAttribute($_product, $_product->getName(), 'name')))?>
    <?php $_productImageUrl = urlencode(trim((string)$this->helper('catalog/image')->init($_product, 'image')))?>
    <?php $_productUrl = urlencode(trim($_product->getProductUrl()))?>
    <li>
        <?php $_u = 'p[url]=' . $_productUrl . '&p[images][0]=' . $_productImageUrl . '&p[title]=' . $_productName . '&p[summary]=' . urlencode(trim($_helper->productAttribute($_product, nl2br($_product->getShortDescription() ?? ''), 'short_description'))); ?>
        <a href="<?= 'http://www.facebook.com/sharer.php?s=100&' . $_u ?>" target="_blank" title="<?= Mage::helper('core')->quoteEscape($this->__('Share on Facebook')) ?>" class="link-facebook">
            <?= $this->__('Share Facebook') ?>
        </a>
    </li>
    <li>
        <a href="<?= 'http://twitter.com/intent/tweet?text=' . $_productName . '&url=' . $_productUrl ?>" target="_blank" title="<?= Mage::helper('core')->quoteEscape($this->__('Share on Twitter')) ?>" class="link-twitter"><?= $this->__('Share on Twitter') ?></a>
    </li>
</ul>

