<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Invoice_Create_Form $this */
?>
<form id="edit_form" method="post" action="<?= $this->getSaveUrl() ?>">
    <?= $this->getBlockHtml('formkey') ?>
    <?php $_order = $this->getInvoice()->getOrder() ?>
    <?= $this->getChildHtml('order_info') ?>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-left">
    <?php else: ?>
    <div class="box-right">
    <?php endif ?>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?= Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <div><?= $this->getChildHtml('order_payment') ?></div>
                <div><?= Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?= Mage::helper('sales')->__('Shipping Information') ?></h4>
            </div>
            <fieldset>
                <div>
                    <strong><?= $this->escapeHtml($_order->getShippingDescription()) ?></strong>
                    <?= $this->helper('sales')->__('Total Shipping Charges') ?>:

                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif ?>
                    <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                    <?= $_excl ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?= $this->__('Incl. Tax') ?> <?= $_incl ?>)
                    <?php endif ?>
                </div>
                <?php if ($this->canCreateShipment() && $this->canShipPartiallyItem()): ?>
                <p class="nm">
                    <label for="invoice_do_shipment" class="normal"><?= Mage::helper('sales')->__('Create Shipment') ?></label>
                    <input type="checkbox" name="invoice[do_shipment]" id="invoice_do_shipment" value="1" <?= $this->hasInvoiceShipmentTypeMismatch()?' disabled="disabled"':'' ?> />
                </p>
                <?php if ($this->hasInvoiceShipmentTypeMismatch()): ?>
                    <small><?= $this->__('Some items in this order have different invoice and shipment types. You can create shipment only after the invoice is created.') ?></small>
                    <?php endif ?>
                <?php endif ?>
                <div id="tracking" style="display:none;"><?= $this->getChildHtml('tracking',false) ?></div>
            </fieldset>
        </div>
    </div>
    <?php endif ?>
    <div class="clear"></div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?= Mage::helper('sales')->__($this->getForcedShipmentCreate() ? 'Items to Invoice and Ship' : 'Items to Invoice') ?></h4>
        </div>
    </div>
    <div id="invoice_item_container">
          <?= $this->getChildHtml('order_items') ?>
    </div>
</form>
<script type="text/javascript">
    var createShipment = document.getElementById('invoice_do_shipment');
    if (createShipment) {
        createShipment.addEventListener('click', function(e){
            if (createShipment.checked) {
                document.getElementById('tracking').style.display = 'block';
            } else {
                document.getElementById('tracking').style.display = 'none'
            }
        })
    }

    /*forced creating of shipment*/
    var forcedShipmentCreate = <?= $this->getForcedShipmentCreate() ?>;
    var shipmentElement = document.getElementById('invoice_do_shipment');
    if (forcedShipmentCreate && shipmentElement) {
        shipmentElement.checked = true;
        shipmentElement.disabled = true;
        document.getElementById('tracking').style.display = 'block';
    }
</script>
