<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Wishlist_Block_Share_Email_Rss $this */
?>
<p style="font-size:12px; line-height:16px; margin:0 0 16px;">
    <?= $this->__("RSS link to %s's wishlist", $this->quoteEscape($this->helper('wishlist')->getCustomerName())) ?>
    <br>
    <a href="<?= $this->helper('wishlist')->getRssUrl($this->getWishlistId()) ?>"><?= $this->helper('wishlist')->getRssUrl($this->getWishlistId()) ?></a>
</p>
