<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Review_Block_View $this */
?>
<?php if($this->getProductData()->getId()): ?>
<div class="product-review">
    <div class="page-title">
        <h1><?= $this->__('Review Details') ?></h1>
    </div>
    <div class="product-img-box">
        <a href="<?= $this->getProductData()->getProductUrl() ?>" title="<?= $this->escapeHtml($this->getProductData()->getName()) ?>">
            <img src="<?= $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(450, 450) ?>"
                 srcset="<?= $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(900, 900) ?> 2x"
                 alt="<?= $this->escapeHtml($this->getProductData()->getName()) ?>"
                 class="product-image" />
        </a>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
             <p class="label"><?= $this->__('Average Customer Rating') ?>:</p>
             <?= $this->getReviewsSummaryHtml($this->getProductData()) ?>
        <?php endif ?>
    </div>
    <div class="product-details">
        <h2 class="product-name"><?= $this->escapeHtml($this->getProductData()->getName()) ?></h2>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
            <h3><?= $this->__('Product Rating:') ?></h3>
            <table class="ratings-table">
                <caption><?= $this->__('Rating:') ?></caption>
                <?php foreach ($this->getRating() as $_rating): ?>
                    <?php if($_rating->getPercent()): ?>
                        <tr>
                            <th><?= $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?= ceil($_rating->getPercent()) ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                    <?php endif ?>
                <?php endforeach ?>
            </table>
            </dl>
        <?php endif ?>
        <dl>
            <dt>
                <?= $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?>
            </dt>
            <dd>
                <?= nl2br($this->escapeHtml($this->getReviewData()->getDetail())) ?>
            </dd>
        </dl>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->__('Back to Product Reviews') ?></a></p>
    </div>
</div>
<?php endif ?>
