<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Index_Block_Adminhtml_Notifications $this */
?>
<?php $_processes = $this->getProcessesForReindex()?>
<?php if($_processes):?>
<div class="notification-global">
    <strong><?= $this->helper('index')->__('One or more of the Indexes are not up to date:') ?></strong>
    <?= implode(', ', $_processes) ?>.
    <?= $this->helper('index')->__('Click here to go to <a href="%s">Index Management</a> and rebuild required indexes.', $this->getManageUrl()) ?>
</div>
<?php endif ?>
