<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_List_Toolbar $this */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <button class="offcanvas-trigger filters-trigger" data-offcanvas-target=".block-layered-nav" data-offcanvas-title="<?= $this->__('Filters') ?>" aria-label="<?= $this->__('Filters') ?>"><?= $this->getIconSvg('adjustments-horizontal') ?></button>
    <?php if( $this->isExpanded() ): ?>
        <div class="sorter">
            <div class="sort-by">
                <label for="toolbar-sortby"><?= $this->__('Sort By') ?></label>
                <select id="toolbar-sortby" onchange="window.location.href=this.value" title="<?= $this->quoteEscape($this->__('Sort By')) ?>">
                    <?php foreach($this->getAvailableOrders() as $_key => $_order): ?>
                        <option value="<?= $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?= $this->__($_order) ?>
                        </option>
                    <?php endforeach ?>
                </select>
                <?php if($this->getCurrentDirection() === 'desc'): ?>
                    <a href="<?= $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" title="<?= $this->quoteEscape($this->__('Set Ascending Direction')) ?>"><?= $this->getIconSvg('arrow-down') ?></a>
                <?php else: ?>
                    <a href="<?= $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" title="<?= $this->quoteEscape($this->__('Set Descending Direction')) ?>"><?= $this->getIconSvg('arrow-up') ?></a>
                <?php endif ?>
            </div>

            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <label><?= $this->__('View as') ?></label>
                        <?php foreach ($this->getModes() as $_code => $_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <strong title="<?= $_label ?>" class="<?= strtolower($_code) ?>">
                                    <?= $this->getIconSvg("layout-{$_code}") ?>
                                    <?= $_label ?>
                                </strong>
                            <?php else: ?>
                                <a href="<?= $this->getModeUrl($_code) ?>" title="<?= $_label ?>" class="<?= strtolower($_code) ?>">
                                    <?= $this->getIconSvg("layout-{$_code}") ?>
                                    <?= $_label ?>
                                </a>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </p>
            <?php endif ?>
        </div>
    <?php endif ?>
    <div class="pager">
        <div class="count-container">
            <?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?= $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?= $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif ?>

            <?php $availableLimits = $this->getAvailableLimit() ?>
            <?php if (count($availableLimits) > 1): ?>
                <div class="limiter">
                    <label for="limiter-toolbar-top"><?= $this->__('Show') ?></label>
                    <select id="limiter-toolbar-top" onchange="window.location.href=this.value" title="<?= $this->quoteEscape($this->__('Results per page')) ?>">
                    <?php foreach ($availableLimits as $_key => $_limit): ?>
                        <option value="<?= $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?= $_limit ?>
                        </option>
                    <?php endforeach ?>
                    </select>
                </div>
            <?php endif ?>
        </div>

        <?= $this->getPagerHtml() ?>

    </div>
</div>
<?php endif ?>
