<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Maho_Blog_Block_Adminhtml_Post $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?= Mage::helper('blog')->__('Manage Blog Posts') ?></h3></td>
            <td class="a-right">
                <?= $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php if (!$this->isSingleStoreMode()): ?>
    <?= $this->getChildHtml('store_switcher') ?>
<?php endif ?>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
