<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Maho_Blog_Block_Adminhtml_Post $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('blog')->__('Blog Posts') ?></h3>
    <p class="content-buttons a-right">
        <?= $this->getButtonsHtml() ?>
    </p>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
