<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php /** @var Mage_Catalog_Block_Product_View_Abstract $this */?>
<?php $_product = $this->getProduct() ?>

<?= $this->getChildHtml('product_type_data_extra') ?>
