<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Media $this */
?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?= $this->getChildHtml('product_type_data_extra') ?>
<div class="grouped-items-table-wrapper">
    <table class="data-table grouped-items-table" id="super-product-table">
        <col />
        <col />
        <col />
        <tbody>
        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
            <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
            <tr>
                <td class='image'>
                    <img class="thumbnail"
                         src="<?= $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(105, 80) ?>"
                         srcset="<?= $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(210, 160) ?> 2x"
                         alt="<?= $this->escapeHtml($this->getImageLabel()) ?>"
                         title="<?= $this->escapeHtml($this->getImageLabel()) ?>" />
                </td>
                <td class="name">
                    <p class="name-wrapper">
                        <?= $this->escapeHtml($_item->getName()) ?>
                    </p>
                    <?php if ($_product->isSaleable()): ?>
                    <div class="qty-wrapper">
                        <?php if ($_item->isSaleable()) : ?>
                            <input id="super_group_<?= $_item->getId() ?>" type="text" pattern="\d*(\.\d+)?" name="super_group[<?= $_item->getId() ?>]" maxlength="12" value="<?= $_item->getQty() * 1 ?>" title="<?= $this->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
                            <label for="super_group_<?= $_item->getId() ?>" class="qty-label">
                                <?= $this->__('Quantity') ?>
                            </label>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                        <?php endif ?>
                    </div>
                    <?php endif ?>
                </td>
                <?php if ($this->getCanShowProductPrice($_product)): ?>
                <td class="a-right">
                    <?php if ($this->getCanShowProductPrice($_item)): ?>
                    <?= $this->getPriceHtml($_item, true) ?>
                    <?= $this->getTierPriceHtml($_item) ?>
                    <?php endif ?>
                </td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
        <?php else: ?>
           <tr>
               <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif ?>"><?= $this->__('No options of this product are available.') ?></td>
           </tr>
        <?php endif ?>
        </tbody>
    </table>
</div>
