<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @var Mage_Customer_Block_Address_Edit $this
 */
?>
<?php if($this->getTitle()): ?>
<div class="page-title">
    <h1><?= $this->getTitle() ?></h1>
</div>
<?php endif ?>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
    <?= $this->getBlockHtml('formkey') ?>
    <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>" />

<?php $_groups = $this->getGroupedFields() ?>
<?php foreach (array_keys($_groups) as $_i => $_group): ?>
    <div class="fieldset">
        <h2 class="legend"><?= $this->__($_group) ?></h2>
    <?php if ($_i === 0): ?>
        <p class="required"><?= $this->__('* Required Fields') ?></p>
    <?php endif ?>
        <ul class="form-list">
    <?php foreach ($_groups[$_group] as $_code => $_attribute): ?>
        <?php if ($_code === 'region'): continue ?>
        <?php elseif ($_code === 'region_id'): ?>
            <li class="wide">
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?= $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?= Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                           <option value=""><?= $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            $('region_id').setAttribute('defaultValue',  "<?= $this->getAddress()->getRegionId() ?>");
                        </script>
                        <input type="text" id="region" name="region" value="<?= $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?= Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
            </li>
        <?php else: ?>
            <?php $_block = 'eav/widget_'.$_attribute->getFrontendInput() ?>
            <?php $_element = $this->getLayout()->createBlock($_block)->setData('attribute', $_attribute) ?>
            <?php if ($_element->isEnabled()): ?>
                <li class="wide"><?= $_element->setObject($this->getAddress())->toHtml() ?></li>
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
        </ul>
    </div>
<?php endforeach ?>

    <div class="fieldset">
        <ul class="form-list">
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?= $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?= Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" /><label for="primary_billing"><?= $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?= $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?= Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?= $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
        <button type="submit" title="<?= Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><span><span><?= $this->__('Save Address') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country_id', 'region', 'region_id', <?= Mage::helper('directory')->getRegionJsonByStore() ?>, undefined, 'postcode');
</script>
