<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Paygate_Block_Authorizenet_Info_Cc $this */
?>
<?php if (!$this->getHideTitle()): ?>
    <p><strong><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>
<?php endif ?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<dl class="cards-list">
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
        <dt><?= sprintf($this->__('Credit Card %s'), $key + 1) ?></dt>
    <?php endif ?>

    <dd <?php if ($showCount):?> class="offset"<?php endif ?>>
    <table class="info-table">
        <tbody>
        <?php foreach ($card as $_label => $_value):?>
        <tr>
            <th><?= $this->escapeHtml($_label) ?>:</th>
            <td><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></td>
        </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    </dd>
<?php endforeach ?>
</dl>
