<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<script type="text/javascript">
//<![CDATA[
var activeRestRole = getActiveRestRole();

/* Retrieve current active rest role */
function getActiveRestRole() {
    var role;
    api2_roles_sectionJsObject.rows.each(function(row) {
        var radiobox = $(row).getElementsByClassName('radio')[0];
        if ('undefined' != typeof radiobox && radiobox.checked) {
            role = radiobox;
        }
    });
    return role;
}

/* Callback function for rest role row click */
function restRolesRowClick(grid, event) {
    var newRestRole = getActiveRestRole();
    if (newRestRole.value !== activeRestRole.value) {
        if (!confirm("<?= Mage::helper('core')->jsQuoteEscape($this->__('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?')) ?>")) {
            newRestRole.checked = !newRestRole.checked;
            activeRestRole.checked = true;
        } else {
            activeRestRole = newRestRole;
        }
    }
}

api2_roles_sectionJsObject.rowClickCallback = restRolesRowClick;
//]]>
</script>
