<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>

<script>
var activeRestRole = getActiveRestRole();

function getActiveRestRole() {
    var role;
    for (const row of api2_roles_sectionJsObject.rows) {
        var radiobox = row.getElementsByClassName('radio')[0];
        if ('undefined' != typeof radiobox && radiobox.checked) {
            role = radiobox;
        }
    }
    return role;
}

function restRolesRowClick(grid, event) {
    var newRestRole = getActiveRestRole();
    if (newRestRole.value !== activeRestRole.value) {
        if (!confirm("<?= $this->jsQuoteEscape($this->__('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?')) ?>")) {
            newRestRole.checked = !newRestRole.checked;
            activeRestRole.checked = true;
        } else {
            activeRestRole = newRestRole;
        }
    }
}

api2_roles_sectionJsObject.rowClickCallback = restRolesRowClick;
</script>
