<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Layer_State $this */
?>
<?php
$_filters = $this->getActiveFilters();
$_renderers = $this->getParentBlock()->getChild('state_renderers')->getSortedChildren();
?>
<?php if(!empty($_filters)): ?>
<ul class="filter-tags">
    <?php foreach ($_filters as $_filter): ?>
        <?php
        $_rendered = false;
        foreach ($_renderers as $_rendererName):
            $_renderer = $this->getParentBlock()->getChild('state_renderers')->getChild($_rendererName);
            if (method_exists($_renderer, 'shouldRender') && $_renderer->shouldRender($_filter)):
                $_renderer->setFilter($_filter);
                echo $_renderer->toHtml();
                $_rendered = true;
                break;
            endif;
        endforeach;

        if (!$_rendered):
        ?>
        <li class="filter-tag">
            <a href="<?= $_filter->getRemoveUrl() ?>" class="filter-tag-link" title="<?= $this->quoteEscape($this->__('Remove filter: %s', $_filter->getLabel())) ?>">
                <span class="filter-tag-label"><?= $this->__($_filter->getName()) ?></span>
                <span class="filter-tag-value"><?= $this->stripTags($_filter->getLabel()) ?></span>
                <?= $this->getIconSvg('x') ?>
            </a>
        </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
<?php endif ?>
