<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Layer_View $this */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-content toggle-content">
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <div class="active-filters-wrapper">
            <div class="active-filters-header">
                <span class="active-filters-title"><?= $this->__('Active Filters') ?></span>
                <a href="<?= $this->getClearUrl() ?>" class="clear-all-filters"><?= $this->__('Clear All') ?></a>
            </div>
            <?= $this->getStateHtml() ?>
        </div>
        <?php endif ?>
        <?php if($this->canShowOptions()): ?>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if ($_filter->getItemsCount() || method_exists($_filter, 'isInputMode') && $_filter->isInputMode()): ?>
                    <dt><?= $this->__($_filter->getName()) ?></dt>
                    <dd><?= $_filter->getHtml() ?></dd>
                <?php endif ?>
                <?php endforeach ?>
            </dl>
        <?php endif ?>
    </div>
</div>
<?php endif ?>
