<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<script>
function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, Template.HANDLEBARS_PATTERN);
        var url = template.evaluate({tab_id:customer_info_tabsJsTabs.activeTab.id});
        editForm.submit(url);
}
</script>
