<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, Template.HANDLEBARS_PATTERN);
        var url = template.evaluate({tab_id:customer_info_tabsJsTabs.activeTab.id});
        editForm.submit(url);
}
</script>
