<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Create_Form $this */
?>
<form id="edit_form" method="post" action="<?= $this->getSaveUrl() ?>">
    <?= $this->getBlockHtml('formkey') ?>
    <?php  $_order = $this->getShipment()->getOrder() ?>
    <?= $this->getChildHtml('order_info') ?>


    <div class="box-left">
        <!--Billing Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?= Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <div><?= $this->getPaymentHtml() ?></div>
                <div><?= Mage::helper('sales')->__('The order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?= Mage::helper('sales')->__('Shipping Information') ?></h4>
            </div>
            <fieldset>
                <div>
                    <strong><?= $this->escapeHtml($_order->getShippingDescription()) ?></strong>
                    <?= $this->helper('sales')->__('Total Shipping Charges') ?>:

                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif ?>
                    <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                    <?= $_excl ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?= $this->__('Incl. Tax') ?> <?= $_incl ?>)
                    <?php endif ?>
                </div>
                <div><?= $this->getChildHtml('shipment_tracking') ?></div>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?= Mage::helper('sales')->__('Items to Ship') ?></h4>
        </div>
    </div>
    <div id="ship_items_container">
            <?= $this->getItemsHtml() ?>
    </div>
</form>
<?= $this->getChildHtml('shipment_packaging') ?>

<script>
    editForm = new varienForm('edit_form');

    document.addEventListener('DOMContentLoaded', () => {
        packaging.setConfirmPackagingCallback(() => {
            const formData = new FormData(document.getElementById('edit_form'));
            packaging.setParamsCreateLabelRequest(Object.fromEntries(formData));
            return packaging.sendCreateLabelRequest();
        });
        packaging.setLabelCreatedCallback((response) => {
            setLocation("<?= $this->getUrl('*/sales_order/view', ['order_id' => $this->getShipment()->getOrderId()]) ?>");
        });
        packaging.setCancelCallback(() => {
            packaging.cleanPackages();
            document.getElementById('create_shipping_label').checked = false;
            toggleCreateLabelCheckbox();
        });
        packaging.setItemQtyCallback((itemId) => {
            const item = document.querySelector(`[name="shipment[items][${itemId}]"]`);
            if (item && !isNaN(item.value)) {
                return item.value;
            }
        });
    });
</script>
