<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Api2_Block_Adminhtml_Attribute_Buttons $this */
?>
<div class="content-header">
    <h3>
        <?= $this->getCaption() ?>
    </h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<form action="<?= $this->getUrl('*/*/save') ?>" method="post" id="role_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script>
    var roleForm = new varienForm('role_edit_form');
</script>
