<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Api2_Block_Adminhtml_Attribute_Tab_Resource $this */
?>
<?= $this->getChildHtml() ?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('User Type Resources') ?></h4>
    </div>
    <input type="hidden" name="resource" id="role_resources" value="" />
    <fieldset id="resources_fieldset">
        <span class="field-row">
            <label for="all"><?= $this->__('Resource Access') ?></label>
            <select id="all" name="all" class="select">
                <option value="0"><?= $this->__('Custom') ?></option>
                <option value="1"><?= $this->__('All') ?></option>
            </select>
        </span>
        <span class="field-row" id="resources_container">
            <label><?= $this->__('Resources') ?></label>
            <div class="inline-block">
                <div id="resource-tree" class="hor-scroll"></div>
            </div>
            <?php if ($this->hasEntityOnlyAttributes()): ?>
                <div>* This attribute data will be returned for a single resource only.</div>
            <?php endif ?>
        </span>
    </fieldset>
</div>

<script type="module">
    const resourceValueEl = document.getElementById('role_resources');
    const resourceAccessSelectEl = document.querySelector('#resources_fieldset select[name=all]');
    const resourceContainerEl = document.getElementById('resources_container');

    resourceAccessSelectEl.addEventListener('change', (event) => {
        resourceContainerEl.classList.toggle('no-display', event.target.value === '1');
    });
    resourceAccessSelectEl.value = '<?= (int)$this->getEverythingAllowed() ?>';
    resourceAccessSelectEl.dispatchEvent(new Event('change'));

    function updateValue() {
        resourceValueEl.value = tree.getChecked().map((obj) => obj.id);
    }

    const tree = new MahoTree('resource-tree', {
        showRootNode: false,
        selectable: {
            mode: 'nested',
            onSelect: updateValue,
        },
    });
    tree.setRootNode(<?= $this->getResTreeJson() ?>);
    tree.expandAll();

    updateValue();
</script>
