<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Cart_Sidebar $this */
?>
<?php $qty = $this->getSummaryCount() ?: 0 ?>
<a href="<?= $this->helper('checkout/cart')->getCartUrl() ?>" data-target-element="header-cart" class="skip-link skip-cart offcanvas-trigger" data-offcanvas-target="#header-cart .minicart-wrapper" data-offcanvas-title="<?= $this->__('Shopping Cart') ?>" data-offcanvas-position="right" data-offcanvas-desktop="true" title="<?= $this->__('Cart') ?>">
    <?= $this->getIconSvg('shopping-bag') ?>
    <span class="label"><?= $this->__('Cart') ?></span>
    <span class="count count-<?= $qty ?>"><?= $qty ?></span>
</a>

<div id="header-cart" class="block-cart skip-content">
    <?= $this->getChildHtml('minicart_content') ?>
</div>

<script>
    // Initialize minicart globally if it doesn't exist
    document.addEventListener('DOMContentLoaded', function() {
        if (typeof window.minicart === 'undefined') {
            window.minicart = new Minicart({
                formKey: "<?= $this->getFormKey() ?>",
                contentUrl: "<?= $this->getUrl('checkout/cart/ajaxContent') ?>"
            });
            minicart.init();
        }
    });
</script>
