<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Cart $this */
?>
<div class="page-title">
    <h1><?= $this->__('Shopping Cart is Empty') ?></h1>
</div>
<div class="cart-empty">
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?= $this->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= $this->__('You have no items in your shopping cart.') ?></p>
    <p><?= $this->__('Click <a href="%s">here</a> to continue shopping.', $this->quoteEscape($this->getContinueShoppingUrl())) ?></p>
    <?= $this->getChildHtml('shopping.cart.table.after') ?>
</div>
