<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var Mage_Checkout_Block_Cart_Totals $this
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?= $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER') ?></div>
<?php else: ?>
    <table id="shopping-cart-totals-table">
        <col>
        <col width="1">
        <tfoot>
            <?= $this->renderTotals('footer') ?>
        </tfoot>
        <tbody>
            <?= $this->renderTotals() ?>
        </tbody>
    </table>
<?php endif ?>
