<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Mage_Sales
 */

/** @var Mage_Sales_Model_Order_Pdf_Items_Shipment_Default $this */
$item = $this->getItem();
?>

<td class="col-qty">
    <?php echo $this->getItemQty() * 1 ?>
</td>

<td class="col-products">
    <div class="item-name"><?php echo $this->escapeHtml($this->getItemName()) ?></div>

    <?php if ($options = $this->getItemOptions()): ?>
    <div class="item-options">
        <?php foreach ($options as $option): ?>
        <div class="option">
            <span class="option-label"><?php echo $this->escapeHtml($option['label']) ?>:</span>
            <span class="option-value"><?php echo $this->escapeHtml($option['value']) ?></span>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</td>

<td class="col-sku text-right">
    <?php echo $this->escapeHtml($this->getSku()) ?>
</td>
