<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Total_Nominal $this */
?>
<tr>
    <th colspan="<?= $this->getColspan() + 1 ?>" style="<?= $this->getTotalStyle() ?>" class="a-right">
        <?= sprintf(($this->getRenderingArea() == $this->getTotalArea()) ? '<strong>%s</strong>' : '%s', $this->escapeHtml($this->getTotalTitle())) ?>
    </th>
</tr>
<?php foreach ($this->getTotalItems() as $i => $item): ?>
<?php foreach ($this->getTotalItemDetails($item) as $j => $row):?>
<tr class="summary-details <?= "summary-details-nominal-{$i}" . ($j == 0 ? ' summary-details-first' : '') . ($this->getItemDetailsRowIsCompounded($row) ? '' : ' summary-details-excluded') ?>" style="display:none;">
    <td colspan="<?= $this->getColspan() ?>" style="<?= $this->getTotalStyle() ?>" class="a-right">
        <?= $this->escapeHtml($this->getItemDetailsRowLabel($row)) ?>
    </td>
    <td class="a-right">
        <?= $this->formatPrice($this->getItemDetailsRowAmount($row)) ?>
    </td>
</tr>
<?php endforeach ?>
<tr class="summary-total" onclick="expandDetails(this, '<?= ".summary-details-nominal-{$i}" ?>')">
    <td colspan="<?= $this->getColspan() ?>" style="<?= $this->getTotalStyle() ?>">
        <div class="summary-collapse"><?= $this->escapeHtml($this->getItemName($item)) ?></div>
    </td>
    <td class="a-right">
        <?= $this->helper('checkout')->formatPrice($this->getItemRowTotal($item)) ?>
    </td>
</tr>
<?php endforeach ?>
