<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_System_Currency $this */
?>
<div class="content-header">
    <h3><?= $this->getHeader() ?></h3>
    <div class="content-buttons form-buttons">
        <form action="<?= $this->getImportFormAction() ?>" method="post">
            <?= $this->getBlockHtml('formkey') ?>
            <?= $this->getServicesHtml() ?>
            <?= $this->getImportButtonHtml() ?>
        </form>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </div>
</div>
<?= $this->getRatesMatrixHtml() ?>
