<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<table class="table-totals" cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td class="padding-totals">
            <table cellpadding="0" cellspacing="0" border="0">
                <?= $this->getChildHtml() ?>
            </table>
        </td>
    </tr>
</table>
