<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_CatalogLinkRule
 */

declare(strict_types=1);

use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Types;

return function (Schema $schema): void {
    $rule = $schema->createTable('catalog_product_link_rule');
    $rule->addColumn('rule_id', Types::INTEGER, ['unsigned' => true, 'autoincrement' => true]);
    $rule->addColumn('name', Types::STRING, ['length' => 255]);
    $rule->addColumn('description', Types::TEXT, ['length' => 65535, 'notnull' => false]);
    $rule->addColumn('link_type_id', Types::SMALLINT, ['unsigned' => true]);
    $rule->addColumn('is_active', Types::SMALLINT, ['default' => 0]);
    $rule->addColumn('priority', Types::INTEGER, ['default' => 0]);
    $rule->addColumn('sort_order', Types::STRING, ['length' => 50, 'default' => 'random']);
    $rule->addColumn('max_links', Types::INTEGER, ['unsigned' => true, 'notnull' => false]);
    $rule->addColumn('from_date', Types::DATE_MUTABLE, ['notnull' => false]);
    $rule->addColumn('to_date', Types::DATE_MUTABLE, ['notnull' => false]);
    $rule->addColumn('source_conditions_serialized', Types::TEXT, ['length' => 65535, 'notnull' => false]);
    $rule->addColumn('target_conditions_serialized', Types::TEXT, ['length' => 65535, 'notnull' => false]);
    $rule->addColumn('created_at', Types::DATETIME_MUTABLE, ['default' => new CurrentTimestamp()]);
    $rule->addColumn('updated_at', Types::DATETIME_MUTABLE, ['default' => new CurrentTimestamp()]);
    $rule->addPrimaryKeyConstraint(
        PrimaryKeyConstraint::editor()->setUnquotedColumnNames('rule_id')->create(),
    );
    $rule->addIndex(['is_active', 'priority', 'link_type_id']);
    $rule->setComment('Catalog Product Link Rules');

    // Tag links generated by a rule so merge mode can refresh its own output while
    // leaving manually assigned links untouched (NULL = manually assigned). Owned
    // here rather than in Mage_Catalog because it only exists for this module.
    $productLink = $schema->getTable('catalog_product_link');
    $productLink->addColumn('rule_id', Types::INTEGER, [
        'unsigned' => true,
        'notnull' => false,
        'default' => null,
        'comment' => 'Catalog link rule that generated this link (NULL = manually assigned)',
    ]);
    $productLink->addIndex(['rule_id']);
};
