<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_CatalogLinkRule
 */

declare(strict_types=1);

use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\SchemaEditor;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Schema\TableEditor;
use Doctrine\DBAL\Types\Types;
use Maho\Db\Schema;

return function (SchemaEditor $schema): void {
    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_link_rule')
            ->addColumn(Schema::column('rule_id', Types::INTEGER, unsigned: true, autoincrement: true))
            ->addColumn(Schema::column('name', Types::STRING, length: 255))
            ->addColumn(Schema::column('description', Types::TEXT, length: 65535, notNull: false))
            ->addColumn(Schema::column('link_type_id', Types::SMALLINT, unsigned: true))
            ->addColumn(Schema::column('is_active', Types::SMALLINT, default: 0))
            ->addColumn(Schema::column('priority', Types::INTEGER, default: 0))
            ->addColumn(Schema::column('sort_order', Types::STRING, length: 50, default: 'random'))
            ->addColumn(Schema::column('max_links', Types::INTEGER, unsigned: true, notNull: false))
            ->addColumn(Schema::column('from_date', Types::DATE_MUTABLE, notNull: false))
            ->addColumn(Schema::column('to_date', Types::DATE_MUTABLE, notNull: false))
            ->addColumn(Schema::column('source_conditions_serialized', Types::TEXT, length: 65535, notNull: false))
            ->addColumn(Schema::column('target_conditions_serialized', Types::TEXT, length: 65535, notNull: false))
            ->addColumn(Schema::column('created_at', Types::DATETIME_MUTABLE, default: new CurrentTimestamp()))
            ->addColumn(Schema::column('updated_at', Types::DATETIME_MUTABLE, default: new CurrentTimestamp()))
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('rule_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('is_active', 'priority', 'link_type_id'))
            ->setComment('Catalog Product Link Rules')
            ->create(),
    );

    // Tag links generated by a rule so merge mode can refresh its own output while
    // leaving manually assigned links untouched (NULL = manually assigned). Owned
    // here rather than in Mage_Catalog because it only exists for this module.
    $schema->modifyTableByUnquotedName('catalog_product_link', static function (TableEditor $productLink): void {
        $productLink->addColumn(Schema::column('rule_id', Types::INTEGER, unsigned: true, notNull: false, default: null, comment: 'Catalog link rule that generated this link (NULL = manually assigned)'));
        $productLink->addIndex(Index::editor()->setUnquotedColumnNames('rule_id'));
    });
};
