<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_CatalogLinkRule
 */

declare(strict_types=1);

use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\SchemaEditor;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Schema\TableEditor;
use Doctrine\DBAL\Types\Types;

return function (SchemaEditor $schema): void {
    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_link_rule')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('rule_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('name')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('description')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('link_type_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_active')
                    ->setTypeName(Types::SMALLINT)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('priority')
                    ->setTypeName(Types::INTEGER)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('sort_order')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->setDefaultValue('random')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_links')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('from_date')
                    ->setTypeName(Types::DATE_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('to_date')
                    ->setTypeName(Types::DATE_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('source_conditions_serialized')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('target_conditions_serialized')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('created_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('updated_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('rule_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('is_active', 'priority', 'link_type_id'))
            ->setComment('Catalog Product Link Rules')
            ->create(),
    );

    // Tag links generated by a rule so merge mode can refresh its own output while
    // leaving manually assigned links untouched (NULL = manually assigned). Owned
    // here rather than in Mage_Catalog because it only exists for this module.
    $schema->modifyTableByUnquotedName('catalog_product_link', static function (TableEditor $productLink): void {
        $productLink->addColumn(
            Column::editor()
                ->setUnquotedName('rule_id')
                ->setTypeName(Types::INTEGER)
                ->setUnsigned(true)
                ->setNotNull(false)
                ->setDefaultValue(null)
                ->setComment('Catalog link rule that generated this link (NULL = manually assigned)')
                ->create(),
        );
        $productLink->addIndex(Index::editor()->setUnquotedColumnNames('rule_id'));
    });
};
