<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/**
 * @see Mage_Payment_Block_Form_Cashondelivery
 * @var Mage_Payment_Block_Form_Cashondelivery $this
 */
?>
<?php if ($this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?= $this->getMethodCode() ?>-instructions-content agreement-content">
                <?= nl2br($this->getInstructions()) ?>
            </div>
        </li>
    </ul>
<?php endif ?>
