<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Payment_Block_Form_Checkmo $this */
?>
<ul id="payment_form_<?= $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getPayableTo()): ?>
                <?= Mage::helper('payment')->__('<label>Make Check payable to:</label> %s', $this->escapeHtml($this->getMethod()->getPayableTo())) ?><br>
            <?php endif ?>
            <?php if ($this->getMethod()->getMailingAddress()): ?>
                <label><?= Mage::helper('payment')->__('Send Check to:') ?></label>
                <div class="checkmo-mailing-address">
                    <?= nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
                </div>
            <?php endif ?>
        </div>
    </li>
</ul>
