<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Form_Purchaseorder $this */
?>
<ul id="payment_form_<?= $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="po_number"><?= Mage::helper('payment')->__('Purchase Order Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="po_number" name="payment[po_number]" title="<?= $this->quoteEscape(Mage::helper('payment')->__('Purchase Order Number')) ?>" class="required-entry input-text" value="<?= $this->getInfoData('po_number') ?>"/>
        </div>
    </li>
</ul>
