<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Multishipping_Address_Select $this */
?>
<div class="multiple-checkout">
    <div class="page-title title-buttons">
        <h1><?= $this->__('Change Billing Address') ?></h1>
        <button type="button" title="<?= $this->quoteEscape($this->__('Add New Address')) ?>" class="button" onclick="setLocation('<?= $this->getAddNewUrl() ?>')"><?= $this->__('Add New Address') ?></button>
    </div>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?php $_index=0 ?>
    <?php foreach ($this->getAddressCollection() as $_address): ?>
        <?php if($_index%3==0): ?><div class="col3-set"><?php endif ?>
        <div class="col-<?= ($_index%3+1) ?>">
                <p class="actions">
                    <a href="<?= $this->getEditAddressUrl($_address) ?>"><?= $this->__('Edit Address') ?></a> <span class="separator">|</span>
                    <a href="<?= $this->getSetAddressUrl($_address) ?>"><strong><?= $this->__('Select Address') ?></strong></a>
                </p>
                <address>
                    <?= $_address->format('html') ?>
                </address>
                <?php if($this->isAddressDefaultBilling($_address)): ?>
                   <strong><?= $this->__('Default Billing') ?></strong>
                <?php endif ?>
                <?php if($this->isAddressDefaultShipping($_address)): ?>
                    <br /><strong><?= $this->__('Default Shipping') ?></strong>
                <?php endif ?>
        </div>
        <?php $_index++ ?>
        <?php if($_index && $_index%3==0): ?></div><?php endif ?>
    <?php endforeach ?>
    <?php if(!$_index || $_index%3!=0): ?></div><?php endif ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->__('Back to Billing Information') ?></a></p>
    </div>
</div>
