<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var Mage_Wishlist_Block_Render_Item_Price $this */
?>

<?= $this->getCleanProductPriceHtml() ?>

<?php /** @var Mage_Catalog_Model_Product $product */ ?>
<?php $product = $this->getProduct(); ?>
<?php $finalPrice = $product->getFinalPrice(1); ?>
<?php if ($product->canConfigure()): ?>
    <p class="configured-price">
        <span class="price-label"><?= Mage::helper('wishlist')->__('Configured Price:') ?></span>
        <span class="price"><?= Mage::helper('core')->currency($finalPrice, true, false) ?></span>
    </p>
<?php endif ?>
