<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Address_Book_Item_Remove $this */
/** @var Mage_Customer_Model_Address $address */
$address = $this->getAddress();
?>
<a href="#" class="link-remove"
   onclick="if (confirmRemoveAddress()) {
                customFormSubmit(
                    '<?= $this->getUrl('customer/address/delete', ['id' => $address->getId()]) ?>',
                    '<?= $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])) ?>',
                    'post'
                );
            }
            return false;">
    <?= $this->__('Delete Address') ?>
</a>
