<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Reports_Block_Product_Compared $this */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="widget widget-compared">
    <div class="widget-title">
        <h2><?= $this->__('Recently Compared') ?></h2>
    </div>
    <div class="widget-products">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
        <?php $i = 0 ?>
        <ul class="products-grid products-grid--max-<?= $_columnCount ?>-col-widget">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <?php $_imgSize = 210; ?>
                    <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                        <img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize) ?>"
                             srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize * 2) ?> 2x"
                             alt="<?= $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-info">
                        <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>)"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?= $this->getPriceHtml($_product, true, '-widget-compared-grid') ?>
                        <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button"
                                        title="<?= $this->quoteEscape($this->__('Add to Cart')) ?>"
                                        class="button btn-cart"
                                        onclick="customFormSubmit(
                                                '<?= $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                                '<?= $_params ?>',
                                                'post')">
                                    <?= $this->__('Add to Cart') ?>
                                </button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                            <?php endif ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_product, false); ?>
                                    <li>
                                        <a href="#" data-url="<?= $_wishlistUrl ?>" data-params="<?= $_params ?>"
                                           class="link-wishlist" title="<?= $this->__('Add to Wishlist') ?>"
                                           onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')">
                                            <?= $this->getIconSvg('heart') ?>
                                            <?= $this->__('Add to Wishlist') ?>
                                        </a>
                                    </li>
                                <?php endif ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                    <li>
                                        <a href="#" title="<?= $this->__('Add to Compare') ?>"
                                           onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                                            <?= $this->getIconSvg('scale') ?>
                                            <?= $this->__('Add to Compare') ?>
                                        </a>
                                    </li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
<?php endif ?>
