<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Install SQLite database configuration template
 *
 * @var Mage_Install_Block_Configuration $this
 */
?>
<li>
    <label for="sqlite_db_path"><?= $this->__('Database File Path') ?></label>
    <input type="text"
           name="connection[<?= $this->getIdPrefix()?>][db_name]"
           id="sqlite_db_path"
           value="<?= $this->getFormData()->getDbName() ?: 'maho.sqlite' ?>"
           title="<?= $this->quoteEscape($this->__('Database File Path')) ?>"
           class="input-text"
           required>
    <p class="field-note">
        <?= $this->__('Relative path from var/db/ directory, or absolute path, or :memory: for in-memory database') ?>
    </p>
</li>
<li>
    <label for="sqlite_prefix"><?= $this->__('Tables Prefix') ?></label>
    <input type="text"
           name="connection[<?= $this->getIdPrefix()?>][db_prefix]"
           id="sqlite_prefix"
           value="<?= $this->getFormData()->getDbPrefix() ?>"
           title="<?= $this->quoteEscape($this->__('Tables Prefix')) ?>"
           class="input-text">
    <p class="field-note">
        <?= $this->__('(Optional. Leave blank for no prefix)') ?>
    </p>
</li>
