<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle $this */
?>
<script type="text/javascript">
if(typeof Bundle=='undefined') {
    Bundle = {};
}
</script>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= Mage::helper('bundle')->__('Shipment') ?></h4>
    </div>
    <fieldset>
        <table cellspacing="0" class="form-list">
        <tr>
            <td class="label"><label for="shipment_type"><?= Mage::helper('bundle')->__('Ship Bundle Items') ?></label></td>
            <td class="value"><select <?php if ($this->isReadonly()): ?>disabled="disabled" <?php endif ?>id="shipment_type" name="<?= $this->getFieldSuffix() ?>[shipment_type]" class="select">
                <option value="1"><?= Mage::helper('bundle')->__('Separately') ?></option>
                <option value="0"<?php if ($this->getProduct()->getShipmentType() == 0): ?> selected="selected"<?php endif ?>><?= Mage::helper('bundle')->__('Together') ?></option>
            </select>
            </td>
        </tr>
        </table>
    </fieldset>
</div>

<div class="entry-edit custom-options bundle" id="product_bundle_container">
    <div class="entry-edit-head">
        <h4><?= $this->__('Bundle Items') ?></h4>
        <div class="right"><?= $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_bundle_container_top"></div>
        <?= $this->getOptionsBoxHtml() ?>
    </div>
</div>

<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
<?php if ($this->isReadonly()):?>
document.getElementById('product_bundle_container').querySelectorAll('input, select, textarea, button').forEach(function(input){
    input.disabled = true;
    if (input.tagName.toLowerCase() == 'button') {
        input.classList.add('disabled');
    }
});
<?php endif ?>
Validation.add('validate-greater-zero-based-on-option', '<?= $this->jsQuoteEscape($this->__('Please enter a number greater 0 in this field.')) ?>', function(v, el) {
    var optionType = el.closest('div.grid').previousElementSibling.querySelector('select.select-product-option-type'),
        v = Number(v) || 0;

    if (optionType && (optionType.value == 'checkbox' || optionType.value == 'multi') && v <= 0) {
        return false;
    }
    return true;
});
</script>

<div><input type="hidden" name="affect_bundle_product_selections" value="1" /></div>
