<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?= $this->__('Edit Account Information') ?></h1>
</div>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" enctype="multipart/form-data">
    <?= $this->getBlockHtml('formkey') ?>

<?php $_groups = $this->getGroupedFields() ?>
<?php foreach (array_keys($_groups) as $_i => $_group): ?>
    <div class="fieldset">
        <h2 class="legend"><?= $this->__($_group) ?></h2>
    <?php if ($_i === 0): ?>
        <p class="required"><?= $this->__('* Required Fields') ?></p>
    <?php endif ?>
        <ul class="form-list">
    <?php foreach ($_groups[$_group] as $_code => $_attribute): ?>
        <?php $_block = 'eav/widget_'.$_attribute->getFrontendInput() ?>
        <?php $_element = $this->getLayout()->createBlock($_block)->setData('attribute', $_attribute) ?>
        <?php if ($_element->isEnabled()): ?>
            <li><?= $_element->setObject($this->getCustomer())->toHtml() ?></li>
        <?php endif ?>
    <?php endforeach ?>
        </ul>
    </div>
<?php endforeach ?>

    <div class="fieldset">
        <h2 class="legend"><?= $this->__('Password Information') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?= Mage::helper('core')->quoteEscape($this->__('Current Password')) ?></label>
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from automatically filling the password -->
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                    <input type="password" title="<?= Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text required-entry" name="current_password" id="current_password" autocomplete="off" />
                </div>
            </li>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?= Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif ?> class="checkbox" /><label for="change_password"><?= $this->__('Change Password') ?></label>
            </li>
            <li style="display:none;">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?= $this->__('New Password') ?></label>
                    <div class="input-box">
                        <?php $minPasswordLength = $this->getCustomer()->getMinPasswordLength(); ?>
                        <input type="password"
                               title="<?= Mage::helper('core')->quoteEscape($this->__('New Password')) ?>"
                               class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                               name="password"
                               id="password"
                               autocomplete="new-password" />
                        <p class="form-instructions">
                            <?= $this->__('The minimum password length is %s', $minPasswordLength) ?>
                        </p>
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?= $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?= Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="new-password" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
        <button type="submit" title="<?= Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><?= $this->__('Save') ?></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg) {
        const fieldset = document.querySelector('#password').closest('li');
        fieldset.style.display = arg ? '' : 'none';
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif ?>
</script>
