<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Account_Forgotpassword $this */
?>
<div class="d-header">
    <h2><?= $this->__('Retrieve your password') ?></h2>
    <button type="button" class="d-close" id="dialog-close-btn" aria-label="<?= $this->__('Close') ?>">&times;</button>
</div>
<div class="d-content">
    <form action="<?= $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate-forgot">
        <div class="fieldset">
            <ul class="form-list">
                <li>
                    <label for="email_address_forgot"><?= $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="email" autocomplete="on" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" alt="email" id="email_address_forgot" class="input-text required-entry validate-email" value="<?= $this->escapeHtml($this->getEmailValue()) ?>" autofocus>
                    </div>
                </li>
                <?= $this->getChildHtml('form.additional.info') ?>
            </ul>
        </div>
        <div class="d-actions">
            <button type="button" class="button" onclick="this.closest('dialog').close()"><?= $this->__('Cancel') ?></button>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Submit')) ?>" class="button"><?= $this->__('Submit') ?></button>
        </div>
    </form>
</div>
<script>
    var dataFormForgot = new VarienForm('form-validate-forgot', true);
</script>
