<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Account_Forgotpassword $this */
?>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getUrl('*/*/magiclinkrequestpost') ?>" method="post" id="form-validate">
    <?= $this->getBlockHtml('formkey') ?>
    <div class="fieldset">
        <h1 class="h2"><?= $this->__('Login with Magic Link') ?></h1>
        <p class="form-instructions"><?= $this->__('Please enter your email address below. You will receive a link to log in to your account.') ?></p>
        <p class="required"><?= $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><?= $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="" />
                </div>
            </li>
            <?= $this->getChildHtml('form.additional.info') ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?= $this->__('Back to Login') ?></a></p>
        <button type="submit" title="<?= $this->quoteEscape($this->__('Send Magic Link')) ?>" class="button"><?= $this->__('Send Magic Link') ?></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
