<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Form_Login $this */
?>
<?php if ($this->canShowLogin()): ?>
<div class="block block-login">
    <div class="block-title">
        <strong><span><?= $this->__('Login') ?></span></strong>
    </div>
    <form action="<?= $this->getPostActionUrl() ?>" method="post">
        <?= $this->getBlockHtml('formkey') ?>
        <div class="block-content">
            <label for="mini-login"><?= $this->__('Email:') ?></label><input type="email" autocomplete="on" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" id="mini-login" class="input-text">
            <label for="mini-password"><?= $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" autocomplete="off">
            <div class="actions">
                <button type="submit" class="button"><?= $this->__('Login') ?></button>
            </div>
        </div>
    </form>
</div>
<?php endif ?>
