<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Create account form template
 *
 * @var $this Mage_Customer_Block_Form_Register
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?= $this->__('Create an Account') ?></h1>
    </div>
    <?= $this->getChildHtml('form_fields_before') ?>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?= $this->getChildHtml('customer.form.register.extra') ?>
    <form action="<?= $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?= Mage::getSingleton('core/session')->getFormKey() ?>" />


    <?php $_groups = $this->getGroupedFields() ?>
    <?php foreach (array_keys($_groups) as $_i => $_group): ?>
        <div class="fieldset">
            <h2 class="legend"><?= $this->__($_group) ?></h2>
        <?php if ($_i === 0): ?>
            <p class="required"><?= $this->__('* Required Fields') ?></p>
        <?php endif ?>
            <ul class="form-list">
        <?php foreach ($_groups[$_group] as $_code => $_attribute): ?>
            <?php $_block = 'eav/widget_'.$_attribute->getFrontendInput() ?>
            <?php $_element = $this->getLayout()->createBlock($_block)->setData('attribute', $_attribute) ?>
            <?php if ($_element->isEnabled()): ?>
                <li class="wide"><?= $_element->setObject($this->getFormData())->toHtml() ?></li>
            <?php endif ?>
        <?php endforeach ?>
            </ul>
        </div>
    <?php endforeach ?>

    <?php if($this->getShowAddressFields()): ?>

            <input type="hidden" name="create_address" value="1" />
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />

<?php $_groups = $this->getGroupedFieldsAddress() ?>
<?php foreach (array_keys($_groups) as $_i => $_group): ?>
    <div class="fieldset">
        <h2 class="legend"><?= $this->__($_group) ?></h2>
    <?php if ($_i === 0): ?>
        <p class="required"><?= $this->__('* Required Fields') ?></p>
    <?php endif ?>
        <ul class="form-list">
    <?php foreach ($_groups[$_group] as $_code => $_attribute): ?>
        <?php if ($_code === 'region'): continue ?>
        <?php elseif ($_code === 'region_id'): ?>
            <li class="wide">
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?= $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?= Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                           <option value=""><?= $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            $('region_id').setAttribute('defaultValue',  "<?= $this->getFormData()->getRegionId() ?>");
                        </script>
                        <input type="text" id="region" name="region" value="<?= $this->escapeHtml($this->getRegion()) ?>"  title="<?= Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
            </li>
        <?php else: ?>
            <?php $_block = 'eav/widget_'.$_attribute->getFrontendInput() ?>
            <?php $_element = $this->getLayout()->createBlock($_block)->setData('attribute', $_attribute) ?>
            <?php if ($_element->isEnabled()): ?>
                <li class="wide"><?= $_element->setObject($this->getAddress())->toHtml() ?></li>
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
        </ul>
    </div>
<?php endforeach ?>

    <?php endif ?>

        <div class="fieldset">
            <h2 class="legend"><?= $this->__('Password Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?= $this->__('Password') ?></label>
                        <div class="input-box">
                            <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                            <input type="password"
                                   name="password"
                                   id="password"
                                   title="<?= $this->quoteEscape($this->__('Password')) ?>"
                                   class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                                   autocomplete="new-password" />
                            <p class="form-instructions">
                                <?= $this->__('The minimum password length is %s', $minPasswordLength) ?>
                            </p>
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?= $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?= $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" autocomplete="new-password" />
                        </div>
                    </div>
                </li>
                <?= $this->getChildHtml('form.additional.info') ?>
                <?= $this->getChildHtml('remember.me') ?>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?= $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?= $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?= $this->getChildHtml('customer.form.register.newsletter') ?>
                </li>
                <?php endif ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Register')) ?>" class="button"><?= $this->__('Register') ?></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country_id', 'region', 'region_id', <?= Mage::helper('directory')->getRegionJsonByStore() ?>, undefined, 'postcode');
        <?php endif ?>
    //]]>
    </script>
</div>
