<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Form_Register $this */
?>
<?= $this->getChildHtml('form_fields_before') ?>
<form action="<?= $this->getPostActionUrl() ?>" method="post" id="form-validate-register" enctype="multipart/form-data" novalidate aria-label="<?= $this->__('Registration Form') ?>">
    <fieldset class="fieldset">
        <legend class="visually-hidden"><?= $this->__('Personal Information') ?></legend>
        <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?= Mage::getSingleton('core/session')->getFormKey() ?>" />
        <p class="required"><?= $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <?= $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
            </li>
            <li>
                <label for="email_address_register" class="required" aria-label="<?= $this->__('Required') ?>"><?= $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="email" autocomplete="on" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address_register" value="<?= $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?= $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" aria-required="true" />
                </div>
            </li>
            <?php if ($this->isNewsletterEnabled()): ?>
            <li class="control">
                <div class="input-box">
                    <input type="checkbox" name="is_subscribed" title="<?= $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed_register"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif ?> class="checkbox" />
                </div>
                <label for="is_subscribed_register"><?= $this->__('Sign Up for Newsletter') ?></label>
                <?php /* Extensions placeholder */ ?>
                <?= $this->getChildHtml('customer.form.register.newsletter') ?>
            </li>
            <?php endif ?>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?= $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?= $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?= $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
        <?php endif ?>
        </ul>
    </fieldset>
<?php if($this->getShowAddressFields()): ?>
    <fieldset class="fieldset">
        <legend class="visually-hidden"><?= $this->__('Address Information') ?></legend>
        <input type="hidden" name="create_address" value="1" />
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="company_register"><?= $this->__('Company') ?></label>
                    <div class="input-box">
                        <input type="text" name="company" id="company_register" value="<?= $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?= $this->quoteEscape($this->__('Company')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="telephone_register" class="required" aria-label="<?= $this->__('Required') ?>"><?= $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="tel" name="telephone" id="telephone_register" value="<?= $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?= $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" aria-required="true" />
                    </div>
                </div>
            </li>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1_register" class="required" aria-label="<?= $this->__('Required') ?>"><?= $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?= $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?= $this->quoteEscape($this->__('Street Address')) ?>" id="street_1_register" class="input-text <?= $_streetValidationClass ?>" />
                </div>
            </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <li class="wide">
                <label for="street_<?= $_i ?>_register"><?= $this->__('Street Address %s', $_i) ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?= $this->escapeHtml($this->getFormData()->getStreet($_i-1)) ?>" title="<?= $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?= $_i ?>_register" class="input-text <?= $_streetValidationClass ?>" />
                </div>
            </li>
        <?php endfor ?>
            <li class="fields">
                <div class="field">
                    <label for="city_register" class="required"><?= $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?= $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?= $this->quoteEscape($this->__('City')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city_register" />
                    </div>
                </div>
                <div class="field">
                    <label for="region_id_register" class="required"><?= $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id_register" name="region_id" title="<?= $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                            <option value=""><?= $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            document.getElementById('region_id_register').setAttribute('defaultValue', "<?= $this->getFormData()->getRegionId() ?>");
                        </script>
                        <input type="text" id="region_register" name="region" value="<?= $this->escapeHtml($this->getRegion()) ?>" title="<?= $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip_register" class="required"><?= $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?= $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?= $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip_register" class="input-text validate-zip-international <?= $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country_register" class="required"><?= $this->__('Country') ?></label>
                    <div class="input-box">
                        <?= $this->getCountryHtmlSelect('country_register') ?>
                    </div>
                </div>
            </li>
        </ul>
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />
    </fieldset>
<?php endif ?>
    <?php $magicLinkMode = Mage::helper('customer')->getMagicLinkRegistrationMode(); ?>
    <?php if ($magicLinkMode !== Mage_Customer_Model_Config_Registrationmode::MODE_NO_PASSWORD): ?>
    <fieldset class="fieldset">
        <legend class="visually-hidden"><?= $this->__('Login Information') ?></legend>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password_register" class="required" aria-label="<?= $this->__('Required') ?>"><?= $this->__('Password') ?></label>
                    <div class="input-box">
                        <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                        <input type="password"
                               name="password"
                               id="password_register"
                               title="<?= $this->quoteEscape($this->__('Password')) ?>"
                               class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                               autocomplete="new-password" aria-required="true" />
                        <p class="form-instructions">
                            <?= $this->__('The minimum password length is %s', $minPasswordLength) ?>
                        </p>
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation_register" class="required" aria-label="<?= $this->__('Required') ?>"><?= $this->__('Confirm Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="confirmation" title="<?= $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation_register" class="input-text required-entry validate-cpassword" autocomplete="new-password" aria-required="true" />
                    </div>
                </div>
            </li>
            <?= $this->getChildHtml('form.additional.info') ?>
            <?= $this->getChildHtml('remember.me.register') ?>
        </ul>
    </fieldset>
    <?php else: ?>
    <ul class="form-list">
        <?= $this->getChildHtml('form.additional.info') ?>
        <?= $this->getChildHtml('remember.me.register') ?>
    </ul>
    <?php endif ?>
    <div class="buttons-set">
        <button type="submit" title="<?= $this->quoteEscape($this->__('Register')) ?>" class="button"><?= $this->__('Register') ?></button>
    </div>
    <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
        <input name="context" type="hidden" value="checkout" />
    <?php endif ?>
</form>
<script type="text/javascript">
    var dataFormRegister = new VarienForm('form-validate-register', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country_register', 'region_register', 'region_id_register', <?= Mage::helper('directory')->getRegionJsonByStore() ?>, undefined, 'zip_register');
    <?php endif ?>
</script>
