<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Create account form template
 *
 * @var Mage_Customer_Block_Form_Register $this
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?= $this->__('Create an Account') ?></h1>
    </div>
    <?= $this->getChildHtml('form_fields_before') ?>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?= $this->getChildHtml('customer.form.register.extra') ?>
    <form action="<?= $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?= Mage::getSingleton('core/session')->getFormKey() ?>" />

        <?= $this->getChildHtml('form_customer_account_create') ?>

        <div class="fieldset">
            <h2 class="legend"><?= $this->__('Password Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?= $this->__('Password') ?></label>
                        <div class="input-box">
                            <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                            <input type="password"
                                   name="password"
                                   id="password"
                                   title="<?= $this->quoteEscape($this->__('Password')) ?>"
                                   class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                                   autocomplete="new-password" />
                            <p class="form-instructions">
                                <?= $this->__('The minimum password length is %s', $minPasswordLength) ?>
                            </p>
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?= $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?= $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" autocomplete="new-password" />
                        </div>
                    </div>
                </li>
                <?= $this->getChildHtml('form.additional.info') ?>
                <?= $this->getChildHtml('remember.me') ?>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?= $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?= $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?= $this->getChildHtml('customer.form.register.newsletter') ?>
                </li>
                <?php endif ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Register')) ?>" class="button"><?= $this->__('Register') ?></button>
        </div>

    <?php if($this->getShowAddressFields()): ?>
        <input type="hidden" name="create_address" value="1" />
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />
    <?php endif ?>
    <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
        <input name="context" type="hidden" value="checkout" />
    <?php endif ?>
    </form>
    <script type="text/javascript">
        const dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        const countryRegions = <?= Mage::helper('directory')->getRegionJsonByStore() ?>;
        new RegionUpdater('country', 'region', 'region_id', countryRegions, undefined, 'zip');
        <?php endif ?>
    </script>
</div>
