<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Customer_Block_Form_Remember
 */
?>
<li class="control remember-me-box">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box">
        <input type="checkbox" name="remember_me" class="checkbox" id="<?= $rememberMeId ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif ?> title="<?= $this->quoteEscape($this->__('Remember Me')) ?>" />
    </div>
    <label for="<?= $rememberMeId ?>"><?= $this->__('Remember Me') ?></label>
</li>
