<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?= $this->__('Reset a Password') ?></h1>
</div>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getUrl('*/*/resetpasswordpost') ?>" method="post" id="form-validate">
    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
    <div class="fieldset" style="margin-top: 70px;">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?= $this->__('New Password') ?></label>
                    <div class="input-box">
                        <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                        <input type="password"
                               class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                               name="password"
                               id="password"
                               autocomplete="off" />
                        <p class="form-instructions">
                            <?= Mage::helper('customer')->__('The minimum password length is %s', $minPasswordLength) ?>
                        </p>
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?= $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="off "/>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?= $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?= Mage::helper('core')->quoteEscape($this->__('Reset a Password')) ?>" class="button"><?= $this->__('Reset a Password') ?></button>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
