<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Sales_Block_Adminhtml_Billing_Agreement_View_Tab_Info $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('General Information') ?></h4>
    </div>
    <div class="log-details">
        <table cellspacing="0">
            <col width="25%">
            <col>
            <tbody>
                <tr>
                    <th><?= $this->__('Reference ID') ?></th>
                    <td><?= $this->escapeHtml($this->getReferenceId()) ?></td>
                </tr>
                <tr>
                    <th><?= $this->__('Customer') ?></th>
                    <td>
                        <a href="<?= $this->getCustomerUrl() ?>">
                            <?= $this->escapeHtml($this->getCustomerEmail()) ?>
                        </a>
                    </td>
                </tr>
                <tr>
                    <th><?= $this->__('Status') ?></th>
                    <td><?= $this->getStatus() ?></td>
                </tr>
                <tr>
                    <th><?= $this->__('Created At') ?></th>
                    <td><?= $this->getCreatedAt() ?></td>
                </tr>
                <tr>
                    <th><?= $this->__('Updated At') ?></th>
                    <td><?= $this->getUpdatedAt() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
