<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Footer $this */
?>

<a href="<?= $this->getMahoProjectUrl() ?>" target="_blank">Powered by Maho <?= Mage::getVersion() ?></a>
<span>|</span>
<?= $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?>

<script type="text/javascript">
    function setInterfaceLanguage(evt) {
        const elem = evt.target;
        if (elem) {
            setLocation('<?= $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?= $this->getRefererParamName() ?>/<?= $this->getUrlForReferer() ?>');
        }
    }

    document.addEventListener('DOMContentLoaded', () => {
        const interfaceLocaleElement = document.getElementById('interface_locale');
        if (interfaceLocaleElement) {
            interfaceLocaleElement.addEventListener('change', setInterfaceLanguage);
        }
    });
    addCopyIcons();
</script>
