<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2020-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Page_Footer $this */
?>

<a href="<?= $this->getMahoProjectUrl() ?>" target="_blank">Powered by Maho <?= Mage::getVersion() ?></a>
<span>|</span>
<?= $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?>

<script>
    function setInterfaceLanguage(evt) {
        const elem = evt.target;
        if (elem) {
            setLocation('<?= $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?= $this->getRefererParamName() ?>/<?= $this->getUrlForReferer() ?>');
        }
    }

    document.addEventListener('DOMContentLoaded', () => {
        const interfaceLocaleElement = document.getElementById('interface_locale');
        if (interfaceLocaleElement) {
            interfaceLocaleElement.addEventListener('change', setInterfaceLanguage);
        }
    });
    addCopyIcons();
</script>
