<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Head $this */
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>"/>
<meta name="robots" content="noindex, nofollow"/>
<title><?= htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" type="image/svg+xml" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" sizes="any">
<link rel="icon" type="image/png" href="<?= $this->getSkinUrl('images/favicon.png') ?>">

<script type="text/javascript">
    var BASE_URL = '<?= $this->getUrl('*') ?>';
    var SKIN_URL = '<?= $this->getSkinUrl() ?>';
    var FORM_KEY = '<?= $this->getFormKey() ?>';
    var LOADING_TIMEOUT = <?= (int)$this->getLoadingTimeout() ?>;
</script>

<?= $this->getCssJsHtml() ?>

<?php if ($this->getData('can_load_wysiwyg')): ?>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill-resize-module@2.0.4/dist/resize.min.css">
    <script src="https://cdn.jsdelivr.net/npm/quill-resize-module@2.0.4/dist/resize.min.js"></script>
<?php endif ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?= Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getChildHtml() ?>
