<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Head $this */
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>"/>
<meta name="robots" content="noindex, nofollow"/>
<title><?= htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" type="image/svg+xml" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" sizes="any">
<link rel="icon" type="image/png" href="<?= $this->getSkinUrl('images/favicon.png') ?>">

<script type="text/javascript">
    var BASE_URL = '<?= $this->getUrl('*') ?>';
    var SKIN_URL = '<?= $this->jsQuoteEscape($this->getSkinUrl()) ?>';
    var FORM_KEY = '<?= $this->getFormKey() ?>';
    var LOADING_TIMEOUT = <?= (int)$this->getLoadingTimeout() ?>;
</script>

<?= $this->getCssJsHtml() ?>

<?php if ($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php?>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>tinymce/tinymce.min.js"></script>
<?php endif ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?= Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getChildHtml() ?>
