<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<tr>
    <td class="label">
        <strong><big>
        <?php if ($this->getGrandTotalTitle()): ?>
            <?= $this->getGrandTotalTitle() ?>
        <?php else: ?>
            <?= Mage::helper('sales')->__('Grand Total') ?>
        <?php endif ?>
        </big></strong>
    </td>
    <td class="emph"><big><?= $this->displayPriceAttribute('grand_total', true) ?></big></td>
</tr>
