<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDataUsingMethod($this->getSourceField())): ?>
    <tr>
        <td class="label"><?php if ($this->getStrong()) : ?><strong><?php endif ?><?= Mage::helper('sales')->__($this->getLabel()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
        <td <?= $this->getHtmlClass() ? ('class="' . $this->getHtmlClass() . '"') : '';?>><?php if ($this->getStrong()) : ?><strong><?php endif ?><?= $this->displayPriceAttribute($this->getSourceField()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
    </tr>
<?php endif ?>
