<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDataUsingMethod($this->getSourceField())): ?>
    <tr>
        <td class="label"><?php if ($this->getStrong()) : ?><strong><?php endif ?><?= Mage::helper('sales')->__($this->getLabel()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
        <td <?= $this->getHtmlClass() ? ('class="' . $this->getHtmlClass() . '"') : '';?>><?php if ($this->getStrong()) : ?><strong><?php endif ?><?= $this->displayPriceAttribute($this->getSourceField()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
    </tr>
<?php endif ?>
