<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php if ($this->getCanDisplayTotalPaid()): ?>
<tr>
    <td class="label"><strong><?= Mage::helper('sales')->__('Total Paid') ?></strong></td>
    <td class="emph"><?= $this->displayPriceAttribute('total_paid', true) ?>
    </td>
</tr>
<?php endif ?>
