<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->getCanDisplayTotalPaid()): ?>
<tr>
    <td class="label"><strong><?= Mage::helper('sales')->__('Total Paid') ?></strong></td>
    <td class="emph"><?= $this->displayPriceAttribute('total_paid', true) ?>
    </td>
</tr>
<?php endif ?>
