<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?= Mage::helper('sales')->__('Shipping &amp; Handling') ?></td>
        <td><?= $this->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif ?>
