<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?= Mage::helper('sales')->__('Shipping &amp; Handling') ?></td>
        <td><?= $this->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif ?>
