<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
    $_source  = $this->getSource();
    $_order   = $this->getOrder();
    $this->setPriceDataObject($_source);
?>
<?php if ($this->helper('tax')->displaySalesSubtotalBoth($_order->getStore())): ?>
    <tr>
        <td class="label">
            <?= Mage::helper('tax')->__('Subtotal (Excl. Tax)') ?>
        </td>
        <td><?= $this->displaySubtotalExclTax() ?></td>
    </tr>
    <tr>
        <td class="label">
            <?= Mage::helper('tax')->__('Subtotal (Incl. Tax)') ?>
        </td>
        <td><?= $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php elseif ($this->helper('tax')->displaySalesSubtotalInclTax($_order->getStore())):?>
    <tr>
        <td class="label">
            <?= Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?= $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php else: ?>
    <tr>
        <td class="label">
            <?= Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?= $this->displaySubtotalExclTax() ?></td>
    </tr>
<?php endif ?>
