<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
    $_source  = $this->getSource();
    $_order   = $this->getOrder();
    $this->setPriceDataObject($_source);
?>
<?php if ($this->helper('tax')->displaySalesSubtotalBoth($_order->getStore())): ?>
    <tr>
        <td class="label">
            <?= Mage::helper('tax')->__('Subtotal (Excl. Tax)') ?>
        </td>
        <td><?= $this->displaySubtotalExclTax() ?></td>
    </tr>
    <tr>
        <td class="label">
            <?= Mage::helper('tax')->__('Subtotal (Incl. Tax)') ?>
        </td>
        <td><?= $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php elseif ($this->helper('tax')->displaySalesSubtotalInclTax($_order->getStore())):?>
    <tr>
        <td class="label">
            <?= Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?= $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php else: ?>
    <tr>
        <td class="label">
            <?= Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?= $this->displaySubtotalExclTax() ?></td>
    </tr>
<?php endif ?>
