<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Totals_Tax $this */

$uniqId = uniqid();
$displayFullSummary = $this->displayFullSummary();
$fullInfo = $this->getFullTaxInfo();
$weees = $this->helper('tax')->getAllWeee($this->getOrder());
?>

<?php if ($displayFullSummary && ($fullInfo || $weees)): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details-<?= $uniqId ?>')">
<?php else: ?>
<tr>
<?php endif ?>
    <td class="label">
    <?php if ($displayFullSummary): ?>
        <div class="summary-collapse"><?= Mage::helper('sales')->__('Total Tax') ?></div>
    <?php else: ?>
        <?= Mage::helper('sales')->__('Tax') ?>
    <?php endif ?>
    </td>
    <td>
        <?= $this->displayAmount($this->getSource()->getTaxAmount(), $this->getSource()->getBaseTaxAmount()) ?>
    </td>
</tr>

<?php if ($displayFullSummary): ?>
    <?php foreach ($fullInfo as $info): ?>
        <?php if ($info['hidden'] ?? false) continue ?>
        <?php $rates = $info['rates'] ?? [$info] ?>
        <?php foreach (array_values($rates) as $i => $rate): ?>
            <tr class="summary-details-<?= $uniqId ?> summary-details no-display">
                <td class="label">
                    <?= $this->escapeHtml($rate['title']) ?>
                    <?php if (!is_null($rate['percent'])): ?>
                        (<?= (float) $rate['percent'] ?>%)
                    <?php endif ?>
                </td>
                <?php if ($i === 0): ?>
                <td rowspan="<?= count($rates) ?>">
                    <?= $this->displayAmount($info['amount'] ?? $info['tax_amount'], $info['base_amount'] ?? $info['base_tax_amount']) ?>
                </td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>
    <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>
        <tr class="summary-details-<?= $uniqId ?> summary-details no-display">
            <td>
                <?= $this->escapeHtml($weeeTitle) ?>
            </td>
            <td>
                <?= $this->helper('checkout')->formatPrice($weeeAmount) ?>
            </td>
        </tr>
    <?php endforeach ?>
<?php endif ?>
