<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Adminhtml_Catalog_Product_Edit_Tab_Downloadable $this */
?>

<div id="alert_messages_block">
    <ul class="messages">
        <li class="notice-msg">
            <?= Mage::helper('downloadable')->__('Alphanumeric, dash and underscore characters are recommended for filenames. Improper characters are replaced with \'_\'.') ?>
        </li>
    </ul>
 </div>

<div id="downloadableInfo" class="entry-edit">
    <?= $this->getChildHtml('accordion') ?>
</div>

<template id="downloadable-uploader-template">
    <div class="no-display" id="[[idName]]-template">
        <div id="{{id}}-container" class="file-row file-row-narrow">
            <span class="file-info">
                <span class="file-info-name">{{name}}</span>
                <span class="file-info-size">{{size}}</span>
            </span>
            <span class="progress-text"></span>
            <div class="clear"></div>
        </div>
    </div>
</template>

<template id="downloadable-filelist-template">
    <span class="file-info">
        <span class="file-info-name">{{name}}</span>
        <span class="file-info-size">({{size}})</span>
    </span>
</template>

<script>
    Downloadable.addValidation();

<?php if ($this->isReadonly()): ?>
    Downloadable.isReadOnly = true;

    document.getElementById('downloadableInfo').querySelectorAll('input, select, textarea, button').forEach((el) => {
        el.disabled = true;
        if (el.tagName === 'BUTTON') {
            el.classList.add('disabled');
        }
    });
<?php endif ?>
</script>
