<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>

<?= $this->getItem()->getName() ?>
<div><strong><?= $this->helper('sales')->__('SKU') ?>:</strong> <?= implode('<br>', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getItem()->getSku()))) ?></div>
<?php if ($this->getOrderOptions()): ?>
    <ul class="item-options">
    <?php foreach ($this->getOrderOptions() as $option): ?>
        <li><strong><?= $this->escapeHtml($option['label']) ?>:</strong><br>
        <?php if (is_array($option['value'])): ?>
        <?php foreach ($option['value'] as $item): ?>
            <?= $this->getValueHtml($item) ?><br>
            <?php endforeach ?>
        <?php else: ?>
            <?= $this->escapeHtml($option['value']) ?>
        <?php endif ?>
        </li>
    <?php endforeach ?>
    </ul>
<?php endif ?>
<?= $this->escapeHtml($this->getItem()->getDescription()) ?>
