<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Paypal_Block_Express_Review_Details $this */
?>
<table id="details-table" class="data-table linearize-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
    <col width="1" />
    <col width="1" />
    <?php endif ?>
    <thead>
        <tr>
            <th rowspan="<?= $rowspan ?>"><?= $this->__('Product') ?></th>
            <th colspan="<?= $colspan ?>" class="a-center"><?= $this->__('Price') ?></th>
            <th rowspan="<?= $rowspan ?>" class="a-center"><?= $this->__('Qty') ?></th>
            <th colspan="<?= $colspan ?>" class="a-center"><?= $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif ?>
    </thead>
<?= $this->getChildHtml('totals') ?>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?= $this->getItemHtml($_item) ?>
        <?php endforeach ?>
    </tbody>
</table>
