<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<div class="page-title">
    <h1><?= $this->__('Currency') ?></h1>
</div>
<p><?= $this->__('Your current currency is: %s', $currency->getCode()) ?></p>
<p><a href="<?= Mage::getBaseUrl() ?>"><?= $this->__('Continue &raquo;') ?></a></p>
