<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_PayPal_Block_Express_Form $this */
?>
<ul class="form-list" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
    <li class="form-alt"><?= $this->getRedirectMessage() ?></li>
    <?php if ($code = $this->getCreateBACode()): ?>
        <li class="form-alt">
            <label for="<?= $code ?>"><input type="checkbox" id="<?= $code ?>" value="1" name="payment[<?= $code ?>]" class="checkbox" />
            <?= $this->__('Sign a billing agreement to streamline further purchases with PayPal.') ?></label>
        </li>
    <?php endif ?>
</ul>
