<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>

<?php
/**
 * JS block for including Countries with Optional Zip
 *
 * @see Mage_Adminhtml_Block_Template
 * @var Mage_Adminhtml_Block_Template $this
 */
?>
<script>
//<![CDATA[
optionalZipCountries = <?= $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;
//]]>
</script>
