<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?= $pageData->getPageMetaKeywords() ?>" />
<?php endif ?>
<?php if($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?= $pageData->getPageMetaDescription() ?>" />
<?php endif ?>
