<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php if($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?= $pageData->getPageMetaKeywords() ?>">
<?php endif ?>
<?php if($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?= $pageData->getPageMetaDescription() ?>">
<?php endif ?>
