<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this */
?>
<?= $this->getChildHtml('wysiwyg_images.js') ?>

<div class="content-header skip-header" id="content_header">
    <h3 id="content_header_text"><?= $this->getHeaderText() ?></h3>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml() ?></p>
</div>

<div class="media-library-content">
    <div id="contents-alt-text" class="no-display">
        <label><?= $this->__('Alt text:') ?> <input name="alt" value="<?= $this->escapeHtml($this->getAltText()) ?>" class="input-text validate-text validate-length max-length-125"></label>
    </div>
    <div id="contents-uploader"><?= $this->getChildHtml('wysiwyg_images.uploader') ?></div>
    <div id="contents"></div>
    <div id="contents-newfolder" class="no-display"><?= $this->getChildHtml('wysiwyg_images.newfolder') ?></div>
</div>
