<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * Directories tree template
 *
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this
 */
?>
<script>
MediabrowserInstance = new Mediabrowser(<?= $this->getFilebrowserSetupObject() ?>);
MediabrowserInstance.storeId = '<?= $this->getStoreId() ?>';
MediabrowserInstance.initializeEventListeners();
</script>
