<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Directories tree template
 *
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this
 */
?>
<script>
MediabrowserInstance = new Mediabrowser(<?= $this->getFilebrowserSetupObject() ?>);
MediabrowserInstance.storeId = '<?= $this->getStoreId() ?>';
MediabrowserInstance.initializeEventListeners();
</script>
