<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Directories tree template
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content
 */
?>
<script type="text/javascript">
//<![CDATA[
MediabrowserInstance = new Mediabrowser(<?= $this->getFilebrowserSetupObject() ?>);
MediabrowserInstance.storeId = '<?= $this->getStoreId() ?>';
//]]>
</script>
