<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Media Library content template
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this 
 */
?>
<?= $this->getChildHtml('wysiwyg_images.js') ?>

<div class="content-header skip-header" id="content_header">
    <table cellspacing="0">
        <tr>
            <td><h3 id="content_header_text"><?= $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?= $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>

<div id="contents-uploader"><?= $this->getChildHtml('wysiwyg_images.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?= $this->getChildHtml('wysiwyg_images.newfolder') ?></div>