<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Directories tree template
 *
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Tree $this
 */
?>
<div class="categories-side-col">
    <div class="tree-actions">
        <a href="#" id="tree_action_collapse"><?= $this->helper('cms')->__('Collapse All') ?></a>
        <span class="separator">|</span>
        <a href="#" id="tree_action_expand"><?= $this->helper('cms')->__('Expand All') ?></a>
    </div>
</div>

<div id="tree" class="hor-scroll"></div>

<script type="module">
    const tree = new MahoTree('tree', {
        showRootNode: true,
        treatAllNodesAsFolders: true,
        lazyload: {
            dataUrl: '<?= $this->getTreeLoaderUrl() ?>',
        },
        selectable: {
            mode: 'radio',
            showInputs: false,
            onSelect: ([node]) => {
                MediabrowserInstance.selectFolder(node);
            },
        },
    });

    tree.setRootNode({
        id: 'root',
        text: '<?= $this->jsQuoteEscape($this->getRootNodeName()) ?>',
        expanded: true,
        children: <?= $this->getTreeJson() ?>
    });

    MediabrowserInstance.setTree(tree);

    document.getElementById('tree_action_collapse').addEventListener('click', () => {
        tree.collapseAll();
    });

    document.getElementById('tree_action_expand').addEventListener('click', () => {
        tree.expandAll();
    });

    tree.expandPath('<?= $this->getTreeCurrentPath() ?>').then((node) => {
        MediabrowserInstance.selectFolder(node, true).then(() => {
            MediabrowserInstance.selectFileById('<?= $this->getTreeCurrentFile() ?>');
        });
    });
</script>
