<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Sales_Order_Item_Renderer_Downloadable $this */
?>
<?php $_item = $this->getItem() ?>
<tr class="border" id="order-item-row-<?= $_item->getId() ?>">
<td><h3 class="product-name"><?= $this->escapeHtml($_item->getName()) ?></h3>
    <?php if ($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                <?php if (!$this->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>>
                        <?= $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <div class="truncated_full_value">
                                <dl class="item-options">
                                    <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                                    <dd><?= $_formatedOptionValue['full_view'] ?></dd>
                                </dl>
                            </div>
                        <?php endif ?>
                    </dd>
                <?php else: ?>
                    <dd><?= $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                <?php endif ?>
            <?php endforeach ?>
        </dl>
    <?php endif ?>

    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
        <dl class="item-options">
            <dt><?= $this->escapeHtml($this->getLinksTitle()) ?></dt>
            <?php foreach ($links->getPurchasedItems() as $link): ?>
                <dd><?= $this->escapeHtml($link->getLinkTitle()) ?></dd>
            <?php endforeach ?>
        </dl>
    <?php endif ?>
    <!-- EOF downloadable -->

    <?= $this->escapeHtml($_item->getDescription()) ?>
    <?php if ($this->canDisplayGiftmessage()): ?>
        <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
        <details class="gift-message">
            <summary class="toggle">
                <?= $this->getIconSvg('gift') ?>
                <?= $this->__('Gift Message') ?>
            </summary>
            <div class="content">
                <div class="header">
                    <span><strong><?= $this->__('From:') ?></strong> <?= $this->escapeHtml($_giftMessage->getSender()) ?></span>
                    <span><strong><?= $this->__('To:') ?></strong> <?= $this->escapeHtml($_giftMessage->getRecipient()) ?></span>
                </div>
                <blockquote class="text"><?= $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></blockquote>
            </div>
        </details>
    <?php endif ?>
</td>
<td data-rwd-label="<?= $this->__('SKU') ?>"><?= $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>

<td class="a-right nowrap<?php if (!$this->helper('tax')->displayCartBothPrices() && !$this->helper('tax')->displayCartPriceExclTax()): ?> lin-hide<?php endif ?>" data-rwd-label="<?= $this->__('Price') ?>">
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <span class="price-excl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-price">
                <?php endif ?>
                <span class="label"><?= $this->__('Excl. Tax') ?>:</span>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    </span>
                <?php endif ?>
            <?php endif ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total"
              onclick="taxToggle('eunit-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <span class="cart-price">
            <?php endif ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [0, 1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                <?= $this->getOrder()->formatPrice($this->getItem()->getPrice() + $this->getItem()->getWeeeTaxAppliedAmount() + $this->getItem()->getWeeeTaxDisposition()) ?>
            <?php else: ?>
                <?= $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
            <?php endif ?>
                </span>

            <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                <span class="cart-tax-info" id="eunit-item-tax-details<?= $this->getItem()->getId() ?>"
                      style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['amount']) ?></span>
                                <?php endforeach ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['amount']) ?></small></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['amount']) ?></span>
                                <?php endforeach ?>
                            </small>
                        <?php endif ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total"
                          onclick="taxToggle('eunit-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?= Mage::helper('weee')->__('Total') ?>
                                :<br/> <?= $this->getOrder()->formatPrice($this->getItem()->getPrice() + $this->getItem()->getWeeeTaxAppliedAmount() + $this->getItem()->getWeeeTaxDisposition()) ?></span>
                    </span>
                <?php endif ?>
            <?php endif ?>
        </span>
        <br/>
        <?php endif ?>
        <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
        <span class="price-incl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-price">
                <?php endif ?>
                <span class="label"><?= $this->__('Incl. Tax') ?>:</span>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    </span>
                <?php endif ?>
            <?php endif ?>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
                  onclick="taxToggle('unit-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [0, 1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                <?= $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?>
            <?php else: ?>
                <?= $this->getOrder()->formatPrice($_incl - $this->getItem()->getWeeeTaxDisposition()) ?>
            <?php endif ?>

                </span>

                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="unit-item-tax-details<?= $this->getItem()->getId() ?>"
                          style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['amount_incl_tax']) ?></span>
                            <?php endforeach ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                            <span class="nobr"><small><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['amount_incl_tax']) ?></small></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['amount_incl_tax']) ?></span>
                            <?php endforeach ?>
                        </small>
                    <?php endif ?>
                </span>

                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total"
                              onclick="taxToggle('unit-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="nobr"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                            :<br/> <?= $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?></span>
                    </span>
                    <?php endif ?>
                <?php endif ?>
        </span>
            <?php endif ?>
</td>

<td class="a-right nowrap" data-rwd-label="<?= $this->__('Qty') ?>">
        <span class="nobr">
                <?php if ($this->getItem()->getQtyOrdered() > 0): ?>
                    <?= $this->__('Ordered') ?>:
                    <strong><?= $this->getItem()->getQtyOrdered() * 1 ?></strong><br/>
                <?php endif ?>
            <?php if ($this->getItem()->getQtyShipped() > 0): ?>
                <?= $this->__('Shipped') ?>:
                <strong><?= $this->getItem()->getQtyShipped() * 1 ?></strong><br/>
            <?php endif ?>
            <?php if ($this->getItem()->getQtyCanceled() > 0): ?>
                <?= $this->__('Canceled') ?>:
                <strong><?= $this->getItem()->getQtyCanceled() * 1 ?></strong><br/>
            <?php endif ?>
            <?php if ($this->getItem()->getQtyRefunded() > 0): ?>
                <?= $this->__('Refunded') ?>:
                <strong><?= $this->getItem()->getQtyRefunded() * 1 ?></strong><br/>
            <?php endif ?>
        </span>
</td>
<td class="a-right nowrap<?php if (!$this->helper('tax')->displayCartBothPrices() && !$this->helper('tax')->displayCartPriceExclTax()): ?> lin-hide<?php endif ?>" data-rwd-label="<?= $this->__('Subtotal') ?>">
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <span class="price-excl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-price">
                <?php endif ?>
                <span class="label"><?= $this->__('Excl. Tax') ?>:</span>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    </span>
                <?php endif ?>
            <?php endif ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total"
              onclick="taxToggle('esubtotal-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <span class="cart-price">
            <?php endif ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [0, 1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                <?= $this->getOrder()->formatPrice($this->getItem()->getRowTotal() + $this->getItem()->getWeeeTaxAppliedRowAmount() + $this->getItem()->getWeeeTaxRowDisposition()) ?>
            <?php else: ?>
                <?= $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
            <?php endif ?>

             </span>


            <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                <span class="cart-tax-info" id="esubtotal-item-tax-details<?= $this->getItem()->getId() ?>"
                      style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['row_amount']) ?></span>
                                <?php endforeach ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['row_amount']) ?></small></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>
                                        : <?= $this->getOrder()->formatPrice($tax['row_amount']) ?></span>
                                <?php endforeach ?>
                            </small>
                        <?php endif ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total"
                          onclick="taxToggle('esubtotal-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?= Mage::helper('weee')->__('Total') ?>
                                :<br/> <?= $this->getOrder()->formatPrice($this->getItem()->getRowTotal() + $this->getItem()->getWeeeTaxAppliedRowAmount() + $this->getItem()->getWeeeTaxRowDisposition()) ?></span>
                        </span>
                <?php endif ?>
            <?php endif ?>
        </span>
        <br/>
        <?php endif ?>
        <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
        <span class="price-incl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-price">
                <?php endif ?>
                <span class="label"><?= $this->__('Incl. Tax') ?>:</span>
                <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    </span>
                <?php endif ?>
            <?php endif ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
                  onclick="taxToggle('subtotal-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), [0, 1, 4], 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                <?= $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?>
            <?php else: ?>
                <?= $this->getOrder()->formatPrice($_incl - $this->getItem()->getWeeeTaxRowDisposition()) ?>
            <?php endif ?>

                </span>

                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="subtotal-item-tax-details<?= $this->getItem()->getId() ?>"
                          style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['row_amount_incl_tax']) ?></span>
                            <?php endforeach ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                            <span class="nobr"><small><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['row_amount_incl_tax']) ?></small></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?= $tax['title'] ?>
                                    : <?= $this->getOrder()->formatPrice($tax['row_amount_incl_tax']) ?></span>
                            <?php endforeach ?>
                        </small>
                    <?php endif ?>
                </span>

                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total"
                              onclick="taxToggle('subtotal-item-tax-details<?= $this->getItem()->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="nobr"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                            :<br/> <?= $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?></span>
                    </span>
                    <?php endif ?>
                <?php endif ?>
        </span>
            <?php endif ?>
</td>
<!--
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <th class="nowrap a-right"><?= $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?></th>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
    <th class="nowrap a-right"><?= $this->getOrder()->formatPrice($this->helper('checkout')->getSubtotalInclTax($this->getItem())) ?></th>
    <?php endif ?>
    -->
</tr>
