<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Comments_View $this */
?>
<?php if ($_entity = $this->getEntity()): ?>
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="history_comment"><?= Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
    </span>
    <div class="f-left">
        <?php if ($this->canSendCommentEmail()): ?>
            <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
            <label class="normal" for="history_notify"><?= Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
        <?php endif ?>
        <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?= Mage::helper('sales')->__('Visible on Frontend') ?></label>
    </div>
    <div class="f-right">
        <?= $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
        <li>
            <div class="note-header">
                <span>
                    <strong><?= $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
                    <?= $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?>
                </span>
                <?php if ($_comment->getIsCustomerNotified()): ?>
                <span class="icon" title="<?= $this->helper('sales')->__('Customer Notified') ?>"><?= $this->getIconSvg('message') ?></span>
                <?php else: ?>
                <span class="icon" title="<?= $this->helper('sales')->__('Customer Not Notified') ?>"><?= $this->getIconSvg('message-off') ?></span>
                <?php endif ?>
            </div>
            <div><?= $this->escapeHtml($_comment->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
        </li>
    <?php endforeach ?>
    </ul>
<script type="text/javascript">
function submitComment() {
    submitAndReloadArea(document.getElementById('comments_block').parentNode, '<?= $this->getSubmitUrl() ?>')
}

if (document.getElementById('submit_comment_button')) {
    document.getElementById('submit_comment_button').addEventListener('click', submitComment);
}
</script>
</div>
<?php endif ?>
