<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profiles $this */ ?>
<div class="page-title">
    <h1><?= $this->__('Recurring Profiles') ?></h1>
</div>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="recurring-profiles">
    <?= $this->getChildHtml('grid') ?>
</div>
