<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Tax_Block_Sales_Order_Tax $this */
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_fullInfo = $_order->getFullTaxInfo();
    $_weees = $this->helper('tax')->getAllWeee($_order);
    global $taxIter; $taxIter++;
    $hasItemsInTaxSection = 0;
?>
<?php  ?>

<?php if ($this->displayFullSummary()): ?>
<?php $isTop = 1; ?>
    <?php if ($_fullInfo) foreach ($_fullInfo as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php
            $percent    = $info['percent'];
            $amount     = $info['amount'];
            $rates      = $info['rates'];
            $isFirst    = 1;
        ?>
        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?= $taxIter ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>"<?php if (!$this->getIsPlaneMode()):?> style="display:none;"<?php endif ?>>
            <td <?= $this->getLabelProperties() ?>>
                <?= $this->escapeHtml($rate['title']) ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?= (float)$rate['percent'] ?>%)
                <?php endif ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td <?= $this->getValueProperties()?> rowspan="<?= count($rates) ?>">
                    <?= $_order->formatPrice($amount) ?>
                </td>
            <?php endif ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php $hasItemsInTaxSection = 1 ?>
        <?php endforeach ?>
    <?php endforeach ?>

    <?php foreach ($_weees as $weeeTitle => $weeeAmount): ?>
        <tr class="summary-details-<?= $taxIter ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>"<?php if (!$this->getIsPlaneMode()):?> style="display:none;"<?php endif ?>>
            <td <?= $this->getLabelProperties() ?>>
                <?= $this->escapeHtml($weeeTitle) ?>
                <br/>
            </td>
            <td <?= $this->getValueProperties() ?> rowspan="1">
                <?= $_order->formatPrice($weeeAmount) ?>
            </td>
        </tr>
        <?php $hasItemsInTaxSection = 1 ?>
    <?php endforeach ?>

<?php endif ?>

<?php if ($this->displayFullSummary() && $hasItemsInTaxSection && !$this->getIsPlaneMode()): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details-<?= $taxIter ?>')">
<?php elseif ($this->displayFullSummary() && $hasItemsInTaxSection && $this->getIsPlaneMode()): ?>
<tr class="show-details">
<?php else: ?>
<tr>
<?php endif ?>
    <td <?= $this->getLabelProperties() ?>>
        <?php if ($this->displayFullSummary() && !$this->getIsPlaneMode()): ?>
            <div class="summary-collapse"><?= $this->__('Tax') ?></div>
        <?php else: ?>
            <?= $this->__('Tax') ?>
        <?php endif ?>
    </td>
    <td <?= $this->getValueProperties()?>><?= $_order->formatPrice($_source->getTaxAmount()) ?></td>
</tr>
