<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Review_Block_Product_View_List $this */
?>

<?php $_items = $this->getReviewsCollection()->getItems() ?>
<?php $userIcon = $this->getIconSvg('user') ?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)): ?>
        <a href="<?= Mage::getUrl('review/product/list', ['id' => $this->getProduct()->getId(), 'category' => $this->getProduct()->getCategoryId(),]) ?>#review-form"><?= $this->__('Add Your Review') ?></a>
        <dl>
        <?php foreach ($_items as $_review):?>
            <?php $_votes = $_review->getRatingVotes() ?>
            <dt style="position: relative;">
                <?= $userIcon ?>
                <?= $this->escapeHtml($_review->getNickname()) ?> -
                <em><?= $this->formatDate($_review->getCreatedAt()) ?></em>
            </dt>
            <dd>
                <?php if (count($_votes) == 1): ?>
                    <?php foreach ($_votes as $_vote): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?= $_vote->getPercent() ?>%"></div>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
                <strong><?= $this->escapeHtml(ucfirst($_review->getTitle())) ?></strong><br />
                <?= nl2br($this->escapeHtml(ucfirst($_review->getDetail()))) ?>

                <?php if (count($_votes) > 1): ?>
                <table class="ratings-table">
                    <caption><?= $this->__('Rating:') ?></caption>
                    <tbody>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?= $this->escapeHtml($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?= $_vote->getPercent() ?>%"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <?php endif ?>
            </dd>
        <?php endforeach ?>
        </dl>
    <?php elseif($this->getParentBlock()): ?>
        <?= $this->getParentBlock()->getReviewsSummaryHtml($this->getProduct(), 'short', true) ?>
    <?php endif ?>
    <?= $this->getChildHtml('review_form') ?>
</div>
