<?php
/**
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<?php if ($this->getLayout()->getBlock('head')->getItems('skin_js/js/configurableswatches/swatches-product.js')): ?>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            new Product.ConfigurableSwatches(spConfig);
        });
    </script>
<?php endif ?>
