<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_ImportExport $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('tax')->__('Import / Export Tax Rates') ?></h3>
</div>
<div class="entry-edit">
    <?php if (!$this->getIsReadonly()): ?>
    <div class="box-left">
        <form id="import_form" action="<?= $this->getUrl('*/*/importPost') ?>" method="post" enctype="multipart/form-data">
            <?= $this->getBlockHtml('formkey') ?>
            <div class="entry-edit-head">
                <h4><?= Mage::helper('tax')->__('Import Tax Rates') ?></h4>
            </div>
            <fieldset>
                <legend><?= Mage::helper('tax')->__('Import Tax Rates') ?></legend>
                <input type="file" name="import_rates_file" class="input-file required-entry">
                <?= $this->getButtonHtml('Import Tax Rates', "this.form.submit()") ?>
            </fieldset>
        </form>
        <script>
            var importForm = new varienForm('import_form');
        </script>
    </div>
    <?php endif ?>
    <div class="<?php if ($this->getIsReadonly()): ?>box-left<?php else: ?>box-right<?php endif ?>">
        <form id="export_form" action="<?= $this->getUrl('*/*/exportPost') ?>" method="post" enctype="multipart/form-data">
            <?= $this->getBlockHtml('formkey') ?>
            <div class="entry-edit-head">
                <h4><?= Mage::helper('tax')->__('Export Tax Rates') ?></h4>
            </div>
            <fieldset>
                <legend><?= Mage::helper('tax')->__('Export Tax Rates') ?></legend>
                <?= $this->getButtonHtml('Export Tax Rates', "this.form.submit()") ?>
            </fieldset>
        </form>
    </div>
    <div class="clear"></div>
</div>
