<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_Form $this */
?>
<div class="entry-edit">
    <?= $this->getFormHtml() ?>
</div>
<?= $this->getChildHtml('form_after') ?>
<script>
var updater = new RegionUpdater('tax_country_id', 'tax_region', 'tax_region_id', <?= Mage::helper('directory')->getRegionJsonByStore() ?>, 'disable');
</script>
