<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_Title $this */
?>
<?php /* <table class="dynamic-grid" cellspacing="0" id="tax-rate-titles-table"> */ ?>
    <tr class="dynamic-grid">
    <?php foreach ($this->getStores() as $_store): ?>
        <th><?= $this->escapeHtml($_store->getName()) ?></th>
    <?php endforeach ?>
    </tr>
    <tr class="dynamic-grid">
        <?php $_labels = $this->getTitles() ?>
        <?php foreach ($this->getStores() as $_store): ?>
        <td>
            <input class="input-text<?php if($_store->getId()==0): ?> required-entry<?php endif ?>" type="text" name="title[<?= $_store->getId() ?>]" value="<?= $_labels[$_store->getId()] ?>">
        </td>
        <?php endforeach ?>
    </tr>
    <tr class="dynamic-grid">
        <td colspan="<?= count($this->getStores()) ?>" class="tax-rate-titles-note-td">
            <p><strong><?= $this->__('Note:') ?></strong> <?= $this->__('Leave empty to use tax identifier') ?></p>
        </td>
    </tr>
<?php /* </table> */ ?>
