<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Options $this */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>
<div class="truncated">
  <div class="truncated_full_value">
      <div class="item-options">
          <p><?= $this->__('Options Details') ?></p>
          <dl>
              <?php foreach ($options as $option): ?>
              <dt><?= $this->escapeHtml($option['label']) ?></dt>
              <dd>
                  <?php if (is_array($option['value'])): ?>
                  <?= nl2br(implode("\n", $option['value'])) ?>
                  <?php else: ?>
                  <?= $option['value'] ?>
                  <?php endif ?>
              </dd>
              <?php endforeach ?>
          </dl>
      </div>
  </div>
  <a href="#" onclick="return false;" class="details"><?= $this->__('View Details') ?></a>
</div>
<?php endif ?>
