<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_ConfigurableSwatches_Block_Catalog_Media_Js_Abstract $this */
?>

<script>
    ConfigurableMediaImages.init('<?= $this->getImageType() ?>');
    <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
    ConfigurableMediaImages.setImageFallback(<?= $imageFallback['product']->getId() ?>, JSON.parse('<?= $imageFallback['image_fallback'] ?>'));
    <?php endforeach ?>
    document.dispatchEvent(new Event('configurable-media-images-init'));
</script>
