<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Packaging_Grid $this */
?>
<div>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing="0" class="data">
                <thead>
                <tr class="headings">
                    <th class="no-link"><span class="nobr"><?= Mage::helper('sales')->__('Product Name') ?></span></th>
                    <th class="no-link"><span class="nobr"><?= Mage::helper('sales')->__('Weight') ?></span></th>
                    <th class="no-link<?= $this->displayCustomsValue() ? '' : ' no-display' ?>" width="100">
                        <span class="nobr"><?= Mage::helper('sales')->__('Customs Value') ?></span>
                    </th>
                    <th class="a-center no-link" width="100">
                        <span class="nobr"><input type="checkbox" name="" onclick="packaging.checkAllItems(this);" class="checkbox" title="<?= Mage::helper('sales')->__('Select All') ?>"></span>
                    </th>
                    <th class="no-link" width="100"><span class="nobr"><?= Mage::helper('sales')->__('Qty Ordered') ?></span></th>
                    <th class="no-link last" width="150"><span class="nobr"><?= Mage::helper('sales')->__('Qty') ?></span></th>
                </tr>
                </thead>

                <tbody>
                <?php foreach($this->getAvailableItems() as $item): ?>
                    <tr title="#" id="" class="">
                        <td class="name">
                            <?= $item->getName() ?>
                        </td>
                        <td class="a-center weight ">
                            <?= $item->getWeight() ?>
                        </td>
                        <td<?= $this->displayCustomsValue() ? '' : ' class="no-display"' ?>>
                            <input type="text" name="customs_value" class="input-text<?= $this->displayCustomsValue() ? ' validate-zero-or-greater' : '' ?>" value="<?= $this->formatPrice($item->getPrice()) ?>" size="10" onblur="packaging.recalcContainerWeightAndCustomsValue(this);">
                        </td>
                        <td class="a-center">
                            <input type="checkbox" name="" value="<?= $item->getId() ? $item->getId() : $item->getOrderItemId() ?>" class="checkbox">
                        </td>
                        <td class="a-center">
                            <?= $item->getOrderItem()->getQtyOrdered()*1 ?>
                        </td>
                        <td class="a-right nobr last">
                            <input type="hidden" name="price" value="<?= $item->getPrice() ?>">
                            <input type="text" name="qty" value="<?= $item->getQty()*1 ?>" class="input-text qty<?= $item->getOrderItem()->getIsQtyDecimal() ? ' qty-decimal' : '' ?>">
                            <button type="button" class="delete icon-btn no-display" onclick="packaging.deleteItem(this);">
                                <span><?= Mage::helper('sales')->__('Delete') ?></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
