<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Packaging $this */
?>

<template id="packed_window_template">
    <div class="buttons-set">
        <?= $this->getPrintButton() ?>
    </div>
    <div class="packed-content">
        <?php foreach ($this->getPackages() as $packageId => $package): ?>
            <div class="package entry-edit">
                <?php $package = new \Maho\DataObject($package) ?>
                <?php $params = new \Maho\DataObject($package->getParams()) ?>
                <div class="entry-edit-head">
                    <h4><?= Mage::helper('sales')->__('Package') . " $packageId" ?></h4>
                </div>
                <div class="fieldset">
                    <div class="package-info">
                        <table class="package-options" cellspacing="0">
                            <colgroup>
                                <col width="80">
                                <col width="*">
                                <col width="60">
                                <col width="70">
                                <col width="140">
                                <col width="*">
                            </colgroup>
                            <tbody>
                                <tr>
                                    <th><?= Mage::helper('sales')->__('Type') ?></th>
                                    <td><?= $this->getContainerTypeByCode($params->getContainer()) ?></td>
                                    <th><?= Mage::helper('sales')->__('Length') ?></th>
                                    <td>
                                        <?php if ($params->getLength() != null): ?>
                                            <?= $params->getLength() .' '. Mage::helper('usa')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif ?>
                                    </td>
                                    <?php if ($params->getDeliveryConfirmation() != null): ?>
                                        <th><?= Mage::helper('sales')->__('Signature Confirmation') ?></th>
                                        <td><?= $this->getDeliveryConfirmationTypeByCode($params->getDeliveryConfirmation()) ?></td>
                                    <?php else: ?>
                                        <th></th>
                                        <td></td>
                                    <?php endif ?>
                                </tr>
                                <tr>
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <th><?= Mage::helper('sales')->__('Customs Value') ?></th>
                                        <td><?= $this->displayCustomsPrice($params->getCustomsValue()) ?></td>
                                    <?php else: ?>
                                        <th><?= Mage::helper('sales')->__('Total Weight') ?></th>
                                        <td><?= $params->getWeight() .' '. Mage::helper('usa')->getMeasureWeightName($params->getWeightUnits()) ?></td>
                                    <?php endif ?>
                                    <th><?= Mage::helper('sales')->__('Width') ?></th>
                                    <td>
                                        <?php if ($params->getWidth() != null): ?>
                                            <?= $params->getWidth() .' '. Mage::helper('usa')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif ?>
                                    </td>
                                    <?php if ($params->getContentType() != null): ?>
                                        <th><?= Mage::helper('sales')->__('Contents') ?></th>
                                        <?php if ($params->getContentType() == 'OTHER'): ?>
                                            <td><?= $this->escapeHtml($params->getContentTypeOther()) ?></td>
                                        <?php else: ?>
                                            <td><?= $this->getContentTypeByCode($params->getContentType()) ?></td>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <th></th>
                                        <td></td>
                                    <?php endif ?>
                                </tr>
                                <tr>
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <th><?= Mage::helper('sales')->__('Total Weight') ?></th>
                                        <td><?= $params->getWeight() .' '. Mage::helper('usa')->getMeasureWeightName($params->getWeightUnits()) ?></td>
                                    <?php else: ?>
                                        <th></th>
                                        <td></td>
                                    <?php endif ?>
                                    <th><?= Mage::helper('sales')->__('Height') ?></th>
                                    <td>
                                        <?php if ($params->getHeight() != null): ?>
                                            <?= $params->getHeight() .' '. Mage::helper('usa')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif ?>
                                    <td>
                                    <th></th>
                                    <td></td>
                                </tr>
                                <tr>
                                    <?php if ($params->getSize()): ?>
                                        <th><?= Mage::helper('sales')->__('Size') ?></th>
                                        <td><?= ucfirst(strtolower($params->getSize())) ?></td>
                                    <?php else: ?>
                                        <th></th>
                                        <td></td>
                                    <?php endif ?>
                                    <?php if ($params->getGirth()): ?>
                                        <th><?= Mage::helper('sales')->__('Girth') ?></th>
                                        <td><?= $params->getGirth() .' '. Mage::helper('usa')->getMeasureDimensionName($params->getGirthDimensionUnits()) ?></td>
                                    <?php else: ?>
                                        <th></th>
                                        <td></td>
                                    <?php endif ?>
                                    <th></th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <strong><?= Mage::helper('sales')->__('Items in the Package') ?></strong>
                    <div class="grid">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="data">
                                <colgroup>
                                    <col>
                                    <col width="100">
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <col width="100">
                                    <?php endif ?>
                                    <col width="100">
                                    <col width="100">
                                </colgroup>
                                <thead>
                                <tr class="headings">
                                    <th class="no-link">
                                        <span class="nobr"><?= Mage::helper('sales')->__('Product') ?></span>
                                    </th>
                                    <th class="no-link">
                                        <span class="nobr"><?= Mage::helper('sales')->__('Weight') ?></span>
                                    </th>
                                    <?php if ($this->displayCustomsValue()): ?>
                                    <th class="no-link">
                                        <span class="nobr"><?= Mage::helper('sales')->__('Customs Value') ?></span>
                                    </th>
                                    <?php endif ?>
                                    <th class="no-link">
                                        <span class="nobr"><?= Mage::helper('sales')->__('Qty Ordered') ?></span>
                                    </th>
                                    <th class="no-link last">
                                        <span class="nobr"><?= Mage::helper('sales')->__('Qty') ?></span>
                                    </th>
                                </tr>
                                </thead>

                                <tbody id="">
                                <?php foreach($package->getItems() as $itemId => $item) : ?>
                                    <?php $item = new \Maho\DataObject($item) ?>
                                    <tr title="#" id="" class="">
                                        <td class="name">
                                            <?= $item->getName() ?>
                                        </td>
                                        <td class="a-center weight">
                                            <?= $item->getWeight() ?>
                                        </td>
                                        <?php if ($this->displayCustomsValue()): ?>
                                        <td class="a-right">
                                            <?= $this->displayCustomsPrice($item->getCustomsValue()) ?>
                                        </td>
                                        <?php endif ?>
                                        <td class="a-right">
                                            <?= $this->getQtyOrderedItem($item->getOrderItemId()) ?>
                                        </td>
                                        <td class="a-right last">
                                            <?= $item->getQty()*1 ?>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</template>

<script type="module">
    let dialog = null;
    window.showPackedWindow = function() {
        dialog = Dialog.info(document.getElementById('packed_window_template').innerHTML, {
            title: '<?= Mage::helper('sales')->__('Packages') ?>',
            className: 'packed-window',
        });
    }
    window.hidePackedWindow = function() {
        dialog.close();
    }
</script>
