<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Packaging $this */

$containers = $this->getContainers();
$contentTypes = $this->getContentTypes();
$shippingMethod = $this->getShipment()->getOrder()->getShippingMethod();
$sizeSource = Mage::getModel('usa/shipping_carrier_usps_source_size')->toOptionArray();
$girthEnabled = Mage::helper('usa')->displayGirthValue($shippingMethod) && $this->isGirthAllowed();
?>

<script>
document.addEventListener('DOMContentLoaded', () => {
    window.packaging = new Packaging({
        girthEnabled: <?= var_export($girthEnabled, true) ?>,
        ...<?= $this->getConfigDataJson() ?>,
    });
});
</script>

<template id="packaging_window_template">
    <div class="buttons-set">
        <button type="button" class="scalable AddPackageBtn">
            <?= Mage::helper('sales')->__('Add Package') ?>
        </button>
    </div>
    <div class="packaging-content">
        <div class="messages no-display"></div>
        <div id="packages_content"></div>
    </div>
</template>

<template id="packaging_package_template" class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="package-number"><?= Mage::helper('sales')->__('Package') ?> <span></span></h4>
        <div class="buttons-set">
            <button type="button" class="scalable AddItemsBtn">
                <span><?= Mage::helper('sales')->__('Add Products') ?></span>
            </button>
            <button type="button" class="scalable DeletePackageBtn">
                <span><?= Mage::helper('sales')->__('Delete Package') ?></span>
            </button>
        </div>
    </div>
    <div class="fieldset">
        <table class="package-options">
            <colgroup>
            <?php if (!empty($containers)): ?>
                <col>
            <?php endif ?>
            <?php if ($girthEnabled): ?>
                <col>
                <col width="0">
                <col>
            <?php endif ?>
            <?php if ($this->displayCustomsValue() && count($contentTypes) === 0): ?>
                <col>
            <?php endif ?>
                <col>
                <col width="0">
                <col width="0">
                <col width="0">
                <col>
            <?php if ($this->getDeliveryConfirmationTypes()): ?>
                <col>
            <?php endif ?>
            </colgroup>
            <thead>
            <?php if (!empty($containers)): ?>
                <th><?= Mage::helper('sales')->__('Type') ?></th>
            <?php endif ?>
            <?php if ($girthEnabled): ?>
                <th><?= Mage::helper('sales')->__('Size') ?></th>
                <th><?= Mage::helper('sales')->__('Girth') ?></th>
                <th></th>
            <?php endif ?>
            <?php if ($this->displayCustomsValue() && count($contentTypes) === 0): ?>
                <th><?= Mage::helper('sales')->__('Customs Value') ?></th>
            <?php endif ?>
                <th><?= Mage::helper('sales')->__('Total Weight') ?></th>
                <th><?= Mage::helper('sales')->__('Length') ?></th>
                <th><?= Mage::helper('sales')->__('Width') ?></th>
                <th><?= Mage::helper('sales')->__('Height') ?></th>
                <th></th>
            <?php if ($this->getDeliveryConfirmationTypes()): ?>
                <th><?= Mage::helper('sales')->__('Signature Confirmation') ?></th>
            <?php endif ?>
            </thead>
            <tbody>
            <?php if (!empty($containers)): ?>
                <td>
                    <select name="package_container">
                    <?php foreach ($this->getContainers() as $key => $value): ?>
                        <option value="<?= $key ?>" ><?= $value ?></option>
                    <?php endforeach ?>
                    </select>
                </td>
            <?php endif ?>
            <?php if ($girthEnabled): ?>
                <td>
                    <select name="package_size">
                    <?php foreach ($sizeSource as $key => $value): ?>
                        <option value="<?= $sizeSource[$key]['value'] ?>"><?= $sizeSource[$key]['label'] ?></option>
                    <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <input class="input-text validate-greater-than-zero" name="container_girth" />
                </td>
                <td>
                    <select name="container_girth_dimension_units" class="options-units-dimensions measures">
                        <option value="<?= Mage_Core_Model_Locale::LENGTH_INCH ?>" selected><?= Mage::helper('sales')->__('in') ?></option>
                        <option value="<?= Mage_Core_Model_Locale::LENGTH_CENTIMETER ?>" ><?= Mage::helper('sales')->__('cm') ?></option>
                    </select>
                </td>
            <?php endif ?>
            <?php if ($this->displayCustomsValue() && count($contentTypes) === 0): ?>
                <td>
                    <input class="customs-value input-text validate-zero-or-greater" name="package_customs_value" />
                    <span class="customs-value-currency">[<?= $this->getCustomValueCurrencyCode() ?>]</span>
                </td>
            <?php endif ?>
                <td>
                    <input class="options-weight input-text required-entry validate-greater-than-zero" name="container_weight" />
                    <select name="container_weight_units" class="options-units-weight measures">
                        <option value="<?= Mage_Core_Model_Locale::WEIGHT_POUND ?>" selected><?= Mage::helper('sales')->__('lb') ?></option>
                        <option value="<?= Mage_Core_Model_Locale::WEIGHT_KILOGRAM ?>" ><?= Mage::helper('sales')->__('kg') ?></option>
                    </select>
                </td>
                <td>
                    <input class="options-dimension input-text validate-greater-than-zero" name="container_length" />
                </td>
                <td>
                    <input class="options-dimension input-text validate-greater-than-zero" name="container_width" />
                </td>
                <td>
                    <input class="options-dimension input-text validate-greater-than-zero" name="container_height" />
                </td>
                <td>
                    <select name="container_dimension_units" class="options-units-dimensions measures">
                        <option value="<?= Mage_Core_Model_Locale::LENGTH_INCH ?>" selected><?= Mage::helper('sales')->__('in') ?></option>
                        <option value="<?= Mage_Core_Model_Locale::LENGTH_CENTIMETER ?>" ><?= Mage::helper('sales')->__('cm') ?></option>
                    </select>
                </td>
                <?php if ($this->getDeliveryConfirmationTypes()): ?>
                <td>
                    <select name="delivery_confirmation_types">
                    <?php foreach ($this->getDeliveryConfirmationTypes() as $key => $value): ?>
                        <option value="<?= $key ?>" ><?= $value ?></option>
                    <?php endforeach ?>
                    </select>
                </td>
                <?php endif ?>
            </tbody>
        </table>

        <?php if (count($contentTypes) > 0): ?>
        <table class="package-options package-options-contents" cellspacing="0">
            <colgroup>
            <?php if ($this->displayCustomsValue()): ?>
                <col width="150">
            <?php endif ?>
                <col width="150">
                <col width="*">
            </colgroup>
            <thead>
            <?php if ($this->displayCustomsValue()): ?>
                <th><?= Mage::helper('sales')->__('Customs Value') ?></th>
            <?php endif ?>
                <th><?= Mage::helper('sales')->__('Contents') ?></th>
                <th><?= Mage::helper('sales')->__('Explanation') ?></th>
            </thead>
            <tbody>
            <?php if ($this->displayCustomsValue()): ?>
                <td>
                    <input class="customs-value input-text validate-zero-or-greater" name="package_customs_value" />
                    <span class="customs-value-currency">[<?= $this->getCustomValueCurrencyCode() ?>]</span>
                </td>
            <?php endif ?>
                <td>
                    <select name="content_type">
                    <?php foreach ($contentTypes as $key => $value): ?>
                        <option value="<?= $key ?>" ><?= $value ?></option>
                    <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <input name="content_type_other" class="input-text options-content-type disabled" disabled />
                </td>
            </tbody>
        </table>
        <?php endif ?>

        <div class="package-add-products">
            <div class="package_prepare no-display">
                <div class="entry-edit-head">
                    <h4><?= Mage::helper('sales')->__('Please Select Products to Add') ?></h4>
                    <button type="button" class="scalable AddSelectedBtn">
                        <span><?= Mage::helper('sales')->__('Add Selected Product(s) to Package') ?></span>
                    </button>
                </div>
                <div class="grid_prepare"></div>
            </div>
        </div>
    </div>
</template>
