<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Baseurl
 * @var Mage_Adminhtml_Block_Notification_Baseurl $this
 */
?>
<?php $_url = $this->getConfigUrl()?>
<?php if ($_url): ?>
<div class="notification-global notification-global-notice">
    <?= $this->helper('adminhtml')->__('{{base_url}} is not recommended to use in a production environment to declare the Base Unsecure URL / Base Secure URL. It is highly recommended to change this value in your Maho <a href="%s">configuration</a>.', $_url) ?>
</div>
<?php endif ?>
