<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Curl
 * @var Mage_Adminhtml_Block_Notification_Curl $this
 */
?>
<div>
    <ul class="messages">
        <li class="notice-msg">
            <?= $this->getMessage() ?>
        </li>
    </ul>
</div>
