<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Curl
 * @var Mage_Adminhtml_Block_Notification_Curl $this
 */
?>
<div>
    <ul class="messages">
        <li class="notice-msg">
            <?= $this->getMessage() ?>
        </li>
    </ul>
</div>
