<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * @see Mage_Adminhtml_Block_Checkout_Formkey
 */
?>

<?php if ($this->canShow()): ?>
    <div class="notification-global notification-global-warning">
        <strong style="color:red">Important: </strong>
        <span>Formkey validation is disabled. This may expose you to security risks.
        We strongly recommend to enable in
        <a href="<?= $this->getEnableCSRFUrl() ?>">Advanced / System / CSRF Protection</a>,
        to protect your checkout, contact and newsletter forms.</span>
    </div>
<?php endif ?>
