<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Notification_Toolbar $this */
?>
<?php if ($this->isShow()): ?>
<div class="notification-global">
    <?php $latestNoticeUrl = $this->getLatestNoticeUrl() ?>

    <span class="label">
        <strong<?= $this->isMessageWindowAvailable() ? ' class="clickable" onclick="openMessagePopup()">' : '' ?>>
            <?= $this->__('Latest Message:') ?>
        </strong>

        <?= $this->escapeHtml($this->getLatestNotice()) ?>

        <?php if (!empty($latestNoticeUrl)): ?>
            <a href="<?= $latestNoticeUrl ?>" target="_blank"><?= $this->__('Read details') ?></a>
        <?php endif ?>
    </span>

    <span>
        <?= $this->__('You have %s unread message(s).', $this->getMessageStats()) ?>
        <a href="<?= $this->getNoticesInboxUrl() ?>">
            <?= !empty($latestNoticeUrl) ? $this->__('Go to messages inbox') : $this->__('Go to notifications') ?>
        </a>
    </span>
</div>
<?php endif ?>
