<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Tag_Block_All $this */
?>
<div class="page-title">
    <h1><?= $this->__('All Tags') ?></h1>
</div>
<?php if(count($this->getTags()) > 0): ?>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?= $_tag->getTaggedProductsUrl() ?>" style="font-size:<?= $_tag->getRatio()*70+75 ?>%;"><?= $this->escapeHtml($_tag->getName()) ?></a></li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?= $this->__('There are no tags available.') ?></p>
<?php endif ?>
