<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Tag_Block_Product_List $this */
?>
<div class="box-collateral box-tags">
    <h2><?= $this->__('Product Tags') ?></h2>
    <?= $this->getChildHtml('list_before') ?>
    <?php if ($this->getCount()): ?>
    <ul id="<?= $this->getUniqueHtmlId('product-tags_') ?>" class="product-tags">
        <?= $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
    </ul>
    <?php endif ?>

    <?php if ($this->helper('tag')->isAddingTagsEnabledOnFrontend()): ?>
        <form id="addTagForm" action="<?= $this->getFormAction() ?>" method="get">
            <div class="form-add">
                <label for="productTagName"><?= $this->__('Add Your Tags:') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
                </div>
                <button type="button" title="<?= $this->quoteEscape($this->__('Add Tags')) ?>" class="button" onclick="submitTagForm()">
                    <span>
                        <span><?= $this->__('Add Tags') ?></span>
                    </span>
                </button>
            </div>
        </form>
        <p class="note"><?= $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
        <script type="text/javascript">
            var addTagFormJs = new VarienForm('addTagForm');
            function submitTagForm() {
                if (addTagFormJs.validator.validate()) {
                    addTagFormJs.form.submit();
                }
            }
        </script>
    <?php endif ?>
</div>
