<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Tag_Block_Popular $this */
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?= $this->__('Popular Tags') ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?= $_tag->getTaggedProductsUrl() ?>" style="font-size:<?= $_tag->getRatio()*70+75 ?>%;"><?= $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach ?>
        </ul>
        <div class="actions">
            <a href="<?= $this->getUrl('tag/list') ?>"><?= $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
