<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Tag_Block_Popular $this */
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?= $this->__('Popular Tags') ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?= $_tag->getTaggedProductsUrl() ?>" style="font-size:<?= $_tag->getRatio()*70+75 ?>%;"><?= $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach ?>
        </ul>
        <div class="actions">
            <a href="<?= $this->getUrl('tag/list') ?>"><?= $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
