<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Sales_Block_Order_Comments $this */
?>
<?php if ($this->hasComments()):?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?= $this->getTitle() ?></h2>
        <dl class="order-about">
            <?php foreach ($this->getComments() as $_commentItem): ?>
                <dt><?= $this->formatDate($_commentItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?= $this->escapeHtml($_commentItem->getComment()) ?></dd>
            <?php endforeach ?>
        </dl>
    </div>
<?php endif ?>
