<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Order_Invoice $this */
?>
<div class="order-items order-details">
<?php if($this->canDisplayGiftmessage()): ?>
    <script type="text/javascript">
        function giftMessageToogle(giftMessageIdentifier) {
            const link = document.getElementById('order-item-gift-message-link-' + giftMessageIdentifier);
            const container = document.getElementById('order-item-gift-message-' + giftMessageIdentifier);
            const row = document.getElementById('order-item-row-' + giftMessageIdentifier);

            if (link.expanded) {
                link.expanded = false;
                link.classList.remove('expanded');
                if (container.classList.contains('last')) {
                    row.classList.add('last');
                }
                container.style.display = 'none';
            } else {
                link.expanded = true;
                link.classList.add('expanded');
                if (container.classList.contains('last')) {
                    row.classList.remove('last');
                }
                container.style.display = 'block';
            }
            return false;
        }
    </script>
<?php endif ?>
    <?= $this->getChildHtml('invoice_items') ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->getBackTitle() ?></a></p>
    </div>
</div>
