<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Order_Items $this */
?>
<?php  $_order = $this->getOrder() ?>
<table class="data-table linearize-table-large" id="my-orders-table" summary="<?= $this->__('Items Ordered') ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?= $this->__('Product') ?></th>
            <th><?= $this->__('SKU') ?></th>
            <th class="a-right"><?= $this->__('Price') ?></th>
            <th class="a-center"><?= $this->__('Qty') ?></th>
            <th class="a-right"><?= $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?= $this->getChildHtml('order_totals') ?>
    </tfoot>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_index = 0; ?>
            <?php $_count = $_items->count(); ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getParentItem()) continue; ?>
        <tbody>
            <?= $this->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach ?>
</table>
