<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Order_Missing $this */

if ($this->shouldShowMissingOrdersLink()): ?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
                <strong><?= $this->__('Missing an order?') ?></strong><br />
                <?= $this->__('If you placed an order as a guest using this email address, you can add it to your account.') ?>
                <a href="<?= $this->getAssociateUrl() ?>" onclick="return confirm('<?= $this->escapeHtml($this->__('This will permanently associate all guest orders placed with your email address to your account. Continue?')) ?>');">
                    <?= $this->__('Click here to check for guest orders') ?>.
                </a>
            </li>
        </ul>
    </li>
</ul>
<?php endif; ?>
