<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */

if (Mage::helper('customer')->isCustomerEligibleForGuestOrderAssociation()): ?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
                <strong><?= $this->__('Missing an order?') ?></strong><br>
                <?= $this->__('Orders you placed as a guest with this email address are not listed here.') ?><br>
                <form action="<?= $this->escapeUrl($this->getUrl('sales/order/associateGuestOrders')) ?>" method="post">
                    <?= $this->getBlockHtml('formkey') ?>
                    <button type="submit" class="button"
                            onclick="return confirm('<?= $this->jsQuoteEscape($this->__('All orders you placed as a guest with this email address will be permanently added to your account. Continue?')) ?>')"
                    ><?= $this->escapeHtml($this->__('Add guest orders to my account')) ?></button>
                </form>
            </li>
        </ul>
    </li>
</ul>
<?php endif ?>
