<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Sales_Block_Order_Shipment $this */
?>
<div class="order-items order-details">
<?php if($this->canDisplayGiftmessage()): ?>
    <script>
        function giftMessageToogle(giftMessageIdentifier) {
            const link = document.getElementById('order-item-gift-message-link-' + giftMessageIdentifier);
            const container = document.getElementById('order-item-gift-message-' + giftMessageIdentifier);
            const row = document.getElementById('order-item-row-' + giftMessageIdentifier);

            if (link.expanded) {
                link.expanded = false;
                link.classList.remove('expanded');
                if (container.classList.contains('last')) {
                    row.classList.add('last');
                }
                container.style.display = 'none';
            } else {
                link.expanded = true;
                link.classList.add('expanded');
                if (container.classList.contains('last')) {
                    row.classList.remove('last');
                }
                container.style.display = 'block';
            }
            return false;
        }
    </script>
<?php endif ?>
    <?= $this->getChildHtml('shipment_items') ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->getBackTitle() ?></a></p>
    </div>
</div>
