<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<span class="field-row grid" id="shipment_tracking_info">

<?php if ($this->getTrackingInfo()): ?>
    <strong><?= $this->escapeHtml($this->getTrackingInfo()->getCarrierTitle()) ?></strong> - <?= $this->getTrackingInfo()->getTracking() ?>
    <div class="info">
        <?php if ($this->getTrackingInfo()->getErrorMessage()): ?>
            <?= $this->escapeHtml($this->getTrackingInfo()->getErrorMessage()) ?>
        <?php else: ?>
            <?php if ($this->getTrackingInfo()->getUrl()): ?>
                Please, visit for more info: <a href="<?= $this->getTrackingInfo()->getUrl() ?>" target="_blank"><?= $this->escapeHtml($this->getTrackingInfo()->getCarrierTitle()) ?></a><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getStatus()): ?>
                Status: <?= $this->getTrackingInfo()->getStatus() ?><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getDeliverydate()): ?>
                Delivery Date: <?= $this->getTrackingInfo()->getDeliverydate() ?><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getDeliverytime()): ?>
                Delivery Time: <?= $this->getTrackingInfo()->getDeliverytime() ?><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getDeliverylocation()): ?>
                Delivery Location: <?= $this->getTrackingInfo()->getDeliverylocation() ?><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getSignedby()): ?>
                Signed by: <?= $this->getTrackingInfo()->getSignedby() ?><br>
            <?php endif ?>

            <?php if ($this->getTrackingInfo()->getTrackSummary()): ?>
                Tracking summary: <?= $this->getTrackingInfo()->getTrackSummary() ?><br>
            <?php endif ?>

        <?php endif ?>
    </div>
<?php endif ?>

</span>
