<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Order_View $this */
?>
<div class="order-items order-details">
    <?php if ($this->canDisplayGiftmessageItems()): ?>
    <script type="text/javascript">
        function giftMessageToogle(giftMessageIdentifier) {
            const link = document.getElementById('order-item-gift-message-link-' + giftMessageIdentifier);
            const container = document.getElementById('order-item-gift-message-' + giftMessageIdentifier);
            const row = document.getElementById('order-item-row-' + giftMessageIdentifier);

            if (link.expanded) {
                link.expanded = false;
                link.classList.remove('expanded');
                if (container.classList.contains('last')) {
                    row.classList.add('last');
                }
                container.style.display = 'none';
            } else {
                link.expanded = true;
                link.classList.add('expanded');
                if (container.classList.contains('last')) {
                    row.classList.remove('last');
                }
                container.style.display = 'block';
            }
            return false;
        }
    </script>
    <?php endif ?>
    <?php $_order = $this->getOrder() ?>
    <h2 class="table-caption"><?= $this->__('Items Ordered') ?>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <span class="separator">|</span> <a href="#" onclick="popWin('<?= $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?= $this->quoteEscape($this->__('Track your order')) ?>"><?= $this->__('Track your order') ?></a>
        <?php endif ?>
    </h2>

    <?= $this->getChildHtml('order_items') ?>

    <?php if($this->canDisplayGiftmessageOrder()): ?>
    <div class="order-additional order-gift-message">
        <h2 class="sub-title"><?= $this->__('Gift Message for This Order') ?></h2>
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
        <dl class="gift-message">
            <dt><strong><?= $this->__('From:') ?></strong> <?= $this->escapeHtml($_giftMessage->getSender()) ?></dt>
            <dt><strong><?= $this->__('To:') ?></strong> <?= $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
            <dd><?= $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
        </dl>
    </div>
    <?php endif ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?= $this->__('About Your Order') ?></h2>
        <dl class="order-about">
            <?php foreach ($_history as $_historyItem): ?>
                <dt><?= $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?= $this->escapeHtml($_historyItem->getComment()) ?></dd>
            <?php endforeach ?>
        </dl>
    </div>
    <?php endif ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->getBackTitle() ?></a></p>
    </div>
</div>
