<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Sales_Block_Order_View $this */
?>
<div class="order-items order-details">
    <?php $_order = $this->getOrder() ?>
    <h2 class="table-caption"><?= $this->__('Items Ordered') ?>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <span class="separator">|</span> <a href="#" onclick="popWin('<?= $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?= $this->quoteEscape($this->__('Track your order')) ?>"><?= $this->__('Track your order') ?></a>
        <?php endif ?>
    </h2>

    <?= $this->getChildHtml('order_items') ?>

    <?php if($this->canDisplayGiftmessageOrder()): ?>
        <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
        <details class="gift-message order-level">
            <summary class="toggle">
                <?= $this->getIconSvg('gift') ?>
                <?= $this->__('Gift Message for This Order') ?>
            </summary>
            <div class="content">
                <div class="header">
                    <span><strong><?= $this->__('From:') ?></strong> <?= $this->escapeHtml($_giftMessage->getSender()) ?></span>
                    <span><strong><?= $this->__('To:') ?></strong> <?= $this->escapeHtml($_giftMessage->getRecipient()) ?></span>
                </div>
                <blockquote class="text"><?= $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></blockquote>
            </div>
        </details>
    <?php endif ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?= $this->__('About Your Order') ?></h2>
        <dl class="order-about">
            <?php foreach ($_history as $_historyItem): ?>
                <dt><?= $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?= $this->escapeHtml($_historyItem->getComment()) ?></dd>
            <?php endforeach ?>
        </dl>
    </div>
    <?php endif ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->getBackTitle() ?></a></p>
    </div>
</div>
