<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Cart_Item_Renderer $this */
?>
<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
$_deleteUrl = $this->getDeleteUrlCustom(false);
$_weeeHelper = Mage::helper('weee');
$_checkoutHelper = $this->helper('checkout');
$_weeeApplied = $_weeeHelper->getApplied($_item);
$_weeeAmount = $_item->getWeeeTaxAppliedAmount();
?>
<tr>
    <td class="product-cart-image">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?= $this->getProductUrl() ?>" title="<?= $this->escapeHtml($this->getProductName()) ?>" class="product-image">
        <?php endif ?>
            <img src="<?= $this->getProductThumbnail()->resize(180) ?>" alt="<?= $this->escapeHtml($this->getProductName()) ?>" />
        <?php if ($this->hasProductUrl()):?>
            </a>
        <?php endif ?>
    </td>

    <td class="product-cart-info">
        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?= $this->getProductUrl() ?>"><?= $this->escapeHtml($this->getProductName()) ?></a>
        <?php else: ?>
            <?= $this->escapeHtml($this->getProductName()) ?>
        <?php endif ?>
        </h2>

        <div class="product-cart-sku">
            <span class="label"><?= $this->__('SKU') ?>:</span> <?= $this->escapeHtml($_item->getSku()) ?>
        </div>

        <?php if ($_options = $this->getOptionList()):?>
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <div class="product-cart-sku<?php if (isset($_formatedOptionValue['full_view'])): ?> truncated<?php endif ?>">
                <span class="label"><?= $this->escapeHtml($_option['label']) ?>:</span>
                <?= $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <span class="label"><?= $this->escapeHtml($_option['label']) ?>:</span>
                    <?= $_formatedOptionValue['full_view'] ?>
                </div>
                <?php endif ?>
            </div>
            <?php endforeach ?>
        <?php endif ?>

        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?= $message['type'] ?>">
                * <?= $this->escapeHtml($message['text']) ?>
            </p>
        <?php endforeach ?>
        <?php endif ?>

        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif ?>

    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="a-center product-cart-price"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?= $this->__('See price before order confirmation.') ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?= $helpLinkId ?>" href="#" class="map-help-link"><?= $this->__("What's this?") ?></a>

                <script type="text/javascript">
                    Catalog.Map.addHelpLink('<?= $helpLinkId ?>', "<?= $this->jsQuoteEscape($this->__("What's this?")) ?>");
                </script>

            </span>
        </td>
    <?php else: ?>
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" data-rwd-label="<?= $this->__('Price') ?>" data-rwd-tax-label="<?= $this->__('Excl. Tax') ?>">
            <span class="cart-price">
                <?php if ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_weeeAmount): ?>
                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice() + $_weeeAmount + $_item->getWeeeTaxDisposition()) ?>
                <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeAmount): ?>
                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice() + $_weeeAmount + $_item->getWeeeTaxDisposition()) ?>
                <?php else: ?>
                    <?= $_checkoutHelper->formatPrice($_item->getCalculationPrice()) ?>
                <?php endif ?>
            </span>
            <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, [1, 2], 'sales') && $_weeeAmount): ?>
                <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_item->getCalculationPrice())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
            <?php endif ?>
        </td>
        <?php endif ?>

        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" data-rwd-label="<?= $this->__('Price') ?>" data-rwd-tax-label="<?= $this->__('Incl. Tax') ?>">
            <?php $_incl = $_checkoutHelper->getPriceInclTax($_item); ?>
            <span class="cart-price">
                <?php if ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_weeeAmount): ?>
                    <?= $_checkoutHelper->formatPrice($_incl + $_weeeHelper->getWeeeTaxInclTax($_item)) ?>
                <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeAmount): ?>
                    <?= $_checkoutHelper->formatPrice($_incl + $_weeeHelper->getWeeeTaxInclTax($_item)) ?>
                <?php else: ?>
                    <?= $_checkoutHelper->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                <?php endif ?>
            </span>
            <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, [1, 2], 'sales') && $_weeeAmount): ?>
                <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_incl - $_item->getWeeeTaxDisposition())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['amount_incl_tax'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
            <?php endif ?>
        </td>
        <?php endif ?>
    <?php endif ?>
    <td class="product-cart-actions" data-rwd-label="<?= $this->__('Qty') ?>">
        <input type="text" pattern="\d*(\.\d+)?" name="cart[<?= $_item->getId() ?>][qty]" value="<?= $this->getQty() ?>" size="4"
               data-cart-item-id="<?= $this->jsQuoteEscape($_item->getSku()) ?>"
               title="<?= $this->quoteEscape($this->__('Qty')) ?>" class="input-text qty" maxlength="12" />

        <button type="submit" name="update_cart_action" data-cart-item-update value="update_qty" title="<?= $this->quoteEscape($this->__('Update')) ?>" class="button btn-update"><?= $this->__('Update') ?>
        </button>
    </td>

    <!--Sub total starts here -->
    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal') ?>">
        <span class="cart-price">
            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php elseif ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_weeeAmount): ?>
                <?= $_checkoutHelper->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?>
            <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeAmount): ?>
                <?= $_checkoutHelper->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?>
            <?php else: ?>
                <?= $_checkoutHelper->formatPrice($_item->getRowTotal()) ?>
            <?php endif ?>
        </span>
        <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, [1, 2], 'sales') && $_weeeAmount): ?>
            <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_item->getRowTotal())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['row_amount'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
        <?php endif ?>
    </td>
    <?php endif ?>

    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal') ?>">
        <?php $_inclSubtotal = $_checkoutHelper->getSubtotalInclTax($_item); ?>
        <span class="cart-price">
            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php elseif ($_weeeHelper->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_weeeAmount): ?>
                <?= $_checkoutHelper->formatPrice($_inclSubtotal + $_weeeHelper->getRowWeeeTaxInclTax($_item)) ?>
            <?php elseif ($_weeeHelper->typeOfDisplay($_item, 2, 'sales') && $_weeeAmount): ?>
                <?= $_checkoutHelper->formatPrice($_inclSubtotal + $_weeeHelper->getRowWeeeTaxInclTax($_item)) ?>
            <?php else: ?>
                <?= $_checkoutHelper->formatPrice($_inclSubtotal - $_item->getWeeeTaxRowDisposition()) ?>
            <?php endif ?>
        </span>
        <?php if ($_weeeApplied && $_weeeHelper->typeOfDisplay($_item, [1, 2], 'sales') && $_weeeAmount): ?>
            <span class="weee-info" data-tooltip="<?= strip_tags($_checkoutHelper->formatPrice($_inclSubtotal - $_item->getWeeeTaxRowDisposition())) ?><?php foreach ($_weeeApplied as $tax): ?> + <?= $this->escapeHtml($tax['title']) ?> <?= strip_tags($_checkoutHelper->formatPrice($tax['row_amount_incl_tax'])) ?><?php endforeach ?>"><?= $this->getIconSvg('info-circle') ?></span>
        <?php endif ?>
    </td>
    <?php endif ?>
    <td class="product-cart-remove">
        <?php if ($isVisibleProduct): ?>
            <a href="<?= $this->getConfigureUrl() ?>" title="<?= $this->quoteEscape($this->__('Edit item parameters')) ?>">
                <?= $this->getIconSvg('edit') ?>
                <?= $this->__('Edit') ?>
            </a>
        <?php endif ?>

        <?php if ($this->helper('wishlist')->isAllowInCart() && $isVisibleProduct) : ?>
            <a href="<?= $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()) ?>" class="link-wishlist use-ajax" title="<?= $this->quoteEscape($this->__('Move to wishlist')) ?>">
                <?= $this->getIconSvg('heart') ?>
                <?= $this->__('Move to wishlist') ?>
            </a>
        <?php endif ?>

        <a href="#" title="<?= $this->quoteEscape($this->__('Remove Item')) ?>"
           onclick="customFormSubmit('<?= $_deleteUrl ?>', '<?= $_params ?>', 'post')">
            <?= $this->getIconSvg('x') ?>
            <?= $this->__('Remove Item') ?>
        </a>
    </td>
</tr>


