<?php
/**
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * New directory template for Wysiwyg Images
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content_Newfolder
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content_Newfolder $this 
 */
?>
