<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<table class="table-totals" cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td class="padding-totals">
            <table cellpadding="0" cellspacing="0" border="0">
                <?= $this->getChildHtml() ?>
            </table>
        </td>
    </tr>
</table>
