<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Paypal_Block_Adminhtml_System_Config_Payflowlink_Info $this */
?>
<div class="payflow-settings-notice">
    <strong class="important-label"><?= $this->__('Important: ') ?></strong>
    <?= $this->__('To use PayPal Payflow Link, you must configure your PayPal Payflow Link account on the PayPal website.') ?>
    <?= $this->__('Once you log into your PayPal Payflow Link account, navigate to the Service Settings - Hosted Checkout Pages - Set Up menu and set the options described below') ?>
    <ul class="options-list">
        <li><strong>AVS:</strong> No</li>
        <li><strong>CSC:</strong> No</li>
        <li><strong>Enable Secure Token:</strong> Yes</li>
    </ul>
</div>
