<?php
/**
 * Maho
 *
 * @package    Maho_Captcha
 * @copyright  Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
$helper = Mage::helper('captcha');
?>
<?php if ($helper->isEnabled()): ?>
<altcha-widget <?= $helper->getWidgetAttributes()->serialize() ?>></altcha-widget>
<script src="<?= Mage::getBaseUrl('js') ?>maho-captcha.js"></script>
<script>
MahoCaptcha.setup({
    frontendSelectors: '<?= $helper->getFrontendSelectors() ?>',
    widgetAttributes: <?= $helper->getWidgetAttributes()->toJson() ?>,
});
</script>
<?php endif ?>
