<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Customer_Edit_Tab_Cart $this */
?>
<?php if($this->getCartHeader()): ?>
<div class="content-header skip-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h4><?= $this->getCartHeader() ?></h4></td>
        </tr>
    </table>
</div>
<?php endif ?>
<?= $this->getGridParentHtml() ?>

<?php if ($this->canDisplayContainer()) : ?>
<script>
<?php $jsObjectName = $this->getJsObjectName() ?>
window.<?= $jsObjectName ?>cartControl = {
    reload (params) {
        if (!params) {
            params = {};
        }
        <?= $jsObjectName ?>.reloadParams = params;
        <?= $jsObjectName ?>.reload();
        <?= $jsObjectName ?>.reloadParams = {};
    },

    configureItem (itemId) {
        productConfigure.setOnLoadIFrameCallback('<?= $jsObjectName ?>', this.cbOnLoadIframe.bind(this));
        productConfigure.showItemConfiguration('<?= $jsObjectName ?>', itemId);
        return false;
    },

    cbOnLoadIframe (response) {
        if (!response.ok) {
            return;
        }
        this.reload();
    },

    removeItem (itemId) {
        if (!itemId) {
            alert('<?= $this->jsQuoteEscape(Mage::helper('customer')->__('No item specified.')) ?>');
            return false;
        }
        if(!confirm('<?= $this->jsQuoteEscape(Mage::helper('customer')->__('Are you sure that you want to remove this item?')) ?>')) {
            return false;
        }

        this.reload({'delete':itemId});

        return false;
    },
};

<?php
$params = [
    'customer_id' => $this->getCustomer()->getId(),
    'website_id' => $this->getWebsiteId(),
];
?>
productConfigure.addListType('<?= $jsObjectName ?>', {
    urlFetch: '<?= $this->getUrl('*/customer_cart_product_composite_cart/configure', $params) ?>',
    urlConfirm: '<?= $this->getUrl('*/customer_cart_product_composite_cart/update', $params) ?>'
});
</script>
<?php endif ?>
