<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 *
 * @see Mage_Adminhtml_Block_Customer_Edit_Tab_View
 * @var Mage_Adminhtml_Block_Customer_Edit_Tab_View $this
 */
?>
<?php
$lastLoginDateAdmin = $this->getLastLoginDate();
$lastLoginDateStore = $this->getStoreLastLoginDate();

$createDateAdmin    = $this->getCreateDate();
$createDateStore    = $this->getStoreCreateDate();
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?= Mage::helper('customer')->__('Personal Information') ?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?= $this->__('Last Logged In:') ?></strong></td>
                <td><?= $this->escapeHtml($lastLoginDateAdmin) ?> (<?= $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
            <tr>
                <td><strong><?= $this->__('Last Logged In (%s):', $this->getStoreLastLoginDateTimezone()) ?></strong></td>
                <td><?= $this->escapeHtml($lastLoginDateStore) ?> (<?= $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php endif ?>
            <tr>
                <td><strong><?= $this->__('Confirmed email:') ?></strong></td>
                <td><?= $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->__('Account Created on:') ?></strong></td>
                <td><?= $createDateAdmin ?></td>
            </tr>
            <?php if ($createDateAdmin != $createDateStore): ?>
            <tr>
                <td><strong><?= $this->__('Account Created on (%s):', $this->getStoreCreateDateTimezone()) ?></strong></td>
                <td><?= $createDateStore ?></td>
            </tr>
            <?php endif ?>
            <tr>
                <td><strong><?= $this->__('Account Created in:') ?></strong></td>
                <td><?= $this->escapeHtml($this->getCreatedInStore()) ?></td>
            </tr>
            <tr>
                <td><strong><?= $this->__('Customer Group:') ?></strong></td>
                <td><?= $this->escapeHtml($this->getGroupName()) ?></td>
            </tr>
        </table>
        <address class="box-right">
            <strong><?= $this->__('Default Billing Address') ?></strong><br/>
            <?= $this->maliciousCodeFilter($this->getBillingAddressHtml()) ?>
        </address>
    </fieldset>
</div>
<?= $this->getChildHtml('', true, true) ?>
