<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Customer_Edit_Tab_Wishlist $this */
?>
<?php if($this->getWishlistHeader()): ?>
<div class="content-header skip-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h4><?= $this->getWishlistHeader() ?></h4></td>
        </tr>
    </table>
</div>
<?php endif ?>
<?= $this->getGridParentHtml() ?>

<?php if($this->canDisplayContainer()): ?>
<script>
<?php $jsObjectName = $this->getJsObjectName() ?>
window.wishlistControl = {
    reload (params) {
        if (!params) {
            params = {};
        }
        <?= $jsObjectName ?>.reloadParams = params;
        <?= $jsObjectName ?>.reload();
        <?= $jsObjectName ?>.reloadParams = {};
    },

    configureItem (itemId) {
        productConfigure.setOnLoadIFrameCallback('wishlist', this.cbOnLoadIframe.bind(this));
        productConfigure.showItemConfiguration('wishlist', itemId);
        return false;
    },

    cbOnLoadIframe (response) {
        if (!response.ok) {
            return;
        }
        this.reload();
    },

    removeItem (itemId) {
        if (!itemId) {
            alert('<?= $this->jsQuoteEscape(Mage::helper('customer')->__('No item specified.')) ?>');
            return false;
        }
        if(!confirm('<?= $this->jsQuoteEscape(Mage::helper('customer')->__('Are you sure that you want to remove this item?')) ?>')) {
            return false;
        }

        this.reload({'delete':itemId});

        return false;
    },
}

<?php
$params = [
    'customer_id' => $this->getCustomer()->getId(),
    'website_id' => $this->getWebsiteId(),
];
?>
productConfigure.addListType('wishlist', {
    urlFetch: '<?= $this->getUrl("*/customer_wishlist_product_composite_wishlist/configure", $params) ?>',
    urlConfirm: '<?= $this->getUrl("*/customer_wishlist_product_composite_wishlist/update", $params) ?>',
});
</script>
<?php endif ?>
