<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>
<form id="co-billing-form" action="">
<div class="fieldset">
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select"><?= $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?= $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>

        <?= $this->getChildHtml('form_checkout_address_create') ?>

        <div class="fieldset">
            <ul class="form-list">

            <?php if (!$this->isCustomerLoggedIn()): ?>
                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="required"><em>*</em><?= $this->__('Password') ?></label>
                        <div class="input-box">
                            <?php $minPasswordLength = $this->getQuote()->getCustomer()->getMinPasswordLength(); ?>
                            <input type="password"
                                   name="billing[customer_password]"
                                   id="billing:customer_password"
                                   title="<?= $this->quoteEscape($this->__('Password')) ?>"
                                   class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
                                   autocomplete="new-password" />
                            <p class="form-instructions">
                                <?= Mage::helper('customer')->__('The minimum password length is %s', $minPasswordLength) ?>
                            </p>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="required"><em>*</em><?= $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?= $this->quoteEscape($this->__('Confirm Password')) ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" autocomplete="new-password" />
                        </div>
                    </div>
                </li>
                <?= $this->getChildHtml('remember.me') ?>
            <?php endif ?>

            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                <li class="control">
                    <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?= $this->quoteEscape($this->__('Save in address book')) ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif ?> class="checkbox" /><label for="billing:save_in_address_book"><?= $this->__('Save in address book') ?></label>
                </li>
            <?php else: ?>
                <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
            <?php endif ?>

                <?= $this->getChildHtml('form.additional.info') ?>
            </ul>
        </div>
    </li>
    <?php /* Extensions placeholder */ ?>
    <?= $this->getChildHtml('checkout.onepage.billing.extra') ?>
    <?php if ($this->canShip()): ?>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?= $this->quoteEscape($this->__('Ship to this address')) ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?=  $this->__('Ship to this address') ?></label></li>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?= $this->quoteEscape($this->__('Ship to different address')) ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?= $this->__('Ship to different address') ?></label>
        </li>
    <?php endif ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif ?>
    <div class="buttons-set" id="billing-buttons-container">
        <button type="button" title="<?= $this->quoteEscape($this->__('Continue')) ?>" class="button" onclick="billing.save()"><?= $this->__('Continue') ?></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" title="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?= $this->__('Loading next step...') ?>
        </span>
    </div>
    <?= $this->getBlockHtml('formkey') ?>
</div>
</form>
<script type="text/javascript">
    var billing = new Billing('co-billing-form', '<?= $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?= $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    const billingAddressSelect = document.getElementById('billing-address-select');
    if (billingAddressSelect) {
        billing.newAddress(!billingAddressSelect.value);
    }

    var billingRegionUpdater = new RegionUpdater(
        'billing:country_id', 'billing:region', 'billing:region_id',
        <?= Mage::helper('directory')->getRegionJsonByStore() ?>, undefined, 'billing:postcode'
    );

    const guestRegisterButton = document.getElementById('onepage-guest-register-button');
    if (guestRegisterButton) {
        guestRegisterButton.addEventListener('click', function(event) {
            const billingForm = document.getElementById('co-billing-form');
            const billingRememberMe = billingForm.querySelectorAll('.remember-me-box');

            if (billingRememberMe.length > 0) {
                const loginGuest = document.getElementById('login:guest');
                const loginRegister = document.getElementById('login:register');

                if (loginGuest && loginGuest.checked) {
                    billingRememberMe[0].style.display = 'none';
                } else if (loginRegister && (loginRegister.checked || loginRegister.type == 'hidden')) {
                    billingRememberMe[0].style.display = 'block';
                }
            }
        });
    }
</script>
