<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Failure $this */
?>
<div class="page-title">
    <h1><?= $this->__('An error occurred in the process of payment') ?></h1>
</div>
<?php if ($this->getRealOrderId()) : ?><p><?= $this->__('Order #') . $this->getRealOrderId() ?></p><?php endif ?>
<?php if ($error = $this->getErrorMessage()) : ?><p><?= $error ?></p><?php endif ?>
<p><?= $this->__('Click <a href="%s">here</a> to continue shopping.', $this->quoteEscape($this->getContinueShoppingUrl())) ?></p>
