<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Link $this */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?= $this->quoteEscape($this->__('Proceed to Checkout')) ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif ?> onclick="window.location='<?= $this->getCheckoutUrl() ?>';"><?= $this->__('Proceed to Checkout') ?></button>
<?php endif ?>
