<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?= Mage::helper('core')->quoteEscape($this->__('Proceed to Checkout')) ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif ?> onclick="window.location='<?= $this->getCheckoutUrl() ?>';"><?= $this->__('Proceed to Checkout') ?></button>
<?php endif ?>
