<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2020-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Payment $this */
?>
<?= $this->getChildChildHtml('before_form') ?>
<script>
    var quoteBaseGrandTotal = <?= (float)$this->getQuoteBaseGrandTotal() ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var quoteGrandTotalClean = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?= $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
</script>
<form action="" id="co-payment-form">
    <div class="fieldset">
        <?= $this->getChildChildHtml('methods_additional', '', true, true) ?>
        <?= $this->getChildHtml('methods') ?>
    </div>
    <?= $this->getBlockHtml('formkey') ?>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?= $this->quoteEscape($this->__('Close')) ?>"><?= $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?= $this->getSkinUrl('images/cvv.gif') ?>" alt="<?= $this->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" title="<?= $this->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>"></div>
</div>
<?= $this->getChildChildHtml('additional') ?>
<div class="buttons-set" id="payment-buttons-container">
    <?php // Moved to CC form ?>
    <button type="button" class="button" onclick="payment.save()"><?= $this->__('Continue') ?></button>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" title="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle"> <?= $this->__('Loading next step...') ?>
    </span>
</div>
<script>
    payment.currentMethod = "<?= $this->getChild('methods')->getSelectedMethodCode() ?>";
    function toggleToolTip(event) {
        let paymentToolTip = document.getElementById('payment-tool-tip');
        if (paymentToolTip) {
            paymentToolTip.style = {
                top: (event.clientY-560) + 'px'
            }
            paymentToolTip.classList.toggle('hidden');
        }
        event.preventDefault();
    }
    let paymentToolTipClose = document.getElementById('payment-tool-tip-close');
    if (paymentToolTipClose){
        paymentToolTipClose.addEventListener('click', toggleToolTip);
    }
</script>
