<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Shipping_Method $this */
?>
<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load"></div>
    <script>
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?= $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    </script>
    <div id="onepage-checkout-shipping-method-additional-load"><?= $this->getChildHtml('additional') ?></div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <button type="button" class="button" onclick="shippingMethod.save()"><?= $this->__('Continue') ?></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" title="<?= $this->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle"> <?= $this->__('Loading next step...') ?>
        </span>
    </div>
    <?= $this->getBlockHtml('formkey') ?>
</form>
