<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Created $this */
?>
<script>
var added = false;
function addProduct(closeAfter) {
    if(window.opener != null && !added) {
        if (window.opener.superProduct) {
            <?php if($this->isEdit()): ?>
            window.opener.superProduct.updateProduct(<?= $this->getProductId() ?>, <?= $this->getAttributesJson() ?>);
            <?php else: ?>
            window.opener.superProduct.addNewProduct(<?= $this->getProductId() ?>, <?= $this->getAttributesJson() ?>);
            window.opener.superProduct.showNoticeMessage();
            <?php endif ?>
            added = true;
        } else if (window.opener.catalog_category_productsJsObject) {
            window.opener.catalog_category_productsJsObject.reload(null);
        }
    }

    if(closeAfter)
    {
        closeWindow();
    }
}

function closeWindow()
{
    if (window.opener) {
        window.opener.focus();
    }
    window.close();
}

addProduct(false);
setTimeout(closeWindow, 3000);
</script>
<div class="a-center">
<?= $this->getCloseButtonHtml() ?>
</div>
