<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?= $this->getColumnHtml($_item, 'configurable_name') ?></td>
    <td><?= $this->getColumnHtml($_item, 'qty') ?></td>


    <td class="<?php if ($this->isShipmentRegular()): ?>last<?php endif ?> a-center">
        <?php if ($this->canShipPartiallyItem()): ?>
            <input type="text" class="input-text" name="shipment[items][<?= $_item->getOrderItemId() ?>]" value="<?= $_item->getQty()*1 ?>" />
        <?php else: ?>
            <?= $_item->getQty()*1 ?>
        <?php endif ?>
    </td>
    <?php if (!$this->canShipPartiallyItem()): ?>
    <td class="a-center last">
        <input type="hidden" name="shipment[items][<?= $_item->getOrderItemId() ?>]" value="0" />
        <input type="checkbox" name="shipment[items][<?= $_item->getOrderItemId() ?>]" value="<?= $_item->getQty()*1 ?>" checked />
    </td>
    <?php endif ?>
</tr>
