<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>

<?php
/**
 * JS block for including Countries with Optional Zip
 *
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<?php $optional_zip_countries = $this->helper('directory')->getCountriesWithOptionalZip(false) ?>
<?php if (!empty($optional_zip_countries)): ?>
    <script>
        optionalZipCountries = <?= $this->helper('core')->jsonEncode($optional_zip_countries) ?>;
    </script>
<?php endif ?>
