<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2023 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
/**
 * JS block for including Countries with Optional Zip
 *
 * @see Mage_Core_Block_Template
 */
?>
<?php $optional_zip_countries = $this->helper('directory')->getCountriesWithOptionalZip(false) ?>
<?php if (!empty($optional_zip_countries)): ?>
    <script>
        //<![CDATA[
        optionalZipCountries = <?= $this->helper('core')->jsonEncode($optional_zip_countries) ?>;
        //]]>
    </script>
<?php endif ?>
