<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Categories $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= Mage::helper('catalog')->__('Product Categories') ?></h4>
    </div>
    <fieldset id="group_fields">
        <input type="hidden" name="category_ids" id="product_categories" value="<?= $this->getIdsString() ?>">
        <div id="product-categories" class="hor-scroll"></div>
    </fieldset>
</div>

<?php if ($rootNode = $this->getRootNode()): ?>
<script type="module">
    // In store view mode, keep a list of categories outside of the store's root category
    const nonRootIds = <?= $this->jsonEncode(
        array_values(array_diff($this->getCategoryIds(), array_keys($rootNode->getAllChildNodes())))
    ) ?>;

    const tree = new MahoTree('product-categories', {
        showRootNode: <?= var_export((bool) $rootNode->getIsVisible(), true) ?>,
        lazyload: {
            nodeParameter: 'category',
            dataUrl: '<?= $this->getLoadTreeUrl() ?>',
        },
        selectable: {
            mode: 'simple',
            onSelect: (selected) => {
                const selectedIds = selected.map((obj) => obj.id);
                document.getElementById('product_categories').value = [...selectedIds, nonRootIds].join(',');
            },
        },
    });
    tree.setRootNode({
        id: '<?= $rootNode->getId() ?>',
        text: '<?= $this->jsQuoteEscape($this->buildNodeName($rootNode)) ?>',
        expanded: true,
        checked: <?= var_export((bool) $rootNode->getChecked(), true) ?>,
        disabled: <?= var_export((bool) $rootNode->getDisabled(), true) ?>,
        children: <?= $this->getTreeJson() ?>
    });
</script>
<?php endif ?>
