<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Options $this */
?>
<div class="entry-edit custom-options product-custom-options">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?= $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?= Mage::helper('catalog')->__('Custom Options') ?></h4>
        <div class="form-buttons"><?= $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
        <?= $this->getOptionsBoxHtml() ?>
    </div>
</div>

<script>
// re-bind form elements onchange
varienWindowOnload();
//show error message
if (document.getElementById('price_type')) {
    if (document.getElementById('price_type').value == '0' && document.getElementById('dynamic-price-warrning')) {
        document.getElementById('dynamic-price-warrning').style.display = '';
    }
}
</script>
