<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Options $this */
?>
<div class="entry-edit custom-options product-custom-options">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?= $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?= Mage::helper('catalog')->__('Custom Options') ?></h4>
        <div class="right"><?= $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
        <?= $this->getOptionsBoxHtml() ?>
    </div>
</div>

<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
//show error message
if (document.getElementById('price_type')) {
    if (document.getElementById('price_type').value == '0' && document.getElementById('dynamic-price-warrning')) {
        document.getElementById('dynamic-price-warrning').style.display = '';
    }
}
</script>
