<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Ajax_Serializer $this */
?>

<?php $_id = 'id_' . md5(microtime()) ?>
<input type="hidden" name="<?= $this->getInputElementName() ?>"  value="" id="<?= $_id ?>">
<script>
// create serializer controller, that will syncronize grid checkboxes with hidden input
new productLinksController('<?= $_id?>', <?= $this->getProductsJSON() ?>, <?= $this->getGridBlock()->getJsObjectName() ?>);
</script>
