<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Ajax_Serializer $this */
?>

<?php $_id = 'id_' . md5(microtime()) ?>
<input type="hidden" name="<?= $this->getInputElementName() ?>"  value="" id="<?= $_id ?>" />
<script type="text/javascript">
// create serializer controller, that will syncronize grid checkboxes with hidden input
new productLinksController('<?= $_id?>', <?= $this->getProductsJSON() ?>, <?= $this->getGridBlock()->getJsObjectName() ?>);
</script>
