<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?php $this->getChild('head')->unsetChildren(); ?>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-popup<?= $this->getBodyClass()?$this->getBodyClass() : '' ?>">
<div>
    <?= $this->getChildHtml('after_body_start') ?>
    <?= $this->getChildHtml('global_notices') ?>
    <?= $this->getChildHtml('content') ?>
    <?= $this->getChildHtml('before_body_end') ?>
</div>
<?= $this->getAbsoluteFooter() ?>
</body>
</html>
