<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2018 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= Mage::helper('adminhtml')->__('Log into Maho Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?= $this->getSkinUrl('login.css') ?>" media="all" />
    <?= Mage::helper('page')->getFaviconHtml() ?>
    <script type="text/javascript" src="<?= $this->getJsUrl('validation.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm">
                <fieldset class="login-form">
                    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
                    <h2><?= Mage::helper('adminhtml')->__('Forgot your user name or password?') ?></h2>
                    <div id="messages">
                        <?= $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div class="input-box forgot-password">
                        <label for="email"><?= Mage::helper('adminhtml')->__('Email Address:') ?></label><br />
                        <input type="email" id="email" name="email" value="" class="required-entry input-text forgot-password validate-email" autofocus="autofocus" style="width:461px;" />
                    </div>
                    <?= $this->getChildHtml('form.additional.info') ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?= $this->getUrl('adminhtml', ['_nosecret' => true]) ?>">&laquo; <?= Mage::helper('adminhtml')->__('Back') ?></a>
                        <input type="submit" class="forgot-password form-button" value="<?= Mage::helper('adminhtml')->__('Retrieve Password') ?>">
                    </div>
                </fieldset>
                <p class="legal">Powered by Maho</p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>
