<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2018 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="<?= substr(Mage::app()->getLocale()->getLocaleCode(), 0, 2) ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= Mage::helper('adminhtml')->__('Log into Maho Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?= $this->getSkinUrl('login.css') ?>" media="all" />
    <?= Mage::helper('page')->getFaviconHtml() ?>
    <script type="text/javascript" src="<?= $this->getJsUrl('validation.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('maho-passkey-tools.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="<?= $this->getUrl('adminhtml') ?>" id="loginForm">
                <div class="login-form">
                    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
                    <h2><?= Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?= $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div id="step1">
                        <div class="input-box input-left">
                            <label for="username"><?= Mage::helper('adminhtml')->__('User Name:') ?></label><br />
                            <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" autofocus="autofocus" autocomplete="username" />
                        </div>
                        <div class="input-box input-right">
                            <label for="login"><?= Mage::helper('adminhtml')->__('Password:') ?></label><br />
                            <input type="password" id="login" name="login[password]" value="" class="required-entry input-text" autocomplete="current-password" />
                        </div>
                        <?= $this->getChildHtml('form.additional.info') ?>
                        <div class="clear"></div>
                        <div class="form-buttons">
                            <a class="left" href="<?= Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', ['_nosecret' => true]) ?>"><?= Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                            <input type="submit" class="form-button" value="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" title="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" />

                            <button type="button" id="passkey-login-button" class="form-button">
                                <?php echo $this->__('Login with Passkey') ?>
                            </button>
                        </div>
                    </div>
                    <div id="step2" class="no-display">
                        <div class="input-box input-left">
                            <label for="twofa_verification_code"><?= Mage::helper('adminhtml')->__('2FA verification code:') ?></label><br />
                            <input type="text" id="twofa_verification_code" name="login[twofa_verification_code]" value="" class="required-entry input-text validate-number" autocomplete="one-time-code" disabled />
                        </div>
                        <div class="clear"></div>
                        <div class="form-buttons">
                            <a id="back-button" class="left" href="#"><?= Mage::helper('adminhtml')->__('Back') ?></a>
                            <input type="submit" class="form-button" value="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" title="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" />
                        </div>
                    </div>
                </div>
                <p class="legal">Powered by Maho</p>
            </form>
            <div class="bottom"></div>
            <script type="module">
                history.replaceState(null, null, window.location.href);
                const formEl = document.getElementById('loginForm');
                const validator = new Validation(formEl);
                const messagesEl = document.getElementById('messages');

                formEl.addEventListener('submit', (event) => {
                    event.preventDefault();
                    messagesEl.textContent = '';
                    if (!validator.validate()) {
                        return;
                    }
                    if (document.getElementById('step1').classList.contains('no-display')) {
                        formEl.submit();
                    } else {
                        gotoStep(2);
                    }
                });

                document.getElementById('back-button').addEventListener('click', (event) => {
                    event.preventDefault();
                    messagesEl.textContent = '';
                    gotoStep(1);
                });

                document.getElementById('passkey-login-button').addEventListener('click', (event) => {
                    validator.reset();
                    messagesEl.textContent = '';
                    if (!Validation.validate(document.getElementById('username'))) {
                        return;
                    }
                    startPasskeyAuthentication();
                });

                async function mahoFetch(url, options) {
                    const ajaxUrl = new URL(url);
                    ajaxUrl.searchParams.set('isAjax', true);

                    const response = await fetch(ajaxUrl, options);
                    const result = await response.json();

                    if (result.redirect) {
                        window.location = result.redirect;
                        await new Promise((resolve) => {});
                    } else if (result.error) {
                        throw new Error(result.message);
                    }
                    if (!response.ok) {
                        throw new Error(
                            "<?= Mage::helper('adminhtml')->__('Network Error. Please refresh the page.') ?>"
                        );
                    }
                    return result;
                }

                async function gotoStep(step) {
                    if (step === 1) {
                        document.getElementById('step1').classList.remove('no-display');
                        document.getElementById('step2').classList.add('no-display');
                        document.getElementById('twofa_verification_code').value = '';
                        document.getElementById('twofa_verification_code').disabled = true;
                    } else if (step === 2) {
                        try {
                            const result = await mahoFetch("<?= $this->getUrl('adminhtml/index/prelogin') ?>", {
                                method: 'POST',
                                body: new FormData(formEl),
                            });

                            if (result.require_twofa) {
                                document.getElementById('step1').classList.add('no-display');
                                document.getElementById('step2').classList.remove('no-display');
                                document.getElementById('twofa_verification_code').disabled = false;
                                document.getElementById('twofa_verification_code').focus();
                            } else {
                                formEl.submit();
                            }
                        } catch (error) {
                            messagesEl.textContent = error.message;
                        }
                    }
                }

                async function startPasskeyAuthentication() {
                    try {
                        const result = await mahoFetch("<?= $this->getUrl('adminhtml/index/passkeyloginstart') ?>", {
                            method: 'POST',
                            body: new FormData(formEl),
                        });

                        recursiveBase64StrToArrayBuffer(result);

                        const cred = await navigator.credentials.get(result);
                        const passkeyData = {
                            id: cred.rawId ? arrayBufferToBase64(cred.rawId) : null,
                        }
                        for (const [ key, val ] of Object.entries(cred.response)) {
                            passkeyData[key] = val ? arrayBufferToBase64(val) : null;
                        }

                        document.getElementById('login').value = JSON.stringify(passkeyData);
                        gotoStep(2);
                    } catch (error) {
                        messagesEl.textContent = error.message;
                    }
                }
            </script>
        </div>
    </div>
</body>
</html>
