<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2018 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= Mage::helper('adminhtml')->__('Log into Maho Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?= $this->getSkinUrl('login.css') ?>" media="all" />
    <link rel="icon" type="image/svg+xml" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" sizes="any">
    <link rel="icon" type="image/png" href="<?= $this->getSkinUrl('images/favicon.png') ?>">
    <script type="text/javascript" src="<?= $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('validation.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="<?= $this->getUrl('adminhtml') ?>" id="loginForm">
                <div class="login-form">
                    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
                    <h2><?= Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?= $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div class="input-box input-left">
                        <label for="username"><?= Mage::helper('adminhtml')->__('User Name:') ?></label><br />
                        <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" autofocus="autofocus" />
                    </div>
                    <div class="input-box input-right">
                        <label for="login"><?= Mage::helper('adminhtml')->__('Password:') ?></label><br />
                        <input type="password" id="login" name="login[password]" value="" class="required-entry input-text" />
                    </div>
                    <?php if (Mage::getSingleton('adminhtml/session')->getShowTwofaVerificationCode()): ?>
                        <div class="input-box input-left">
                            <label for="twofa_verification_code"><?= Mage::helper('adminhtml')->__('2FA verification code:') ?></label><br />
                            <input type="text" id="twofa_verification_code" name="login[twofa_verification_code]" value="" class="required-entry input-text validate-number" />
                        </div>
                    <?php endif; ?>
                    <?= $this->getChildHtml('form.additional.info') ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?= Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', ['_nosecret' => true]) ?>"><?= Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                        <input type="submit" class="form-button" value="<?= Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" title="<?= Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" />
                    </div>
                </div>
                <p class="legal">Powered by Maho</p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>
