<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page $this */
?>
<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
    <?= $this->getChildHtml('head') ?>
</head>

<body id="html-body"<?= $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
<?= $this->getChildHtml('notification_window') ?>
<div class="wrapper">
    <?= $this->getChildHtml('global_notices') ?>
        <div class="header">
            <?= $this->getChildHtml('header') ?>
        <div class="clear"></div>
            <?= $this->getChildHtml('menu') ?>
        </div>
        <?= $this->getChildHtml('notifications') ?>
        <div class="middle" id="anchor-content">
            <div id="page:main-container">
            <?php if($this->getChildHtml('left')): ?>

                <div class="columns <?= $this->getContainerCssClass() ?>">
                    <div class="side-col" id="page:left">
                        <?= $this->getChildHtml('left') ?>
                    </div>
                    <div class="main-col" id="content">
                        <div class="main-col-inner">
                            <div id="messages"><?= $this->getMessagesBlock()->toHtml() ?></div>
                            <?= $this->getChildHtml('content') ?>
                        </div>
                    </div>
                </div>

            <?php else: ?>
                <div id="messages"><?= $this->getMessagesBlock()->toHtml() ?></div>
                <?= $this->getChildHtml('content') ?>
            <?php endif ?>
            </div>
        </div>
        <div class="footer">
            <?= $this->getChildHtml('footer') ?>
        </div>
    </div>
    <?= $this->getChildHtml('js') ?>
    <?= $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <div class="backdrop"></div>
    <p class="loader" id="loading_mask_loader">
        <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>"/><br/><?= Mage::helper('adminhtml')->__('Please wait...') ?>
    </p>
</div>

<?= $this->getChildHtml('before_body_end') ?>

</body>
</html>
