<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page $this */
?>
<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
    <?= $this->getChildHtml('head') ?>
</head>

<body id="html-body"<?= $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
    <?= $this->getChildHtml('notification_window') ?>

    <div class="wrapper">
        <?= $this->getChildHtml('global_notices') ?>
        <header class="header">
            <?= $this->getChildHtml('header') ?>
            <?= $this->getChildHtml('menu') ?>
        </header>
        <?= $this->getChildHtml('notifications') ?>
        <div id="anchor-content" class="middle">
            <div id="page:main-container">
                <div id="page:container" class="columns <?php echo $this->getContainerCssClass() ?>">
                    <aside id="page:left" class="side-col">
                        <?= $this->getChildHtml('left') ?>
                    </aside>
                    <main id="content" class="main-col">
                        <div id="messages"><?= $this->getMessagesBlock()->toHtml() ?></div>
                        <?= $this->getChildHtml('content') ?>
                    </main>
                </div>
            </div>
        </div>
        <footer class="footer">
            <?= $this->getChildHtml('footer') ?>
        </footer>
    </div>

    <?= $this->getChildHtml('js') ?>
    <?= $this->getChildHtml('profiler') ?>
    <?= $this->getChildHtml('before_body_end') ?>

</body>
</html>
