<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<div class="content-header">
    <h3><?= $this->__('System busy') ?></h3>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('Status') ?></h4>
    </div>
    <div class="fieldset ">
        <ul class="messages">
            <li class="success-msg">
                <ul>
                    <li><?= $this->getStatusMessage() ?></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
