<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Options_Type_File $this */
$option = $this->getOption();
$optionId = $option->getId();
$fileInfo = $this->getFileInfo();
$fileExists = (bool) $fileInfo->hasData();
$fileName = "options_{$option->getId()}_file";
$fieldNameAction = "{$fileName}_action";
$fieldValueAction = $fileExists ? 'save_old' : 'save_new';
$fileNamed = "{$fileName}_name";
$jsVarName = 'opFile' . rand();
?>

<dt>
    <label<?= $option->getIsRequired() ? ' class="required"' : '' ?> for="option_<?= $optionId ?>"><?= $this->escapeHtml($option->getTitle()) ?></label>
    <?= $this->getFormatedPrice() ?>
</dt>
<dd>
<?php if ($fileExists): ?>
    <span class="<?= $fileNamed ?>"><?= $this->escapeHtml($fileInfo->getTitle()) ?></span>
    <a href="javascript:void(0)" class="label" onclick="<?= $jsVarName ?>.toggleFileChange(this.closest('dd').querySelector('.input-box'))">
        <?= Mage::helper('catalog')->__('Change') ?>
    </a>
    <?php if (!$option->getIsRequired()): ?>
        <label>
            <input type="checkbox" onclick="<?= $jsVarName ?>.toggleFileDelete(this, this.closest('dd').querySelector('.input-box'))" />
            <?= Mage::helper('catalog')->__('Delete') ?>
        </label>
    <?php endif ?>
<?php endif ?>
    <div class="input-box<?= $fileExists ? ' no-display' : '' ?>">
        <input type="file" id="option_<?= $optionId ?>" name="<?= $fileName ?>" class="product-custom-option<?= $option->getIsRequired() ? ' required-entry' : '' ?>" <?= $fileExists ? 'disabled="disabled"' : '' ?> onchange="opConfig.reloadPrice()" />
        <input type="hidden" name="<?= $fieldNameAction ?>" value="<?= $fieldValueAction ?>" />
        <?php $sanitizedExtensions = $this->getSanitizedFileExtension(); ?>
        <?php if ($sanitizedExtensions): ?>
        <p class="no-margin"><?= Mage::helper('catalog')->__('Allowed file extensions to upload')?>: <strong><?= $sanitizedExtensions ?></strong></p>
        <?php endif ?>
        <?php if ($option->getImageSizeX() > 0): ?>
        <p class="no-margin"><?= Mage::helper('catalog')->__('Maximum image width')?>: <strong><?= $option->getImageSizeX() ?> <?= Mage::helper('catalog')->__('px.') ?></strong></p>
        <?php endif ?>
        <?php if ($option->getImageSizeY() > 0): ?>
        <p class="no-margin"><?= Mage::helper('catalog')->__('Maximum image height')?>: <strong><?= $option->getImageSizeY() ?> <?= Mage::helper('catalog')->__('px.') ?></strong></p>
        <?php endif ?>
        <p class="no-margin"><?= Mage::helper('catalog')->__('Maximum file size')?>: <strong><?= $this->getMaxFileSizeMb() ?> MB</strong></p>
    </div>
</dd>

<script>
    window.<?= $jsVarName ?> = {
        initializeFile(inputBox) {
            this.inputFile = inputBox.querySelector('input[name="<?= $fileName ?>"]');
            this.inputFileAction = inputBox.querySelector('input[name="<?= $fieldNameAction ?>"]');
            this.fileNameBox = inputBox.closest('dd').querySelector('.<?= $fileNamed ?>');
        },
        toggleFileChange(inputBox) {
            this.initializeFile(inputBox);
            inputBox.classList.remove('no-display');
            this.fileChangeFlag = this.fileChangeFlag ? false : true;
            if (!this.fileDeleteFlag) {
                if (this.fileChangeFlag) {
                     this.inputFileAction.value = 'save_new';
                     this.inputFile.disabled = false;
                 } else {
                     this.inputFileAction.value = 'save_old';
                     this.inputFile.disabled = true;
                 }
            }
        },
        toggleFileDelete(fileDeleteFlag, inputBox) {
            this.initializeFile(inputBox);
            this.fileDeleteFlag = fileDeleteFlag.checked ? true : false;
            if (this.fileDeleteFlag) {
                this.inputFileAction.value = '';
                this.inputFile.disabled = true;
                this.fileNameBox.style.textDecoration = 'line-through';
            } else {
                this.inputFileAction.value = this.fileChangeFlag ? 'save_new' : 'save_old';
                this.inputFile.disabled = this.fileChangeFlag === 'save_old';
                this.fileNameBox.style.textDecoration = null;
            }
        }
    };
</script>
