<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Mage_Bundle
 */

declare(strict_types=1);

use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\ForeignKeyConstraint;
use Doctrine\DBAL\Schema\ForeignKeyConstraint\ReferentialAction;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Index\IndexType;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\SchemaEditor;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Types;

return function (SchemaEditor $schema): void {
    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_option')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('parent_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('required')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('position')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('type')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('option_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('parent_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('parent_id')
                    ->setUnquotedReferencedTableName('catalog_product_entity')
                    ->setUnquotedReferencedColumnNames('entity_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Option')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_option_value')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('value_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('store_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('title')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('value_id')->create())
            ->addIndex(Index::editor()->setType(IndexType::UNIQUE)->setUnquotedColumnNames('option_id', 'store_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('option_id')
                    ->setUnquotedReferencedTableName('catalog_product_bundle_option')
                    ->setUnquotedReferencedColumnNames('option_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Option Value')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_selection')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('parent_product_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('product_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('position')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_default')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_price_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_price_value')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setDefaultValue('0.0000')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_qty')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_can_change_qty')
                    ->setTypeName(Types::SMALLINT)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('selection_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('option_id'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('product_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('option_id')
                    ->setUnquotedReferencedTableName('catalog_product_bundle_option')
                    ->setUnquotedReferencedColumnNames('option_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('product_id')
                    ->setUnquotedReferencedTableName('catalog_product_entity')
                    ->setUnquotedReferencedColumnNames('entity_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Selection')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_selection_price')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_price_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_price_value')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setDefaultValue('0.0000')
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('selection_id', 'website_id')
                    ->create(),
            )
            ->addIndex(Index::editor()->setUnquotedColumnNames('website_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('website_id')
                    ->setUnquotedReferencedTableName('core_website')
                    ->setUnquotedReferencedColumnNames('website_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('selection_id')
                    ->setUnquotedReferencedTableName('catalog_product_bundle_selection')
                    ->setUnquotedReferencedColumnNames('selection_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Selection Price')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_price_index')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('min_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'website_id', 'customer_group_id')
                    ->create(),
            )
            ->addIndex(Index::editor()->setUnquotedColumnNames('website_id'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('customer_group_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('customer_group_id')
                    ->setUnquotedReferencedTableName('customer_group')
                    ->setUnquotedReferencedColumnNames('customer_group_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('entity_id')
                    ->setUnquotedReferencedTableName('catalog_product_entity')
                    ->setUnquotedReferencedColumnNames('entity_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('website_id')
                    ->setUnquotedReferencedTableName('core_website')
                    ->setUnquotedReferencedColumnNames('website_id')
                    ->setOnUpdateAction(ReferentialAction::CASCADE)
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Price Index')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_bundle_stock_index')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('stock_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('stock_status')
                    ->setTypeName(Types::SMALLINT)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'website_id', 'stock_id', 'option_id')
                    ->create(),
            )
            ->setComment('Catalog Product Bundle Stock Index')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_idx')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tax_class_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('special_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_percent')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('orig_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('min_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('base_tier')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('base_group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price_percent')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Idx')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_tmp')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tax_class_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('special_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_percent')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('orig_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('min_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('base_tier')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('base_group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price_percent')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Tmp')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_sel_idx')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_required')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id', 'option_id', 'selection_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Sel Idx')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_sel_tmp')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('selection_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_type')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_required')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id', 'option_id', 'selection_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Sel Tmp')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_opt_idx')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('min_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id', 'option_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Opt Idx')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('catalog_product_index_price_bundle_opt_tmp')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('entity_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('customer_group_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('website_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('option_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('min_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('max_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_tier_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('alt_group_price')
                    ->setTypeName(Types::DECIMAL)
                    ->setPrecision(12)
                    ->setScale(4)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('entity_id', 'customer_group_id', 'website_id', 'option_id')
                    ->create(),
            )
            ->setComment('Catalog Product Index Price Bundle Opt Tmp')
            ->create(),
    );
};
