<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Eav_Block_Widget_Form_Element_Multiline $this */
?>
<?php foreach ($this->getFields() as $field): ?>
<div class="field">
    <label for="<?= $field->getFieldId()?>" class="<?= $field->getLabelClass() ?>"><?= $field->getLabel() ?></label>
    <div class="input-box">
        <input type="text" id="<?= $field->getFieldId()?>" name="<?= $field->getFieldName()?>" value="<?= $this->escapeHtml($field->getValue())?>" title="<?= $this->quoteEscape($field->getLabel()) ?>" class="input-text <?= $field->getClass() ?>" <?= $this->getFieldParams() ?> />
    </div>
</div>
<?php endforeach ?>
