<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php foreach ($this->getFields() as $_field): ?>
<div class="field">
    <label for="<?= $_field->getFieldId()?>" class="<?= $_field->getLabelClass() ?>"><?= $_field->getLabel() ?></label>
    <div class="input-box">
        <input type="text" id="<?= $_field->getFieldId()?>" name="<?= $_field->getFieldName()?>" value="<?= $this->escapeHtml($_field->getValue())?>" title="<?= $this->quoteEscape($_field->getLabel()) ?>" class="input-text <?= $_field->getClass() ?>" <?= $this->getFieldParams() ?> />
    </div>
</div>
<?php endforeach ?>
