<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Eav_Block_Widget_Form_Element_Text $this */
?>
<label for="<?= $this->getFieldId() ?>" class="<?= $this->getLabelClass() ?>"><?= $this->getLabel() ?></label>
<div class="input-box">
    <input type="text" id="<?= $this->getFieldId() ?>" name="<?= $this->getFieldName()?>" value="<?= $this->escapeHtml($this->getValue()) ?>" title="<?= $this->quoteEscape($this->getLabel()) ?>" class="input-text <?= $this->getClass() ?>" <?= $this->getFieldParams() ?> />
</div>
