<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Sales_Order_Items_Renderer $this */
?>
<?php $parentItem = $this->getItem() ?>
<?php $_order = $this->getItem()->getOrder(); ?>

<?php $items = $this->getChilds($parentItem) ?>

<?php $_prevOptionId = '' ?>

<?php if($this->getItemOptions() || $parentItem->getDescription() || $this->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php foreach ($items as $_item): ?>
<?php if ($_item->getOrderItem()->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td class="bundle-item"><strong><em><?= $this->escapeHtml($attributes['option_label']) ?></em></strong></td>
        <td class="bundle-item">&nbsp;</td>
        <td class="bundle-item">&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif ?>
<?php endif ?>
<tr id="order-item-row-<?= $_item->getId() ?>">
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td class="bundle-item-parent product-info">
            <p class="product-name"><?= $this->escapeHtml($_item->getName()) ?></p>
            <p class="sku"><?= $this->__('SKU') ?>: <?= $this->escapeHtml($this->getSku()) ?></p>
        </td>
        <td class="bundle-item-parent align-center">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?= $_item->getQty()*1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif ?>
        </td>
        <td class="bundle-item-parent align-right">
    <?php else: ?>
        <td class="bundle-item bundle-details product-info"><div><?= $this->getValueHtml($_item) ?></div></td>
        <td class="bundle-item bundle-details align-center">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?= $_item->getQty()*1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif ?>
        </td>
        <td class="bundle-item align-right">
    <?php endif ?>
        <?php if ($this->canShowPriceInfo($_item)): ?>
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?= Mage::helper('tax')->__('Excl. Tax') ?>:</span>
            <?php endif ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'email', $_order->getStore())): ?>
                <?= $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()) ?>
            <?php else: ?>
                <?= $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></span><br />
                    <?php endforeach ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></small></span><br />
                    <?php endforeach ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></span><br />
                    <?php endforeach ?>
                    </small>
                <?php endif ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?= Mage::helper('weee')->__('Total') ?>:<br /> <?= $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()) ?></span>
                <?php endif ?>
            <?php endif ?>
        <?php endif ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?= Mage::helper('tax')->__('Incl. Tax') ?>:</span>
            <?php endif ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'email', $_order->getStore())): ?>
                    <?= $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?>
                <?php else: ?>
                    <?= $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span><br />
                    <?php endforeach ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></small></span><br />
                    <?php endforeach ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span><br />
                    <?php endforeach ?>
                    </small>
                <?php endif ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?= Mage::helper('weee')->__('Total incl. tax') ?>:<br /> <?= $_order->formatPrice($_incl +  Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?></span>
                <?php endif ?>
            <?php endif ?>
        <?php endif ?>
        <?php else: ?>
            &nbsp;
        <?php endif ?>
    </td>
</tr>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
<tr>
    <td align="left" valign="top" style="padding:3px 9px">
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?= $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?= $option['value'] ?></dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?= $this->escapeHtml($parentItem->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif ?>
