<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Logo
 * @deprecated
 */
?>
<div class="paypal-logo">
    <a href="#" title="<?= Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Additional Options')) ?>" onclick="javascript:window.open('<?= $this->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?= $this->escapeHtml($this->getLogoImageUrl()) ?>" alt="<?= Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Additional Options')) ?>" title="<?= Mage::helper('paypal')->__('Additional Options') ?>" /></a>
</div>
