<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @see Mage_Adminhtml_Block_Sales_Order_Create_Billing_Address $this */
/** @see Mage_Adminhtml_Block_Sales_Order_Create_Shipping_Address $this */
/** @var Mage_Adminhtml_Block_Sales_Order_Create_Form_Address $this */

$addressType = $this->getIsShipping() ? 'shipping' : 'billing';
$fieldsContainerId = "order-{$addressType}_address_fields";
$addressChoiceContainerId = "order-{$addressType}_address_choice";
?>
<script>
<?php if ($this->getIsShipping()): ?>
    order.shippingAddressContainer = '<?= $fieldsContainerId ?>';
    order.setAddresses(<?= $this->getAddressCollectionJson() ?>);
<?php else: ?>
    order.billingAddressContainer = '<?= $fieldsContainerId ?>';
<?php endif ?>
</script>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="fieldset-legend <?= $this->getHeaderCssClass() ?>"><?= $this->getHeaderText() ?></h4>
    </div>

    <fieldset class="fieldset-wide">
    <div id="<?= $addressChoiceContainerId ?>" class="order-choose-address">
        <?= Mage::helper('sales')->__('Select from existing customer addresses:') ?><br/>
        <?php $id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
        <select id="<?= $id ?>" name="<?= $this->getForm()->getHtmlNamePrefix() ?>[customer_address_id]">
            <option value=""><?= Mage::helper('sales')->__('Add New Address') ?></option>
        <?php foreach ($this->getAddressCollection() as $address): ?>
            <?php $selected = $address->getId() == $this->getAddressId() ? ' selected="selected"' : '' ?>
            <option value="<?= $address->getId() ?>"<?= $selected ?>>
                <?= $this->getAddressAsString($address) ?>
            </option>
        <?php endforeach ?>
        </select>

        <br/>
        <?php if ($this->getIsShipping()): ?>
            <input type="checkbox" id="order-shipping_as_billing" name="shipping_as_billing" value="1" onclick="order.setShippingAsBilling(this.checked)"<?= $this->getIsAsBilling() ? ' checked' : '' ?> />
            <label for="order-shipping_as_billing" class="no-float"><?= Mage::helper('sales')->__('Same As Billing Address') ?></label>
        <?php else: ?>
            &nbsp;
        <?php endif ?>
    </div>

    <div class="order-address" id="<?= $fieldsContainerId ?>">
        <div class="content">
            <?= $this->getForm()->toHtml() ?>
        </div>
        <div class="order-save-in-address-book">
            <input name="<?= $this->getForm()->getHtmlNamePrefix() ?>[save_in_address_book]" type="checkbox" id="<?= $this->getForm()->getHtmlIdPrefix() ?>save_in_address_book" value="1" <?php if (!$this->getDontSaveInAddressBook() && $this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif ?>/>
            <label for="<?= $this->getForm()->getHtmlIdPrefix() ?>save_in_address_book"><?= Mage::helper('sales')->__('Save in address book') ?></label>
        </div>
    </div>
    <div id="address-<?= $addressType ?>-overlay" class="overlay no-display">
        <?= $this->__('Shipping address selection is not applicable') ?>
    </div>
    <script>
        order.bindAddressFields('<?= $fieldsContainerId ?>');
        order.bindAddressFields('<?= $addressChoiceContainerId ?>');
        <?php if ($this->getIsShipping() && $this->getIsAsBilling()): ?>
        order.disableShippingAddress(true);
        <?php endif ?>
        document.getElementById('<?= $id ?>').addEventListener('change', (event) => {
            order.selectAddress(event.target, '<?= $fieldsContainerId ?>');
        });
    </script>
    </fieldset>
</div>
