<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Core_Block_Template $this */
?>
<script>
    window.validateOptionsCallback = (elmId, result) => {
        const container = document.getElementById(elmId).closest('ul.options-list');
        if (result === 'failed') {
            container.classList.remove('validation-passed');
            container.classList.add('validation-failed');
        } else {
            container.classList.remove('validation-failed');
            container.classList.add('validation-passed');
        }
    }

    productConfigure.opConfig ??= {};
    productConfigure.opConfig.dateOption = new Product.OptionsDate();
</script>
