<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Store_Switcher_Form_Renderer_Fieldset $this */
?>
<?php $_element = $this->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?= $_element->getFieldsetContainerId() ?>">
<?php endif ?>
<?php if ($_element->getLegend()): ?>
<div class="entry-edit-head">
    <h4><?= $_element->getLegend() ?></h4>
    <div class="form-buttons"><?= $_element->getHeaderBar() ?></div>
</div>
<?php endif ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="fieldset <?= $_element->getClass() ?>" id="<?= $_element->getHtmlId() ?>">
<?php endif ?>
<div class="store-scope">
    <div class="tree-store-scope">
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?= $this->escapeHtml($_element->getComment()) ?></p>
        <?php endif ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?= $_element->getHtmlContent() ?>
        <?php else: ?>
        <table cellspacing="0" class="<?= $_element->hasTableClass() ? $_element->getTableClass() : 'form-list' ?>">
            <tbody>
                <?= $_element->getChildrenHtml() ?>
            </tbody>
        </table>
        <?php endif ?>
    </div>
</div>
    <?= $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
    </div>
<?php endif ?>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif ?>
