<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
 ?>
<?php /** @var Mage_Adminhtml_Block_Customer_Edit_Tab_View_Grid_Renderer_Item $this */ ?>
<?php
    $product = $this->getProduct();
    $options = $this->getOptionList();
?>

<?php if (!$options): ?>
    <?= $this->escapeHtml($product->getName()) ?>
<?php else: ?>
<div class="bundle-product-options">
    <strong><?= $this->escapeHtml($product->getName()) ?></strong>
    <dl>
        <?php foreach ($options as $option) : ?>
            <dt><?= $this->escapeHtml($option['label']) ?></dt>
            <?php $formatedOptionValue = $this->getFormattedOptionValue($option) ?>
            <dd><?= $formatedOptionValue['value'] ?></dd>
        <?php endforeach ?>
    </dl>
</div>
<?php endif ?>
