<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Mustishipping state
 *
 * @see Mage_Checkout_Block_Multishipping_State
 * @var Mage_Checkout_Block_Multishipping_State $this
 */
?>
<ul class="checkout-progress" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?= $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif ?>><span><?= $_step->getLabel() ?></span></li>
<?php endforeach ?>
</ul>
