<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Multishipping_Success $this */
?>
<div class="multiple-checkout">
    <div class="page-title">
        <h1 data-role="page-title"><?= $this->__('Order Success') ?></h1>
    </div>
    <h2 class="sub-title"><?= $this->__('Thank you for your purchase!') ?></h2>
    <p><?= $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
    <?php if($_orderIds = $this->getOrderIds()): ?>
    <p data-role="order-numbers">
        <?php $flag = false ?>
        <?= $this->__('Your order number is ') ?>
        <?php foreach ($_orderIds as $orderId => $incrementId): ?>
            <?php if ($flag): ?>
                <?= ', ' ?>
            <?php endif ?>
            <?php $flag = true ?>
            <a href="<?= $this->getViewOrderUrl($orderId) ?>"><?= $incrementId ?></a>
        <?php endforeach ?>
    </p>
    <?php endif ?>
    <?= $this->getChildHtml() ?>
    <div class="buttons-set">
        <button type="button" title="<?= $this->quoteEscape($this->__('Continue Shopping')) ?>" class="button" onclick="setLocation('<?= $this->getContinueUrl() ?>')"><?= $this->__('Continue Shopping') ?></button>
    </div>
</div>
