<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_System_Email_Template_Edit $this */
?>
<div class="content-header">
    <h3><?= $this->getHeaderText() ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?php if ($this->getEditMode()): ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?php endif ?>
        <?php if (!$this->isTextType()): ?>
        <?= $this->getToPlainButtonHtml() ?>
        <?= $this->getToHtmlButtonHtml() ?>
        <?php endif ?>
        <?= $this->getPreviewButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php if (!$this->getEditMode()): ?>
<form action="<?= $this->getLoadUrl() ?>" method="post" id="email_template_load_form">
    <?= $this->getBlockHtml('formkey') ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4>
            <?= Mage::helper('adminhtml')->__('Load default template') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <table class="form-list" cellspacing="0">
                <tbody>
                    <tr>
                        <td class="label">
                            <label for="template_select">
                            <?= Mage::helper('adminhtml')->__('Template') ?>
                            <span class="required">*</span>
                            </label>
                        </td>
                        <td class="value">
                            <select id="template_select" name="code" class="select required-entry">
                                <?php foreach ($this->getTemplateOptions() as $_option): ?>
                                <option value="<?= $_option['value'] ?>"<?= $this->getOrigTemplateCode() == $_option['value'] ? ' selected="selected"' : '' ?>><?= $_option['label'] ?></option>
                                <?php endforeach ?>
                            </select>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="locale_select">
                            <?= Mage::helper('adminhtml')->__('Locale') ?>
                            <span class="required">*</span>
                            </label>
                        </td>
                        <td class="value">
                            <select id="locale_select" name="locale" class="select required-entry">
                                <?php foreach ($this->getLocaleOptions() as $_option): ?>
                                <option value="<?= $_option['value'] ?>"<?php if ($_option['value']==$this->getCurrentLocale()): ?> selected="selected"<?php endif ?>><?= $_option['label'] ?></option>
                                <?php endforeach ?>
                            </select>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label>&nbsp;</label>
                        </td>
                        <td class="value">
                            <?= $this->getLoadButtonHtml() ?>
                        </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</form>
<?php endif ?>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="email_template_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
    <fieldset>
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
        <input type="hidden" id="orig_template_code" name="orig_template_code" value="<?= $this->getOrigTemplateCode() ?>" />
        <?= $this->getFormHtml() ?>
    </fieldset>
</form>
<form action="<?= $this->getPreviewUrl() ?>" method="post" id="email_template_preview_form" target="_blank">
    <?= $this->getBlockHtml('formkey') ?>
    <div class="no-display">
        <input type="hidden" id="preview_type" name="type" value="<?= $this->isTextType()?1:2 ?>" />
        <input type="hidden" id="preview_text" name="text" value="" />
        <input type="hidden" id="preview_styles" name="styles" value="" />
    </div>
</form>
<script>
const templateControl = new EmailTemplateEditForm({
    forms: {
        edit: new varienForm('email_template_edit_form'),
        preview: new varienForm('email_template_preview_form'),
        load: new varienForm('email_template_load_form'),
    },
    urls: {
        delete: '<?= $this->getDeleteUrl() ?>',
    },
    elements: {
        templateText: 'template_text',
        templateStyles: 'template_styles',
        previewType: 'preview_type',
        previewText: 'preview_text',
        previewStyles: 'preview_styles',
    },
    paths: {
        used_default_for: <?= $this->getUsedDefaultForPaths() ?>,
        used_currently_for: <?= $this->getUsedCurrentlyForPaths() ?>,
    },
});
</script>
