<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Items $this */
?>

<?php if ($this->canDisplayGiftMessage()): ?>
    <div class="no-display">
        <div id="gift-message-form-data-<?= $this->getItem()->getId() ?>">
            <?= $this->getFormHtml() ?>
        </div>

        <?php if ($this->getMessageText()): ?>
        <div class="gift-options-tooltip-content">
            <div><strong><?= $this->helper('giftmessage')->__('Gift Message') ?></strong>:</div>
            <div><?= $this->getMessageText() ?></div>
        </div>
        <?php endif ?>
    </div>
<?php endif ?>
