<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Admin login form template
 *
 * @see Mage_Oauth_Block_Adminhtml_Oauth_Authorize
 * @var Mage_Oauth_Block_Adminhtml_Oauth_Authorize $this
 */

 ?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <?= $this->getMessagesBlock()->toHtml() ?>
            <?php if (!$this->getHasException()): ?>
                <form method="post" action="<?= $this->getPostActionUrl() ?>" id="loginForm">
                    <?= $this->getBlockHtml('formkey') ?>
                    <fieldset>
                        <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
                        <h2><?= $this->__('Log in to Admin Panel') ?></h2>
                        <p class="description"><?= $this->__('Log in to use <strong>%s</strong>', $this->getConsumer()->getName()) ?></p>
                        <div class="input-box input-left"><label for="username"><?= $this->__('User Name:') ?></label><br/>
                            <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
                        <div class="input-box input-right"><label for="login"><?= $this->__('Password:') ?></label><br />
                            <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                            <input type="password" class="input-text no-display" name="dummy" id="dummy" />
                            <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" autocomplete="new-password"/></div>
                        <div class="clear"></div>
                        <div class="form-buttons">
                            <button type="submit" class="form-button" title="<?= $this->quoteEscape($this->__('Login')) ?>" ><?= $this->__('Login') ?></button>
                            <button onclick="document.location.href='<?= $this->getRejectUrl() ?>'; return false;" title="<?= $this->quoteEscape($this->__('Reject')) ?>"><?= $this->__('Reject') ?></button>
                        </div>
                        <input type="hidden" name="oauth_token" value="<?= $this->escapeHtml($this->getToken()) ?>"/>
                    </fieldset>
                </form>
                <script type="text/javascript">
                //<![CDATA[
                     var loginForm = new varienForm('loginForm');
                //]]>
                </script>
            <?php endif ?>
        </div>
        <div class="bottom"></div>
    </div>
</div>
