<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_CatalogLinkRule
 */

declare(strict_types=1);

use Maho\Db\Ddl\Table;

/** @var Mage_Core_Model_Resource_Setup $this */
$installer = $this;
$installer->startSetup();

// Tag links generated by a rule so merge mode can refresh its own output while
// leaving manually assigned links untouched. NULL = manually assigned.
$installer->getConnection()->addColumn(
    $installer->getTable('catalog/product_link'),
    'rule_id',
    [
        'type'     => Table::TYPE_INTEGER,
        'unsigned' => true,
        'nullable' => true,
        'default'  => null,
        'comment'  => 'Catalog link rule that generated this link (NULL = manually assigned)',
    ],
);

// Index only, no foreign key: rule deletion is handled in Rule::_afterDelete() and the
// processor self-heals orphan rule links, so an FK with cascade would be redundant.
$installer->getConnection()->addIndex(
    $installer->getTable('catalog/product_link'),
    $installer->getIdxName('catalog/product_link', ['rule_id']),
    ['rule_id'],
);

$installer->endSetup();
