<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<script>
function toggleValueElement(element) {
    var disabled = false;
    if (element.value == 1) {
        // use default value
        disabled = true;
    }
    document.getElementById('plain_value').disabled = disabled;
    document.getElementById('html_value').disabled = disabled;
    if (disabled) {
        document.getElementById('plain_value').classList.add('disabled');
        document.getElementById('html_value').classList.add('disabled');
    } else {
        document.getElementById('plain_value').classList.remove('disabled');
        document.getElementById('html_value').classList.remove('disabled');
    }
}
</script>
