<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Payment_Block_Info_Checkmo $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getPayableTo()): ?>
        <?= Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <?= Mage::helper('payment')->__('Send Check to:') ?>
        {{pdf_row_separator}}
        <?= nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
<?php endif ?>
