<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Payment_Block_Info $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<?php foreach ($_specificInfo as $_label => $_value):?>
<?= $_label ?>: <?= implode(' ', $this->getValueAsArray($_value)) ?>{{pdf_row_separator}}
<?php endforeach ?>
<?php endif ?>

<?= implode('{{pdf_row_separator}}', $this->getChildPdfAsArray()) ?>
