<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Account_Dashboard $this */
?>
<div class="dashboard">
    <div class="page-title">
        <h1><?= $this->__('My Dashboard') ?></h1>
    </div>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?= $this->getChildHtml('hello') ?>
    <?= $this->getChildHtml('top') ?>
    <?= $this->getChildHtml('missing_orders_after_recent') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?= $this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?= $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?= $this->getChildHtml('info') ?>
    </div>
    <?= $this->getChildHtml('address') ?>
    <?= $this->getChildHtml('info1') ?>
    <?= $this->getChildHtml('info2') ?>
</div>
