<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Account_Dashboard $this */
?>
<div class="dashboard">
    <div class="page-title">
        <h1><?= $this->__('My Dashboard') ?></h1>
    </div>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?= $this->getChildHtml('hello') ?>
    <?= $this->getChildHtml('top') ?>
    <?= $this->getChildHtml('missing_orders_after_recent') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?= $this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?= $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?= $this->getChildHtml('info') ?>
    </div>
    <?= $this->getChildHtml('address') ?>
    <?= $this->getChildHtml('info1') ?>
    <?= $this->getChildHtml('info2') ?>
</div>
