<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Customer_Block_Account_Navigation $this */
?>
<div class="block block-account">
    <button class="block-title offcanvas-trigger" data-offcanvas-target="ul.nav-account" data-offcanvas-title="<?= $this->__('My Account') ?>">
        <?= $this->__('My Account') ?>
    </button>
    <div class="block-content">
        <ul class="nav-account">
            <?php $links = $this->getLinks(); ?>
            <?php foreach ($links as $link): ?>
                <li <?= $this->isActive($link) ? 'class="current level0"' : 'class="level0"' ?>>
                    <a href="<?= $link->getUrl() ?>" class="level0"><?= $link->getLabel() ?></a>
                </li>
            <?php endforeach ?>
            <li class="level0">
                <a href="<?= Mage::helper('customer')->getLogoutUrl() ?>" class="level0"><?= $this->__('Logout') ?></a>
            </li>
        </ul>
    </div>
</div>
