<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Customer_Block_Account_Navigation $this */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><label for="sidebar-toggle" class="sidebar-trigger-label"><span><?= $this->__('My Account') ?></span></label></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $links = $this->getLinks(); ?>
            <?php foreach ($links as $link): ?>
                <li <?= $this->isActive($link) ? 'class="current"' : '' ?>>
                    <a href="<?= $link->getUrl() ?>"><?= $link->getLabel() ?></a>
                </li>
            <?php endforeach ?>
            <li>
                <a href="<?= Mage::helper('customer')->getLogoutUrl() ?>"><?= $this->__('Logout') ?></a>
            </li>
        </ul>
    </div>
</div>
