<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Newsletter_Template_Edit $this */
?>
<div class="content-header">
    <h3><?= $this->getHeaderText() ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?php if (!$this->isTextType()): ?>
        <?= $this->getToPlainButtonHtml() ?>
        <?= $this->getToHtmlButtonHtml() ?>
        <?php endif ?>
        <?= $this->getPreviewButtonHtml() ?>
        <?php if ($this->getEditMode()): ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?php endif ?>
        <?php if ($this->getEditMode()): ?>
        <?= $this->getSaveAsButtonHtml() ?>
        <?php endif ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="newsletter_template_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
        <input type="hidden" id="save_as_flag" name="_save_as_flag" value="<?= $this->getSaveAsFlag() ?>" />
    </div>
    <?= $this->getForm() ?>
</form>
<form action="<?= $this->getPreviewUrl() ?>" method="post" id="newsletter_template_preview_form" target="_blank">
    <?= $this->getBlockHtml('formkey') ?>
    <div class="no-display">
        <input type="hidden" id="preview_type" name="type" value="<?= $this->isTextType()?1:2 ?>" />
        <input type="hidden" id="preview_text" name="text" value="" />
        <input type="hidden" id="preview_styles" name="styles" value="" />
        <input type="hidden" id="preview_id" name="id" value="" />
    </div>
</form>
<script>
const templateControl = new EmailTemplateEditForm({
    templateName: "<?= $this->getJsTemplateName() ?>",
    forms: {
        edit: new varienForm('newsletter_template_edit_form'),
        preview: new varienForm('newsletter_template_preview_form'),
    },
    urls: {
        delete: '<?= $this->getDeleteUrl() ?>',
    },
    elements: {
        templateId: 'id',
        templateName: 'code',
        templateText: 'text',
        templateStyles: 'template_styles',
        previewId: 'preview_id',
        previewType: 'preview_type',
        previewText: 'preview_text',
        previewStyles: 'preview_styles',
    },
});
</script>
