<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Newsletter_Template $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?= $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <button class="scalable add" onclick="window.location='<?= $this->getCreateUrl() ?>'"><span><?= Mage::helper('newsletter')->__('Add New Template') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
