<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Newsletter_Template $this */
?>
<div class="content-header">
    <h3><?= $this->getHeaderText() ?></h3>
    <p class="content-buttons form-buttons">
        <button class="scalable add" onclick="window.location='<?= $this->getCreateUrl() ?>'"><span><?= Mage::helper('newsletter')->__('Add New Template') ?></span></button>
    </p>
</div>
<div>
    <?= $this->getChildHtml('grid') ?>
</div>
