<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): ?>
            <a href="<?= $this->escapeUrl($_item->getUrl()) ?>">
                <?= $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                <span class="count">(<?= $_item->getCount() ?>)</span>
                <?php endif ?>
            </a>
        <?php else: ?>
            <span>
                <?= $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?= $_item->getCount() ?>)</span>
                <?php endif ?>
            </span>
        <?php endif ?>
    </li>
<?php endforeach ?>
</ol>
