<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php /** @var Mage_ProductAlert_Block_Product_View $this */?>
<p class="<?= $this->getHtmlClass() ?>">
    <a href="<?= $this->escapeHtml($this->getSignupUrl()) ?>" title="<?= $this->escapeHtml($this->__($this->getSignupLabel())) ?>"><?= $this->escapeHtml($this->__($this->getSignupLabel())) ?></a>
</p>
