<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_ProductAlert_Block_Product_View */?>
<p class="<?= $this->getHtmlClass() ?>">
    <a href="<?= $this->escapeHtml($this->getSignupUrl()) ?>" title="<?= $this->escapeHtml($this->__($this->getSignupLabel())) ?>"><?= $this->escapeHtml($this->__($this->getSignupLabel())) ?></a>
</p>
