<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Reports_Block_Product_Compared $this */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block block-list block-compared">
    <div class="block-title">
        <strong><span><?= $this->__('Recently Compared Products') ?></span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a href="<?= $this->getProductUrl($_item) ?>"><?= $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>
