<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Totals_Tax $this */

$uniqId = uniqid();
$displayFullSummary = $this->helper('tax')->displayFullSummary();
?>

<?php if ($displayFullSummary): ?>
<tr class="<?= $this->getTotal()->getCode() ?> summary-total" onclick="expandDetails(this, '.summary-details-<?= $uniqId ?>')">
<?php else: ?>
<tr class="<?= $this->getTotal()->getCode() ?>">
<?php endif ?>
    <td style="<?= $this->getTotal()->getStyle() ?>" colspan="<?= $this->getColspan() ?>">
    <?php if ($displayFullSummary): ?>
        <div class="summary-collapse"><?= $this->getTotal()->getTitle() ?></div>
    <?php else: ?>
        <?= $this->getTotal()->getTitle() ?>
    <?php endif ?>
    </td>
    <td style="<?= $this->getTotal()->getStyle() ?>">
        <?= $this->formatPrice($this->getTotal()->getValue()) ?>
    </td>
</tr>

<?php if ($displayFullSummary): ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if ($info['hidden'] ?? false) continue ?>
        <?php foreach (array_values($info['rates']) as $i => $rate): ?>
        <tr class="summary-details-<?= $uniqId ?> summary-details no-display">
            <td style="<?= $this->getTotal()->getStyle() ?>" colspan="<?= $this->getColspan() ?>">
                <?= $this->escapeHtml($rate['title']) ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?= (float) $rate['percent'] ?>%)
                <?php endif ?>
            </td>
            <?php if ($i === 0): ?>
            <td style="<?= $this->getTotal()->getStyle() ?>" rowspan="<?= count($info['rates']) ?>">
                <?= $this->formatPrice($info['amount']) ?>
            </td>
            <?php endif ?>
        </tr>
        <?php endforeach ?>
    <?php endforeach ?>
    <?php foreach ($this->helper('tax')->getAllWeee($this->getQuote()) as $weeeTitle => $weeeAmount): ?>
        <tr class="summary-details-<?= $uniqId ?> summary-details no-display">
            <td>
                <?= $this->escapeHtml($weeeTitle) ?>
            </td>
            <td>
                <?= $this->helper('checkout')->formatPrice($weeeAmount) ?>
            </td>
        </tr>
    <?php endforeach ?>
<?php endif ?>
