<?php
/**
 * Maho
 *
 * @package    Maho_ApiPlatform
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Maho_ApiPlatform_Block_Adminhtml_Apiplatform_Role_Edit_Tab_Permissions $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('Resource Permissions') ?></h4>
    </div>
    <input type="hidden" name="permissions_tree" id="role_permissions" value="" />
    <fieldset id="permissions_fieldset">
        <span class="field-row">
            <label for="permissions_all"><?= $this->__('Resource Access') ?></label>
            <select id="permissions_all" name="permissions_access" class="select">
                <option value="0"><?= $this->__('Custom') ?></option>
                <option value="1"><?= $this->__('All') ?></option>
            </select>
        </span>
        <span class="field-row" id="permissions_container">
            <label><?= $this->__('Resources') ?></label>
            <div class="inline-block">
                <div id="permissions-tree" class="hor-scroll"></div>
            </div>
        </span>
    </fieldset>
</div>

<script type="module">
    const permissionsValueEl = document.getElementById('role_permissions');
    const accessSelectEl = document.querySelector('#permissions_fieldset select[name=permissions_access]');
    const containerEl = document.getElementById('permissions_container');

    const tree = new MahoTree('permissions-tree', {
        showRootNode: false,
        selectable: {
            mode: 'nested',
            onSelect: updateValue,
        },
    });
    tree.setRootNode(<?= $this->getResTreeJson() ?>);
    tree.expandAll();

    function updateValue() {
        if (accessSelectEl.value === '1') {
            permissionsValueEl.value = 'all';
        } else {
            permissionsValueEl.value = tree.getChecked().map((obj) => obj.id).join(',');
        }
    }

    accessSelectEl.addEventListener('change', (event) => {
        containerEl.classList.toggle('no-display', event.target.value === '1');
        updateValue();
    });
    accessSelectEl.value = '<?= (int)$this->getEverythingAllowed() ?>';
    accessSelectEl.dispatchEvent(new Event('change'));
</script>
