<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Action_Attribute_Tab_Attributes $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('catalog')->__('Update attributes') ?></h3>
    <div class="form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getCancelButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </div>
</div>
<form action="<?= $this->getSaveUrl() ?>" method="post" id="attributes_edit_form" enctype="multipart/form-data">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
var attributesForm = new varienForm('attributes_edit_form', '<?= $this->getValidationUrl() ?>');
attributesForm._processValidationResult = function(transport) {
    var response = transport.responseText.evalJSON();

    if (response.error){
        if (response.attribute && $(response.attribute)) {
            $(response.attribute).setHasError(true, attributesForm);
            Validation.ajaxError($(response.attribute), response.message);
            $(response.attribute).focus();
        } else if ($('messages')) {
            $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
        }
    } else {
        attributesForm._submit();
    }
};
</script>
