<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Checkboxes_Tree $this */
?>

<?php $divId = 'tree-div_' . uniqid() ?>
<div id="<?= $divId ?>" class="hor-scroll"></div>

<script type="module">
    const tree = new MahoTree('<?= $divId ?>', {
        showRootNode: false,
        lazyload: {
            nodeParameter: 'id',
            dataUrl: '<?= $this->getLoadTreeUrl() ?>',
        },
        selectable: {
            mode: 'simple',
            onSelect: (selected) => {
                const formJsObject = <?= $this->getJsFormObject() ?>;
                formJsObject.updateElement.value = selected.map((obj) => obj.id).join(',');
            },
        },
    });
    tree.setRootNode(<?= $this->getTreeJson() ?>);
</script>
