<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Sales_Order_Items_Renderer $this */
?>
<?php $parentItem = $this->getItem() ?>
<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $this->getChilds($parentItem) ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if($this->getItemOptions() || $parentItem->getDescription() || $this->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php foreach ($items as $_item): ?>

<?php if ($_item->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td><div class="option-label"><?= $this->escapeHtml($attributes['option_label']) ?></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif ?>
<?php endif ?>
<tr<?= (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?> id="order-item-row-<?= $_item->getId() ?>">
    <?php if (!$_item->getParentItem()): ?>
    <td><h4 class="product-name"><?= $this->escapeHtml($_item->getName()) ?></h4></td>
    <?php else: ?>
    <td><div class="option-value"><?= $this->getValueHtml($_item) ?></div></td>
    <?php endif ?>
    <td><?= $this->escapeHtml($_item->getSku()) ?></td>
    <td class="a-center">
        <?php if (($this->isShipmentSeparately() && $_item->getParentItem()) || (!$this->isShipmentSeparately() && !$_item->getParentItem())): ?>
            <?php if (isset($shipItems[$_item->getId()])): ?>
                <?= $shipItems[$_item->getId()]->getQty()*1 ?>
            <?php elseif ($_item->getIsVirtual()): ?>
                <?= $this->__('N/A') ?>
            <?php else: ?>
                0
            <?php endif ?>
        <?php else: ?>
        &nbsp;
        <?php endif ?>
    </td>
</tr>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
<tr class="border">
    <td>
        <?php if($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?= $this->escapeHtml($_option['label']) ?></dt>
            <?php if (!$this->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>>
                    <?= $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value">
                        <dl class="item-options">
                            <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                            <dd><?= $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif ?>
                </dd>
            <?php else: ?>
                <dd><?= $this->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) ) ?></dd>
            <?php endif ?>
        <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?= $this->escapeHtml($parentItem->getDescription()) ?>
        <?php if($this->canDisplayGiftmessage()): ?>
            <a href="#" id="order-item-gift-message-link-<?= $parentItem->getId() ?>" class="gift-message-link" onclick="return giftMessageToogle('<?= $parentItem->getId() ?>')"><?= Mage::helper('sales')->__('Gift Message') ?></a>
        <?php endif ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif ?>
