<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Review_Block_Customer_Recent $this */
?>
<?php if( $this->getCollection() && $this->count()): ?>
<div class="box-account box-reviews">
    <div class="box-head">
        <h2><?= $this->__('My Recent Reviews') ?></h2>
        <a href="<?= $this->getAllReviewsUrl() ?>"><?= $this->__('View All Reviews') ?></a>
    </div>
    <ol id="my_recent_reviews">
    <?php $iterator = 0 ?>
    <?php foreach ($this->getCollection() as $_review): ?>
        <li class="item">
            <span class="number"><?= ++$iterator ?></span>
            <div class="details">
                <h3 class="product-name"><a href="<?= $this->getReviewUrl($_review->getReviewId()) ?>"><?= $this->escapeHtml($_review->getName()) ?></a></h3>
                <?php if($_review->getSum()): ?>
                    <div class="ratings">
                        <strong><?= $this->__('Rating:') ?></strong>
                        <div class="rating-box">
                            <div class="rating" style="width:<?= ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
</div>
<?php endif ?>
