<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Downloadable_Block_Catalog_Product_Links $this */

$linksPurchasedSeparately = $this->getLinksPurchasedSeparately();
?>
<?php if ($this->getProduct()->isSaleable() && $this->hasLinks()): ?>
<?php $links = $this->getLinks() ?>
<?php $isRequired = $this->getLinkSelectionRequired() ?>
<?php $requiredIds = []; ?>
<dl>
    <dt>
        <label<?= $isRequired ? ' class="required"' : '' ?>><?= $this->escapeHtml($this->getLinksTitle()) ?></label>
    </dt>
    <dd>
        <ul id="downloadable-links-list" class="options-list">
        <?php foreach ($links as $link): ?>
            <?php if ($isRequired) $requiredIds[] = $link->getId() ?>
            <li>
                <?php if ($linksPurchasedSeparately): ?>
                <input type="checkbox" class="checkbox<?= $isRequired ? ' validate-one-required-by-name' : '' ?> product-downloadable-link" onclick="dConfig.reloadPrice()" name="links[]" id="links_<?= $link->getId() ?>" value="<?= $link->getId() ?>" <?= $this->getLinkCheckedValue($link) ?>>
                <?php endif ?>
                <span class="label">
                    <label for="links_<?= $link->getId() ?>">
                        <?= $this->escapeHtml($link->getTitle()) ?>
                    </label>
                    <?php if ($this->getLinkHasSample($link)): ?>
                        <?php $onclick = $this->getIsOpenInNewWindow() ? ' onclick="this.target=\'_blank\'"' : '' ?>
                        (<a href="<?= $this->getLinkSamlpeUrl($link) ?>"<?= $onclick ?>><?= Mage::helper('downloadable')->__('sample') ?></a>)
                    <?php endif ?>
                    <?php if ($linksPurchasedSeparately): ?>
                        <?= $this->getFormattedLinkPrice($link) ?>
                    <?php endif ?>
                </span>
            </li>
        <?php endforeach ?>
        </ul>

        <?php if ($isRequired): ?>
            <span id="links-advice-container"></span>
        <?php endif ?>
    </dd>
</dl>

<script type="module">
<?php if (count($requiredIds)): ?>
    const requiredIds = <?= json_encode($requiredIds) ?>;
    for (const linkId of requiredIds) {
        for (const inputEl of document.querySelectorAll(`input[id="links_${linkId}"]`)) {
            inputEl.adviceContainer = inputEl.closest('dd').querySelector('.links-advice-container');
            inputEl.callbackFunction = 'validateDownloadableCallback';
        }
    }
    window.validateDownloadableCallback = (elmId, result) => {
        const container = document.getElementById('downloadable-links-list');
        if (result === 'failed') {
            container.classList.remove('validation-passed');
            container.classList.add('validation-failed');
        } else {
            container.classList.remove('validation-failed');
            container.classList.add('validation-passed');
        }
    }
<?php endif ?>

    window.dConfig = new Product.Downloadable(<?= $this->getJsonConfig() ?>);
</script>
<?php endif ?>
