<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */


/**
 * Downloadable product links
 *
 * @see Mage_Downloadable_Block_Catalog_Product_Samples
 * @var Mage_Downloadable_Block_Catalog_Product_Samples $this
 */
?>

<?php if ($this->hasSamples()): ?>
    <dl class="item-options">
        <dt><?= $this->getSamplesTitle() ?></dt>
        <?php $_samples = $this->getSamples() ?>
        <?php foreach ($_samples as $_sample): ?>
            <dd>
                <a href="<?= $this->getSampleUrl($_sample) ?>" <?= $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':'' ?>><?= $this->escapeHtml($_sample->getTitle()) ?></a>
            </dd>
        <?php endforeach ?>
    </dl>
<?php endif ?>
