<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Downloadable product type
 *
 * @see Mage_Downloadable_Block_Catalog_Product_View_Type
 * @var Mage_Downloadable_Block_Catalog_Product_View_Type $this
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
    <p class="availability in-stock"><?= $this->__('Availability:') ?> <span><?= $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?= $this->__('Availability:') ?> <span><?= $this->__('Out of stock') ?></span></p>
<?php endif ?>
<?= $this->getChildHtml('product_type_data_extra') ?>
<?= $this->getPriceHtml($_product) ?>
<?= $this->getChildHtml('samples') ?>
