<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Downloadable_Block_Catalog_Product_View_Type $this */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
    <p class="availability in-stock">
        <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
        <span class="value"><?= $this->helper('catalog')->__('In stock') ?></span>
    </p>
<?php else: ?>
    <p class="availability out-of-stock">
        <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
        <span class="value"><?= $this->helper('catalog')->__('Out of stock') ?></span>
    </p>
<?php endif ?>
<?= $this->getChildHtml('product_type_data_extra') ?>
<?php //echo $this->getPriceHtml($_product) ?>
<?php //echo $this->getChildHtml('samples') ?>
