<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Catalog_Product_View_Type $this */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
    <p class="availability in-stock">
        <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
        <span class="value"><?= $this->helper('catalog')->__('In stock') ?></span>
    </p>
<?php else: ?>
    <p class="availability out-of-stock">
        <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
        <span class="value"><?= $this->helper('catalog')->__('Out of stock') ?></span>
    </p>
<?php endif ?>
<?= $this->getChildHtml('product_type_data_extra') ?>
<?php //echo $this->getPriceHtml($_product) ?>
<?php //echo $this->getChildHtml('samples') ?>
