<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_View_Tab_History $this */
?>
<div class="entry-edit">
    <fieldset>
        <ul class="note-list">
        <?php foreach ($this->getFullHistory() as $_item): ?>
            <li>
                <div class="note-header">
                    <span>
                        <strong><?= $this->getItemCreatedAt($_item) ?></strong>
                        <?= $this->getItemCreatedAt($_item, 'time') ?>
                    </span>
                    <?php if ($this->getItemTitle($_item)): ?>
                    <strong><?= $this->getItemTitle($_item) ?></strong>
                    <?php endif ?>
                    <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                    <span class="icon" title="<?= $this->helper('sales')->__('Customer Notification Not Applicable') ?>"><?= $this->getIconSvg('message-question') ?></span>
                    <?php elseif ($this->isItemNotified($_item)): ?>
                    <span class="icon" title="<?= $this->helper('sales')->__('Customer Notified') ?>"><?= $this->getIconSvg('message') ?></span>
                    <?php else: ?>
                    <span class="icon" title="<?= $this->helper('sales')->__('Customer Not Notified') ?>"><?= $this->getIconSvg('message-off') ?></span>
                    <?php endif ?>
                </div>
                <?php if ($_comment = $this->getItemComment($_item)): ?>
                    <div><?= $_comment ?></div>
                <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
    </fieldset>
</div>
