<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Reports_Block_Product_Viewed $this */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="widget widget-viewed">
    <div class="block block-products">
        <div class="block-title">
            <strong><span><?= $this->__('Recently Viewed') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list" id="widget-viewed-<?= $suffix ?>">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(50) ?>" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(100) ?> 2x" width="50" height="50" alt="<?= $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                    </div>
                </li>
            <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif ?>
