<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Template_Container $this */
?>
<div class="page-sitemap">
    <div class="page-title">
        <h1><?= $this->getTitle() ?></h1>
    </div>
    <div id="sitemap_top_links">
        <?= $this->getChildHtml('links') ?>
    </div>
    <?= $this->getChildHtml('pager_top') ?>
    <?= $this->getChildHtml('sitemap') ?>
    <?= $this->getChildHtml('links') ?>
    <?= $this->getChildHtml('pager_bottom') ?>
</div>
