<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Template_Container $this */
?>
<div class="page-sitemap">
    <div class="page-title">
        <h1><?= $this->getTitle() ?></h1>
    </div>
    <div id="sitemap_top_links">
        <?= $this->getChildHtml('links') ?>
    </div>
    <?= $this->getChildHtml('pager_top') ?>
    <?= $this->getChildHtml('sitemap') ?>
    <?= $this->getChildHtml('links') ?>
    <?= $this->getChildHtml('pager_bottom') ?>
</div>
