<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Cart_Item_Configure $this */
?>

<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if (!$_product->isGrouped()): ?>
        <div class="qty-wrapper">
            <label for="qty"><?= $this->__('Qty:') ?></label>
            <input type="text" pattern="\d*(\.\d+)?" name="qty" id="qty" maxlength="12" value="<?= $this->getProductDefaultQty() * 1 ?>" title="<?= $this->quoteEscape($this->__('Qty')) ?>" class="input-text qty" aria-required="true" />
        </div>
        <?php endif ?>
        <div class="add-to-cart-buttons">
            <button type="button" title="<?= $this->quoteEscape($buttonTitle) ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><?= $buttonTitle ?></button>
            <?= $this->getChildHtml('', true, true) ?>
        </div>
    </div>
<?php endif ?>
