<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?= nl2br($this->escapeHtml($this->getObjectData($row, 'value'))) ?></address>
<?php endforeach ?>

<?php else: ?>

<table class="info-table">
    <tbody>
        <?php foreach ($this->getRenderedInfo() as $row):?>
        <?php $isAmount = $this->getObjectData($row, 'is_amount');?>
        <tr>
            <th><?= $this->escapeHtml($this->getObjectData($row, 'label')) ?>:</th>
            <td><?= $this->renderRowValue($row) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
