<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
//<![CDATA[
function setSettings(urlTemplate, typeElement, packageThemeElement) {
    if (editForm.validator && editForm.validator.validate()) {
        typeElement = $F(typeElement).replace(/\//g, '-');
        packageThemeElement = $F(packageThemeElement).split(/\//g);

        setLocation(new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/).evaluate({
            'type': typeElement,
            'package': packageThemeElement[0],
            'theme': packageThemeElement[1]
        }));
    } else {
        return false;
    }
}

function saveAndContinueEdit() {
    editForm.submit($('edit_form').action + 'back/edit/');
}
//]]>
</script>
