<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getInstructions()): ?>
<table>
    <tbody>
        <tr>
            <td><?= nl2br($this->getInstructions()) ?></td>
        </tr>
    </tbody>
</table>
<?php endif ?>
