<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Payment_Block_Info_Checkmo $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?><br><?= Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?><?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <label><?= Mage::helper('payment')->__('Send Check to:') ?></label>
        <div class="checkmo-mailing-address">
            <?= nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        </div>
    <?php endif ?>
<?php endif ?>
