<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2019-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Info $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?= $this->escapeHtml($_label) ?>:</td>
        <td><?= nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></td>
    </tr>
<?php endforeach ?>
</table>
<?php endif ?>

<?= $this->getChildHtml() ?>
