<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Form_Purchaseorder $this */
?>
<p><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<p><?= Mage::helper('payment')->__('Purchase Order Number: %s', $this->escapeHtml($this->getInfo()->getPoNumber())) ?></p>
