<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Uploader_Block_Multiple|Mage_Uploader_Block_Single $this */
?>
<div id="<?= $this->getHtmlId() ?>" class="uploader">
    <div class="buttons a-right">
        <?= $this->getBrowseButtonHtml() ?>
        <?= $this->getUploadButtonHtml() ?>
    </div>
</div>
<div class="no-display" id="<?= $this->getElementId('template') ?>">
    <div id="{{id}}-container" class="file-row">
        <span class="file-info">{{name}} {{size}}</span>
        <span class="delete-button"><?= $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
    </div>
</div>
<script type="module">
    const uploader = new Uploader(<?= $this->getJsonConfig() ?>);
    varienGlobalEvents?.attachEventHandler('tabChangeBefore', uploader.onContainerHideBefore);
</script>
<?= $this->getChildHtml('additional_scripts') ?>
