<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Attribute options control
 *
 * @var Mage_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract $this
 */
?>
<?php $entityTypeCode = Mage::registry('entity_type')->getEntityTypeCode() ?>
<?php $disabledAttr = $this->getReadOnly() ? 'disabled' : '' ?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?= $this->__('If you do not specify an option value for a specific store view then the default (Admin) value will be used.') ?></li>
        </ul>
    </li>
</ul>

<div class="entity-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('Manage Titles (Size, Color, etc.)') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0" id="attribute-labels-table">
                <tr>
                <?php foreach ($this->getStores() as $store): ?>
                    <th><?= $this->escapeHtml($store->getName()) ?></th>
                <?php endforeach ?>
                </tr>
                <tr>
                    <?php $labels = $this->getLabelValues() ?>
                    <?php foreach ($this->getStores() as $store): ?>
                    <td>
                        <input class="input-text<?php if($store->getId()==0): ?> required-entry<?php endif ?>" type="text" name="frontend_label[<?= $store->getId() ?>]" value="<?= $this->escapeHtml($labels[$store->getId()]) ?>" <?= $disabledAttr ?>/>
                    </td>
                    <?php endforeach ?>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="entity-edit" id="manage-options-panel">
    <div class="entry-edit-head">
        <h4><?= $this->__('Manage Options (values of your attribute)') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0" cellpadding="0" id="attribute-options-table">
                <tr>
                <?php if ($this->isConfigurableSwatchesEnabled()): ?>
                    <th><?= $this->escapeHtml($this->__('Swatch')) ?></th>
                <?php endif ?>
                <?php foreach ($this->getStores() as $store): ?>
                    <th><?= $this->escapeHtml($store->getName()) ?></th>
                <?php endforeach ?>
                    <th><?= $this->__('Position') ?></th>
                    <th class="nobr a-center"><?= $this->escapeHtml($this->__('Is Default')) ?></th>
                    <th>
                        <?php if (!$this->getReadOnly()):?>
                            <?= $this->getAddNewButtonHtml() ?>
                        <?php endif ?>
                    </th>
                </tr>
            </table>
        </div>
        <input type="hidden" id="option-count-check" value="" />
    </div>
</div>

<template id="row-template">
    <tr class="option-row" title="Option ID: {{id}}">
        <?php if ($this->isConfigurableSwatchesEnabled()): ?>
        <td class="swatch-option {{swatch_class}}">
            <input type="hidden" name="option[swatch][{{id}}]" class="swatch-value" disabled />
            <input type="color" class="input-color-html5 validate-hex-color-hash" />
            <button title="Delete Swatch" type="button" class="swatch-delete">X</button>
        </td>
        <?php endif ?>
        <?php foreach ($this->getStores() as $store): ?>
        <td><input type="text" name="option[value][{{id}}][<?= $store->getId() ?>]" value="{{store<?= $store->getId() ?>}}" class="input-text <?= $store->getId() == 0 ? 'required-entry' : '' ?>" <?= $disabledAttr ?>/></td>
        <?php endforeach ?>
        <td><input type="text" name="option[order][{{id}}]" value="{{sort_order}}" class="input-text" <?= $disabledAttr ?>/></td>
        <td class="a-center"><input type="{{intype}}" name="default[]" value="{{id}}" class="input-radio" {{checked}} <?= $disabledAttr ?>/></td>
        <td class="a-left">
            <input type="hidden" name="option[delete][{{id}}]" value="" class="delete-flag" />
            <?php if (!$this->getReadOnly()):?>
                <?= $this->getDeleteButtonHtml() ?>
            <?php endif ?>
        </td>
    </tr>
</template>

<script>
Validation.add('required-options-count', '<?= $this->jsQuoteEscape($this->__('Options is required')) ?>', (v) => !Validation.get('IsEmpty').test(v));

document.addEventListener('DOMContentLoaded', () => {
    const template = document.getElementById('row-template').innerHTML;
    const inputTypeOptionsInfo = <?= Mage::helper('core')->jsonEncode(Mage::helper('eav')->getInputTypeOptionsPanelInfo($entityTypeCode)) ?>;
    const optionsForm = new EavAttributeOptionsForm('manage-options-panel', inputTypeOptionsInfo, template);
    optionsForm.addMany(<?= Mage::helper('core')->jsonEncode($this->getOptionValues()) ?>);
});
</script>
