<?php
/**
 * Maho
 *
 * @package    Maho_Paypal
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<div id="admin_paypal_vault_form">
    <p><?= $this->escapeHtml($this->__('Vault payment will use the customer\'s saved payment methods.')) ?></p>
</div>
