<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="entry-edit" id="export_filter_container" style="display:none;">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?= $this->__('Entity Attributes') ?></h4>
    </div>
    <form id="export_filter_form" action="<?= $this->getUrl('*/*/export') ?>" method="post">
        <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
        <div id="export_filter_grid_container" class="fieldset"><!-- --></div>
    </form>
    <div class="a-right">
        <button class="scalable" type="button" onclick="getFile();"><span><span><span><?= $this->__('Continue') ?></span></span></span></button>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
   $('entity').selectedIndex = 0; // forced resetting entity selector after page refresh
//]]>
</script>
