<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<div class="entry-edit" id="export_filter_container" style="display:none;">
    <div class="entry-edit-head">
        <h4><?= $this->__('Entity Attributes') ?></h4>
    </div>
    <form id="export_filter_form" action="<?= $this->getUrl('*/*/export') ?>" method="post">
        <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>">
        <div id="export_filter_grid_container" class="fieldset"><!-- --></div>
    </form>
    <div class="a-right">
        <button class="scalable" type="button" onclick="getFile();"><span><?= $this->__('Continue') ?></span></button>
    </div>
</div>
<script>
   document.getElementById('entity').selectedIndex = 0; // forced resetting entity selector after page refresh
</script>
