<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Checkout_Cart_Item_Renderer $this */
?>
<h3 class="product-name"><a href="<?= $this->getProductUrl() ?>"><?= $this->escapeHtml($this->getProductName()) ?></a></h3>
<!-- item custom options -->
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
    <dt><?= $this->escapeHtml($_option['label']) ?></dt>
    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?= $_formatedOptionValue['value'] ?>
        <?php if (isset($_formatedOptionValue['full_view'])): ?>
        <div class="truncated_full_value">
            <dl class="item-options">
                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                <dd><?= $_formatedOptionValue['full_view'] ?></dd>
            </dl>
        </div>
        <?php endif ?>
    </dd>
    <?php endforeach ?>
</dl>
<?php endif ?>
<!-- / -->
    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
    <dl class="item-options">
        <dt><?= $this->escapeHtml($this->getLinksTitle()) ?></dt>
        <?php foreach ($links as $link): ?>
            <dd><?= $this->escapeHtml($link->getTitle()) ?></dd>
        <?php endforeach ?>
    </dl>
    <?php endif ?>
    <!-- EOF downloadable -->
