<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 * @var Mage_Directory_Block_Currency $this 
 */
?>
<?php if($this->getCurrencyCount()>1): ?>
<div class="block block-currency">
    <div class="block-title">
        <strong><span><?= $this->__('Select Your Currency') ?></span></strong>
    </div>
    <div class="block-content">
        <select name="currency" title="<?= Mage::helper('core')->quoteEscape($this->__('Select Your Currency')) ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?= $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif ?>>
                <?= $_name ?> - <?= $_code ?>
            </option>
        <?php endforeach ?>
        </select>
    </div>
</div>
<?php endif ?>
