<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Directory_Block_Currency $this */
?>
<?php if ($this->getCurrencyCount() > 1): ?>
<div class="currency-switcher">
    <label for="select-currency" class="visually-hidden"><?= $this->__('Your Currency:') ?></label>
    <select id="select-currency" name="currency" title="<?= $this->quoteEscape($this->__('Your Currency')) ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <option value="<?= $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif ?>>
            <?= Mage::app()->getLocale()->getCurrencySymbol($_code) ?>
        </option>
    <?php endforeach ?>
    </select>
</div>
<?php endif ?>
