<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Rss_Block_List $this */
?>
<div class="page-title rss-title">
    <h1><?= $this->__('RSS Feeds') ?></h1>
</div>
<?php
    $_categories = $this->getRssCatalogFeeds();
    $_misc = $this->getRssMiscFeeds();
?>
<?php if ($_categories || $_misc): ?>
<?php if($_misc): ?>
<table class="data-table rss-table" id="rss-table-misc">
    <col>
    <col width="1">
    <thead>
        <tr>
            <th colspan="2"><?= $this->__('Miscellaneous Feeds') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_misc as $_feed): ?>
        <tr>
            <td><?= $_feed->getLabel() ?></td>
            <td><a href="<?= $_feed->getUrl() ?>" class="link-rss"><?= $this->__('Get Feed') ?></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
<?php if ($_categories && $_misc): ?>
<br>
<?php endif ?>
<?php if($_categories): ?>
<table class="data-table rss-table" id="rss-table-category">
    <col>
    <col width="1">
    <thead>
        <tr>
            <th colspan="2"><?= $this->__('Category Feeds') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_categories as $_category): ?>
        <tr>
            <td><?= $_category->getLabel() ?></td>
            <td><a href="<?= $_category->getUrl() ?>" class="link-rss"><?= $this->__('Get Feed') ?></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
<?php else: ?>
    <p><?= $this->__('There are no Rss Feeds') ?></p>
<?php endif ?>
