<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<dt class="complete"><?= $this->__('Billing Address') ?></dt>
<dd class="complete">
    <address><?= $this->getBilling()->format('html') ?></address>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Billing Address') ?>
</dt>
<?php endif ?>
