<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?= $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-payment'); return false;"><?= $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    <?= $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Payment Method') ?>
</dt>
<?php endif ?>

