<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete"><?= $this->__('Payment Method') ?></dt>
<dd class="complete">
    <?= $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Payment Method') ?>
</dt>
<?php endif ?>
