<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
<dt class="complete"><?= $this->__('Shipping Method') ?></dt>
<dd class="complete">
    <?php if ($this->getShippingMethod()): ?>
    <?= $this->getShippingDescription() ?>

    <?php $_excl = $this->getShippingPriceExclTax(); ?>
    <?php $_incl = $this->getShippingPriceInclTax(); ?>
    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
        <?= $_incl ?>
        <?php else: ?>
        <?= $_excl ?>
        <?php endif ?>
    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
        (<?= $this->__('Incl. Tax') ?> <?= $_incl ?>)
        <?php endif ?>

    <?php else: ?>
    <?= $this->__('Shipping method has not been selected yet') ?>
    <?php endif ?>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Shipping Method') ?>
</dt>
<?php endif ?>
