<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<dt class="complete"><?= $this->__('Shipping Address') ?></dt>
<dd class="complete">
    <address><?= $this->getShipping()->format('html') ?></address>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Shipping Address') ?>
</dt>
<?php endif ?>
