<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<dt class="<?= $completeClass ?>"><?= $this->__('Shipping Address') ?></dt>
<dd class="<?= $completeClass ?>">
    <address><?= $this->getShipping()->format('html') ?></address>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Shipping Address') ?>
</dt>
<?php endif ?>

