<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<dt class="<?= $completeClass ?>">
    <?= $this->__('Shipping Address') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-shipping');return false;"><?= $this->__('Change') ?></a></span>
</dt>
<dd class="<?= $completeClass ?>">
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
    <address><?= $this->getShipping()->format('html') ?></address>
    <?php endif ?>
</dd>
<?php else: ?>
<dt>
    <?= $this->__('Shipping Address') ?>
</dt>
<?php endif ?>

