<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Button $this */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?= $this->quoteEscape($this->__('Update Wishlist')) ?>" class="button btn-update button-secondary"><?= $this->__('Update Wishlist') ?></button>
<?php endif ?>
