<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Button $this */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?= $this->quoteEscape($this->__('Update Wishlist')) ?>" class="button btn-update button-secondary"><?= $this->__('Update Wishlist') ?></button>
<?php endif ?>
