<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Catalog_Block_Product_Widget_New $this */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="widget-title">
        <h2><?= $this->__('New Products') ?></h2>
    </div>
    <div class="widget-products">
        <?= $this->getPagerHtml() ?>
        <ol class="mini-products-list">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?= (++$i == count($_products))?' last':'' ?>">
                <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(50) ?>" width="50" height="50" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(100) ?> 2x" alt="<?= $this->stripTags($_product->getName(), null, true) ?>"></a>
                <div class="product-details">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>)"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>
