<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_System_Convert_Profile_Edit_Tab_Run $this */
?>
<script type="text/javascript">
function runProfile(popup)
{
    var url = "<?= $this->getUrl('*/*/run', ['id' => $this->getProfileId()]) ?>";
    if (document.getElementById('profile_direction') != undefined
        && document.getElementById('profile_data_transfer') != undefined
        && getDirection() == 'import' && getTransferType() == 'interactive') {
        var file = getSelectedFiles();
        if (file == '') {
            alert('Please select imported files');
            document.getElementById('file_list').style.display = '';
            return false;
        }
        url += 'files/' + file + '/';
    }

    if (!popup) {
        document.getElementById('run_iframe').style.display = 'block';
        document.getElementById('run_iframe').src = url;
    } else {
        window.open(url);
    }
}

function getDirection()
{
    return document.getElementById('profile_direction').options[document.getElementById('profile_direction').options.selectedIndex].value;
}

function getSelectedFiles()
{
    return document.getElementById('files').options[document.getElementById('files').options.selectedIndex].value;
}

function getTransferType()
{
    return document.getElementById('profile_data_transfer').options[document.getElementById('profile_data_transfer').options.selectedIndex].value;
}
</script>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?= $this->__('Please make sure that your changes were saved before running the profile.') ?></li>
        </ul>
    </li>
</ul>
<div id="file_list" style="display: none;">
    <select id="files" name="files">
        <option value="">Select a file</option>
        <?php if ($files = $this->getImportedFiles()): ?>
            <?php foreach ($files as $file): ?>
                <option value=<?= $file ?>><?= $file ?></option>
            <?php endforeach ?>
        <?php endif ?>
    </select>
    <br />&nbsp;
</div>

<?= $this->getRunButtonHtml() ?><br />
<iframe id="run_iframe" frameborder="0" style="display:none; width:100%; height:400px;"></iframe>
