<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/**
 * @see Mage_CatalogInventory_Block_Qtyincrements
 * @var Mage_CatalogInventory_Block_Qtyincrements $this
 */
?>
<?php if ($this->getProductQtyIncrements()) : ?>
    <div class="product-pricing">
        <?= $this->__('%s is available for purchase in increments of %s', $this->getProductName(), $this->getProductQtyIncrements()) ?>
    </div>
<?php endif ?>
