<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Paypal_Block_Payflow_Link_Iframe
 * @var Mage_Paypal_Block_Payflow_Link_Iframe $this
 */
?>
<html>
<head></head>
<body>
    <form id="token_form" method="POST" action="<?= $this->getTransactionUrl() ?>">
        <input type="hidden" name="SECURETOKEN" value="<?= $this->getSecureToken() ?>" />
        <input type="hidden" name="SECURETOKENID" value="<?= $this->getSecureTokenId() ?>" />
        <input type="hidden" name="MODE" value="<?= $this->isTestMode() ? 'TEST' : 'LIVE' ?>" />
    </form>
    <script type="text/javascript">
        document.getElementById('token_form').submit();
    </script>
</body>
</html>
