<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Attribute_New_Product_Created $this */
?>
<script type="text/javascript">
var added = false;
function addAttribute(closeAfter) {
    if(window.opener!=null && !added) {
        window.opener.Product.AttributesBridge.addAttributeRow(<?= $this->getAttributesBlockJson() ?>);
        added = true;
    }

    if(closeAfter)
    {
        closeWindow();
    }
}

function closeWindow()
{
    if (window.opener) {
        window.opener.focus();
    }
    window.close();
}

addAttribute(false);
setTimeout(closeWindow, 3000);
</script>
<div class="a-center">
<?= $this->getCloseButtonHtml() ?>
</div>
