<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php if ($this->canDisplayGiftmessageForm()): ?>
<div id="gift_options_giftmessage">
    <div class="giftcard-form">
        <div class="giftcard-send-form">
            <h4><?= Mage::helper('giftmessage')->__('Gift Message') ?></h4>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="current_item_giftmessage_sender"><?= Mage::helper('giftmessage')->__('From') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" name="current_item_giftmessage_sender" id="current_item_giftmessage_sender" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="current_item_giftmessage_recipient"><?= Mage::helper('giftmessage')->__('To') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" name="current_item_giftmessage_recipient" id="current_item_giftmessage_recipient" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="current_item_giftmessage_message"><?= Mage::helper('giftmessage')->__('Message') ?></label>
                        <div class="input-box">
                            <textarea class="textarea" cols="15" rows="2" name="current_item_giftmessage_message" id="current_item_giftmessage_message"></textarea>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<?php endif ?>
