<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>

<?php if ($this->getChildHtml()) :?>
<div id="gift_options_form_contents" style="display: none;">
    <?= $this->getChildHtml() ?>
</div>

<script>
_giftOptions = new GiftOptionsPopup();
</script>
<?php endif ?>
