<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>

<?php if ($this->getChildHtml()) :?>
<template id="gift_options_configure">
    <form id="gift_options_configuration_form" action="#" method="post">
        <?= $this->getChildHtml() ?>
    </form>
</template>

<script>
    new GiftOptionsPopup();
</script>
<?php endif ?>
