<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<tbody>
    <tr>
        <td class="cell-content product-info">
            <p class="product-name"><?= $this->escapeHtml($_item->getName()) ?></p>
            <?php if ($this->getItemOptions()): ?>
                <dl style="margin:0; padding:0;">
                    <?php foreach ($this->getItemOptions() as $option): ?>
                        <dt><strong><em><?= $option['label'] ?></em></strong></dt>
                        <dd style="margin:0; padding:0 0 0 9px;"><?= nl2br($option['value']) ?></dd>
                    <?php endforeach ?>
                </dl>
            <?php endif ?>
            <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
            <?php endif ?>
            <?= $this->escapeHtml($_item->getDescription()) ?>
        </td>
        <td class="cell-content align-center"><?= $this->escapeHtml($this->getSku($_item)) ?></td>
        <td class="cell-content align-right"><?= $_item->getQty()*1 ?></td>
    </tr>
</tbody>
