<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Transactions_Detail $this */
?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml() ?></p>
</div>

<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?= $this->__('Transaction Data') ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <table cellspacing="0" class="log-info table">
                <col width="25%">
                <col>
                <tbody>
                    <tr>
                        <th><?= $this->__('Transaction ID') ?></th>
                        <td><?= $this->getTxnIdHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->__('Parent Transaction ID') ?></th>
                        <td>
                            <?php if ($this->getParentTxnIdHtml()): ?>
                                <a href="<?= $this->getParentTxnIdUrlHtml() ?>">
                                    <?= $this->getParentTxnIdHtml() ?>
                                </a>
                            <?php else: ?>
                                <?= $this->__('N/A') ?>
                            <?php endif ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $this->__('Order ID') ?></th>
                        <td>
                            <a href="<?= $this->getOrderIdUrlHtml() ?>">
                                <?= $this->getOrderIncrementIdHtml() ?>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $this->__('Transaction Type') ?></th>
                        <td><?= $this->getTxnTypeHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->__('Is Closed') ?></th>
                        <td><?= $this->getIsClosedHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->__('Created At') ?></th>
                        <td><?= $this->getCreatedAtHtml() ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?= $this->__('Child Transactions') ?></h4>
        </div>
        <div class="log-details-grid">
            <?= $this->getChildHtml('child_grid') ?>
        </div>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?= $this->__('Transaction Details') ?></h4>
        </div>
        <div class="log-details-grid">
            <?= $this->getChildHtml('detail_grid') ?>
        </div>
    </div>
</div>
