<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Review_Info $this */
?>
<?= $this->getChildHtml('items_before') ?>
<div id="checkout-review-table-wrapper">
    <?php $_tableClass = $this->helper('tax')->displayCartBothPrices() ? 'linearize-table-large' : 'linearize-table'; ?>
    <table class="data-table <?= $_tableClass ?> checkout-review-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif ?>
        <thead>
            <tr>
                <th rowspan="<?= $rowspan ?>"><?= $this->__('Product') ?></th>
                <th colspan="<?= $colspan ?>" class="a-center"><?= $this->__('Price') ?></th>
                <th rowspan="<?= $rowspan ?>" class="a-center"><?= $this->__('Qty') ?></th>
                <th colspan="<?= $colspan ?>" class="a-center"><?= $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif ?>
        </thead>
        <?= $this->getChildHtml('totals') ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?= $this->getItemHtml($_item) ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?= $this->getChildHtml('items_after') ?>
<script type="text/javascript">truncateOptions();</script>
<div id="checkout-review-submit">
    <?= $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <a class="continue-shopping" href="<?= $this->getUrl() ?>"><?= $this->__('Continue Shopping') ?></a>
        <?= $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape($this->__('Submitting order information...')) ?>" title="<?= $this->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?= $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
        review = new Review(
            '<?= $this->getUrl('checkout/onepage/saveOrder') ?>',
            '<?= $this->getUrl('checkout/onepage/success') ?>',
            document.getElementById('checkout-agreements')
        );
    </script>
</div>
