<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/**
 * @see Mage_Checkout_Block_Cart_Totals
 * @var Mage_Checkout_Block_Cart_Totals $this
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?= $this->renderTotals(null, $_colspan) ?>
    <?= $this->renderTotals('footer', $_colspan) ?>
    <?php if ($this->needDisplayBaseGrandtotal()): ?>
    <tr>
        <td colspan="<?= $_colspan + 1 ?>" style="font-weight: normal; text-align: center; color: var(--maho-color-text-secondary); padding-top: .5rem;">
            <small>
                <?= $this->helper('sales')->__('You\'ll be charged in the store currency: %s.', $this->displayBaseGrandtotal()) ?><br>
                <?= $this->helper('sales')->__('Your bank may apply its own conversion rate.') ?>
            </small>
        </td>
    </tr>
    <?php endif ?>
</tfoot>
<?php endif ?>
