<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Checkout_Block_Cart_Totals
 * @var Mage_Checkout_Block_Cart_Totals $this
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?= $this->renderTotals(null, $_colspan) ?>
    <?= $this->renderTotals('footer', $_colspan) ?>
    <?php if ($this->needDisplayBaseGrandtotal()): ?>
    <tr>
        <td colspan="<?= $_colspan + 1 ?>" style="font-weight: normal; text-align: center; color: var(--maho-color-text-secondary); padding-top: .5rem;">
            <small>
                <?= $this->helper('sales')->__('You\'ll be charged in the store currency: %s.', $this->displayBaseGrandtotal()) ?><br>
                <?= $this->helper('sales')->__('Your bank may apply its own conversion rate.') ?>
            </small>
        </td>
    </tr>
    <?php endif ?>
</tfoot>
<?php endif ?>
