<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Checkout_Block_Cart_Totals
 * @var Mage_Checkout_Block_Cart_Totals $this
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?= $this->renderTotals(null, $_colspan) ?>
    <?= $this->renderTotals('footer', $_colspan) ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>
        <td class="a-right" colspan="<?= $_colspan ?>">
            <small><?= $this->helper('sales')->__('Grand Total to be Charged') ?></small>
        </td>
        <td class="a-right">
            <small><?= $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif ?>
</tfoot>
<?php endif ?>
