<?php
/**
 * Maho
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="my-wishlist">
        <div class="page-title title-buttons">
            <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
                <a href="<?= $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()) ?>" class="link-rss"><?= $this->__('RSS Feed') ?></a>
            <?php endif ?>
            <h1><?= $this->getTitle() ?></h1>
        </div>
        <?= $this->getMessagesBlock()->toHtml() ?>

        <form id="wishlist-view-form" action="<?= $this->getUrl('*/*/update', ['wishlist_id' => $this->getWishlistInstance()->getId()]) ?>" method="post">
            <?= $this->getChildHtml('top') ?>
            <div class="fieldset">
                <?php if ($this->hasWishlistItems()): ?>
                        <?= $this->getBlockHtml('formkey') ?>
                        <?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
                        <?= $this->getChildHtml('items') ?>
                <?php else: ?>
                    <p class="wishlist-empty"><?= $this->__('You have no items in your wishlist.') ?></p>
                <?php endif ?>
                <div class="buttons-set buttons-set2">
                    <?= $this->getChildHtml('control_buttons') ?>
                </div>
            </div>
        </form>

        <form id="wishlist-allcart-form" action="<?= $this->getUrl('*/*/allcart') ?>" method="post">
            <?= $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="wishlist_id" id="wishlist_id" value="<?= $this->getWishlistInstance()->getId() ?>" />
                <input type="hidden" name="qty" id="qty" value="" />
            </div>
        </form>

        <script type="text/javascript">
        //<![CDATA[
            var wishlistForm = new Validation($('wishlist-view-form'));
            var wishlistAllCartForm = new Validation($('wishlist-allcart-form'));

            function calculateQty() {
                var itemQtys = new Array();
                $$('#wishlist-view-form .qty').each(
                    function (input, index) {
                        var idxStr = input.name;
                        var idx = idxStr.replace( /[^\d.]/g, '' );
                        itemQtys[idx] = input.value;
                    }
                );

                $$('#qty')[0].value = JSON.stringify(itemQtys);
            }

            function addAllWItemsToCart() {
                calculateQty();
                wishlistAllCartForm.form.submit();
            }
        //]]>
        </script>
    </div>
    <?= $this->getChildHtml('bottom') ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
    </div>
<?php endif ?>
