<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_FeedManager
 */

declare(strict_types=1);

use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\DefaultExpression\CurrentTimestamp;
use Doctrine\DBAL\Schema\ForeignKeyConstraint;
use Doctrine\DBAL\Schema\ForeignKeyConstraint\ReferentialAction;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Index\IndexType;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\SchemaEditor;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Types;

return function (SchemaEditor $schema): void {
    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_destination')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('destination_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('name')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('type')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('config')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_enabled')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('last_upload_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('last_upload_status')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('created_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('updated_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()
                    ->setUnquotedColumnNames('destination_id')
                    ->create(),
            )
            ->addIndex(Index::editor()->setUnquotedColumnNames('type'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('is_enabled'))
            ->setComment('Feed Manager - Upload Destinations')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_feed')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('feed_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('name')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('platform')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('store_id')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_enabled')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('filename')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('file_format')
                    ->setTypeName(Types::STRING)
                    ->setLength(10)
                    ->setDefaultValue('xml')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('generation_time')
                    ->setTypeName(Types::STRING)
                    ->setLength(8)
                    ->setDefaultValue('03:00:00')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('configurable_mode')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setDefaultValue('children_only')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('destination_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('auto_upload')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('schedule')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('product_filters')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('conditions_serialized')
                    ->setTypeName(Types::TEXT)
                    ->setLength(1048576)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('exclude_disabled')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('exclude_out_of_stock')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('include_product_types')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->setNotNull(false)
                    ->setDefaultValue('simple')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('condition_groups')
                    ->setTypeName(Types::TEXT)
                    ->setLength(1048576)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('xml_header')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('xml_item_template')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('xml_footer')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('xml_item_tag')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->setNotNull(false)
                    ->setDefaultValue('item')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('xml_structure')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('csv_columns')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('csv_delimiter')
                    ->setTypeName(Types::STRING)
                    ->setLength(5)
                    ->setNotNull(false)
                    ->setDefaultValue(',')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('csv_enclosure')
                    ->setTypeName(Types::STRING)
                    ->setLength(5)
                    ->setNotNull(false)
                    ->setDefaultValue('"')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('csv_include_header')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('json_structure')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('json_root_key')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->setNotNull(false)
                    ->setDefaultValue('products')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('format_preset')
                    ->setTypeName(Types::STRING)
                    ->setLength(32)
                    ->setNotNull(false)
                    ->setDefaultValue('english')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_currency')
                    ->setTypeName(Types::STRING)
                    ->setLength(10)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_decimals')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(2)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_decimal_point')
                    ->setTypeName(Types::STRING)
                    ->setLength(5)
                    ->setNotNull(false)
                    ->setDefaultValue('.')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_thousands_sep')
                    ->setTypeName(Types::STRING)
                    ->setLength(5)
                    ->setNotNull(false)
                    ->setDefaultValue('')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('price_currency_suffix')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('tax_mode')
                    ->setTypeName(Types::STRING)
                    ->setLength(10)
                    ->setNotNull(false)
                    ->setDefaultValue('incl')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('use_parent_value')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('exclude_category_url')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('no_image_url')
                    ->setTypeName(Types::STRING)
                    ->setLength(500)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('gzip_compression')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('notification_mode')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setDefaultValue('none')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('notification_frequency')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setDefaultValue('once_until_success')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('notification_email')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('notification_sent')
                    ->setTypeName(Types::SMALLINT)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('last_generated_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('last_product_count')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('last_file_size')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('created_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('updated_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('feed_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('platform'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('is_enabled'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('store_id'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('destination_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('store_id')
                    ->setUnquotedReferencedTableName('core_store')
                    ->setUnquotedReferencedColumnNames('store_id')
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('destination_id')
                    ->setUnquotedReferencedTableName('feedmanager_destination')
                    ->setUnquotedReferencedColumnNames('destination_id')
                    ->setOnDeleteAction(ReferentialAction::SET_NULL)
                    ->create(),
            )
            ->setComment('Feed Manager - Feeds')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_attribute_mapping')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('mapping_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('feed_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('platform_attribute')
                    ->setTypeName(Types::STRING)
                    ->setLength(100)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('source_type')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('source_value')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('conditions')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('transformers')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('sort_order')
                    ->setTypeName(Types::INTEGER)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('mapping_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('feed_id', 'platform_attribute'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('feed_id')
                    ->setUnquotedReferencedTableName('feedmanager_feed')
                    ->setUnquotedReferencedColumnNames('feed_id')
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Feed Manager - Attribute Mappings')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_category_mapping')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('mapping_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('platform')
                    ->setTypeName(Types::STRING)
                    ->setLength(50)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('category_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('platform_category_id')
                    ->setTypeName(Types::STRING)
                    ->setLength(100)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('platform_category_path')
                    ->setTypeName(Types::STRING)
                    ->setLength(500)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('mapping_id')->create())
            ->addIndex(Index::editor()->setType(IndexType::UNIQUE)->setUnquotedColumnNames('platform', 'category_id'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('category_id')
                    ->setUnquotedReferencedTableName('catalog_category_entity')
                    ->setUnquotedReferencedColumnNames('entity_id')
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Feed Manager - Category Mappings')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_log')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('log_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('feed_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('started_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('completed_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('status')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setDefaultValue('running')
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('product_count')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('error_count')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('errors')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('file_path')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('file_size')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('upload_status')
                    ->setTypeName(Types::STRING)
                    ->setLength(20)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('uploaded_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('upload_message')
                    ->setTypeName(Types::STRING)
                    ->setLength(500)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('destination_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('log_id')->create())
            ->addIndex(Index::editor()->setUnquotedColumnNames('feed_id', 'started_at'))
            ->addForeignKeyConstraint(
                ForeignKeyConstraint::editor()
                    ->setUnquotedReferencingColumnNames('feed_id')
                    ->setUnquotedReferencedTableName('feedmanager_feed')
                    ->setUnquotedReferencedColumnNames('feed_id')
                    ->setOnDeleteAction(ReferentialAction::CASCADE)
                    ->create(),
            )
            ->setComment('Feed Manager - Generation Logs')
            ->create(),
    );

    $schema->addTable(
        Table::editor()
            ->setUnquotedName('feedmanager_dynamic_rule')
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('rule_id')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setAutoincrement(true)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('name')
                    ->setTypeName(Types::STRING)
                    ->setLength(255)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('code')
                    ->setTypeName(Types::STRING)
                    ->setLength(100)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('description')
                    ->setTypeName(Types::TEXT)
                    ->setLength(65535)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_system')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('is_enabled')
                    ->setTypeName(Types::SMALLINT)
                    ->setUnsigned(true)
                    ->setDefaultValue(1)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('cases')
                    ->setTypeName(Types::TEXT)
                    ->setLength(16777215)
                    ->setNotNull(false)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('sort_order')
                    ->setTypeName(Types::INTEGER)
                    ->setUnsigned(true)
                    ->setDefaultValue(0)
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('created_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addColumn(
                Column::editor()
                    ->setUnquotedName('updated_at')
                    ->setTypeName(Types::DATETIME_MUTABLE)
                    ->setDefaultValue(new CurrentTimestamp())
                    ->create(),
            )
            ->addPrimaryKeyConstraint(PrimaryKeyConstraint::editor()->setUnquotedColumnNames('rule_id')->create())
            ->addIndex(Index::editor()->setType(IndexType::UNIQUE)->setUnquotedColumnNames('code'))
            ->addIndex(Index::editor()->setUnquotedColumnNames('is_enabled', 'sort_order'))
            ->setComment('FeedManager Dynamic Attribute Rules')
            ->create(),
    );
};
