<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * Mage_Adminhtml_Block_Sales_Order_Create_Coupons
 *
 * @var Mage_Adminhtml_Block_Sales_Order_Create_Coupons $this
 */
?>
<div class="entry-edit box-left">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?= Mage::helper('sales')->__('Apply Coupon Code') ?></h4>
     </div>
     <fieldset class="np">
         <div class="content">
            <p><input type="text" class="input-text" id="coupons:code" value="" name="coupon_code" style="width:200px">&nbsp;<?= $this->getButtonHtml(Mage::helper('sales')->__('Apply'), 'order.applyCoupon(document.getElementById(\'coupons:code\').value)') ?></p>
            <?php if($this->getCouponCode()): ?>
                <p><strong><?= $this->escapeHtml($this->getCouponCode()) ?></strong> [<a href="#" onclick="order.applyCoupon(''); return false;" title="<?= Mage::helper('sales')->__('Remove Coupon Code') ?>"><?= Mage::helper('sales')->__('Remove') ?></a>]</p>
            <?php endif ?>
            <script>
                order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif ?>);
                order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif ?>);
            </script>
        </div>
    </fieldset>
</div>
