<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product $this */
?>
<div class="content-header">
    <h3><?= Mage::helper('catalog')->__('Manage Products') ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getButtonsHtml() ?>
    </p>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
<?= $this->getChildHtml('store_switcher') ?>
<?php endif ?>
<div>
    <?= $this->getGridHtml() ?>
</div>
