<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Catalog_Product
 * @var Mage_Adminhtml_Block_Catalog_Product $this
 */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3><?= Mage::helper('catalog')->__('Manage Products') ?></h3></td>
        <td class="a-right">
            <?= $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
<?= $this->getChildHtml('store_switcher') ?>
<?php endif ?>
<div>
    <?= $this->getGridHtml() ?>
</div>
