<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @see Mage_Adminhtml_Block_Dashboard_Tab_Amounts */
/** @see Mage_Adminhtml_Block_Dashboard_Tab_Orders */
/** @var Mage_Adminhtml_Block_Dashboard_Graph $this */
?>

<?php $chartRandomId = rand(100,999) ?>

<?php if ($this->getCount()): ?>
    <?php $this->processData() ?>
    <canvas id="chart<?= $chartRandomId ?>"></canvas>
    <script>
        dashboard.drawChart(
            <?= json_encode("chart{$chartRandomId}") ?>,
            <?= json_encode($this->getAllSeries()) ?>,
            <?= json_encode($this->getAxisLabels('x')) ?>,
        );
    </script>
<?php else: ?>
    <?= $this->__('No Data Found') ?>
<?php endif ?>
