<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @see Mage_Adminhtml_Block_Dashboard_Tab_Amounts */
/** @see Mage_Adminhtml_Block_Dashboard_Tab_Orders */
/** @var Mage_Adminhtml_Block_Dashboard_Graph $this */
?>

<div style="margin:20px;">
    <p class="switcher a-right" style="padding:5px 10px;"><?= $this->__('Select Range') ?>:
    <select name="period" id="order_<?= $this->getHtmlId() ?>_period" onchange="changeDiagramsPeriod(this);">
        <?php foreach ($this->helper('adminhtml/dashboard_data')->getDatePeriods() as $_value=>$_label): ?>
            <?php if(in_array($_value, ['custom'])) continue; ?>
            <option value="<?= $_value ?>" <?php if($this->getRequest()->getParam('period')==$_value): ?> selected="selected"<?php endif ?>><?= $_label ?></option>
        <?php endforeach ?>
    </select></p><br>
    <?php
    $_containerStyle = "width:{$this->getWidth()}px;height:{$this->getHeight()}px; margin:0 auto;";
    ?>
    <?php if($this->getCount()): ?>
        <?php $this->processData() ?>
        <?php $allSeries = $this->getAllSeries() ?>
        <div class="a-center dashboard-chart"
             style="<?= $_containerStyle ?>"
             data-chart-labels="<?= $this->escapeHtml(json_encode($this->getAxisLabels('x'))) ?>"
             data-chart-data="<?= $this->escapeHtml(json_encode($allSeries[array_key_first($allSeries)])) ?>">
            <canvas></canvas>
        </div>
    <?php else: ?>
    <p class="a-center" style="<?= $_containerStyle?>"><?= $this->__('No Data Found') ?></p>
    <?php endif ?>
</div>
