<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Dashboard $this */
?>

<div class="content-header">
    <h3 class="head-dashboard"><?= $this->__('Dashboard') ?></h3>
    <?= $this->getChildHtml('store_switcher') ?>
</div>

<script>
    const dashboard = new MahoDashboard({
        diagrams: {
            htmlId: <?= json_encode($this->getChild('diagrams')->getId()) ?>,
            tabs: <?= json_encode($this->getChild('diagrams')->getTabsIds()) ?>,
            switcherId: <?= json_encode("order_{$this->getHtmlId()}_period") ?>,
            ajaxUrl: <?= json_encode($this->getUrl('*/*/ajaxBlock')) ?>,
        },
    });
</script>

<div class="dashboard-container">
    <div>
        <?= $this->getChildHtml('sales') ?>
        <div class="entry-edit">
            <div class="entry-edit-head"><h4><?= $this->__('Last 5 Orders') ?></h4></div>
            <fieldset><?= $this->getChildHtml('lastOrders') ?></fieldset>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head"><h4><?= $this->__('Last 5 Search Terms') ?></h4></div>
            <fieldset><?= $this->getChildHtml('lastSearches') ?></fieldset>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head"><h4><?= $this->__('Top 5 Search Terms') ?></h4></div>
            <fieldset><?= $this->getChildHtml('topSearches') ?></fieldset>
        </div>
    </div>

    <div>

    <?php if (is_array($this->getChild('diagrams')->getTabsIds())) : ?>
        <div>
            <div id="diagram_tabs">
                <?= $this->getChildHtml('diagrams') ?>
                <div>
                    <?= $this->__('Select Range') ?>:
                    <select name="period" id="order_<?= $this->getHtmlId() ?>_period">
                    <?php $selected = $this->getRequest()->getParam('period') ?>
                    <?php foreach ($this->helper('adminhtml/dashboard_data')->getDatePeriods() as $value => $label): ?>
                        <?php if (in_array($value, ['custom'])) continue ?>
                        <option value="<?= $value ?>"<?= $selected === $value ? ' selected="selected"' : '' ?>>
                            <?= $label ?>
                        </option>
                    <?php endforeach ?>
                    </select>
               </div>
            </div>
            <div id="diagram_tab_content" class="box"></div>
        </div>
    <?php else: ?>
        <?= $this->getChildHtml('diagrams') ?>
    <?php endif ?>

        <?= $this->getChildHtml('totals') ?>

        <div>
            <?= $this->getChildHtml('grids') ?>
            <div id="grid_tab_content"></div>
        </div>

    </div>
</div>
