<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<div style="padding:5px;">
<?php if(count($this->getCollection()->getItems()) > 0): ?>
    <?php foreach ($this->getCollection()->getItems() as $item): ?>
    <span><?= $item->getQueryText() ?></span><br>
    <?php endforeach ?>
<?php else: ?>
<div class="a-center"><?= $this->__('No search keywords.') ?></div>
<?php endif ?>
</div>
