<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div style="padding:5px;">
<?php if(count($this->getCollection()->getItems()) > 0): ?>
    <?php foreach ($this->getCollection()->getItems() as $item): ?>
    <span><?= $item->getQueryText() ?></span><br />
    <?php endforeach ?>
<?php else: ?>
<div class="a-center"><?= $this->__('No search keywords.') ?></div>
<?php endif ?>
</div>
