<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Dashboard_Totals $this */
?>
<?php if(count($this->getTotals()) > 0): ?>
<div class="box" id="dashboard_diagram_totals">
    <div class="dashboard-totals-stats">
        <?php foreach($this->getTotals() as $_total): ?>
        <div class="stat-col">
            <div class="stat-value"><?= $_total['value'] ?><span class="stat-decimals"><?= $_total['decimals'] ?></span></div>
            <div class="stat-label"><?= $_total['label'] ?></div>
        </div>
        <?php endforeach ?>
    </div>
</div>
<?php endif ?>
