<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php /** @var Mage_Sales_Block_Payment_Form_Billing_Agreement $this */?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?= $_code ?>" style="display:none;">
    <li>
        <div class="input-box">
            <label for="<?= $_code ?>_ba_agreement_id"><?= $this->__('Billing Agreement') ?> <span class="required">*</span></label><br>
            <select id="<?= $_code ?>_ba_agreement_id" name="payment[<?= $this->getTransportName() ?>]" class="required-entry">
                <option value=""><?= $this->__('-- Please Select Billing Agreement--') ?></option>
            <?php foreach ($this->getBillingAgreements() as $id => $referenceId): ?>
                <option value="<?= $id ?>"<?= ($id == $this->getInfoData($this->getTransportName())) ? ' selected="selected"' : ''?>><?= $this->escapeHtml($referenceId) ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
</ul>
