<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle $this */
$product = $this->getProduct();
$options = $this->getOptions();
?>
<?php if ($product->isSaleable()): ?>
    <?php if (count($options)): ?>
        <dl>
        <?php foreach ($options as $option): ?>
        <?php if ($option->getSelections()): ?>
            <?= $this->getOptionHtml($option) ?>
        <?php endif ?>
        <?php endforeach ?>
        </dl>
    <?php else: ?>
        <p><?= $this->__('No options of this product are available.') ?></p>
    <?php endif ?>
<?php endif ?>
