<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle $this */
$product = $this->getProduct();
$options = $this->getOptions();
?>
<?php if ($product->isSaleable()): ?>
    <?php if (count($options)): ?>
        <dl>
        <?php foreach ($options as $option): ?>
        <?php if ($option->getSelections()): ?>
            <?= $this->getOptionHtml($option) ?>
        <?php endif ?>
        <?php endforeach ?>
        </dl>
    <?php else: ?>
        <p><?= $this->__('No options of this product are available.') ?></p>
    <?php endif ?>
<?php endif ?>
