<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Cache_Additional $this */
?>
<br/>
<div class="content-header">
    <h3><?= Mage::helper('adminhtml')->__('Additional Cache Management') ?></h3>
    <p class="content-buttons form-buttons"></p>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?= $this->getCleanImagesUrl()?>')" type="button" class="scalable"><span><?= Mage::helper('adminhtml')->__('Flush Catalog Images Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?= Mage::helper('adminhtml')->__('Pregenerated product images files.') ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?= $this->getCleanSwatchesUrl()?>')" type="button" class="scalable"><span><?= Mage::helper('adminhtml')->__('Flush Swatch Images Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?= Mage::helper('adminhtml')->__('Pregenerated configurable swatches image files.') ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?= $this->getCleanMinifiedFilesUrl()?>')" type="button" class="scalable"><span><?= Mage::helper('adminhtml')->__('Flush Minified CSS/JS Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?= Mage::helper('adminhtml')->__('Minified CSS and JavaScript files.') ?>
        </td>
    </tr>
</table>
<?= $this->getChildHtml() ?>
