<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Cache_Notifications $this */
?>
<?php if($processes = $this->getCacheTypesForRefresh()): ?>
<div class="notification-global">
    <span class="label">
        <strong><?= $this->helper('adminhtml')->__('One or more of the Cache Types are invalidated:') ?></strong>
        <?= implode(', ', $processes) ?>.
        <?= $this->helper('index')->__('Click here to go to <a href="%s">Cache Management</a> and refresh cache types.', $this->getManageUrl()) ?>
    </span>
</div>
<?php endif ?>
