<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<div class="content-header">
    <h3><?= $header ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php if( $form ): ?>
<?= $form->toHtml() ?>
<script>
    var wigetForm = new varienForm('<?= $form->getForm()->getId() ?>');
</script>
<?php endif ?>
