<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Type_Configurable $this */
?>

<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>
        <dt><label class="required"><em>*</em><?= $_attribute->getLabel() ?></label></dt>
        <dd<?php if ($_attribute->decoratedIsLast) {?> class="last"<?php }?>>
            <div class="input-box">
                <select name="super_attribute[<?= $_attribute->getAttributeId() ?>]" id="attribute<?= $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?= $this->__('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
    <?php endforeach ?>
    </dl>
    <script type="text/javascript">
        var spConfig = new Product.Config(<?= $this->getJsonConfig() ?>);
    </script>
<?php endif ?>
