<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_View_Type_Configurable $this */
$product = $this->getProduct();
$attributes = $this->getAllowAttributes();
$jsonConfig = $this->getJsonConfig();
?>
<?php if ($product->isSaleable() && count($attributes)): ?>
    <dl>
    <?php foreach ($attributes as $attribute): ?>
    <?php if ($html = $this->renderAttributeBlock($attribute)): ?>
        <?= $html ?>
    <?php else: ?>
        <dt><label class="required"><?= $attribute->getLabel() ?></label></dt>
        <dd>
            <div class="input-box">
                <select name="super_attribute[<?= $attribute->getAttributeId() ?>]" id="attribute<?= $attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?= $this->__('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
    <?php endif ?>
    <?php endforeach ?>
    </dl>
    <script>
        window.spConfig = new Product.Config(<?= $jsonConfig ?>);
    </script>
    <?= $this->getChildHtml('after') ?>
<?php endif ?>
