<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_attribute = $this->getAttribute() ?>
<?php $_code = $_attribute->getAttributeCode() ?>
<label for="<?= $this->getFieldId($_code)?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?= $this->__($_attribute->getStoreLabel()) ?></label>
<div class="input-box">
    <input type="text" list="<?= $this->getDatalistId($_code)?>" id="<?= $this->getFieldId($_code)?>" name="<?= $this->getFieldName($_code)?>" value="<?= $this->escapeHtml($this->getObject()->getData($_code)) ?>" title="<?= Mage::helper('core')->quoteEscape($this->__($_attribute->getStoreLabel())) ?>" class="input-text <?= $_attribute->getFrontend()->getClass() ?>" <?= $this->getFieldParams() ?> />
    <datalist id="<?= $this->getDatalistId($_code)?>">
        <?php $options = $this->getOptions() ?>
        <?php $value = $this->getObject()->getData($_code) ?>
        <?php foreach ($options as $option): ?>
            <option value="<?= $option['label'] ?>"></option>
        <?php endforeach ?>
    </datalist>
</div>
