<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Catalog_Product_Price $this */
?>
<?php $_product = $this->getProduct() ?>
<?php $_finalPrice = $_product->getFinalPrice() ?>
<?php $_finalPriceInclTax = $_product->getFinalPrice() ?>
<?php $_weeeTaxAmount = 0; ?>
<?php
if ($_product->getPriceType() == 1) {
    $_weeeTaxAmount = Mage::helper('weee')->getAmount($_product);
    if (Mage::helper('weee')->typeOfDisplay($_product, [1,2,4])) {
        $_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForRenderer($_product, null, null, null, true);
    }
}
$isMAPTypeOnGesture = Mage::helper('catalog')->isShowPriceOnGesture($_product);
$canApplyMAP  = Mage::helper('catalog')->canApplyMsrp($_product);
?>
<?php if ($_product->getCanShowPrice() !== false):?>
<div class="price-box">
    <p class="price-as-configured">
        <span class="price-label"><?= $this->helper('bundle')->__('Price as configured') ?>:</span>
        <?php if (!$this->getWithoutPrice()): ?>
        <span<?php if (!$isMAPTypeOnGesture && $canApplyMAP): ?> style="display:none"<?php endif ?> class="full-product-price">
        <?php if ($this->helper('tax')->displayBothPrices()): ?>
        <span class="price-tax">
            <span class="price-excluding-tax">
                <span class="label"><?= Mage::helper('tax')->__('Excl. Tax:') ?></span>
                <span class="price" id="price-excluding-tax-<?= $_product->getId() ?><?= $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?= Mage::helper('core')->currency($_finalPrice,true,false) ?>
                <?php endif ?>
                </span>
            </span>
            <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, [2, 1, 4])): ?>
                <span class="weee">(<small>
                    <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_product, [2, 4])): ?>
                            <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                        <?php else: ?>
                            <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                        <?php endif ?>

                        <?= $_weeeSeparator ?>
                        <?= $_weeeTaxAttribute->getName() ?>: <?= Mage::helper('core')->currency($amount, true, true) ?>
                        <?php $_weeeSeparator = ' + '; ?>
                    <?php endforeach ?>
                </small>)</span>
            <?php endif ?>
            <span class="price-including-tax">
                <span class="label"><?= Mage::helper('tax')->__('Incl. Tax:') ?></span>
                <span class="price" id="price-including-tax-<?= $_product->getId() ?><?= $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?= Mage::helper('core')->currency($_finalPriceInclTax,true,false) ?>
                <?php endif ?>
                </span>
            </span>
        </span>
        <?php else: ?>
        <span class="price" id="product-price-<?= $_product->getId() ?><?= $this->getIdSuffix() ?>">
            <?php if (!$canApplyMAP): ?>
                <?= Mage::helper('core')->currency($_finalPrice,true,false) ?>
            <?php endif ?>
        </span>
        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, [2, 1, 4])): ?>
            <span class="weee">(<small>
                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                    <?php if ($this->helper('tax')->displayPriceIncludingTax()): ?>
                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                    <?php else: ?>
                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                    <?php endif ?>

                    <?= $_weeeSeparator ?>
                    <?= $_weeeTaxAttribute->getName() ?>: <?= Mage::helper('core')->currency($amount, true, true) ?>
                    <?php $_weeeSeparator = ' + '; ?>
                <?php endforeach ?>
            </small>)</span>
        <?php endif ?>
    <?php endif ?>
    </span>
    <?php endif ?>
    </p>
</div>
<?php endif ?>
<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        bundle.reloadPrice();
    });
</script>
<?php endif ?>
