<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Catalog_Block_Product_View $this */
?>
<?php
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
?>
<?php if (count($_tierPrices) > 0): ?>
    <ul class="tier-prices product-pricing">
    <?php foreach($_tierPrices as $_price): ?>
        <li><?= $this->__('Buy %1$s with %2$s discount each', $_price['price_qty'], '<strong class="benefit">'.($_price['price']*1).'%</strong>') ?></li>
    <?php endforeach ?>
    </ul>
<?php endif ?>
