<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_CatalogRule_Block_Product_Widget_OnSale $this */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-onsale">
    <div class="widget-title">
        <h2><?= $this->__('On Sale') ?></h2>
    </div>
    <div class="widget-products">
        <?= $this->getPagerHtml() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
        <?php $i=0; ?>
        <ul class="products-grid products-grid--max-<?= $_columnCount ?>-col-widget">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <div>
                        <?php $_imgSize = 210; ?>
                        <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                            <img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize) ?>" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize * 2) ?> 2x" alt="<?= $this->stripTags($_product->getName(), null, true) ?>">
                        </a>
                        <ul>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_product, false); ?>
                                <li>
                                    <a href="#" data-url="<?= $_wishlistUrl ?>" data-params="<?= $_params ?>"
                                       class="link-wishlist" title="<?= $this->__('Add to Wishlist') ?>"
                                       onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')">
                                        <?= $this->getIconSvg('heart') ?>
                                        <?= $this->__('Add to Wishlist') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                <li>
                                    <a href="#" title="<?= $this->__('Add to Compare') ?>"
                                       onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                                        <?= $this->getIconSvg('scale') ?>
                                        <?= $this->__('Add to Compare') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                        </ul>
                    </div>
                    <div class="product-info">
                        <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?= $this->getPriceHtml($_product, true, '-widget-onsale-grid') ?>
                        <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                    </div>
                    <div class="actions">
                        <?php if(Mage::getStoreConfigFlag('catalog/frontend/enable_addtocart_in_product_listings')): ?>
                            <?php if ($_product->isSaleable()): ?>
                                <button type="button"
                                        title="<?= $this->quoteEscape($this->__('Add to Cart')) ?>"
                                        class="button btn-cart"
                                        onclick="customFormSubmit(
                                                '<?= $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                                '<?= $_params ?>',
                                                'post')">
                                    <?= $this->__('Add to Cart') ?>
                                </button>
                            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                <a title="<?= $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?= $_product->getProductUrl() ?>"><?= $this->__('View Details') ?></a>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                            <?php endif ?>
                        <?php endif ?>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
<?php endif ?>
