<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Checkout_Block_Onepage_Payment_Methods $this */
?>
<dl class="sp-methods" id="checkout-payment-method-load">
<?php if ($this->getQuote()->isVirtual()): ?>
<?= $this->getLayout()->createBlock('checkout/onepage_payment_methods')
    ->setTemplate('checkout/onepage/payment/methods.phtml')
    ->toHtml() ?>
<?php endif ?>
</dl>
