<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<dl class="sp-methods" id="checkout-payment-method-load">
   <!-- Content dynamically loaded. Content from the methods.phtml is loaded during the ajax call -->
</dl>
