<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?= $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?= $this->getBackButtonHtml() ?>
                <?= $this->getResetButtonHtml() ?>
                <span style="display:none;" id="formButtons">
                <?= $this->getSaveButtonHtml() ?>
                </span>
            </td>
        </tr>
    </table>
</div>

<div style="display:none;" id="formContainer">
<?= $this->getFormHtml() ?>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>
