<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Form_Banktransfer $this */
?>
<?php if ($instructions = $this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?= $this->getMethodCode() ?>-instructions-content agreement-content">
                <?= nl2br($instructions) ?>
            </div>
        </li>
    </ul>
<?php endif ?>
