<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Form_Checkmo $this */
?>
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?= $this->__('Make Check payable to:') ?></label>
            <?= $this->escapeHtml($this->getMethod()->getPayableTo()) ?>
        </li>
        <?php endif ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?= Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?= nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif ?>
    </ul>
<?php endif ?>
