<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Payment_Block_Form_Checkmo $this */
?>
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?= $this->__('Make Check payable to:') ?></label>
            <?= $this->escapeHtml($this->getMethod()->getPayableTo()) ?>
        </li>
        <?php endif ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?= Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?= nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif ?>
    </ul>
<?php endif ?>
