<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Payment_Block_Form_Purchaseorder $this */
?>
<ul class="form-list" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
    <li>
        <label for="po_number" class="required"><?= $this->__('Purchase Order Number') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?= $this->quoteEscape($this->__('Purchase Order Number')) ?>" class="input-text required-entry" value="<?= $this->escapeHtml($this->getInfoData('po_number')) ?>">
        </div>
    </li>
</ul>
