<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Customer_Edit_Renderer_Attribute_Group $this */
?>
<?php
$_element = $this->getElement();
$_note = $_element->getNote();
$_trId = $_element->getHtmlContainerId();
$_class = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
<tr<?php if ($_trId): ?> id="<?= $_trId ?>"<?php endif ?>>
    <?php if ($_element->getType() == 'hidden'): ?>
    <td colspan="2" class="hidden"><?= trim($_element->getElementHtml()) ?></td>
    <?php else: ?>
    <td class="label<?= $_class ? " {$_class}-label" : '' ?>"><?= trim($_element->getLabelHtml()) ?></td>
    <td class="<?= $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?= $_class ? " {$_class}-value" : '' ?>">
        <?= trim($_element->getElementHtml()) ?>
        <?php if ($this->getDisableAutoGroupChangeAttribute()): ?>
            <br/>
            <input id="<?= $this->escapeHtml($this->getDisableAutoGroupChangeCheckboxElementId()) ?>" name="<?= $this->escapeHtml($this->getDisableAutoGroupChangeCheckboxElementName()) ?>" type="checkbox"<?php if ($this->getDisableAutoGroupChangeCheckboxState() == 'checked') :?> checked="checked"<?php endif ?> value="1"/>
            <label for="<?= $this->escapeHtml($this->getDisableAutoGroupChangeCheckboxElementId()) ?>"><?= $this->escapeHtml($this->getDisableAutoGroupChangeCheckboxLabel()) ?></label>
        <?php endif ?>
        <?php if ($_note): ?>
            <p class="note<?= $_class ? " {$_class}-note" : '' ?>" id="note_<?= $_element->getId() ?>"><span><?= $_note ?></span></p>
        <?php endif ?>
    </td>
    <?php endif ?>
</tr>
<?php endif ?>
