<?php
$helper = Mage::helper('maho_captcha');
if (!$helper->isEnabled()) return;
?><script>
    let mahoCaptchaRenderedElements = [];
    function mahoCaptchaInject(element) {
        if (mahoCaptchaRenderedElements.includes(element.id)) return;
        mahoCaptchaRenderedElements.push(element.id);

        if (mahoCaptchaRenderedElements.length <= 1) {
            element.insertAdjacentHTML('beforeend', '<altcha-widget challengeurl="https://your-challenge-url" hidelogo hidefooter></altcha-widget>');
            let script = document.createElement('script');
            script.type = 'module';
            script.src = 'https://eu.altcha.org/js/latest/altcha.min.js';
            document.head.appendChild(script);
        } else {
            mahoCaptchaRender();
        }
    }
    function mahoCaptchaRender() {
        let element = document.getElementById(mahoCaptchaRenderedElements[mahoCaptchaRenderedElements.length - 1]);
    }
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll('<?= $helper->getFrontendSelectors() ?>').forEach(function (element) {
            if (element.matches(':focus-within')) {
                mahoCaptchaInject(element);
                return;
            }
            element.addEventListener('focusin', function (event) {
                mahoCaptchaInject(element);
            });
        });
    });
</script>