<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Adminhtml_Catalog_Product_Composite_Fieldset_Downloadable $this */

$linksPurchasedSeparately = $this->getLinksPurchasedSeparately();
$skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck();
?>

<?php if (($this->getProduct()->isSaleable() || $skipSaleableCheck) && $this->hasLinks()):?>
<?php $links = $this->getLinks(); ?>
<?php $isRequired = $this->getLinkSelectionRequired(); ?>
<?php $requiredIds = []; ?>
<div>
    <h4><?= Mage::helper('catalog')->__('Downloadable Information') ?></h4>
    <div class="product-options">
        <dl>
            <dt>
                <label<?= $isRequired ? ' class="required"' : '' ?>><?= $this->escapeHtml($this->getLinksTitle()) ?></label>
            </dt>
            <dd>
                <ul id="downloadable-links-list" class="options-list">
                <?php foreach ($links as $link): ?>
                    <?php if ($isRequired) $requiredIds[] = $link->getId() ?>
                    <li>
                    <?php if ($linksPurchasedSeparately): ?>
                        <input type="checkbox" class="checkbox<?= $isRequired ? ' validate-one-required-by-name' : '' ?> product-downloadable-link" name="links[]" id="links_<?= $link->getId() ?>" value="<?= $link->getId() ?>" <?= $this->getLinkCheckedValue($link) ?> price="<?= $this->getCurrencyPrice($link->getPrice()) ?>"/>
                    <?php endif ?>
                        <span class="label">
                            <label for="links_<?= $link->getId() ?>"><?= $this->escapeHtml($link->getTitle()) ?></label>
                        <?php if ($link->getSampleFile() || $link->getSampleUrl()): ?>
                            <?php $onclick = $this->getIsOpenInNewWindow() ? ' onclick="this.target=\'_blank\'"' : '' ?>
                            (<a href="<?= $this->getLinkSamlpeUrl($link) ?>"<?= $onclick ?>><?= Mage::helper('downloadable')->__('sample') ?></a>)
                        <?php endif ?>
                        <?php if ($linksPurchasedSeparately): ?>
                            <?= $this->getFormattedLinkPrice($link) ?>
                        <?php endif ?>
                        </span>
                    </li>
                <?php endforeach ?>
                </ul>
            <?php if ($isRequired): ?>
                <span class="links-advice-container"></span>
            <?php endif ?>
            </dd>
        </dl>
    </div>
</div>

<?php if (count($requiredIds)): ?>
<script type="module">
    const requiredIds = <?= json_encode($requiredIds) ?>;
    for (const linkId of requiredIds) {
        for (const inputEl of document.querySelectorAll(`input[id="links_${linkId}"]`)) {
            inputEl.adviceContainer = inputEl.closest('dd').querySelector('.links-advice-container');
            inputEl.callbackFunction = 'validateDownloadableCallback';
        }
    }
    window.validateDownloadableCallback = (elmId, result) => {
        const container = document.getElementById('downloadable-links-list');
        if (result === 'failed') {
            container.classList.remove('validation-passed');
            container.classList.add('validation-failed');
        } else {
            container.classList.remove('validation-failed');
            container.classList.add('validation-passed');
        }
    }
</script>
<?php endif ?>
<?php endif ?>
