<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<span class="widget widget-category-link-inline"><a <?= $this->getLinkAttributes() ?>><span><?= $this->escapeHtml($this->getAnchorText()) ?></span></a></span>
