<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Paypal_Block_Payflow_Link_Iframe $this */
?>
<div id="iframe-warning" class="warning-message">
    <?= $this->__('Please do not refresh the page until you complete payment.') ?>
</div>
<iframe id="payflow-link-iframe" style="display:none;" scrolling="no" frameborder="0" border="0"
        src="<?= $this->getFrameActionUrl() ?>" height="610" width="100%"></iframe>
<script type="text/javascript">
    const headers = document.querySelectorAll('#' + checkout.accordion.container.getAttribute('id') + ' .section');
    headers.forEach(header => {
        header.classList.remove('allow');
    });

    document.getElementById('payflow-link-iframe').addEventListener('load', function() {
        const iframe = document.getElementById('payflow-link-iframe');
        const warning = document.getElementById('iframe-warning');
        const reviewSubmit = document.getElementById('checkout-review-submit');

        if (iframe) {
            iframe.style.display = 'block';
        }

        if (warning) {
            warning.style.display = 'block';
        }

        checkout.loadWaiting = 'review';
        checkout.setLoadWaiting(false);

        if (checkout.accordion.currentSection == 'opc-review' && reviewSubmit) {
            reviewSubmit.style.display = 'none';
        }
    });
</script>
