<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Paypal_Block_Payflow_Link_Form $this
 */
?>
<ul id="payment_form_<?= $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li>
    <?= $this->__('You will be required to enter your payment details after you place an order.') ?>
    </li>
</ul>
