<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html_Breadcrumbs $this */
?>
<?php if($crumbs && is_array($crumbs)): ?>
<div class="breadcrumbs" role="navigation" aria-label="<?= $this->__('Breadcrumbs') ?>">
    <ul>
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?= $_crumbName ?>">
            <?php if($_crumbInfo['link']): ?>
                <a href="<?= $_crumbInfo['link'] ?>" title="<?= $this->escapeHtml($_crumbInfo['title']) ?>"><?= $this->escapeHtml($_crumbInfo['label']) ?></a>
            <?php elseif($_crumbInfo['last']): ?>
                <strong><?= $this->escapeHtml($_crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?= $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>
