<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html_CookieNotice $this */
?>
<?php if (Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<div class="global-site-notice notice-cookie" id="notice-cookie-block">
    <div class="notice-inner">
        <div class="notice-text"><?= $this->getCookieRestrictionBlockContent() ?></div>
        <div class="actions"><button class="button" onclick="allowSaveCookie()"><?= $this->__('Allow') ?></button></div>
    </div>
</div>
<script>
    function allowSaveCookie() {
        Mage.Cookies.set('<?= Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>', '<?= Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds()?>', new Date(new Date().getTime() + <?= Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));
        window.location.reload();
    }

    document.getElementById('notice-cookie-block').style.display = 'block';
</script>
<?php endif ?>
