<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Footer $this
 */
?>
<div class="footer-container">
    <div class="footer">
        <?= $this->getChildHtml() ?>
        <p class="bugs"><?= $this->__('Help Us to Keep OpenMage Healthy') ?> - <a href="https://github.com/OpenMage/magento-lts/issues" onclick="this.target='_blank'"><strong><?= $this->__('Report All Bugs') ?></strong></a> <?= Mage::getMahoVersion() ?></p>
        <address><?= $this->getCopyright() ?></address>
    </div>
</div>
