<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2020-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html_Footer $this */
?>
<footer class="footer-container" role="contentinfo">
    <div class="footer">
        <?= $this->getChildHtml() ?>
        <address><?= $this->getCopyright() ?></address>
    </div>
</footer>
