<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html_Head $this */
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>" />
<title><?= $this->getTitle() ?></title>
<meta name="description" content="<?= htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?= htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?= htmlspecialchars($this->getRobots()) ?>" />
<?= $this->getHreflang() ?>
<?= $this->helper('page')->getFaviconHtml() ?>
<?= $this->getCssJsHtml() ?>
<?= $this->getChildHtml() ?>
<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getIncludes() ?>
