<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html_Header $this */
?>
<header id="header" class="page-header" role="banner">
    <div class="page-header-container skip-links">
        <div>
            <a href="#header-nav" class="skip-link skip-nav offcanvas-trigger" data-offcanvas-target="#nav" data-offcanvas-title="<?= $this->__('Menu') ?>" title="<?= $this->__('Menu') ?>">
                <?= $this->getIconSvg('menu-2') ?>
                <span class="label"><?= $this->__('Menu') ?></span>
            </a>

            <a class="logo" href="<?= $this->getUrl('') ?>" title="<?= $this->__('Go to Home Page') ?>" aria-label="<?= $this->__('%s - Go to Home Page', $this->getLogoAlt()) ?>">
                <img src="<?= $this->getLogoSrc() ?>" alt="<?= $this->getLogoAlt() ?>" width="<?= $this->getLogoWidth() ?>" height="<?= $this->getLogoHeight() ?>" />
            </a>
        </div>

        <?= $this->getChildHtml('topSearch') ?>

        <div>
            <?= $this->getChildHtml('store_language') ?>
            <?= $this->getChildHtml('currency_switcher') ?>

            <a href="<?= $this->helper('customer')->getAccountUrl() ?>" class="skip-link skip-account" title="<?= $this->__('Account') ?>">
                <?= $this->getIconSvg('user') ?>
                <span class="label"><?= $this->__('Account') ?></span>
            </a>

            <?php if ($this->isModuleOutputEnabled('Mage_Wishlist') && Mage::getStoreConfig('wishlist/general/active')): ?>
            <a href="<?= $this->helper('customer')->getWishlistUrl() ?>" class="skip-link skip-wishlist" title="<?= $this->__('Wishlist') ?>">
                <?= $this->getIconSvg('heart') ?>
                <span class="label"><?= $this->__('Wishlist') ?></span>
            </a>
            <?php endif ?>

            <div class="header-minicart" role="region" aria-label="<?= $this->__('Shopping Cart') ?>">
                <?= $this->getChildHtml('minicart_head') ?>
            </div>
        </div>
    </div>

    <div id="minicart-container-mobile" class="header-minicart"></div>
    <nav id="header-nav" class="skip-content" role="navigation" aria-label="<?= $this->__('Main Navigation') ?>">
        <?= $this->getChildHtml('topMenu') ?>
    </nav>
</header>

<?= $this->getChildHtml('topContainer') ?>
