<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html_Header $this */
?>
<header id="header" class="page-header-minimal" role="banner">
    <a class="logo" href="<?= $this->getUrl('') ?>" title="<?= $this->__('Go to Home Page') ?>" aria-label="<?= $this->__('%s - Go to Home Page', $this->getLogoAlt()) ?>">
        <img src="<?= $this->getLogoSrc() ?>" alt="<?= $this->getLogoAlt() ?>" width="<?= $this->getLogoWidth() ?>" height="<?= $this->getLogoHeight() ?>">
    </a>
</header>
