<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Html_Notices $this */
?>
<?php if ($this->displayDemoNotice()): ?>
    <aside class="global-site-notice demo-notice" role="complementary" aria-label="<?= $this->__('Store Notice') ?>">
        <div class="notice-inner"><?= $this->getDemoNoticeContent() ?></div>
    </aside>
<?php endif ?>
