<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Core_Block_Template $this */
?>
<dialog id="offcanvas">
    <div class="offcanvas-header">
        <div class="offcanvas-title"></div>
        <button class="offcanvas-close" aria-label="<?= $this->__('Close') ?>" type="button"><?= $this->getIconSvg('x') ?></button>
    </div>
    <div class="offcanvas-content"></div>
</dialog>
