<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<dialog id="offcanvas">
    <div class="offcanvas-header">
        <div class="offcanvas-title"></div>
        <button class="offcanvas-close" aria-label="<?= $this->__('Close') ?>" type="button"><?= $this->getIconSvg('x') ?></button>
    </div>
    <div class="offcanvas-content"></div>
</dialog>
