<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @deprecated after 1.4.0.1
 */
?>
<?php if($toplinks && is_array($toplinks)): ?>
<ul class="links">
    <?= $this->getChildHtml() ?>
    <?php foreach($toplinks as $_toplink): ?>
    <li<?php if($_toplink['first']||$_toplink['last']): ?> class="<?php if($_toplink['first']): ?>first<?php endif ?><?php if($_toplink['last']): ?> last<?php endif ?>"<?php endif ?> <?= $_toplink['liParams'] ?>><?= $_toplink['beforeText'] ?><a <?= $_toplink['aParams'] ?>><?= $_toplink['innerText'] ?></a><?= $_toplink['afterText'] ?></li>
    <?php endforeach ?>
</ul>
<?php endif ?>
