<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @deprecated  after 1.4.0.0-alpha3
 */

/**
 * This template is for generic wrapper purposes, including ajax.updater loaded blocks
 *
 * Usage in layout xml files:
 * <block type="core/template" template="page/html/wrapper.phtml">
 *    <action method="setId"><id>some-custom-identificator</id></action>
 *
 *    <!-- optional -->
 *    <action method="setTag"><tag>span</tag></action> <!-- div is used if not specified -->
 *    <action method="setParams"><params>class="custom-class"</params></action>
 *
 *    <!-- insert wrapped blocks here -->
 * </block>
 */
?>
<?php $_tag = $this->hasTag() ? $this->getTag() : "div" ?>
<<?= $_tag ?> id="<?= $this->getId() ?>" <?= $this->getParams() ?>>
<?= $this->getChildHtml() ?>
</<?= $_tag ?>>
