<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?= $_code ?>" style="display:none;">
    <li>
        <label for="<?= $_code ?>_ba_agreement_id" class="required"><em>*</em><?= $this->__('Billing Agreement') ?></label>
        <div class="input-box">
            <select id="<?= $_code ?>_ba_agreement_id" name="payment[<?= $this->getTransportBAId() ?>]" class="required-entry">
                <option value="">--<?= $this->__('Please Select') ?>--</option>
            <?php foreach ($this->getBillingAgreements() as $id => $referenceId): ?>
                <option value="<?= $id ?>"><?= $this->escapeHtml($referenceId) ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
</ul>
