<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Totalbar $this */
?>
<?php if(count($this->getTotals()) > 0): ?>
<div class="sales-totalbar box">
<?php foreach( $this->getTotals() as $total ): ?>
    <div class="<?= $total['grand'] ? 'grand-total' : '' ?>">
        <span><?= $total['label'] ?></span>
        <span><?= $total['value'] ?></span>
    </div>
<?php endforeach ?>
</div>
<?php endif ?>
