<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Edit_Form $this */
?>

<div class="content-header">
    <h3><?= $this->escapeHtml($this->getHeader()) ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getCategoryId() ? $this->getDeleteButtonHtml() : '' ?>
        <?= $this->getAdditionalButtonsHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php if($this->hasStoreRootCategory()): ?>
    <?= $this->getTabsHtml() ?>
<?php else: ?>
<div class="messages warning-msg">
    <?= Mage::helper('catalog')->__('Set root category for this store in the <a href="%s">configuration</a>', $this->getStoreConfigurationUrl()) ?>
</div>
<?php endif ?>

<form id="category_edit_form" action="<?= $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
    <input type="hidden" name="category_products" id="in_category_products" value="" />
    <div id="category_tab_content"></div>
</form>

<script>
    window.categoryInfo = <?= $this->getCategoryInfoJson() ?>;
    window.productsInfo = <?= $this->getProductsInfoJson() ?>;
</script>
