<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Newsletter_Block_Subscribe $this */
?>
<div class="block block-subscribe">
    <div class="block-title"><?= $this->__('Newsletter') ?></div>
    <form action="<?= $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" autocomplete="off">
        <?= $this->getBlockHtml('formkey') ?>
        <div class="block-content">
            <div class="input-box">
                <label for="newsletter" class="visually-hidden"><?= $this->__('Sign Up for Our Newsletter:') ?></label>
               <input type="email" autocomplete="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?= $this->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" aria-required="true">
            </div>
            <div class="actions">
                <button type="submit" title="<?= $this->quoteEscape($this->__('Subscribe')) ?>" class="button"><?= $this->__('Subscribe') ?></button>
            </div>
        </div>
    </form>
    <script>
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    </script>
</div>
