<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Newsletter_Block_Subscribe $this */
?>
<div class="block block-subscribe">
    <div class="block-title"><?= $this->__('Newsletter') ?></div>
    <form action="<?= $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <?= $this->getBlockHtml('formkey') ?>
        <div class="block-content">
            <div class="input-box">
                <label for="newsletter" class="visually-hidden"><?= $this->__('Sign Up for Our Newsletter:') ?></label>
               <input type="email" autocomplete="on" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?= $this->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" aria-required="true" />
            </div>
            <div class="actions">
                <button type="submit" title="<?= $this->quoteEscape($this->__('Subscribe')) ?>" class="button"><?= $this->__('Subscribe') ?></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    </script>
</div>
