<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_Paypal
 */

/** @var Maho_Paypal_Block_Payment_Info $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
<table class="data-table">
    <?php foreach ($_specificInfo as $label => $value): ?>
    <tr>
        <th><?= $this->escapeHtml($label) ?></th>
        <td><?= $this->escapeHtml($value) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
