<?php
/**
 * Maho
 *
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @var Maho_ContentVersion_Block_Adminhtml_Version_Tab $this
 */
?>
<?php if ($this->hasVersions()): ?>
    <?= $this->getGridHtml() ?>
<?php else: ?>
    <p><?= $this->__('No versions available. Versions are created when content is saved.') ?></p>
<?php endif ?>
