<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */ ?>

<div class="order-page">

<!-- title 'n' actions -->
<div class="page-title recurring-profiles-title">
    <h1><?= $this->__('Recurring Profile # %s', $this->escapeHtml($this->getReferenceId())) ?></h1>
</div>
<div class="title-buttons recurring-profiles-title-buttons">
    <?php $confirm = $this->jsQuoteEscape($this->getConfirmationMessage()) ?>
    <?php if ($this->getCanCancel()): ?>
        <form action="<?= $this->escapeUrl($this->getCancelUrl()) ?>" method="post" onsubmit="return confirm('<?= $confirm ?>')">
            <?= $this->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Cancel')) ?>" class="button"><?= $this->__('Cancel') ?></button>
        </form>
    <?php endif ?>
    <?php if ($this->getCanSuspend()): ?>
        <form action="<?= $this->escapeUrl($this->getSuspendUrl()) ?>" method="post" onsubmit="return confirm('<?= $confirm ?>')">
            <?= $this->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Suspend')) ?>" class="button"><?= $this->__('Suspend') ?></button>
        </form>
    <?php endif ?>
    <?php if ($this->getCanActivate()): ?>
        <form action="<?= $this->escapeUrl($this->getActivateUrl()) ?>" method="post" onsubmit="return confirm('<?= $confirm ?>')">
            <?= $this->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Activate')) ?>" class="button"><?= $this->__('Activate') ?></button>
        </form>
    <?php endif ?>
    <?php if ($this->getCanUpdate()): ?>
        <form action="<?= $this->escapeUrl($this->getUpdateUrl()) ?>" method="post" onsubmit="return confirm('<?= $confirm ?>')">
            <?= $this->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $this->quoteEscape($this->__('Get Update')) ?>" class="button"><?= $this->__('Get Update') ?></button>
        </form>
    <?php endif ?>
</div>

<div class="recurring-profiles-messages">
    <?= $this->getMessagesBlock()->toHtml() ?>
</div>

<!-- info tabs -->
<?php $infoTabs = $this->getChildGroup('info_tabs'); ?>
<dl class="order-info">
    <dt><?= $this->__('About This Profile:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
        <?php foreach ($infoTabs as $block): ?>
            <?php if ($this->getObjectData($block, 'is_view_current')): ?>
                <li class="current"><strong><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></strong></li>
            <?php else: ?>
                <li><a href="<?= $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>"><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></a></li>
            <?php endif ?>
        <?php endforeach ?>
        </ul>
    </dd>
</dl>

<!-- info blocks in 2 columns -->
<?php for ($i = 1; $i <= 5; $i++): ?>
    <?php $infoBlocks = $this->getChildGroup("info_blocks_row_{$i}"); ?>
    <?php if ($infoBlocks): ?>
<div class="col2-set order-info-box">
        <?php for ($j = 1; $j <= 2; $j++): ?>
            <?php foreach ($infoBlocks as $alias => $block): ?>
<?php if ($j == $this->getObjectData($block, 'view_column')): ?>
    <div class="col-<?= $j ?>">
        <div class="info-box">
            <div class="box-title">
                <h2><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></h2>
            </div>
            <div class="box-content">
                <?= $this->getChildHtml($alias) ?: $this->__('No information available.') ?>
            </div>
        </div>
    </div>
<?php endif ?>
            <?php endforeach ?>
        <?php endfor ?>
</div>
    <?php endif ?>
<?php endfor ?>

<!-- table data block -->
<?php $table = $this->getChild('table') ?>
<?php if ($table): ?>
<div>
    <h2 class="table-caption"><?= $this->escapeHtml($this->getObjectData($table, 'view_label')) ?></h2>
    <?= $this->getChildHtml('table') ?>
</div>
<?php endif ?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->__('Back to Recurring Profiles') ?></a></p>
    </div>
</div>
