<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @var Mage_Page_Block_Js_Cookie $this
 */
?>

<script type="text/javascript">
    Mage.Cookies.path   = '<?= $this->jsQuoteEscape($this->getPath()) ?>';
    Mage.Cookies.domain = '<?= $this->jsQuoteEscape($this->getDomain()) ?>';
</script>
