<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @var Mage_Page_Block_Js_Cookie $this
 */
?>

<script type="text/javascript">
//<![CDATA[
Mage.Cookies.path     = '<?= Mage::helper('core')->jsQuoteEscape($this->getPath()) ?>';
Mage.Cookies.domain   = '<?= Mage::helper('core')->jsQuoteEscape($this->getDomain()) ?>';
//]]>
</script>
