<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @var Mage_Page_Block_Js_Cookie $this
 */
?>

<script>
    Mage.Cookies.path   = '<?= $this->jsQuoteEscape($this->getPath()) ?>';
    Mage.Cookies.domain = '<?= $this->jsQuoteEscape($this->getDomain()) ?>';
</script>
