<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_GoogleAnalytics_Block_Ga $this */
$_helper = $this->helper('googleanalytics');
?>
<?php if (!$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php if ($_helper->isUseAnalytics4()): ?>
        <?php $_gaAccountId = $_helper->getAccountId() ?>
        <!-- BEGIN GOOGLE ANALYTICS 4 CODE -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $_gaAccountId ?>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            <?= $this->_getPageTrackingCode($_gaAccountId) ?>
            <?= $this->_getEnhancedEcommerceDataForAnalytics4() ?>
        </script>
        <!-- END GOOGLE ANALYTICS 4 CODE -->
    <?php endif ?>
<?php endif ?>
