<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Customer_System_Config_Validatevat $this */
?>
<script type="text/javascript">
//<![CDATA[
    function validateVat() {
        var elem = $('<?= $this->getHtmlId() ?>');

        params = {
            country: $('general_store_information_merchant_country').value,
            vat: $('general_store_information_merchant_vat_number').value
        };

        new Ajax.Request('<?= $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                result = '<?= $this->jsQuoteEscape($this->__('VAT Number is Invalid')) ?>';
                try {
                    response = response.responseText;
                    if (response == 1) {
                        result = '<?= $this->jsQuoteEscape($this->__('VAT Number is Valid')) ?>';
                        elem.removeClassName('fail').addClassName('success')
                    } else {
                        elem.removeClassName('success').addClassName('fail')
                    }
                } catch (e) {
                    elem.removeClassName('success').addClassName('fail')
                }
                $('validation_result').update(result);
            }
        });
    }
//]]>
</script>
<button onclick="javascript:validateVat(); return false;" class="scalable" type="button" id="<?= $this->getHtmlId() ?>">
    <span id="validation_result"><?= $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
