<?php
/**
 * Maho
 *
 * @package    Mage_Sales
 * @copyright  Copyright (c) 2025-2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Mage_Sales_Model_Order_Pdf_Items_Creditmemo_Default $this */
$item = $this->getItem();
?>

<td class="col-products">
    <div class="item-name"><?= $this->escapeHtml($this->getItemName()) ?></div>

    <?php if ($options = $this->getItemOptions()): ?>
    <div class="item-options">
        <?php foreach ($options as $option): ?>
        <div class="option">
            <span class="option-label"><?= $this->escapeHtml($option['label']) ?>:</span>
            <span class="option-value"><?= $this->escapeHtml($option['value']) ?></span>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</td>

<td class="col-sku text-right">
    <?= $this->escapeHtml($this->getSku()) ?>
</td>

<td class="col-price text-right">
    <?php $prices = $this->getItemPricesForDisplay() ?>
    <?php foreach ($prices as $priceData): ?>
        <?php if (isset($priceData['label'])): ?>
            <div class="price-label"><?= $this->escapeHtml($priceData['label']) ?></div>
        <?php endif; ?>
        <div class="price-value"><?= $priceData['subtotal'] ?></div>
    <?php endforeach; ?>
</td>

<td class="col-discount text-right">
    <?= $this->formatPrice(-$item->getDiscountAmount()) ?>
</td>

<td class="col-qty text-right">
    <?= $this->getItemQty() * 1 ?>
</td>

<td class="col-tax text-right">
    <?= $this->formatPrice($this->getItemTax()) ?>
</td>

<td class="col-subtotal text-right">
    <?= $this->formatPrice($this->getItemTotalInclTax()) ?>
</td>
