<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_CatalogInventory_Block_Stockqty_Composite
 * @var Mage_CatalogInventory_Block_Stockqty_Composite $this
 */
?>
<?php if($this->isMsgVisible()): ?>
    <p class="availability-only">
        <a href="#" id="<?= $this->getPlaceholderId() ?>" title="<?= $this->quoteEscape($this->__('Only %s left', ($this->getStockQty()))) ?>"><?= $this->__('Only %s left', "<strong>{$this->getStockQty()}</strong>") ?></a>
    </p>
    <table id="<?= $this->getDetailsPlaceholderId() ?>" class="availability-only-details no-display">
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?= $this->__('Product Name') ?></th>
                <th class="a-center"><?= $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getChildProducts() as $childProduct) : ?>
            <?php $childProductStockQty = $this->getProductStockQty($childProduct); ?>
            <?php if ($childProductStockQty > 0) : ?>
                <tr>
                    <td><?= $childProduct->getName() ?></td>
                    <td class="a-center"><?= $childProductStockQty ?></td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">
        document.getElementById('<?= $this->getPlaceholderId() ?>').addEventListener('click', function(event){
            this.classList.toggle('expanded');
            document.getElementById('<?= $this->getDetailsPlaceholderId() ?>').classList.toggle('no-display');
            event.preventDefault();
            event.stopPropagation();
        });
    </script>
<?php endif ?>
