<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/**
 * @see Mage_CatalogInventory_Block_Stockqty_Default
 * @var Mage_CatalogInventory_Block_Stockqty_Default $this
 */
?>
<?php if($this->isMsgVisible()): ?>
    <p class="availability-only">
        <span title="<?= $this->__('Only %s left', ($this->getStockQty())) ?>"><?= $this->__('Only %s left', "<strong>{$this->getStockQty()}</strong>") ?></span>
    </p>
<?php endif ?>
