<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Checkout_Cart_Item_Renderer $this */
?>
<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
$_deleteUrl = $this->getDeleteUrlCustom(false);
?>
<tr>
<td class="product-cart-image"><a href="<?= $this->getProductUrl() ?>" class="product-image"
       title="<?= $this->escapeHtml($this->getProductName()) ?>"><img
            src="<?= $this->getProductThumbnail()->resize(180) ?>"
            alt="<?= $this->escapeHtml($this->getProductName()) ?>"/></a>
</td>
<td class="product-cart-info">
    <h2 class="product-name"><a
            href="<?= $this->getProductUrl() ?>"><?= $this->escapeHtml($this->getProductName()) ?></a>
    </h2>

    <div class="product-cart-sku">
        <span class="label"><?= $this->__('SKU') ?>:</span> <?= $this->escapeHtml($_item->getSku()) ?>
    </div>

    <?php if ($_options = $this->getOptionList()): ?>
        <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <div class="product-cart-sku<?php if (isset($_formatedOptionValue['full_view'])): ?> truncated<?php endif ?>">
                <span class="label"><?= $this->escapeHtml($_option['label']) ?>:</span>
                <?= $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <span class="label"><?= $this->escapeHtml($_option['label']) ?>:</span>
                    <?= $_formatedOptionValue['full_view'] ?>
                </div>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
        <div class="product-cart-sku">
            <span class="label"><?= $this->escapeHtml($this->getLinksTitle()) ?>:</span>
            <?= implode(', ', array_map(fn($link) => (string) $this->escapeHtml($link->getTitle()), $links)) ?>
        </div>
    <?php endif ?>
    <!-- EOF downloadable -->

    <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <div class="shopping-cart-item-message <?= $message['type'] ?>">
                * <?= $this->escapeHtml($message['text']) ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</td>
<?php if ($canApplyMsrp): ?>
    <td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif ?>>
        <span class="cart-price">
            <span class="cart-msrp-unit"><?= $this->__('See price before order confirmation.') ?></span>
            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
            <a id="<?= $helpLinkId ?>" href="#"
               class="map-help-link"><?= $this->__("What's this?") ?></a>
            <script type="text/javascript">
                Catalog.Map.addHelpLink('<?= $helpLinkId ?>', "<?= $this->jsQuoteEscape($this->__("What's this?")) ?>");
            </script>
        </span>
    </td>
<?php else: ?>


    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" data-rwd-label="<?= $this->__('Price') ?>" data-rwd-tax-label="<?= $this->__('Excl. Tax') ?>">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('eunit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <span class="cart-price">
                    <?php endif ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                    <?php endif ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="eunit-item-tax-details<?= $_item->getId() ?>"
                         style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total"
                             onclick="taxToggle('eunit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?= Mage::helper('weee')->__('Total') ?>
                                : <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?></span>
                        </div>
                    <?php endif ?>
                <?php endif ?>
        </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" data-rwd-label="<?= $this->__('Price') ?>" data-rwd-tax-label="<?= $this->__('Incl. Tax') ?>">
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('unit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <span class="cart-price">
                    <?php endif ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                    <?php endif ?>

                </span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="unit-item-tax-details<?= $_item->getId() ?>"
                         style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total"
                             onclick="taxToggle('unit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                                : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?></span>
                        </div>
                    <?php endif ?>
                <?php endif ?>
        </td>
    <?php endif ?>
<?php endif ?>
<td class="product-cart-actions" data-rwd-label="<?= $this->__('Qty') ?>">
    <input type="text" pattern="\d*(\.\d+)?" name="cart[<?= $_item->getId() ?>][qty]" value="<?= $this->getQty() ?>"
           data-cart-item-id="<?= $this->jsQuoteEscape($_item->getSku()) ?>"
           size="4" title="<?= $this->quoteEscape($this->__('Qty')) ?>" class="input-text qty" maxlength="12" />

    <button type="submit" data-cart-item-update name="update_cart_action" value="update_qty" title="<?= $this->quoteEscape($this->__('Update')) ?>" class="button btn-update"><?= $this->__('Update') ?>
    </button>
</td>
<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal') ?>">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <div class="cart-tax-total"
             onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <div class="cart-price">
                <?php endif ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                    <?php endif ?>
                <?php endif ?>

            </div>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="esubtotal-item-tax-details<?= $_item->getId() ?>"
                     style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total"
                         onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?= Mage::helper('weee')->__('Total') ?>
                            : <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?></span>
                    </div>
                <?php endif ?>
            <?php endif ?>
    </td>
<?php endif ?>
<?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal') ?>">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <div class="cart-tax-total"
             onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <div class="cart-price">
                <?php endif ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif ?>
                <?php endif ?>

            </div>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="subtotal-item-tax-details<?= $_item->getId() ?>"
                     style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total"
                         onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                            : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?></span>
                    </div>
                <?php endif ?>
            <?php endif ?>
    </td>
<?php endif ?>
<td class="product-cart-remove">
    <?php if ($isVisibleProduct): ?>
        <a href="<?= $this->getConfigureUrl() ?>" title="<?= $this->quoteEscape($this->__('Edit item parameters')) ?>">
            <?= $this->getIconSvg('edit') ?>
            <?= $this->__('Edit') ?>
        </a>
    <?php endif ?>

    <?php if ($this->helper('wishlist')->isAllowInCart() && $isVisibleProduct) : ?>
        <a href="<?= $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()) ?>" class="link-wishlist use-ajax" title="<?= $this->quoteEscape($this->__('Move to wishlist')) ?>">
            <?= $this->getIconSvg('heart') ?>
            <?= $this->__('Move to wishlist') ?>
        </a>
    <?php endif ?>

    <a href="#" title="<?= $this->quoteEscape($this->__('Remove Item')) ?>"
       onclick="customFormSubmit('<?= $_deleteUrl ?>', '<?= $_params ?>', 'post')">
        <?= $this->getIconSvg('x') ?>
        <?= $this->__('Remove Item') ?>
    </a>
</td>
</tr>
