<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset $this */
/** @var \Maho\Data\Form\Element\Fieldset $_element */
?>
<?php $_element = $this->getElement() ?>
<div class="rule-tree">
    <div class="entry-edit-head">
        <h4><?= $_element->getLegend() ?></h4>
    </div>
    <fieldset id="<?= $_element->getHtmlId() ?>" <?= $_element->serialize(['class']) ?>>
    <?php if ($_element->getComment()): ?>
        <p class="comment"><?= $this->escapeHtml($_element->getComment()) ?></p>
    <?php endif ?>
    <?= $_element->getChildrenHtml() ?>
    </fieldset>
</div>
<script>
var <?= $_element->getHtmlId() ?> = new VarienRulesForm('<?= $_element->getHtmlId() ?>', '<?= $this->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()): ?>
    <?= $_element->getHtmlId() ?>.setReadonly(true);
<?php endif ?>
</script>
