<?php
/**
 * SPDX-FileCopyrightText: 2025-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Promo_Catalog_Edit_Js $this */
?>
<script>
function hideShowSubproductOptions()
{
    if (document.getElementById('rule_sub_is_enable').value == 1) {
        document.getElementById('rule_sub_simple_action').closest('tr').style.display = '';
        document.getElementById('rule_sub_discount_amount').closest('tr').style.display = '';
        document.getElementById('rule_sub_discount_amount').classList.add('required-entry', 'validate-not-negative-number');
    } else {
        document.getElementById('rule_sub_simple_action').closest('tr').style.display = 'none';
        document.getElementById('rule_sub_discount_amount').closest('tr').style.display = 'none';
        document.getElementById('rule_sub_discount_amount').classList.remove('required-entry', 'validate-not-negative-number');
    }

    return true;
}

document.addEventListener('DOMContentLoaded', hideShowSubproductOptions);
</script>
