<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Creditmemo_Create_Adjustments $this */
?>
<?php $_source  = $this->getSource() ?>
<?php if ($_source): ?>
    <tr>
        <td class="label"><?= $this->getShippingLabel() ?></td>
        <td><input type="text" name="creditmemo[shipping_amount]" value="<?= $this->getShippingAmount() ?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="shipping_amount" /></td>
    </tr>
    <tr>
        <td colspan="2"><div id="shipping_amount_adv"></div></td>
    </tr>
    <tr>
        <td class="label"><?= $this->helper('sales')->__('Adjustment Refund') ?></td>
        <td><input type="text" name="creditmemo[adjustment_positive]" value="<?= $_source->getBaseAdjustmentPositive()*1 ?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="adjustment_positive" /></td>
    </tr>
    <tr>
        <td colspan="2"><div id="adjustment_positive_adv"></div></td>
    </tr>
    <tr>
        <td class="label"><?= $this->helper('sales')->__('Adjustment Fee') ?></td>
        <td><input type="text" name="creditmemo[adjustment_negative]" value="<?= $_source->getBaseAdjustmentNegative()*1 ?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="adjustment_negative"/></td>
    </tr>
    <tr>
        <td colspan="2"><div id="adjustment_negative_adv"></div></td>
    </tr>
    <?php
        $orderId = $this->getSource()->getOrderId();
        $invoiceId = $this->getRequest()->getParam('invoice_id');
        $updateUrl = $this->getUrl('*/*/updateQty', ['order_id' => $orderId, 'invoice_id' => $invoiceId]);
    ?>
    <tr>
        <td colspan="2" class="a-right" style="padding-top:10px">
            <button type="button" class="scalable" onclick="submitAndReloadArea(document.getElementById('creditmemo_item_container'),'<?= $updateUrl ?>')">
                <span><span><span><?= $this->helper('sales')->__('Update Totals') ?></span></span></span>
            </button>
        </td>
    </tr>
    <script type="text/javascript">
        Validation.addAllThese([
            ['not-negative-amount', '<?= $this->jsQuoteEscape($this->helper('sales')->__('Please enter positive number in this field.')) ?>', function(v) {
                if (v.length) {
                    return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                } else {
                    return true;
                }
            }]
        ]);

    const shippingAmount = document.getElementById('shipping_amount');
    const adjustmentPositive = document.getElementById('adjustment_positive');
    const adjustmentNegative = document.getElementById('adjustment_negative');

    if (shippingAmount) {
        const shippingAmountAdv = document.getElementById('shipping_amount_adv');
        if (shippingAmountAdv) {
            shippingAmount.adviceContainer = shippingAmountAdv;
        }
        unblockSubmit('shipping_amount');
    }
    if (adjustmentPositive) {
        const adjustmentPositiveAdv = document.getElementById('adjustment_positive_adv');
        if (adjustmentPositiveAdv) {
            adjustmentPositive.adviceContainer = adjustmentPositiveAdv;
        }
        unblockSubmit('adjustment_positive');
    }
    if (adjustmentNegative) {
        const adjustmentNegativeAdv = document.getElementById('adjustment_negative_adv');
        if (adjustmentNegativeAdv) {
            adjustmentNegative.adviceContainer = adjustmentNegativeAdv;
        }
        unblockSubmit('adjustment_negative');
    }

    function unblockSubmit(id) {
        const element = document.getElementById(id);
        if (element) {
            element.addEventListener('focus', function(event) {
                const disabledUpdateButtons = document.querySelectorAll('button.scalable.update-button.disabled');
                if (disabledUpdateButtons.length > 0) {
                    enableElements('submit-button');
                }
            });
        }
    }
    </script>
<?php endif ?>
