<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Widget_Grid_Massaction $this */
?>
<div id="<?= $this->getHtmlId() ?>">
<table cellspacing="0" cellpadding="0" class="massaction">
<tr>
    <td><span class="massaction-label"><?= $this->__('Select') ?>:</span>
        <?php if ($this->getUseSelectAll()):?>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.selectAll()"><?= $this->__('All') ?></a>
        <span class="separator">|</span>
        <?php endif ?>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.selectVisible()"><?= $this->__('Visible') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.unselectAll()"><?= $this->__('None') ?></a>
        <span class="separator">|</span>
        <span id="<?= $this->getHtmlId() ?>-count">0</span> <?= $this->__('selected') ?>
    </td>
    <td>
        <div class="massaction-actions">
            <div class="entry-edit">
                <?php if ($this->getHideFormElement() !== true):?>
                <form action="" id="<?= $this->getHtmlId() ?>-form" method="post">
                <?php endif ?>
                    <?= $this->getBlockHtml('formkey') ?>
                    <fieldset>
                        <span class="field-row">
                            <label for="<?= $this->getHtmlId() ?>-select"><?= $this->__('Actions') ?></label>
                            <select id="<?= $this->getHtmlId() ?>-select" class="required-entry select absolute-advice local-validation">
                                <option value=""></option>
                                <?php foreach($this->getGroupedItems() as $key => $group): ?>
                                    <?php if ($key === 'default'): ?>
                                        <?php foreach($group as $_item): ?>
                                            <option value="<?= $_item->getId() ?>"<?= ($_item->getSelected() ? ' selected="selected"' : '')?>><?= $_item->getLabel() ?></option>
                                        <?php endforeach ?>
                                    <?php elseif ($key === 'grouped'): ?>
                                        <?php foreach($group as $label => $_massGroup): ?>
                                            <optgroup label="<?= $this->quoteEscape($label) ?>">
                                                <?php foreach($_massGroup as $_item): ?>
                                                    <option value="<?= $_item->getId() ?>"<?= ($_item->getSelected() ? ' selected="selected"' : '')?>><?= $_item->getLabel() ?></option>
                                                <?php endforeach ?>
                                            </optgroup>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </span>
                        <span class="outer-span" id="<?= $this->getHtmlId() ?>-form-hiddens"></span>
                        <span class="outer-span" id="<?= $this->getHtmlId() ?>-form-additional"></span>
                        <span class="field-row">
                            <?= $this->getApplyButtonHtml() ?>
                        </span>
                    </fieldset>
                <?php if ($this->getHideFormElement() !== true):?>
                </form>
                <?php endif ?>
            </div>

            <div class="no-display">
            <?php foreach($this->getItems() as $_item): ?>
                <div id="<?= $this->getHtmlId() ?>-item-<?= $_item->getId() ?>-block">
                    <?= $_item->getAdditionalActionBlockHtml() ?>
                </div>
            <?php endforeach ?>
            </div>
        </div>
    </td>
</tr>
</table>
<?php
/** @var Mage_Adminhtml_Block_Widget_Grid $parent */
$parent = $this->getParentBlock();
if (!$parent->canDisplayContainer()): ?>
<script>
    <?= $this->getJsObjectName() ?>.setGridIds('<?= $this->getGridIdsJson() ?>');
</script>
<?php endif ?>
</div>
