<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?= $header ?></h3></td>
            <td class="form-buttons">
                <button class="scalable add" onclick="window.location.href='<?= $createUrl ?>'"><span><span><span><?= Mage::helper('tax')->__('Add New Tax Rule') ?></span></span></span></button>
            </td>
        </tr>
    </table>
</div>
