<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <h3><?= $header ?></h3>
    <div class="form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
        <?= $this->getDeleteButtonHtml() ?>
    </div>
</div>
<?php if ($form): ?>
<?= $form->toHtml() ?>
<script>
    window.wigetForm = new varienForm('<?= $form->getForm()->getId() ?>');
</script>
<?php endif ?>
