<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Attribute_Set_Toolbar_Add $this */
?>
<div class="content-header">
    <h3><?= $this->_getHeader() ?></h3>
    <div class="form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </div>
</div>
<?= $this->getFormHtml() ?>
<script type="text/javascript">
    var addSet = new varienForm('<?= $this->getFormId() ?>');
</script>
