<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Attribute_Set_Toolbar_Add $this */
?>
<div class="content-header">
    <h3><?= $this->_getHeader() ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?= $this->getFormHtml() ?>
<script>
    var addSet = new varienForm('<?= $this->getFormId() ?>');
</script>
