<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Address_Form $this */
?>
<div>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?= Mage::helper('sales')->__('Changing address information will not recalculate shipping, tax or other order amount.') ?></li>
        </ul>
    </li>
</ul>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend"><?= $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?= $this->getForm()->toHtml() ?>
    </div>
</div>
