<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Template_Links_Block $this */
?>
<li<?php if($this->getIsFirst()||$this->getIsLast()): ?> class="<?php if($this->getIsFirst()): ?>first<?php endif ?><?php if($this->getIsLast()): ?> last<?php endif ?>"<?php endif ?> <?= $this->getLiParams() ?>><?= $this->getBeforeText() ?><a href="<?= $this->getLinkUrl() ?>" title="<?= $this->getTitle() ?>" <?= $this->getAParams() ?>><?= $this->getLabel() ?></a><?= $this->getAfterText() ?></li>
