<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Template_Links_Block $this */
?>
<li<?php if($this->getIsFirst()||$this->getIsLast()): ?> class="<?php if($this->getIsFirst()): ?>first<?php endif ?><?php if($this->getIsLast()): ?> last<?php endif ?>"<?php endif ?> <?= $this->getLiParams() ?>><?= $this->getBeforeText() ?><a href="<?= $this->getLinkUrl() ?>" title="<?= $this->getTitle() ?>" <?= $this->getAParams() ?>><?= $this->getLabel() ?></a><?= $this->getAfterText() ?></li>
