<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2023 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Page_Block_Template_Links $this */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<div class="links">
    <?php if($this->getTitle()): ?>
    <div class="block-title"><?= $this->__($this->getTitle()) ?></div>
    <?php endif ?>
    <ul<?php if($this->getName()): ?> id="<?= $this->getName() ?>"<?php endif ?>>
        <?php foreach($_links as $_link): ?>
            <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
                <?= $_link->toHtml() ?>
            <?php else: ?>
                <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif ?><?php if($_link->getIsLast()): ?> last<?php endif ?>"<?php endif ?> <?= $_link->getLiParams() ?>><?= $_link->getBeforeText() ?><a href="<?= $_link->getUrl() ?>" title="<?= $_link->getTitle() ?>" <?= $_link->getAParams() ?>><?= $_link->getLabel() ?></a><?= $_link->getAfterText() ?></li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>
