<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Tag_Edit $this */
?>
<?= $this->getFormInitScripts() ?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml('header') ?></p>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
    <?= $this->getStoreSwitcherHtml() ?>
<?php endif ?>

<form action="<?= $this->getFormActionUrl() ?>" method="post" id="edit_form">
    <?= $this->getFormHtml() ?>

    <?= $this->getTagAssignAccordionHtml() ?>

<script>
    function saveAndContinueEdit(url) {
        var tagForm = new varienForm('edit_form');
        tagForm.submit(url);
    }
</script>

</form>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="content-buttons form-buttons"><?= $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif ?>
<script>
    var editForm = new varienForm('edit_form', '<?= $this->getValidationUrl() ?>');
</script>
<?= $this->getFormScripts() ?>
<?= $this->getAcordionsHtml() ?>
