<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Core_Block_Template $this */
?>
<div class="block block-banner">
    <div class="block-content">
        <?php if(strtolower(substr($this->getLinkUrl(), 0, 4)) === 'http'): ?>
            <a href="<?= $this->getLinkUrl() ?>" title="<?= $this->quoteEscape($this->__($this->getImgAlt())) ?>">
        <?php elseif($this->getLinkUrl()): ?>
            <a href="<?= $this->getUrl($this->getLinkUrl()) ?>" title="<?= $this->quoteEscape($this->__($this->getImgAlt())) ?>">
        <?php endif ?>
            <img src="<?= $this->getSkinUrl($this->getImgSrc()) ?>"<?php if(!$this->getLinkUrl()): ?> title="<?= $this->quoteEscape($this->__($this->getImgAlt())) ?>"<?php endif ?> alt="<?= $this->quoteEscape($this->__($this->getImgAlt())) ?>" />
        <?php if($this->getLinkUrl()): ?>
        </a>
        <?php endif ?>
    </div>
</div>
