<?php
/**
 * Maho
 *
 * @package    Maho_Revocation
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Maho_Revocation_Block_Footer $this */
?>
<div class="revocation-footer-button">
    <a href="<?= $this->getRevocationUrl() ?>"><?= $this->escapeHtml($this->getButtonLabel()) ?></a>
</div>
