<?php
/**
 * Maho
 *
 * @package    Maho_Revocation
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Maho_Revocation_Block_Order_Link $this */
?>
<span class="separator">|</span>
<a href="<?= $this->getRevocationUrl() ?>" class="link-revocation"><?= Mage::helper('revocation')->__('Revoke this contract') ?></a>
