<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Core_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
<style>
    html, body { height: 100%; background: white; }
</style>
</head>
<body id="html-body">
<div id="preview" class="cms-revision-preview">
    <div class="toolbar">
        <?php if (!Mage::app()->isSingleStoreMode()): ?>
        <div class="switcher">
            <?= $this->getChildHtml('store_switcher') ?>
            <button class="button"><?= $this->__('Preview') ?></button>
        </div>
        <?php endif ?>
    </div>
    <iframe name="preview_iframe" id="preview_iframe" frameborder="0"></iframe>
    <?= $this->getChildHtml('preview_form') ?>
</div>

<script type="module">
    const previewEl = document.getElementById('preview');
    const previewForm = document.getElementById('preview_form');
    const previewIframe = document.getElementById('preview_iframe');

    previewEl.querySelector('.toolbar .switcher .button').addEventListener('click', () => {
        window.showLoader(previewEl);
        previewForm.target = previewIframe.id
        previewForm.submit();
    });
    previewIframe.addEventListener('load', () => {
        window.hideLoader();
    });
</script>
</body>
</html>
