<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Core_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
<style type="text/css">
    html,body { height:100%; }
</style>
</head>
<body id="html-body" style="background:#fff;">
<div id="preview" class="cms-revision-preview">
    <div class="toolbar">
        <?php if (!Mage::app()->isSingleStoreMode()) :?>
        <p class="switcher">
            <?= $this->getChildHtml('store_switcher') ?>
            <button class="button" onclick="preview();"><span><?= $this->__('Preview') ?></span></button>
        </p>
        <?php endif ?>
    </div>
    <iframe name="preview_iframe" id="preview_iframe" frameborder="0"></iframe>
    <?= $this->getChildHtml('preview_form') ?>
</div>
<div id="loading-mask" style="display:none">
    <div class="backdrop"></div>
    <p class="loader" id="loading_mask_loader">
        <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= $this->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>"/><br/><?= Mage::helper('adminhtml')->__('Please wait...') ?>
    </p>
</div>

<script type="text/javascript">
//<![CDATA[
var previewForm = $('preview_form');
var previewIframe = $('preview_iframe');

function preview() {
    previewForm.writeAttribute('target', previewIframe.readAttribute('id'));
    blockPreview();
    previewForm.submit();
}

function blockPreview() {
    showLoader($('preview'));
}

function unBlockPreview() {
    hideLoader();
}

Event.observe(window, 'load', preview);
Event.observe(previewIframe, 'load', unBlockPreview);
//]]>
</script>
</body>
</html>
