<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Store_Switcher $this */
?>

<?php if ($websites = $this->getWebsites()): ?>
<label for="store_switcher"><?= $this->__('Choose Store View:') ?></label>
<select name="store_switcher" id="store_switcher">
    <?php foreach ($websites as $website): ?>
        <?php $showWebsite=false; ?>
        <?php foreach ($website->getGroups() as $group): ?>
            <?php $showGroup=false; ?>
            <?php foreach ($this->getStores($group) as $store): ?>
                <?php if ($showWebsite == false): ?>
                    <?php $showWebsite = true; ?>
                    <optgroup label="<?= $this->escapeHtml($website->getName()) ?>"></optgroup>
                <?php endif ?>
                <?php if ($showGroup == false): ?>
                    <?php $showGroup = true; ?>
                    <optgroup label="&nbsp;&nbsp;&nbsp;<?= $this->escapeHtml($group->getName()) ?>">
                <?php endif ?>
                <option value="<?= $store->getId() ?>"<?php if($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?= $this->escapeHtml($store->getName()) ?></option>
            <?php endforeach ?>
            <?php if ($showGroup): ?>
                </optgroup>
            <?php endif ?>
        <?php endforeach ?>
    <?php endforeach ?>
</select>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const storeSwitcher = document.getElementById('store_switcher');
    if (storeSwitcher) {
        storeSwitcher.addEventListener('change', (event) => {
            const previewStoreIdElement = document.getElementById('preview_store_id');
            if (previewStoreIdElement) {
                previewStoreIdElement.value = event.target.value;
            }
        });
    }
});
</script>
<?php endif ?>
