<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Install_Block_End $this */
?>
<div class="page-head">
    <h3><?= $this->__("You're All Set") ?>!</h3>
</div>
<?php if ($this->getIframeSourceUrl()): ?>
    <iframe id="iframe_box" src="<?= $this->getIframeSourceUrl() ?>" frameborder="0" width="650" height="600"></iframe>
<?php endif ?>
<p><?= $this->__('Get ready to experience Open-Source eCommerce Evolved.') ?></p>
<p>
    <button class="form-button" onclick="window.open('<?= $this->getUrl('') ?>')" type="button"><?= $this->__('Go to Frontend') ?></button>&nbsp;&nbsp;
    <button class="form-button" onclick="window.open('<?= $this->getUrl('adminhtml') ?>')" type="button"><?= $this->__('Go to Backend') ?></button>
</p>
