<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Install_Block_Locale $this */
?>
<div class="page-head">
    <h3><?= $this->__('Localization') ?></h3>
</div>

<div class="messages">
    <?= $this->getMessagesBlock()->toHtml() ?>
</div>

<form action="<?= $this->getPostUrl() ?>" method="get" id="form-validate">
<div class="form-list">
    <ul>
        <li>
            <label for="locale"><?= $this->__('Locale') ?> <span class="required">*</span></label>
            <?= $this->getLocaleSelect() ?>
        </li>
        <li>
            <label for="timezone"><?= $this->__('Time Zone') ?> <span class="required">*</span></label>
            <?= $this->getTimezoneSelect() ?>
        </li>
        <li>
            <label for="currency"><?= $this->__('Default Currency') ?> <span class="required">*</span></label>
            <?= $this->getCurrencySelect() ?>
        </li>
    </ul>
</div>
<div class="button-set">
    <p class="required">* <?= $this->__('Required Fields') ?></p>
    <button class="form-button" type="submit"><span><?= $this->__('Continue') ?></span></button>
</div>
</form>
<script>
    const localeSelect = document.querySelector('#locale');
    localeSelect?.addEventListener('change', () => {
        const params = new URLSearchParams({
            timezone: document.querySelector('#timezone').value,
            currency: document.querySelector('#currency').value
        });
        window.location.href = `<?= $this->getChangeUrl() ?>locale/${localeSelect.value}/?${params}`;
    });
</script>
