<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Multi $this */
$option = $this->getOption();
$selections = $option->getSelections();
?>
<dt>
    <label for="bundle-option-<?= $option->getId() ?>"<?= $option->getRequired() ? ' class="required"' : '' ?>>
        <?= $this->escapeHtml($option->getTitle()) ?>
    </label>
</dt>
<dd>
    <div class="input-box">
    <?php if (count($selections) == 1 && $option->getRequired()): ?>
        <?= $this->getSelectionQtyTitlePrice($selections[0]) ?>
        <input type="hidden" name="bundle_option[<?= $option->getId() ?>]" value="<?= $selections[0]->getSelectionId() ?>"/>
    <?php else: ?>
        <select onchange="bundle.changeSelection(this)" multiple="multiple" size="5" id="bundle-option-<?= $option->getId() ?>" name="bundle_option[<?= $option->getId() ?>][]" class="bundle-option-<?= $option->getId() ?><?= $option->getRequired() ? ' required-entry' : '' ?> bundle-option-select multiselect change-container-classname">
        <?php if (!$option->getRequired()): ?>
            <option value=""><?= $this->__('None') ?></option>
        <?php endif ?>
        <?php foreach ($selections as $selection): ?>
            <?php $selected = $this->_isSelected($selection) ? ' selected="selected"' : '' ?>
            <?php $disabled = !$selection->isSaleable() ? ' disabled="disabled"' : '' ?>
            <option value="<?= $selection->getSelectionId() ?>"<?= $selected ?><?= $disabled ?>><?= $this->getSelectionQtyTitlePrice($selection, false) ?></option>
        <?php endforeach ?>
        </select>
    <?php endif ?>
    </div>
</dd>
