<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Radio $this */
$option = $this->getOption();
$selections  = $option->getSelections();
$default     = $option->getDefaultSelection();
list($defaultQty, $canChangeQty) = $this->_getDefaultValues();
$tierPriceHtml = '';
?>
<dt>
    <label<?= $option->getRequired() ? ' class="required"' : '' ?>>
        <?= $this->escapeHtml($option->getTitle()) ?>
    </label>
</dt>
<dd>
    <div class="input-box">
        <?php if ($this->_showSingle()): ?>
            <?= $this->getSelectionTitlePrice($selections[0]) ?>
            <?php if ($selections[0]->getSelectionCanChangeQty()): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($selections[0]); ?>
        <?php endif ?>
        <input type="hidden" name="bundle_option[<?= $option->getId() ?>]" value="<?= $selections[0]->getSelectionId() ?>" />
    <?php else: ?>
        <ul class="options-list">
        <?php if (!$option->getRequired()): ?>
            <li>
                <input type="radio" class="radio" id="bundle-option-<?= $option->getId() ?>" name="bundle_option[<?= $option->getId() ?>]"<?= $default?->isSalable() ? '' : ' checked="checked"' ?> value="" onclick="bundle.changeSelection(this)"/>
                <span class="label"><label for="bundle-option-<?= $option->getId() ?>"><?= $this->__('None') ?></label></span>
            </li>
        <?php endif ?>
        <?php foreach ($selections as $selection): ?>
            <?php if ($selection->getSelectionCanChangeQty() && $this->_isSelected($selection)): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($selection); ?>
            <?php endif ?>
                <li>
                <?php $checked = $this->_isSelected($selection) ? ' checked="checked"' : '' ?>
                <?php $disabled = !$selection->isSaleable() ? ' disabled="disabled"' : '' ?>
                <input type="radio" class="change-container-classname radio bundle-option-<?= $option->getId() ?><?= $option->getRequired() ? ' validate-one-required-by-name' : '' ?>" id="bundle-option-<?= $option->getId() ?>-<?= $selection->getSelectionId() ?>" name="bundle_option[<?= $option->getId() ?>]"<?= $checked ?><?= $disabled ?> value="<?= $selection->getSelectionId() ?>" onclick="bundle.changeSelection(this)"/>
                <span class="label"><label for="bundle-option-<?= $option->getId() ?>-<?= $selection->getSelectionId() ?>"><?= $this->getSelectionTitlePrice($selection) ?></label></span>
            <?php if ($option->getRequired()): ?>
                <?= $this->setValidationContainer("bundle-option-{$option->getId()}-{$selection->getSelectionId()}", "bundle-option-{$option->getId()}-container") ?>
            <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
        <div id="bundle-option-<?= $option->getId() ?>-container"></div>
    <?php endif ?>
    </div>
    <span id="bundle-option-<?= $option->getId() ?>-tier-prices"> <?= $tierPriceHtml ?></span>
    <span class="qty-holder">
        <label for="bundle-option-<?= $option->getId() ?>-qty-input"><?= $this->__('Qty:') ?>&nbsp;</label>
        <input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)"<?= !$canChangeQty ? ' disabled="disabled"' : '' ?> id="bundle-option-<?= $option->getId() ?>-qty-input" class="input-text qty<?= !$canChangeQty ? ' qty-disabled' : '' ?>" type="text" pattern="\d*(\.\d+)?" name="bundle_option_qty[<?= $option->getId() ?>]" value="<?= $defaultQty ?>"/>
    </span>
</dd>
