<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Select $this */
$option = $this->getOption();
$selections = $option->getSelections();
list($defaultQty, $canChangeQty) = $this->_getDefaultValues();
$tierPriceHtml = '';
?>
<dt>
    <label for="bundle-option-<?= $option->getId() ?>"<?= $option->getRequired() ? ' class="required"' : '' ?>>
        <?= $this->escapeHtml($option->getTitle()) ?>
    </label>
</dt>
<dd>
    <div class="input-box">
    <?php if ($this->_showSingle()): ?>
        <?= $this->getSelectionTitlePrice($selections[0]) ?>
        <?php if ($selections[0]->getSelectionCanChangeQty()): ?>
            <?php $tierPriceHtml = $this->getTierPriceHtml($selections[0]); ?>
        <?php endif ?>
        <input type="hidden" name="bundle_option[<?= $option->getId() ?>]" value="<?= $selections[0]->getSelectionId() ?>"/>
    <?php else: ?>
        <select onchange="bundle.changeSelection(this)" id="bundle-option-<?= $option->getId() ?>" name="bundle_option[<?= $option->getId() ?>]" class="bundle-option-<?= $option->getId() ?><?= $option->getRequired() ? ' required-entry' : '' ?> bundle-option-select change-container-classname">
            <option value=""><?= $this->__('Choose a selection...') ?></option>
        <?php /** @var Mage_Catalog_Model_Product $selection */ ?>
        <?php foreach ($selections as $selection): ?>
            <?php $selected = $this->_isSelected($selection) ? ' selected="selected"' : '' ?>
            <?php $disabled = !$selection->isSaleable() ? ' disabled="disabled"' : '' ?>
            <?php if ($selection->getSelectionCanChangeQty() && $this->_isSelected($selection)): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($selection); ?>
            <?php endif ?>
            <option value="<?= $selection->getSelectionId() ?>"<?= $selected ?><?= $disabled ?>><?= $this->getSelectionTitlePrice($selection, false) ?></option>
        <?php endforeach ?>
        </select>
    <?php endif ?>
    </div>
    <span id="bundle-option-<?= $option->getId() ?>-tier-prices"> <?= $tierPriceHtml ?></span>
    <span class="qty-holder">
        <label for="bundle-option-<?= $option->getId() ?>-qty-input"><?= $this->__('Qty:') ?>&nbsp;</label>
        <input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)"<?= !$canChangeQty ? ' disabled="disabled"' : '' ?> id="bundle-option-<?= $option->getId() ?>-qty-input" class="input-text qty<?= !$canChangeQty ? ' qty-disabled' : '' ?>" type="text" pattern="\d*(\.\d+)?" name="bundle_option_qty[<?= $option->getId() ?>]" value="<?= $defaultQty ?>"/>
    </span>
</dd>
