<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_CatalogSearch_Block_Autocomplete $this */
$numResults = count($this->getLoadedProductCollection());
$productList = $this->getLayout()->createBlock('core/template')
    ->setLoadedProductCollection($this->getLoadedProductCollection())
    ->setTemplate('catalog/product/list.phtml');
?>
<?php if ($numResults): ?>
    <a class="view-all" href="ciaociao">
        <?= $this->__("View all %s results", $numResults) ?>
    </a>
<?php endif ?>

<div class="results-list">
    <?= $productList->toHtml() ?>
</div>
