<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_CatalogSearch_Block_Term $this */
?>
<div class="page-title">
    <h1><?= $this->__('Popular Search Terms') ?></h1>
</div>
<?php if(count($this->getTerms()) > 0): ?>
    <ul class="tags-list">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li><a href="<?= $this->getSearchUrl($_term) ?>" style="font-size:<?= $_term->getRatio()*70+75 ?>%;"><?= $this->escapeHtml($_term->getName()) ?></a></li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?= $this->__('There are no search terms available.') ?></p>
<?php endif ?>
