<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Paypal_Block_Express_Review $this */
?>
<div class="fieldset" id="shipping-method-container">
<?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
        <?php if ($groups = $this->getShippingRateGroups()):?>
            <?php $currentRate = $this->getCurrentShippingRate(); ?>
            <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
            <?php if (!$currentRate):?>
                <option value=""><?= $this->__('Please select a shipping method...') ?></option>
            <?php endif ?>
            <?php foreach ($groups as $code => $rates):?>
                <optgroup label="<?= $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                <?php foreach ($rates as $rate):?>
                    <option value="<?= $this->renderShippingRateValue($rate) ?>"<?= ($currentRate === $rate) ? ' selected="selected"' : ''  ?>>
                        <?= $this->renderShippingRateOption($rate) ?>
                    </option>
                <?php endforeach ?>
                </optgroup>
            <?php endforeach ?>
            </select>
        <?php else: ?>
            <p><strong><?= $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
        <?php endif ?>
<?php else: ?>
    <p><strong><?= $this->renderShippingRateOption($this->getCurrentShippingRate()) ?></strong></p>
<?php endif ?>
</div>
<div style="display:none" id="shipping_method_update"><p><?= $this->__('Please update order data to get shipping methods and rates') ?></p></div>
