<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Catalog_Block_Product_New $this */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<h2 class="subtitle"><?= $this->__('New Products') ?></h2>
<?php $_columnCount = $this->getColumnCount(); ?>
<?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item">
                <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->escapeHtml($_product->getName()) ?>" class="product-image"><img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(270) ?> 2x" width="135" height="135" alt="<?= $this->escapeHtml($_product->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->escapeHtml($_product->getName()) ?>"><?= $this->escapeHtml($_product->getName()) ?></a></h3>
                <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?= $this->getPriceHtml($_product, true, '-new') ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button"
                                title="<?= $this->quoteEscape($this->__('Add to Cart')) ?>"
                                class="button btn-cart"
                                onclick="customFormSubmit(
                                        '<?= $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                        '<?= $_params ?>',
                                        'post')">
                            <?= $this->__('Add to Cart') ?>
                        </button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_product, false); ?>
                            <li>
                                <a href="#" data-url="<?= $_wishlistUrl ?>" data-params="<?= $_params ?>"
                                   class="link-wishlist" title="<?= $this->__('Add to Wishlist') ?>"
                                   onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')">
                                    <?= $this->getIconSvg('heart') ?>
                                    <?= $this->__('Add to Wishlist') ?>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                            <li>
                                <a href="#" title="<?= $this->__('Add to Compare') ?>"
                                   onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                                    <?= $this->getIconSvg('scale') ?>
                                    <?= $this->__('Add to Compare') ?>
                                </a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
