<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/**
 * Template for displaying product price at catalog, sidebars and RSS feeds
 *
 * @var Mage_Catalog_Block_Product_Price $this
 */

/** @var Mage_Catalog_Model_Product $_product */
$_product = $this->getProduct();
/** @var Mage_Catalog_Helper_Data $_catalogHelper */
$_catalogHelper = $this->helper('catalog');
?>
<?php if ($this->getIsRssFeed()): ?>
<div class="price-box map-info">
    <?php if ($_catalogHelper->canApplyMsrp($_product)): ?>
        <a href="<?= $_product->getProductUrl() ?>"><?= $this->__('Click for price') ?></a>
    <?php endif ?>
</div>
<?php else: ?>
<?php
$_msrpPrice = '';
if ($_product->getMsrp()) {
    $_msrpPrice = $this->helper('core')->currency($_product->getMsrp(), true, true);
}
$_mapData = ['title' => $_product->getName()];
if ($_catalogHelper->isShowPriceOnGesture($_product)) {
    $_mapData['price'] = $this->hasRealPriceHtml() ? $this->getRealPriceHtml() : $_product->getRealPriceHtml();
    $_mapData['msrp'] = $_msrpPrice;
    if ($_product->isSalable()) {
        $_mapData['cartUrl'] = $this->getAddToCartUrlCustom($_product, [], false);
    }
    $_mapData['productId'] = $_product->getId();
} else {
    $_mapData['cartUrl'] = $_product->getProductUrl();
}
?>
<div class="price-box map-info">
    <?php if ($_msrpPrice): ?>
        <span class="old-price" id="product-price-<?= $_product->getId() ?><?= $this->getIdSuffix() ?>"><?= $_msrpPrice ?></span>
    <?php endif ?>
    <a href="<?= $_product->getProductUrl() ?>" class="map-link" data-map-popup="<?= $this->escapeHtml(Mage::helper('core')->jsonEncode($_mapData)) ?>"><?= $this->__('Click for price') ?></a>
</div>
<?php endif ?>
