<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for displaying product price at rss feeds pages
 *
 * @var Mage_Catalog_Block_Product_Price $this
 */

/** @var Mage_Catalog_Model_Product $_product */
$_product = $this->getProduct();
?>
<div class="price-box map-info">

    <?php if ($this->helper('catalog')->canApplyMsrp($_product)): ?>
        <a href="<?= $_product->getProductUrl() ?>"><?= $this->__('Click for price') ?></a>
    <?php endif ?>
</div>
