<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Items_Column_Name $this */
?>
<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><span id="order_item_<?= $_item->getId() ?>_title"><?= $this->escapeHtml($_item->getName()) ?></span></h5>
    <div><strong><?= $this->helper('sales')->__('SKU') ?>:</strong> <?= implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getSku()))) ?></div>
    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?= $this->escapeHtml($_option['label']) ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?= $this->getCustomizedOptionValue($_option) ?>
            <?php else: ?>
                <?php
                $optionValue = $_option['value'];
                if (isset($_option['option_type'], $_option['option_value']) && in_array($_option['option_type'], ['date', 'date_time', 'time'])) {
                    $order = $this->getItem()->getOrder();
                    $locale = Mage::app()->getLocale();
                    $locale->setLocaleCode(Mage::getStoreConfig('general/locale/code', $order->getStoreId()));
                    
                    $optionValue = match ($_option['option_type']) {
                        'date' => $locale->date($_option['option_value'], Zend_Date::ISO_8601, null, false)
                            ->toString($locale->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM)),
                        'date_time' => $locale->date($_option['option_value'], Varien_Date::DATETIME_INTERNAL_FORMAT, null, false)
                            ->toString($locale->getDateTimeFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, Mage_Core_Model_Locale::FORMAT_TIME_12H)),
                        'time' => $locale->date($_option['option_value'], Varien_Date::DATETIME_INTERNAL_FORMAT, null, false)
                            ->toString($locale->getTimeFormat(Mage_Core_Model_Locale::FORMAT_TIME_12H)),
                        default => $_option['print_value'],
                    };
                }
                $_option = $this->getFormattedOption($optionValue);
                ?>
                <?= $_option['value'] ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?><span id="<?= $_dots = 'dots' . uniqid()?>"> ...</span><span id="<?= $_id = 'id' . uniqid() ?>"><?= $_option['remainder'] ?></span>
                    <script type="text/javascript">
                    $('<?= $_id ?>').hide();
                    $('<?= $_id ?>').up().observe('mouseover', function(){$('<?= $_id ?>').show();});
                    $('<?= $_id ?>').up().observe('mouseover', function(){$('<?= $_dots ?>').hide();});
                    $('<?= $_id ?>').up().observe('mouseout',  function(){$('<?= $_id ?>').hide();});
                    $('<?= $_id ?>').up().observe('mouseout',  function(){$('<?= $_dots ?>').show();});
                    </script>
                <?php endif ?>
            <?php endif ?>
            </dd>
        <?php endforeach ?>
        </dl>
    <?php endif ?>
    <?= $this->escapeHtml($_item->getDescription()) ?>
<?php endif ?>
