<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Items_Column_Qty $this */
?>
<?php if ($_item = $this->getItem()): ?>
<table cellspacing="0" class="qty-table">
    <tr>
        <td><?= Mage::helper('sales')->__('Ordered') ?></td>
        <td><strong><?= $_item->getQtyOrdered()*1 ?></strong></td>
    </tr>
    <?php if ((float) $_item->getQtyInvoiced()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Invoiced') ?></td>
        <td><strong><?= $_item->getQtyInvoiced()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyShipped()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Shipped') ?></td>
        <td><strong><?= $_item->getQtyShipped()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyRefunded()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Refunded') ?></td>
        <td><strong><?= $_item->getQtyRefunded()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyCanceled()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Canceled') ?></td>
        <td><strong><?= $_item->getQtyCanceled()*1 ?></strong></td>
    </tr>
    <?php endif ?>
</table>
<?php endif ?>
