<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Downloadable_Block_Checkout_Success $this */
?>
<?php if ($this->getOrderHasDownloadable()): ?>
    <?= Mage::helper('downloadable')->__('Go to <a href="%s">My Downloadable Products</a>', $this->getDownloadableProductsUrl()) ?>
<?php endif ?>
