<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?= $this->__('Roles') ?></h3></td>
            <td class="form-buttons">
            <button class="scalable add" onclick="window.location='<?= $this->getAddNewUrl() ?>'"><span><span><span><?= $this->__('Add New Role') ?></span></span></span></button>
            </td>
        </tr>
    </table>
</div>
<?= $this->getGridHtml() ?>
