<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Api_Roles $this */
?>
<div class="content-header">
    <h3><?= $this->__('Roles') ?></h3>
    <p class="content-buttons form-buttons">
        <button class="scalable add" onclick="window.location='<?= $this->getAddNewUrl() ?>'"><span><?= $this->__('Add New Role') ?></span></button>
    </p>
</div>
<?= $this->getGridHtml() ?>
