<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Api_Tab_Userroles $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('User Roles') ?></h4>
    </div>
    <fieldset id="user_roles">
    <?php foreach ($roles as $role): ?>
    <?php
        $checked = false;
        foreach( $user_roles->getItems() as $user_role )
        {
            if( $user_role->getParentId() == $role->getRoleId() ) {
                $checked = true;
            }
        }
    ?>
        <input type="checkbox" value="<?= $role->getRoleId() ?>" <?= ($checked ? "checked" : "") ?> name="roles[]" id="_<?= $role->getRoleId() ?>"> <label for="_<?= $role->getRoleId() ?>" class="normal"><?= $role->getRoleName() ?></label><br>
    <?php endforeach ?>
    </fieldset>
</div>
