<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Api_Buttons $this */
?>
<div class="content-header">
    <h3>
      <?php if($this->getUser()->getUserId()): ?>
      <?php $_userName = $this->getUser()->getFirstname() . ' ' . $this->getUser()->getLastname() ?>
      <?= $this->__("Edit User '%s'", $_userName) ?>
      <?php else: ?>
      <?= $this->__('Add New User') ?>
      <?php endif ?>
    </h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<form action="<?= $this->getUrl('*/*/saveuser') ?>" method="post" id="user_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
    var userForm = new varienForm('user_edit_form');
</script>
