<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
$object = $this->getObject();
?>

<a href="<?= $this->getLinkUrl() ?>" class="<?= $object->getIsDefault() ? 'bold' : '' ?> <?= $this->getClass() ?>" title="<?= $this->__('Id') . ': ' . $object->getId() ?>">
    <?= $this->escapeHtml($object->getName()) ?>
</a>
<br />
<span class="additional-info">(<?= $this->getInfo() ?>)</span>
