<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
$object = $this->getObject();
?>

<a href="<?= $this->getLinkUrl() ?>" class="<?= $object->getIsDefault() ? 'bold' : '' ?> <?= $this->getClass() ?>" title="<?= $this->__('Id') . ': ' . $object->getId() ?>">
    <?= $this->escapeHtml($object->getName()) ?>
</a>
<br>
<span class="additional-info">(<?= $this->getInfo() ?>)</span>
