<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
<?= $this->getPriceHtml($product, empty($options)) ?>
<div class="add-to-cart-alt">
<?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
    <input type="text" class="input-text qty validate-not-negative-number" name="qty[<?= $item->getId() ?>]" value="<?= $this->getAddToCartQty($item) * 1 ?>" />
<?php endif ?>
<?php if ($product->isSaleable()): ?>
    <button type="button"
        title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
        onclick="addWItemToCartCustom(<?= $item->getId() ?>, false);"
        class="button btn-cart">
    <?= $this->__('Add to Cart') ?>
    </button>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock"><span><?= $this->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
    <?php endif ?>
<?php endif ?>
</div>
<?php foreach($this->getSortedChildren() as $childName):?>
    <?= $this->getChildHtml($childName, false) ?>
<?php endforeach ?>
<?php if ($product->isVisibleInSiteVisibility()): ?>
    <p><a class="link-edit" href="<?= $this->getItemConfigureUrl($item) ?>"><?= $this->__('Edit') ?></a></p>
<?php endif ?>
</div>
