<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart $this */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
<?php if ($product->isSaleable()): ?>
    <button type="button"
            title="<?= $this->quoteEscape($this->__('Add to Cart')) ?>"
            onclick="addWItemToCartCustom(<?= $item->getId() ?>, false);"
            class="button btn-cart">
        <?= $this->__('Add to Cart') ?>
    </button>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock">
            <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?= $this->helper('catalog')->__('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="availability out-of-stock">
            <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?= $this->helper('catalog')->__('Out of stock') ?></span>
        </p>
    <?php endif ?>
<?php endif ?>
</div>
<?php if ($product->isVisibleInSiteVisibility()): ?>
    <p><a class="link-edit button button-secondary" href="<?= $this->getItemConfigureUrl($item) ?>"><?= $this->__('Edit') ?></a></p>
<?php endif ?>
<?php foreach($this->getSortedChildren() as $childName):?>
    <?= $this->getChildHtml($childName, false) ?>
<?php endforeach ?>
</div>
