<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Image $this */
/** @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<a class="product-image" href="<?= $this->getProductUrl($item) ?>" title="<?= $this->escapeHtml($product->getName()) ?>">
    <img src="<?= $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113) ?>"
         srcset="<?= $this->helper('catalog/image')->init($product, 'small_image')->resize(226, 226) ?> 2x"
         width="113" height="113" alt="<?= $this->escapeHtml($product->getName()) ?>">
</a>
