<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column $this */
/** @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<h3 class="product-name">
    <a href="<?= $this->getProductUrl($item) ?>" title="<?= $this->escapeHtml($product->getName()) ?>"><?= $this->escapeHtml($product->getName()) ?></a>
</h3>

<div class="wishlist-sku">
    <span><?= $this->__('SKU') ?> <?= $this->escapeHtml($product->getSku()) ?></span>
</div>

<textarea name="description[<?= $item->getWishlistItemId() ?>]" rows="3" cols="5" title="<?= $this->quoteEscape($this->__('Comment')) ?>" placeholder="<?= $this->helper('wishlist')->defaultCommentString() ?>"><?= ($this->escapeHtml($item->getDescription() ? $item->getDescription() : '')) ?></textarea>

<?php if($this->getSortedChildren()): ?>
    <div class="item-manage">
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?= $this->getChildHtml($childName, false) ?>
    <?php endforeach ?>
    </div>
<?php endif ?>
