<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart $this */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
    <div class="add-to-cart-alt">
    <?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
        <input type="text" pattern="\d*(\.\d+)?" class="input-text qty validate-not-negative-number" name="qty[<?= $item->getId() ?>]" value="<?= $this->getAddToCartQty($item) * 1 ?>" />
    <?php endif ?>
    </div>
</div>
