<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Remove $this */
?>
<a href="#" title="<?= $this->quoteEscape($this->__('Remove Item')) ?>"
   onclick="if (confirmRemoveWishlistItem()) {
                customFormSubmit(
                    '<?= $this->getItemRemoveUrlCustom($this->getItem(), false) ?>',
                    '<?= $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])) ?>',
                    'post'
                )
            }">
    <?= $this->getIconSvg('x') ?>
    <?= $this->__('Remove item') ?>
</a>
