<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<?php
/**
 * Template for Mage_Adminhtml_Block_Widget_Accordion
 *
 * @var Mage_Adminhtml_Block_Customer_Edit_Tab_View_Accordion $this
 */
?>
<dl id="tab_content_<?= $this->getHtmlId() ?>" name="tab_content_<?= $this->getHtmlId() ?>" class="accordion">
<?php foreach ($this->getItems() as $_item): ?>
    <?= $this->getChildHtml($_item->getId()) ?>
<?php endforeach ?>
</dl>
<script>
    tab_content_<?= $this->getHtmlId() ?>AccordionJs = new varienAccordion('tab_content_<?= $this->getHtmlId() ?>', '<?= $this->getShowOnlyOne() ?>');
</script>
