<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2021-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Widget_Breadcrumbs $this */
?>
<?php if(!empty($links)): ?>
<ul class="breadcrumbs">
    <?php $_size = count($links); ?>
    <?php foreach ($links as $_index => $_link): ?>
    <li>
        <?php if(empty($_link['url'])): ?>
            <?php if($_index != $_size - 1): ?>
                <span><?= $this->escapeHtml($_link['label']) ?></span>
            <?php else: ?>
                <strong><?= $this->escapeHtml($_link['label']) ?></strong>
            <?php endif ?>
        <?php else: ?>
            <a href="<?= $_link['url'] ?>" title="<?= $this->escapeHtml($_link['title']) ?>"><?= $this->escapeHtml($_link['label']) ?></a>
        <?php endif ?>
        <?php if($_index != $_size - 1): ?>
            &raquo;
        <?php endif ?>
    </li>
    <?php endforeach ?>
</ul>
<?php endif ?>
