<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
?>
<dl id="dl-<?= $id ?>" class="accordion">
<?php foreach ($sections as $sectionId=>$section): ?>
    <dt id="dt-<?= $id ?>-<?= $sectionId ?>">
        <strong><?= $section['title'] ?></strong>
    </dt>
    <dd id="dd-<?= $id ?>-<?= $section['id'] ?>" class="section-menu <?= !empty($section['active'])?'open':'' ?>">
        <ul>
        <?php foreach ($section['children'] as $menuId=>$menuItem): ?>
            <li id="li-<?= $id ?>-<?= $sectionId ?>-<?= $menuId ?>">
                <a href="#" title="<?= $menuItem['title'] ?>">
                    <span><?= $menuItem['label'] ?></span>
                </a>
            </li>
        <?php endforeach ?>
        </ul>
    </dd>
<?php endforeach ?>
</dl>
