<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Widget_Tabs $this */
?>
<?php if ($this->getTitle()): ?>
    <h3><?= $this->getTitle() ?></h3>
<?php endif ?>
<?php if (!empty($tabs)): ?>
<ul id="<?= $this->getId() ?>" class="tabs">
<?php foreach ($tabs as $tab): ?>
    <?php if (!$this->canShowTab($tab)) continue ?>
    <li<?= $this->getTabIsHidden($tab) ? ' class="no-display"' : ''?>>
        <a href="<?= $this->getTabUrl($tab) ?>" id="<?= $this->getTabId($tab) ?>" name="<?= $this->getTabId($tab, false) ?>" title="<?= $this->quoteEscape($this->getTabTitle($tab)) ?>" class="<?= $this->getTabClasses($tab) ?>">
            <?= $this->getTabLabel($tab) ?>
        </a>
        <div id="<?= $this->getTabId($tab) ?>_content" class="no-display"><?= $this->getTabContent($tab) ?></div>
    </li>
<?php endforeach ?>
</ul>
<script>
    <?= $this->getJsObjectName() ?> = new varienTabs('<?= $this->getId() ?>', '<?= $this->getDestElementId() ?>', '<?= $this->getActiveTabId() ?>', <?= $this->getAllShadowTabs() ?>);
</script>
<?php endif ?>
