<?php

/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Mage_Core
 */

declare(strict_types=1);

namespace Mage\Core\Api;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\GraphQl\Query;
use ApiPlatform\Metadata\GraphQl\QueryCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use Maho\ApiPlatform\CrudResource;
use Maho\Config\ApiResource;

#[ApiResource(
    mahoLabel: 'URL Rewrites',
    mahoSection: 'Catalog',
    mahoOperations: ['read' => 'View', 'write' => 'Create & Update', 'delete' => 'Delete'],
    shortName: 'UrlRewrite',
    description: 'URL rewrite: maps a storefront request path to a target path for one store view, either as an internal rewrite or as a 301/302 redirect. System rewrites (isSystem true) are generated by the catalog URL indexer and are read-only; only custom rewrites can be created, updated or deleted.',
    provider: UrlRewriteProvider::class,
    processor: UrlRewriteProcessor::class,
    operations: [
        new Get(
            uriTemplate: '/url-rewrites/{id}',
            requirements: ['id' => '\d+'],
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/read')",
            description: 'Get a URL rewrite by id',
        ),
        new GetCollection(
            uriTemplate: '/url-rewrites',
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/read')",
            description: 'List URL rewrites across every store view. Filter by storeId, requestPath, search, productId, categoryId or isSystem.',
        ),
        new Post(
            uriTemplate: '/url-rewrites',
            processor: UrlRewriteProcessor::class,
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/write')",
            description: 'Create a custom URL rewrite. storeId and requestPath are required. Give productId and/or categoryId to point at a catalog entity (idPath and targetPath are then generated), or give idPath and targetPath for a custom target. options: empty for an internal rewrite, "R" for a 302 redirect, "RP" for a 301 permanent redirect.',
        ),
        new Put(
            uriTemplate: '/url-rewrites/{id}',
            requirements: ['id' => '\d+'],
            processor: UrlRewriteProcessor::class,
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/write')",
            description: 'Update a custom URL rewrite. Only the fields in the request body change. A system rewrite cannot be updated.',
        ),
        new Delete(
            uriTemplate: '/url-rewrites/{id}',
            requirements: ['id' => '\d+'],
            processor: UrlRewriteProcessor::class,
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/delete')",
            description: 'Delete a custom URL rewrite. A system rewrite cannot be deleted.',
        ),
    ],
    graphQlOperations: [
        new Query(
            name: 'item_query',
            description: 'Get a URL rewrite by id',
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/read')",
        ),
        new QueryCollection(
            name: 'collection_query',
            description: 'List URL rewrites',
            security: "is_granted('ROLE_ADMIN') or is_granted('url-rewrites/read')",
            extraArgs: [
                'storeId' => ['type' => 'Int', 'description' => 'Only rewrites of this store view id'],
                'requestPath' => ['type' => 'String', 'description' => 'Exact request path (returns 0 or more rewrites, one per store view)'],
                'search' => ['type' => 'String', 'description' => 'Partial match on the request path or target path'],
                'productId' => ['type' => 'Int', 'description' => 'Only rewrites of this product id'],
                'categoryId' => ['type' => 'Int', 'description' => 'Only rewrites of this category id'],
                'isSystem' => ['type' => 'Boolean', 'description' => 'true for indexer-generated rewrites only, false for custom rewrites only'],
            ],
        ),
    ],
)]
class UrlRewrite extends CrudResource
{
    public const MODEL = 'core/url_rewrite';
    public const PRIMARY_KEY = 'url_rewrite_id';

    /** Admin ACL gate. Mirrors backend Mage_Adminhtml_UrlrewriteController. */
    public const ADMIN_RESOURCE = \Mage_Adminhtml_UrlrewriteController::ADMIN_RESOURCE;

    public const OPTIONS = ['', 'R', 'RP'];

    #[ApiProperty(identifier: true, writable: false)]
    public ?int $id = null;

    #[ApiProperty(description: 'Store view id the rewrite applies to')]
    public ?int $storeId = null;

    #[ApiProperty(description: 'Internal key of the rewrite, unique per store view. Generated as "product/{id}", "product/{id}/{categoryId}" or "category/{id}" when productId or categoryId is given.')]
    public ?string $idPath = null;

    #[ApiProperty(description: 'Path the shopper requests, relative to the store base URL and without a leading slash. Stored lower-case.')]
    public ?string $requestPath = null;

    #[ApiProperty(description: 'Path the request is rewritten or redirected to. Generated when productId or categoryId is given.')]
    public ?string $targetPath = null;

    #[ApiProperty(writable: false, description: 'True for a rewrite the catalog URL indexer generated. System rewrites are read-only.')]
    public ?bool $isSystem = null;

    #[ApiProperty(description: 'Redirect type: "" for an internal rewrite, "R" for a 302 temporary redirect, "RP" for a 301 permanent redirect')]
    public ?string $options = null;

    #[ApiProperty(description: 'Free-text note shown in the admin grid')]
    public ?string $description = null;

    #[ApiProperty(description: 'Category the rewrite points at, or null')]
    public ?int $categoryId = null;

    #[ApiProperty(description: 'Product the rewrite points at, or null')]
    public ?int $productId = null;
}
