<?php
/**
 * Maho
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2025 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Reports_Block_Product_Viewed $this */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
<div class="widget widget-viewed">
    <div class="widget-title">
        <h2><?= $this->__('Recently Viewed') ?></h2>
    </div>
    <div class="widget-products">
        <ol class="products-list">
        <?php $i=0; foreach ($_products as $_product): ?>
            <li class="item<?= (++$i == count($_products))?' last':'' ?>">
                <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" srcset="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(170) ?> 2x" width="85" height="85" alt="<?= $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?= $this->getPriceHtml($_product, true, '-widget-viewed-list') ?>
                        <?php if($_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart"
                                    onclick="customFormSubmit(
                                            '<?= $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                            '<?= $_params ?>',
                                            'post')">
                                <?= $this->__('Add to Cart') ?>
                            </button>
                        <?php else: ?>
                                <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                        <?php endif ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li>
                                    <a href="#"
                                       class="link-wishlist"
                                       onclick="customFormSubmit(
                                               '<?= $this->getAddToWishlistUrlCustom($_product, false) ?>',
                                               '<?= $_params ?>',
                                               'post')">
                                        <?= $this->__('Add to Wishlist') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                <li>
                                    <span class="separator">|</span>
                                    <a href="#"
                                       class="link-compare"
                                       onclick="customFormSubmit(
                                               '<?= $_compareUrl ?>',
                                               '<?= $_params ?>',
                                               'post')">
                                        <?= $this->__('Add to Compare') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>
