on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  phpdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@2.37.1
        with:
          php-version: 8.3
          tools: phpdoc

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Strip SPDX lines from PHP source
        run: find app lib -name "*.php" -exec sed -i '/ \* SPDX-/d' {} +

      - name: Generate phpDoc
        run: phpdoc -c .github/phpdoc.xml

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .github/phpdoc --project-name=maho-phpdoc
