name: Security

on:
  # Run automatically every Monday on midnight.
  schedule:
    - cron: '0 0 * * 1'
  # Run on pull requests only when composer.lock has changed.
  pull_request:
    paths:
      - 'composer.lock'
  # Allow manually triggering the workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5 # v5
