name: PHP Security Check

on:
  # Run automatically every Monday on midnight.
  schedule:
    - cron: '0 0 * * 1'
  # Run on pull requests only when composer.lock has changed.
  pull_request:
    paths:
      - 'composer.lock'
  # Allow manually triggering the workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5 # v5
