<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Paypal_Block_Bml_Banners $this */
?>
<div class="bml-ad large">
<script type="text/javascript" data-pp-pubid="<?= $this->escapeHtml($this->getPublisherId()) ?>" data-pp-placementtype="<?= $this->escapeHtml($this->getSize()) ?>"> (function (d, t) {
    "use strict";
    var s = d.getElementsByTagName(t)[0], n = d.createElement(t);
    n.src = "//paypal.adtag.where.com/merchant.js";
    s.parentNode.insertBefore(n, s);
}(document, "script"));
</script>
</div>
<div class="bml-ad small">
    <script type="text/javascript" data-pp-pubid="<?= $this->escapeHtml($this->getPublisherId()) ?>" data-pp-placementtype="300x50"> (function (d, t) {
            "use strict";
            var s = d.getElementsByTagName(t)[0], n = d.createElement(t);
            n.src = "//paypal.adtag.where.com/merchant.js";
            s.parentNode.insertBefore(n, s);
        }(document, "script"));
    </script>
</div>
