<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2025 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<ul>
<?php foreach ($items as $item): ?>
    <li id="<?= $item['id'] ?>" url="<?= $item['url'] ?>">
        <span class="type"><?= $this->escapeHtml($item['type']) ?></span>
        <strong><?= $this->escapeHtml($item['name']) ?></strong>
        <span class="informal"><?= $this->escapeHtml($item['description']) ?></span>
    </li>
<?php endforeach ?>
</ul>
