<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<ul>
<?php foreach ($items as $item): ?>
    <li id="<?= $item['id'] ?>">
        <a href="<?= $item['url'] ?>">
            <div>
                <strong><?= $this->escapeHtml($item['name']) ?></strong><br>
                <span class="informal"><?= $this->escapeHtml($item['description']) ?></span>
            </div>
            <div class="chip-accent"><?= $item['type'] ?></div>
        </a>
    </li>
<?php endforeach ?>
</ul>
