<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?= $this->getColumnHtml($_item, 'configurable_name') ?></td>
    <td class="a-center last"><?= $_item->getQty()*1 ?></td>
</tr>
