<?php
/**
 * SPDX-FileCopyrightText: 2024-2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2022-2024 The OpenMage Contributors <https://openmage.org>
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <https://magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Items_Renderer_Default $this */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?= $this->getColumnHtml($_item, 'name') ?></td>
    <td class="a-center last"><?= $_item->getQty()*1 ?></td>
</tr>
