<?php
/**
 * Maho
 *
 * @category   design
 * @package    base_default
 * @copyright  Copyright (c) 2025 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @var Maho_Giftcard_Block_Payment_Info $this
 */
?>
<p><?php echo $this->getMethodTitle() ?></p>
<?php if ($specificInfo = $this->getSpecificInformation()): ?>
    <table class="giftcard-payment-info">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <th><?php echo $this->escapeHtml($label) ?>:</th>
                <td><?php echo nl2br($this->escapeHtml($value)) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>