<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Permissions_Buttons $this */
?>
<div class="content-header">
    <h3><?= ($this->getRoleId() > 0 ) ? ($this->__('Edit Role') . " '{$this->escapeHtml($this->getRoleInfo()->getRoleName())}'") : $this->__('Add New Role') ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getBackButtonHtml() ?>
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getDeleteButtonHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<form action="<?= $this->getUrl('*/*/saverole') ?>" method="post" id="role_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
    var roleForm = new varienForm('role_edit_form');
</script>
