<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?= ($this->getRoleId() > 0 ) ? ($this->__('Edit Role') . " '{$this->escapeHtml($this->getRoleInfo()->getRoleName())}'") : $this->__('Add New Role') ?></h3></td>
            <td class="form-buttons">
                <?= $this->getBackButtonHtml() ?>
                <?= $this->getResetButtonHtml() ?>
                <?= $this->getDeleteButtonHtml() ?>
                <?= $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?= $this->getUrl('*/*/saverole') ?>" method="post" id="role_edit_form">
    <?= $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
    var roleForm = new varienForm('role_edit_form');
</script>
