<?php
/**
 * Maho
 *
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Permissions_Roles $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?= $this->__('Roles') ?></h3></td>
            <td class="form-buttons">
            <button class="scalable" onclick="window.location='<?= $this->getRefreshRolesUrl() ?>'"><span><?= $this->__('Refresh Roles') ?></span></button>
            <button class="scalable add" onclick="window.location='<?= $this->getAddNewUrl() ?>'"><span><?= $this->__('Add New Role') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<?= $this->getGridHtml() ?>
