<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Permissions_UsernRoles $this */
?>
<div id="roles">
    <li class="add"><a href="<?= $this->getUrl('*/*/edituser') ?>"><?= $this->__('Add New User') ?></a></li>
    <li class="add"><a href="<?= $this->getUrl('*/*/editroles') ?>"><?= $this->__('Add New Role') ?></a></li>
</div>
<div class="clear"></div>
