<?php
/**
 * Maho
 *
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024-2026 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Bundle_Block_Sales_Order_Items_Renderer $this */
?>
<?php $parentItem = $this->getItem() ?>

<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $this->getChilds($parentItem) ?>

<?php $_prevOptionId = '' ?>

<?php if($this->getItemOptions() || $parentItem->getDescription() || $this->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php foreach ($items as $_item): ?>
<?php if ($_item->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td class="bundle-item"><strong><em><?= $this->escapeHtml($attributes['option_label']) ?></em></strong></td>
        <td class="bundle-item">&nbsp;</td>
        <td class="bundle-item">&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif ?>
<?php endif ?>
<tr id="order-item-row-<?= $_item->getId() ?>">
    <?php if (!$_item->getParentItem()): ?>
    <td class="bundle-item-parent product-info">
        <p class="product-name"><?= $this->escapeHtml($_item->getName()) ?></p>
    </td>
    <td class="bundle-item-parent align-center">
        <?= $this->escapeHtml($_item->getSku()) ?>
    </td>
    <td class="bundle-item-parent align-right">
    <?php else: ?>
    <td class="bundle-item bundle-details product-info"><div><?= $this->getValueHtml($_item) ?></div></td>
    <td class="bundle-item bundle-details align-center">
        <?= $this->escapeHtml($_item->getSku()) ?>
    </td>
    <td class="bundle-item align-right">
    <?php endif ?>
    <?php if (($this->isShipmentSeparately() && $_item->getParentItem()) || (!$this->isShipmentSeparately() && !$_item->getParentItem())): ?>
        <?php if (isset($shipItems[$_item->getId()])): ?>
            <?= $shipItems[$_item->getId()]->getQty()*1 ?>
        <?php elseif ($_item->getIsVirtual()): ?>
            <?= $this->__('N/A') ?>
        <?php else: ?>
            0
        <?php endif ?>
    <?php else: ?>
    &nbsp;
    <?php endif ?>
    </td>
</tr>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
<tr>
    <td align="left" valign="top" style="padding:3px 9px">
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?= $option['label'] ?></em></strong>
                        <dd style="margin:0; padding:0 0 0 9px;"><?= $option['value'] ?></dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?= $this->escapeHtml($parentItem->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif ?>
